// Port of Go 1.25.5 regexp/syntax/op_string.go.
//
// Go's file is `stringer`-generated: one packed name string plus an
// index table, so `Op.String()` is two slice indexes and no branch per
// case. Ported as written — a `match` with nineteen arms would read
// better and would also be a different thing, and the point of an
// anchored port is that the next reader can diff it.

use crate::gostring::string;
use crate::types::int;

use super::regexp::Op;

// go: sdk 1.25.5 regexp/syntax/op_string.go:33-34 _Op_name_0
/// The nineteen operator names, packed end to end.
const _Op_name_0: &str = "NoMatchEmptyMatchLiteralCharClassAnyCharNotNLAnyCharBeginLineEndLineBeginTextEndTextWordBoundaryNoWordBoundaryCaptureStarPlusQuestRepeatConcatAlternate";
// go: none — goish-only placement: op_string.go line 35, in the same
//     const block as `_Op_name_0`.
/// The one pseudo-op name.
const _Op_name_1: &str = "opPseudo";

// go: sdk 1.25.5 regexp/syntax/op_string.go:38-40 _Op_index_0
/// Start offsets into [`_Op_name_0`], with the end of the last name.
const _Op_index_0: [u8; 20] = [
    0, 7, 17, 24, 33, 45, 52, 61, 68, 77, 84, 96, 110, 117, 121, 125, 130, 136, 142, 151,
];

impl Op {
    // go: sdk 1.25.5 regexp/syntax/op_string.go:42-52 Op.String
    /// Go: an unknown operator renders as `Op(N)`, not as the empty
    /// string — unlike `InstOp.String`, which returns `""`. The two
    /// are generated by different tools and they do not agree; both
    /// are pinned.
    pub fn String(&self) -> string {
        let i = self.0;
        if 1 <= i && i <= 19 {
            let j = (i - 1) as usize;
            let lo = _Op_index_0[j] as usize;
            let hi = _Op_index_0[j + 1] as usize;
            return string::from_bytes(&_Op_name_0.as_bytes()[lo..hi]);
        }
        if i == 128 {
            return string::from_static(_Op_name_1);
        }
        return string::from_static("Op(")
            + crate::strconv::FormatInt(int::from(crate::int64(i)), 10)
            + string::from_static(")");
    }
}
