// go: file crypto/ecdsa/ecdsa.go decls: PublicKey.ECDH, PublicKey.Equal, ParseUncompressedPublicKey, parseUncompressedPublicKey, PublicKey.Bytes, publicKeyBytes, PrivateKey.ECDH, curveToECDH, PrivateKey.Public, PrivateKey.Equal, bigIntEqual, ParseRawPrivateKey, parseRawPrivateKey, PrivateKey.Bytes, privateKeyBytes, PrivateKey.Sign, GenerateKey, generateFIPS, SignASN1, signFIPS, signRFC6979, signFIPSDeterministic, encodeSignature, addASN1IntBytes, VerifyASN1, verifyFIPS, parseSignature, publicKeyFromFIPS, privateKeyFromFIPS, publicKeyToFIPS, privateKeyToFIPS, leftPadBytesEqual, pointFromAffine, pointToAffine
//
// Package ecdsa implements the Elliptic Curve Digital Signature Algorithm,
// as defined in FIPS 186-5.
//
// Signatures generated by this package are not deterministic, but entropy
// is mixed with the private key and the message, achieving the same level
// of security in case of randomness source failure.
//
// Operations involving private keys are implemented using constant-time
// algorithms, as long as an `elliptic.Curve` returned by `elliptic::P224`,
// `elliptic::P256`, `elliptic::P384` or `elliptic::P521` is used.
//
// Deviations from ecdsa[go] @ Go 1.25.5:
//
//   * Go embeds `elliptic.Curve` in PublicKey and `PublicKey` in
//     PrivateKey. goish has no embedding, so both are named fields —
//     `pub.Curve` and `priv.PublicKey`, which is how Go's promotion reads
//     anyway (AGENTS.md §5).
//   * `rand io.Reader` is nilable at two call sites (`PrivateKey.Sign`
//     switches on it), and `opts crypto.SignerOpts` is nil-checked in
//     `signRFC6979`. Both become `Option<&mut …>` / `Option<&…>`, the
//     shape crypto/rsa already uses for a nilable Go interface argument.
//   * Go returns a nil `*PublicKey` / `*PrivateKey` on every error path.
//     goish returns a zero value paired with the error, and both types get
//     `PartialEq<Nil>` so `k == nil` still reads the same (cf. crypto/rsa).
//   * `switch curve { case elliptic.P256(): … }` is Go *interface
//     identity*: `elliptic.P256()` and `elliptic.P256().Params()` are
//     different values and the latter falls to default. goish compares the
//     data half of the fat pointer, which is exactly that test — see
//     `sameCurve`. The `switch c.Params()` sites compare by value instead,
//     and there `curveName` is the discriminator.
//   * `boring.*` is dropped throughout, as everywhere else in the tree;
//     the two stubs live in notboring.rs.

#![allow(non_snake_case, non_upper_case_globals)]

extern crate alloc;
use alloc::vec::Vec;

use crate::crypto;
use crate::crypto::cryptobyte::{self, asn1};
use crate::crypto::ecdh;
use crate::crypto::elliptic;
use crate::crypto::internal::fips140::ecdsa as fipsec;
use crate::crypto::internal::fips140::nistec;
use crate::crypto::internal::fips140cache;
use crate::crypto::internal::fips140only;
use crate::crypto::internal::randutil;
use crate::crypto::sha512;
use crate::crypto::subtle;
use crate::errors::{self, error, nil};
use crate::goslice::slice;
use crate::gostring::string;
use crate::int;
use crate::io;
use crate::math::big::Int;
use crate::types::{byte, uint};

// Go: ecdsa.go:41-57
//   type PublicKey struct { elliptic.Curve; X, Y *big.Int }
/// An ECDSA public key.
///
/// `X`, `Y` are the coordinates of the public key point. Modifying the raw
/// coordinates can produce invalid keys, and may invalidate internal
/// optimizations; moreover, `big::Int` methods are not suitable for
/// operating on cryptographic values. To encode and decode PublicKey
/// values, use [`PublicKey::Bytes`] and [`ParseUncompressedPublicKey`].
/// For ECDH, use `crypto/ecdh`.
#[derive(Clone)]
pub struct PublicKey {
    /// Go embeds `elliptic.Curve`; goish names the field.
    pub Curve: &'static (dyn elliptic::Curve + Send + Sync),
    pub X: Int,
    pub Y: Int,
}

// go: none — Go's error paths return a nil `*PublicKey`. goish pairs a
// zero value with the error; P-256 stands in for the curve, which is never
// read because every caller checks the error first.
fn zeroPublicKey() -> PublicKey {
    return PublicKey {
        Curve: elliptic::P256(),
        X: Int::default(),
        Y: Int::default(),
    };
}

// go: none — polymorphic nil for `*ecdsa.PublicKey`, as crypto/rsa does
// for its own key types.
impl PartialEq<crate::nilval::Nil> for PublicKey {
    // go: none — polymorphic nil, see the note above.
    fn eq(&self, _: &crate::nilval::Nil) -> bool {
        return self.X == crate::nilval::nil && self.Y == crate::nilval::nil;
    }
}
impl PartialEq<PublicKey> for crate::nilval::Nil {
    // go: none — polymorphic nil, see the note above.
    fn eq(&self, other: &PublicKey) -> bool {
        return other.X == crate::nilval::nil && other.Y == crate::nilval::nil;
    }
}

// go: none — the third of AGENTS.md §6's polymorphic-nil impls, which
// this type was missing. `From<Nil>` is what lets a `*ecdsa.PublicKey`
// error return be spelled `nil.into()` — Go's `return nil, err` — instead
// of naming the zero key at every call site. crypto/x509's SEC 1 and
// PKCS #8 parsers are the first callers.
impl From<crate::nilval::Nil> for PublicKey {
    // go: none — polymorphic nil, see the note above.
    fn from(_: crate::nilval::Nil) -> Self {
        return zeroPublicKey();
    }
}

// go: none — Go's `switch curve { case elliptic.P256(): … }` compares
// interface values: same dynamic type AND same pointer. Comparing the data
// half of goish's fat pointer is that same test, and it keeps
// `elliptic::P256()` distinct from a `CurveParams` with identical fields —
// which is the distinction Go relies on for `PublicKey.Equal`.
fn sameCurve(
    a: &(dyn elliptic::Curve + Send + Sync),
    b: &(dyn elliptic::Curve + Send + Sync),
) -> bool {
    return core::ptr::eq(a as *const _ as *const (), b as *const _ as *const ());
}

// go: none — the `switch c.Params()` sites compare CurveParams *by value*.
// Among the four NIST curves the canonical name is the discriminator, and
// it is what `sameParams` compares first.
fn curveName(c: &(dyn elliptic::Curve + Send + Sync)) -> string {
    return c.Params().Name;
}

impl PublicKey {
    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:65-75 PublicKey.ECDH
    /// Return `k` as an `ecdh::PublicKey`. Returns an error if the key is
    /// invalid according to the definition of `ecdh::Curve::NewPublicKey`,
    /// or if the Curve is not supported by crypto/ecdh.
    pub fn ECDH(&self) -> (ecdh::PublicKey, error) {
        let c = curveToECDH(self.Curve);
        if c.is_none() {
            return (
                ecdh::PublicKey::default(),
                errors::New("ecdsa: unsupported curve by crypto/ecdh"),
            );
        }
        if !self.Curve.IsOnCurve(&self.X, &self.Y) {
            return (
                ecdh::PublicKey::default(),
                errors::New("ecdsa: invalid public key"),
            );
        }
        return c
            .unwrap()
            .NewPublicKey(&elliptic::Marshal(self.Curve, &self.X, &self.Y));
    }

    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:77-92 PublicKey.Equal
    /// Report whether `pub` and `x` have the same value.
    ///
    /// Two keys are only considered to have the same value if they have the
    /// same Curve value. Note that for example `elliptic::P256()` and
    /// `elliptic::P256().Params()` are different values, as the latter is a
    /// generic not constant time implementation.
    pub fn Equal(&self, x: &PublicKey) -> bool {
        return bigIntEqual(&self.X, &x.X)
            && bigIntEqual(&self.Y, &x.Y)
            // Standard library Curve implementations are singletons, so
            // this check will work for those. Other Curves might be
            // equivalent even if not singletons, but there is no definitive
            // way to check for that, and better to err on the side of
            // safety.
            && sameCurve(self.Curve, x.Curve);
    }

    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:145-158 PublicKey.Bytes
    /// Encode the public key as an uncompressed point according to SEC 1,
    /// Version 2.0, Section 2.3.3 (also known as the X9.62 uncompressed
    /// format). Returns an error if the public key is invalid.
    ///
    /// `PublicKey.Curve` must be one of `elliptic::P224`, `elliptic::P256`,
    /// `elliptic::P384` or `elliptic::P521`, or Bytes returns an error.
    pub fn Bytes(&self) -> (slice<byte>, error) {
        if sameCurve(self.Curve, elliptic::P224()) {
            return publicKeyBytes(fipsec::P224(), self);
        }
        if sameCurve(self.Curve, elliptic::P256()) {
            return publicKeyBytes(fipsec::P256(), self);
        }
        if sameCurve(self.Curve, elliptic::P384()) {
            return publicKeyBytes(fipsec::P384(), self);
        }
        if sameCurve(self.Curve, elliptic::P521()) {
            return publicKeyBytes(fipsec::P521(), self);
        }
        return (
            empty(),
            errors::New("ecdsa: curve not supported by PublicKey.Bytes"),
        );
    }
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:108-124 ParseUncompressedPublicKey
/// Parse a public key encoded as an uncompressed point according to SEC 1,
/// Version 2.0, Section 2.3.3 (also known as the X9.62 uncompressed
/// format). Returns an error if the point is not in uncompressed form, is
/// not on the curve, or is the point at infinity.
///
/// `curve` must be one of `elliptic::P224`, `elliptic::P256`,
/// `elliptic::P384` or `elliptic::P521`, or an error is returned.
pub fn ParseUncompressedPublicKey(
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    data: &slice<byte>,
) -> (PublicKey, error) {
    let d: &[byte] = data;
    if d.len() < 1 || d[0] != 4 {
        return (
            zeroPublicKey(),
            errors::New("ecdsa: invalid uncompressed public key"),
        );
    }
    if sameCurve(curve, elliptic::P224()) {
        return parseUncompressedPublicKey(fipsec::P224(), curve, data);
    }
    if sameCurve(curve, elliptic::P256()) {
        return parseUncompressedPublicKey(fipsec::P256(), curve, data);
    }
    if sameCurve(curve, elliptic::P384()) {
        return parseUncompressedPublicKey(fipsec::P384(), curve, data);
    }
    if sameCurve(curve, elliptic::P521()) {
        return parseUncompressedPublicKey(fipsec::P521(), curve, data);
    }
    return (
        zeroPublicKey(),
        errors::New("ecdsa: curve not supported by ParseUncompressedPublicKey"),
    );
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:126-132 parseUncompressedPublicKey
fn parseUncompressedPublicKey<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    data: &slice<byte>,
) -> (PublicKey, error) {
    let (k, err) = fipsec::NewPublicKey(c, data);
    if err != nil {
        return (zeroPublicKey(), err);
    }
    return publicKeyFromFIPS(curve, &k);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:160-166 publicKeyBytes
fn publicKeyBytes<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    pub_: &PublicKey,
) -> (slice<byte>, error) {
    let (k, err) = publicKeyToFIPS(c, pub_);
    if err != nil {
        return (empty(), err);
    }
    return (k.Bytes(), nil);
}

// Go: ecdsa.go:169-183
//   type PrivateKey struct { PublicKey; D *big.Int }
/// An ECDSA private key.
///
/// `D` is the private scalar value. Modifying the raw value can produce
/// invalid keys, and may invalidate internal optimizations; moreover,
/// `big::Int` methods are not suitable for operating on cryptographic
/// values. To encode and decode PrivateKey values, use
/// [`PrivateKey::Bytes`] and [`ParseRawPrivateKey`].
#[derive(Clone)]
pub struct PrivateKey {
    /// Go embeds `PublicKey`; goish names the field.
    pub PublicKey: PublicKey,
    pub D: Int,
}

// go: none — see zeroPublicKey.
fn zeroPrivateKey() -> PrivateKey {
    return PrivateKey {
        PublicKey: zeroPublicKey(),
        D: Int::default(),
    };
}

// go: none — polymorphic nil for `*ecdsa.PrivateKey`.
impl PartialEq<crate::nilval::Nil> for PrivateKey {
    // go: none — polymorphic nil, see the note above.
    fn eq(&self, _: &crate::nilval::Nil) -> bool {
        return self.D == crate::nilval::nil && self.PublicKey == crate::nilval::nil;
    }
}
impl PartialEq<PrivateKey> for crate::nilval::Nil {
    // go: none — polymorphic nil, see the note above.
    fn eq(&self, other: &PrivateKey) -> bool {
        return other.D == crate::nilval::nil && other.PublicKey == crate::nilval::nil;
    }
}

// go: none — the third of AGENTS.md §6's polymorphic-nil impls. See the
// note on `From<Nil> for PublicKey` above.
impl From<crate::nilval::Nil> for PrivateKey {
    // go: none — polymorphic nil, see the note above.
    fn from(_: crate::nilval::Nil) -> Self {
        return zeroPrivateKey();
    }
}

impl PrivateKey {
    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:188-198 PrivateKey.ECDH
    /// Return `k` as an `ecdh::PrivateKey`. Returns an error if the key is
    /// invalid according to the definition of
    /// `ecdh::Curve::NewPrivateKey`, or if the Curve is not supported by
    /// crypto/ecdh.
    pub fn ECDH(&self) -> (ecdh::PrivateKey, error) {
        let c = curveToECDH(self.PublicKey.Curve);
        if c.is_none() {
            return (
                ecdh::PrivateKey::default(),
                errors::New("ecdsa: unsupported curve by crypto/ecdh"),
            );
        }
        let size = (self.PublicKey.Curve.Params().N.BitLen() + 7) / 8;
        if self.D.BitLen() > size * 8 {
            return (
                ecdh::PrivateKey::default(),
                errors::New("ecdsa: invalid private key"),
            );
        }
        return c.unwrap().NewPrivateKey(&self.D.FillBytes(zeros(size)));
    }

    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:214-216 PrivateKey.Public
    /// Return the public key corresponding to `priv`.
    pub fn Public(&self) -> PublicKey {
        return self.PublicKey.clone();
    }

    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:218-227 PrivateKey.Equal
    /// Report whether `priv` and `x` have the same value.
    ///
    /// See [`PublicKey::Equal`] for details on how Curve is compared.
    pub fn Equal(&self, x: &PrivateKey) -> bool {
        return self.PublicKey.Equal(&x.PublicKey) && bigIntEqual(&self.D, &x.D);
    }

    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:288-301 PrivateKey.Bytes
    /// Encode the private key as a fixed-length big-endian integer
    /// according to SEC 1, Version 2.0, Section 2.3.6 (sometimes referred
    /// to as the raw format). Returns an error if the private key is
    /// invalid.
    pub fn Bytes(&self) -> (slice<byte>, error) {
        if sameCurve(self.PublicKey.Curve, elliptic::P224()) {
            return privateKeyBytes(fipsec::P224(), self);
        }
        if sameCurve(self.PublicKey.Curve, elliptic::P256()) {
            return privateKeyBytes(fipsec::P256(), self);
        }
        if sameCurve(self.PublicKey.Curve, elliptic::P384()) {
            return privateKeyBytes(fipsec::P384(), self);
        }
        if sameCurve(self.PublicKey.Curve, elliptic::P521()) {
            return privateKeyBytes(fipsec::P521(), self);
        }
        return (
            empty(),
            errors::New("ecdsa: curve not supported by PrivateKey.Bytes"),
        );
    }

    // go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:325-330 PrivateKey.Sign
    /// Sign a hash (which should be the result of hashing a larger message
    /// with `opts.HashFunc()`) using the private key, `priv`. If the hash
    /// is longer than the bit-length of the private key's curve order, the
    /// hash will be truncated to that length. Returns the ASN.1 encoded
    /// signature, like [`SignASN1`].
    ///
    /// If `rand` is not None, the signature is randomized. Most
    /// applications should use `crypto/rand.Reader` as rand.
    ///
    /// If `rand` is None, Sign produces a deterministic signature according
    /// to RFC 6979. When producing a deterministic signature,
    /// `opts.HashFunc()` must be the function used to produce `digest` and
    /// `priv.Curve` must be one of the four NIST curves.
    pub fn Sign(
        &self,
        rand: Option<&mut (dyn io::Reader + Send + Sync + 'static)>,
        digest: &slice<byte>,
        opts: Option<&dyn crypto::SignerOpts>,
    ) -> (slice<byte>, error) {
        if rand.is_none() {
            return signRFC6979(self, digest, opts);
        }
        return SignASN1(rand.unwrap(), self, digest);
    }
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:200-211 curveToECDH
fn curveToECDH(
    c: &(dyn elliptic::Curve + Send + Sync),
) -> Option<&'static (dyn ecdh::Curve + Send + Sync)> {
    if sameCurve(c, elliptic::P256()) {
        return Some(ecdh::P256());
    }
    if sameCurve(c, elliptic::P384()) {
        return Some(ecdh::P384());
    }
    if sameCurve(c, elliptic::P521()) {
        return Some(ecdh::P521());
    }
    return None;
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:231-233 bigIntEqual
/// Report whether `a` and `b` are equal, leaking only their bit length
/// through timing side-channels.
fn bigIntEqual(a: &Int, b: &Int) -> bool {
    return subtle::ConstantTimeCompare(&a.Bytes(), &b.Bytes()) == 1;
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:249-262 ParseRawPrivateKey
/// Parse a private key encoded as a fixed-length big-endian integer,
/// according to SEC 1, Version 2.0, Section 2.3.6 (sometimes referred to as
/// the raw format). Returns an error if the value is not reduced modulo the
/// curve's order, or if it's zero.
pub fn ParseRawPrivateKey(
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    data: &slice<byte>,
) -> (PrivateKey, error) {
    if sameCurve(curve, elliptic::P224()) {
        return parseRawPrivateKey(fipsec::P224(), nistec::NewP224Point, curve, data);
    }
    if sameCurve(curve, elliptic::P256()) {
        return parseRawPrivateKey(fipsec::P256(), nistec::NewP256Point, curve, data);
    }
    if sameCurve(curve, elliptic::P384()) {
        return parseRawPrivateKey(fipsec::P384(), nistec::NewP384Point, curve, data);
    }
    if sameCurve(curve, elliptic::P521()) {
        return parseRawPrivateKey(fipsec::P521(), nistec::NewP521Point, curve, data);
    }
    return (
        zeroPrivateKey(),
        errors::New("ecdsa: curve not supported by ParseRawPrivateKey"),
    );
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:264-286 parseRawPrivateKey
fn parseRawPrivateKey<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    newPoint: fn() -> P,
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    data: &slice<byte>,
) -> (PrivateKey, error) {
    let mut q = newPoint();
    let err = q.ScalarBaseMult(data);
    if err != nil {
        return (zeroPrivateKey(), err);
    }
    let (k, err) = fipsec::NewPrivateKey(c, data, &q.Bytes());
    if err != nil {
        return (zeroPrivateKey(), err);
    }
    return privateKeyFromFIPS(curve, &k);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:303-309 privateKeyBytes
fn privateKeyBytes<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    priv_: &PrivateKey,
) -> (slice<byte>, error) {
    let (k, err) = privateKeyToFIPS(c, priv_);
    if err != nil {
        return (empty(), err);
    }
    return (k.Bytes(), nil);
}

// go: none — goish idiom: Go's `*ecdsa.PrivateKey` satisfies
// `crypto.Signer` through the inherent `Sign` above; the trait impl
// forwards to it and widens `Public` to `crypto::PublicKey`.
//
// This was MISSING, and its absence was not local: `crypto/tls`
// finds a certificate's signer by downcasting to `dyn crypto::Signer`,
// so with no impl here every ECDSA server certificate failed the
// handshake with "certificate private key does not implement
// crypto.Signer" — the modern default key type could not serve TLS at
// all.
//
// One deviation, forced by types rather than chosen. `SignASN1` takes
// `&mut (dyn io::Reader + Send + Sync + 'static)`, because
// `fips140only::ApprovedRandomReader` has to downcast it; the trait's
// reader carries none of those bounds. The caller's reader is
// therefore not threaded through, and `crypto/rand`'s is used instead.
// Signatures stay randomised — the security property is unchanged —
// but a caller supplying a deterministic reader here does not get a
// deterministic signature. Go would.
//
// split-brain-ok: the two Sign bodies differ on purpose, and the
// reason is the paragraph above — SignASN1's reader bounds cannot be
// met from the trait, so this impl cannot forward to the inherent
// Sign. Marked so split_brain_check reports zero and the NEXT pair
// stands out instead of being lost in a permanent count of one.
impl crypto::Signer for PrivateKey {
    // go: none — goish idiom: Go's `*PrivateKey` satisfies
    // `crypto.Signer` structurally; this forwards and widens the
    // return to `crypto::PublicKey`.
    fn Public(&self) -> crypto::PublicKey {
        return alloc::sync::Arc::new(self.PublicKey.clone());
    }

    // go: none — goish idiom: see Public. The reader is not threaded
    // through; see the note above the impl.
    fn Sign(
        &self,
        _rand: &mut dyn io::Reader,
        digest: slice<byte>,
        _opts: &dyn crypto::SignerOpts,
    ) -> (slice<byte>, error) {
        return SignASN1(&mut crate::crypto::rand::Reader, self, &digest);
    }
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:337-361 GenerateKey
/// Generate a new ECDSA private key for the specified curve.
///
/// Most applications should use `crypto/rand.Reader` as rand. Note that the
/// returned key does not depend deterministically on the bytes read from
/// rand, and may change between calls and/or between versions.
pub fn GenerateKey(
    c: &'static (dyn elliptic::Curve + Send + Sync),
    rand: &mut (dyn io::Reader + Send + Sync + 'static),
) -> (PrivateKey, error) {
    randutil::MaybeReadByte(rand);

    let name = curveName(c);
    if name == curveName(elliptic::P224()) {
        return generateFIPS(c, fipsec::P224(), rand);
    }
    if name == curveName(elliptic::P256()) {
        return generateFIPS(c, fipsec::P256(), rand);
    }
    if name == curveName(elliptic::P384()) {
        return generateFIPS(c, fipsec::P384(), rand);
    }
    if name == curveName(elliptic::P521()) {
        return generateFIPS(c, fipsec::P521(), rand);
    }
    return super::ecdsa_legacy::generateLegacy(c, rand);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:363-373 generateFIPS
fn generateFIPS<P: fipsec::Point>(
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    c: &fipsec::Curve<P>,
    rand: &mut (dyn io::Reader + Send + Sync + 'static),
) -> (PrivateKey, error) {
    if fips140only::Enabled && !fips140only::ApprovedRandomReader(rand) {
        return (
            zeroPrivateKey(),
            errors::New("crypto/ecdsa: only crypto/rand.Reader is allowed in FIPS 140-only mode"),
        );
    }
    let (privateKey, err) = fipsec::GenerateKey(c, rand);
    if err != nil {
        return (zeroPrivateKey(), err);
    }
    return privateKeyFromFIPS(curve, &privateKey);
}

goish::var! {
    /// Returned by signAsm and verifyAsm when the assembly implementation
    /// is not available. goish has no assembly ECDSA, so nothing raises it
    /// — it is ported because Go declares it at package scope.
    errNoAsm: error = "no assembly implementation available";
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:386-410 SignASN1
/// Sign a hash (which should be the result of hashing a larger message)
/// using the private key, `priv`. If the hash is longer than the bit-length
/// of the private key's curve order, the hash will be truncated to that
/// length. Returns the ASN.1 encoded signature.
///
/// The signature is randomized. Most applications should use
/// `crypto/rand.Reader` as rand.
pub fn SignASN1(
    rand: &mut (dyn io::Reader + Send + Sync + 'static),
    priv_: &PrivateKey,
    hash: &slice<byte>,
) -> (slice<byte>, error) {
    randutil::MaybeReadByte(rand);

    let name = curveName(priv_.PublicKey.Curve);
    if name == curveName(elliptic::P224()) {
        return signFIPS(fipsec::P224(), priv_, rand, hash);
    }
    if name == curveName(elliptic::P256()) {
        return signFIPS(fipsec::P256(), priv_, rand, hash);
    }
    if name == curveName(elliptic::P384()) {
        return signFIPS(fipsec::P384(), priv_, rand, hash);
    }
    if name == curveName(elliptic::P521()) {
        return signFIPS(fipsec::P521(), priv_, rand, hash);
    }
    return super::ecdsa_legacy::signLegacy(priv_, rand, hash);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:412-428 signFIPS
fn signFIPS<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    priv_: &PrivateKey,
    rand: &mut (dyn io::Reader + Send + Sync + 'static),
    hash: &slice<byte>,
) -> (slice<byte>, error) {
    if fips140only::Enabled && !fips140only::ApprovedRandomReader(rand) {
        return (
            empty(),
            errors::New("crypto/ecdsa: only crypto/rand.Reader is allowed in FIPS 140-only mode"),
        );
    }
    let (k, err) = privateKeyToFIPS(c, priv_);
    if err != nil {
        return (empty(), err);
    }
    // Always using SHA-512 instead of the hash that computed hash is
    // technically a violation of draft-irtf-cfrg-det-sigs-with-noise-04 but
    // in our API we don't get to know what it was, and this has no security
    // impact.
    let (sig, err) = fipsec::Sign(c, sha512::NewHash, &k, rand, hash);
    if err != nil {
        return (empty(), err);
    }
    return encodeSignature(&sig.R, &sig.S);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:430-450 signRFC6979
fn signRFC6979(
    priv_: &PrivateKey,
    hash: &slice<byte>,
    opts: Option<&dyn crypto::SignerOpts>,
) -> (slice<byte>, error) {
    if opts.is_none() {
        return (empty(), errors::New("ecdsa: Sign called with nil opts"));
    }
    let h = opts.unwrap().HashFunc();
    if h.Size() != hash.Len() {
        return (
            empty(),
            errors::New("ecdsa: hash length does not match hash function"),
        );
    }
    let name = curveName(priv_.PublicKey.Curve);
    if name == curveName(elliptic::P224()) {
        return signFIPSDeterministic(fipsec::P224(), h, priv_, hash);
    }
    if name == curveName(elliptic::P256()) {
        return signFIPSDeterministic(fipsec::P256(), h, priv_, hash);
    }
    if name == curveName(elliptic::P384()) {
        return signFIPSDeterministic(fipsec::P384(), h, priv_, hash);
    }
    if name == curveName(elliptic::P521()) {
        return signFIPSDeterministic(fipsec::P521(), h, priv_, hash);
    }
    return (
        empty(),
        errors::New("ecdsa: curve not supported by deterministic signatures"),
    );
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:452-466 signFIPSDeterministic
fn signFIPSDeterministic<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    hashFunc: crypto::Hash,
    priv_: &PrivateKey,
    hash: &slice<byte>,
) -> (slice<byte>, error) {
    let (k, err) = privateKeyToFIPS(c, priv_);
    if err != nil {
        return (empty(), err);
    }
    // Go writes `fips140hash.UnwrapNew(hashFunc.New)` — a method value.
    // Rust has none, so the closure Go builds implicitly is spelled out.
    let h = crate::crypto::internal::fips140hash::UnwrapNew(move || hashFunc.New());
    if fips140only::Enabled && !fips140only::ApprovedHash(&h.Call()) {
        return (
            empty(),
            errors::New(
                "crypto/ecdsa: use of hash functions other than SHA-2 or SHA-3 is not allowed in FIPS 140-only mode",
            ),
        );
    }
    let (sig, err) = fipsec::SignDeterministic(c, h, &k, hash);
    if err != nil {
        return (empty(), err);
    }
    return encodeSignature(&sig.R, &sig.S);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:468-475 encodeSignature
pub(super) fn encodeSignature(r: &slice<byte>, s: &slice<byte>) -> (slice<byte>, error) {
    let mut b = cryptobyte::NewBuilder(empty());
    b.AddASN1(asn1::SEQUENCE, |b: &mut cryptobyte::Builder| {
        addASN1IntBytes(b, r);
        addASN1IntBytes(b, s);
    });
    return b.Bytes();
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:477-493 addASN1IntBytes
/// Encode in ASN.1 a positive integer represented as a big-endian byte
/// slice with zero or more leading zeroes.
fn addASN1IntBytes(b: &mut cryptobyte::Builder, bytes: &slice<byte>) {
    let raw: &[byte] = bytes;
    let mut i: usize = 0;
    while i < raw.len() && raw[i] == 0 {
        i += 1;
    }
    let bytes = &raw[i..];
    if bytes.is_empty() {
        b.SetError(errors::New("invalid integer"));
        return;
    }
    let body = slice::__from_vec(bytes.to_vec());
    b.AddASN1(asn1::INTEGER, move |c: &mut cryptobyte::Builder| {
        let raw: &[byte] = &body;
        if raw[0] & 0x80 != 0 {
            c.AddUint8(0);
        }
        c.AddBytes(&body);
    });
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:500-521 VerifyASN1
/// Verify the ASN.1 encoded signature, `sig`, of `hash` using the public
/// key, `pub`. Its return value records whether the signature is valid.
///
/// The inputs are not considered confidential, and may leak through timing
/// side channels, or if an attacker has control of part of the inputs.
pub fn VerifyASN1(pub_: &PublicKey, hash: &slice<byte>, sig: &slice<byte>) -> bool {
    let name = curveName(pub_.Curve);
    if name == curveName(elliptic::P224()) {
        return verifyFIPS(fipsec::P224(), pub_, hash, sig);
    }
    if name == curveName(elliptic::P256()) {
        return verifyFIPS(fipsec::P256(), pub_, hash, sig);
    }
    if name == curveName(elliptic::P384()) {
        return verifyFIPS(fipsec::P384(), pub_, hash, sig);
    }
    if name == curveName(elliptic::P521()) {
        return verifyFIPS(fipsec::P521(), pub_, hash, sig);
    }
    return super::ecdsa_legacy::verifyLegacy(pub_, hash, sig);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:523-536 verifyFIPS
fn verifyFIPS<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    pub_: &PublicKey,
    hash: &slice<byte>,
    sig: &slice<byte>,
) -> bool {
    let (r, s, err) = parseSignature(sig);
    if err != nil {
        return false;
    }
    let (k, err) = publicKeyToFIPS(c, pub_);
    if err != nil {
        return false;
    }
    let err = fipsec::Verify(c, &k, hash, &fipsec::Signature { R: r, S: s });
    if err != nil {
        return false;
    }
    return true;
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:539-550 parseSignature
pub(super) fn parseSignature(sig: &slice<byte>) -> (slice<byte>, slice<byte>, error) {
    let mut inner = cryptobyte::String::default();
    let mut input = cryptobyte::String::New(sig.clone());
    let mut r = empty();
    let mut s = empty();
    if !input.ReadASN1(&mut inner, asn1::SEQUENCE)
        || !input.Empty()
        || !inner.ReadASN1Integer(&mut r)
        || !inner.ReadASN1Integer(&mut s)
        || !inner.Empty()
    {
        return (empty(), empty(), errors::New("invalid ASN.1"));
    }
    return (r, s, nil);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:552-558 publicKeyFromFIPS
fn publicKeyFromFIPS(
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    pub_: &fipsec::PublicKey,
) -> (PublicKey, error) {
    let (x, y, err) = pointToAffine(curve, &pub_.Bytes());
    if err != nil {
        return (zeroPublicKey(), err);
    }
    return (
        PublicKey {
            Curve: curve,
            X: x,
            Y: y,
        },
        nil,
    );
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:560-566 privateKeyFromFIPS
fn privateKeyFromFIPS(
    curve: &'static (dyn elliptic::Curve + Send + Sync),
    priv_: &fipsec::PrivateKey,
) -> (PrivateKey, error) {
    let (pub_, err) = publicKeyFromFIPS(curve, &priv_.PublicKey());
    if err != nil {
        return (zeroPrivateKey(), err);
    }
    let mut d = Int::default();
    d.SetBytes(priv_.Bytes());
    return (
        PrivateKey {
            PublicKey: pub_,
            D: d,
        },
        nil,
    );
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:568-574 publicKeyToFIPS
fn publicKeyToFIPS<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    pub_: &PublicKey,
) -> (fipsec::PublicKey, error) {
    let (Q, err) = pointFromAffine(pub_.Curve, &pub_.X, &pub_.Y);
    if err != nil {
        return (fipsec::PublicKey::default(), err);
    }
    return fipsec::NewPublicKey(c, &Q);
}

// Go: ecdsa.go:576
//   var privateKeyCache fips140cache.Cache[PrivateKey, ecdsa.PrivateKey]
static privateKeyCache: fips140cache::Cache<PrivateKey, fipsec::PrivateKey> =
    fips140cache::Cache::New();

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:578-589 privateKeyToFIPS
fn privateKeyToFIPS<P: fipsec::Point>(
    c: &fipsec::Curve<P>,
    priv_: &PrivateKey,
) -> (fipsec::PrivateKey, error) {
    let (Q, err) = pointFromAffine(
        priv_.PublicKey.Curve,
        &priv_.PublicKey.X,
        &priv_.PublicKey.Y,
    );
    if err != nil {
        return (fipsec::PrivateKey::default(), err);
    }
    let Qc = Q.clone();
    return privateKeyCache.Get(
        priv_,
        || {
            return fipsec::NewPrivateKey(c, &priv_.D.Bytes(), &Q);
        },
        |k: &fipsec::PrivateKey| {
            return subtle::ConstantTimeCompare(&k.PublicKey().Bytes(), &Qc) == 1
                && leftPadBytesEqual(&k.Bytes(), &priv_.D.Bytes());
        },
    );
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:591-603 leftPadBytesEqual
fn leftPadBytesEqual(a: &slice<byte>, b: &slice<byte>) -> bool {
    let (mut a, mut b): (&[byte], &[byte]) = (a, b);
    if a.len() < b.len() {
        core::mem::swap(&mut a, &mut b);
    }
    let padded: Vec<byte>;
    if a.len() > b.len() {
        // Go: enough for a P-521 private key.
        let mut x: Vec<byte> = Vec::with_capacity(66);
        x.extend(core::iter::repeat(0u8).take(a.len() - b.len()));
        x.extend_from_slice(b);
        padded = x;
        b = &padded;
    }
    return subtle::ConstantTimeCompare(
        &slice::__from_vec(a.to_vec()),
        &slice::__from_vec(b.to_vec()),
    ) == 1;
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:605-622 pointFromAffine
/// Convert the PublicKey to a nistec SetBytes input.
fn pointFromAffine(
    curve: &(dyn elliptic::Curve + Send + Sync),
    x: &Int,
    y: &Int,
) -> (slice<byte>, error) {
    let bitSize = curve.Params().BitSize;
    // Reject values that would not get correctly encoded.
    if x.Sign() < 0 || y.Sign() < 0 {
        return (empty(), errors::New("negative coordinate"));
    }
    if x.BitLen() > bitSize || y.BitLen() > bitSize {
        return (empty(), errors::New("overflowing coordinate"));
    }
    // Encode the coordinates and let SetBytes reject invalid points.
    let byteLen = (bitSize + 7) / 8;
    let mut buf: Vec<byte> = alloc::vec![0u8; 1 + 2 * (byteLen as usize)];
    buf[0] = 4; // uncompressed point
    let xb = x.FillBytes(zeros(byteLen));
    let yb = y.FillBytes(zeros(byteLen));
    let (xr, yr): (&[byte], &[byte]) = (&xb, &yb);
    let n = byteLen as usize;
    buf[1..1 + n].copy_from_slice(xr);
    buf[1 + n..1 + 2 * n].copy_from_slice(yr);
    return (slice::__from_vec(buf), nil);
}

// go: sdk 1.25.5 crypto/ecdsa/ecdsa.go:624-633 pointToAffine
/// Convert a nistec Bytes encoding to a PublicKey.
fn pointToAffine(
    curve: &(dyn elliptic::Curve + Send + Sync),
    p: &slice<byte>,
) -> (Int, Int, error) {
    let raw: &[byte] = p;
    if raw.len() == 1 && raw[0] == 0 {
        // This is the encoding of the point at infinity.
        return (
            Int::default(),
            Int::default(),
            errors::New("ecdsa: public key point is the infinity"),
        );
    }
    let byteLen = ((curve.Params().BitSize + 7) / 8) as usize;
    let mut x = Int::default();
    let mut y = Int::default();
    x.SetBytes(slice::__from_vec(raw[1..1 + byteLen].to_vec()));
    y.SetBytes(slice::__from_vec(raw[1 + byteLen..].to_vec()));
    return (x, y, nil);
}

// go: none — Go writes `nil` for an absent `[]byte`; goish's slice has no
// nil, so the empty slice stands in at every such return.
fn empty() -> slice<byte> {
    return slice::__from_vec(Vec::<byte>::new());
}

// go: none — Go writes `make([]byte, n)` inline as a FillBytes target.
fn zeros(n: int) -> slice<byte> {
    return slice::__from_vec(alloc::vec![0u8; n as usize]);
}

// go: none — silence the unused warning on `uint`, kept in the import list
// because Go's ecdsa.go uses `uint(excess)` in the legacy path.
#[allow(dead_code)]
type __unused_uint = uint;
