// go: file crypto/md5/md5block.go decls: blockGeneric
//
// The MD5 block step. Go generates md5block.go from gen[go]; goish ports
// the generated result, which is what `go build` actually compiles.

#![allow(non_snake_case, non_upper_case_globals)]

use crate::math::bits;
use crate::types::byte;

use super::md5::{Digest, CHUNK};

// go: sdk 1.25.5 crypto/md5/md5block.go:14-133 blockGeneric
/// Go: `func blockGeneric(dig *digest, p []byte)` — the pure-Go MD5
/// compression function, generated by md5's gen[go] from the RFC 1321
/// round table.
///
/// `p` is a borrowed `&[byte]`: package-internal, called only from
/// `block`, and the borrow avoids re-wrapping the caller's buffer.
pub(crate) fn blockGeneric(dig: &mut Digest, p: &[byte]) {
    // Go: a, b, c, d := dig.s[0], dig.s[1], dig.s[2], dig.s[3]
    let mut a = dig.s[0];
    let mut b = dig.s[1];
    let mut c = dig.s[2];
    let mut d = dig.s[3];

    let mut i: usize = 0;
    while i + CHUNK <= p.len() {
        let q = &p[i..i + CHUNK];

        // Go: aa, bb, cc, dd := a, b, c, d
        let aa = a;
        let bb = b;
        let cc = c;
        let dd = d;

        // Go: x0..xf := byteorder.LEUint32(q[4*N:])
        let le = |k: usize| -> u32 {
            (q[k] as u32)
                | ((q[k + 1] as u32) << 8)
                | ((q[k + 2] as u32) << 16)
                | ((q[k + 3] as u32) << 24)
        };
        let x0 = le(0x0 * 4);
        let x1 = le(0x1 * 4);
        let x2 = le(0x2 * 4);
        let x3 = le(0x3 * 4);
        let x4 = le(0x4 * 4);
        let x5 = le(0x5 * 4);
        let x6 = le(0x6 * 4);
        let x7 = le(0x7 * 4);
        let x8 = le(0x8 * 4);
        let x9 = le(0x9 * 4);
        let xa = le(0xa * 4);
        let xb = le(0xb * 4);
        let xc = le(0xc * 4);
        let xd = le(0xd * 4);
        let xe = le(0xe * 4);
        let xf = le(0xf * 4);

        // Round 1: F = (c^d)&b ^ d
        macro_rules! r1 {
            ($a:ident, $b:ident, $c:ident, $d:ident, $x:ident, $k:expr, $s:expr) => {
                $a = $b.wrapping_add(bits::RotateLeft32(
                    ((($c ^ $d) & $b) ^ $d)
                        .wrapping_add($a)
                        .wrapping_add($x)
                        .wrapping_add($k),
                    $s,
                ));
            };
        }
        r1!(a, b, c, d, x0, 0xd76aa478u32, 7);
        r1!(d, a, b, c, x1, 0xe8c7b756u32, 12);
        r1!(c, d, a, b, x2, 0x242070dbu32, 17);
        r1!(b, c, d, a, x3, 0xc1bdceeeu32, 22);
        r1!(a, b, c, d, x4, 0xf57c0fafu32, 7);
        r1!(d, a, b, c, x5, 0x4787c62au32, 12);
        r1!(c, d, a, b, x6, 0xa8304613u32, 17);
        r1!(b, c, d, a, x7, 0xfd469501u32, 22);
        r1!(a, b, c, d, x8, 0x698098d8u32, 7);
        r1!(d, a, b, c, x9, 0x8b44f7afu32, 12);
        r1!(c, d, a, b, xa, 0xffff5bb1u32, 17);
        r1!(b, c, d, a, xb, 0x895cd7beu32, 22);
        r1!(a, b, c, d, xc, 0x6b901122u32, 7);
        r1!(d, a, b, c, xd, 0xfd987193u32, 12);
        r1!(c, d, a, b, xe, 0xa679438eu32, 17);
        r1!(b, c, d, a, xf, 0x49b40821u32, 22);

        // Round 2: F = (b^c)&d ^ c
        macro_rules! r2 {
            ($a:ident, $b:ident, $c:ident, $d:ident, $x:ident, $k:expr, $s:expr) => {
                $a = $b.wrapping_add(bits::RotateLeft32(
                    ((($b ^ $c) & $d) ^ $c)
                        .wrapping_add($a)
                        .wrapping_add($x)
                        .wrapping_add($k),
                    $s,
                ));
            };
        }
        r2!(a, b, c, d, x1, 0xf61e2562u32, 5);
        r2!(d, a, b, c, x6, 0xc040b340u32, 9);
        r2!(c, d, a, b, xb, 0x265e5a51u32, 14);
        r2!(b, c, d, a, x0, 0xe9b6c7aau32, 20);
        r2!(a, b, c, d, x5, 0xd62f105du32, 5);
        r2!(d, a, b, c, xa, 0x02441453u32, 9);
        r2!(c, d, a, b, xf, 0xd8a1e681u32, 14);
        r2!(b, c, d, a, x4, 0xe7d3fbc8u32, 20);
        r2!(a, b, c, d, x9, 0x21e1cde6u32, 5);
        r2!(d, a, b, c, xe, 0xc33707d6u32, 9);
        r2!(c, d, a, b, x3, 0xf4d50d87u32, 14);
        r2!(b, c, d, a, x8, 0x455a14edu32, 20);
        r2!(a, b, c, d, xd, 0xa9e3e905u32, 5);
        r2!(d, a, b, c, x2, 0xfcefa3f8u32, 9);
        r2!(c, d, a, b, x7, 0x676f02d9u32, 14);
        r2!(b, c, d, a, xc, 0x8d2a4c8au32, 20);

        // Round 3: F = b^c^d
        macro_rules! r3 {
            ($a:ident, $b:ident, $c:ident, $d:ident, $x:ident, $k:expr, $s:expr) => {
                $a = $b.wrapping_add(bits::RotateLeft32(
                    ($b ^ $c ^ $d)
                        .wrapping_add($a)
                        .wrapping_add($x)
                        .wrapping_add($k),
                    $s,
                ));
            };
        }
        r3!(a, b, c, d, x5, 0xfffa3942u32, 4);
        r3!(d, a, b, c, x8, 0x8771f681u32, 11);
        r3!(c, d, a, b, xb, 0x6d9d6122u32, 16);
        r3!(b, c, d, a, xe, 0xfde5380cu32, 23);
        r3!(a, b, c, d, x1, 0xa4beea44u32, 4);
        r3!(d, a, b, c, x4, 0x4bdecfa9u32, 11);
        r3!(c, d, a, b, x7, 0xf6bb4b60u32, 16);
        r3!(b, c, d, a, xa, 0xbebfbc70u32, 23);
        r3!(a, b, c, d, xd, 0x289b7ec6u32, 4);
        r3!(d, a, b, c, x0, 0xeaa127fau32, 11);
        r3!(c, d, a, b, x3, 0xd4ef3085u32, 16);
        r3!(b, c, d, a, x6, 0x04881d05u32, 23);
        r3!(a, b, c, d, x9, 0xd9d4d039u32, 4);
        r3!(d, a, b, c, xc, 0xe6db99e5u32, 11);
        r3!(c, d, a, b, xf, 0x1fa27cf8u32, 16);
        r3!(b, c, d, a, x2, 0xc4ac5665u32, 23);

        // Round 4: F = c ^ (b | ^d)
        macro_rules! r4 {
            ($a:ident, $b:ident, $c:ident, $d:ident, $x:ident, $k:expr, $s:expr) => {
                $a = $b.wrapping_add(bits::RotateLeft32(
                    ($c ^ ($b | (!$d)))
                        .wrapping_add($a)
                        .wrapping_add($x)
                        .wrapping_add($k),
                    $s,
                ));
            };
        }
        r4!(a, b, c, d, x0, 0xf4292244u32, 6);
        r4!(d, a, b, c, x7, 0x432aff97u32, 10);
        r4!(c, d, a, b, xe, 0xab9423a7u32, 15);
        r4!(b, c, d, a, x5, 0xfc93a039u32, 21);
        r4!(a, b, c, d, xc, 0x655b59c3u32, 6);
        r4!(d, a, b, c, x3, 0x8f0ccc92u32, 10);
        r4!(c, d, a, b, xa, 0xffeff47du32, 15);
        r4!(b, c, d, a, x1, 0x85845dd1u32, 21);
        r4!(a, b, c, d, x8, 0x6fa87e4fu32, 6);
        r4!(d, a, b, c, xf, 0xfe2ce6e0u32, 10);
        r4!(c, d, a, b, x6, 0xa3014314u32, 15);
        r4!(b, c, d, a, xd, 0x4e0811a1u32, 21);
        r4!(a, b, c, d, x4, 0xf7537e82u32, 6);
        r4!(d, a, b, c, xb, 0xbd3af235u32, 10);
        r4!(c, d, a, b, x2, 0x2ad7d2bbu32, 15);
        r4!(b, c, d, a, x9, 0xeb86d391u32, 21);

        // Go: a += aa; b += bb; c += cc; d += dd
        a = a.wrapping_add(aa);
        b = b.wrapping_add(bb);
        c = c.wrapping_add(cc);
        d = d.wrapping_add(dd);

        i += CHUNK;
    }

    dig.s[0] = a;
    dig.s[1] = b;
    dig.s[2] = c;
    dig.s[3] = d;
}
