// go: file encoding/binary/varint.go decls: AppendUvarint, PutUvarint, Uvarint, AppendVarint, PutVarint, Varint, ReadUvarint, ReadVarint
//
// The `decls:` manifest above lists varint.go's funcs only. GOISH017
// matches a manifest entry against Rust `fn` items, so naming
// `MaxVarintLen16`/`32`/`64` or `errOverflow` there would report all
// four as dropped ports. They are not dropped — each carries its own
// `// go: sdk` anchor below.
//
// encoding/binary/varint.go — variable-length integers.
//
// Unsigned integers are LEB128: seven bits of payload per byte, low
// group first, with the high bit set on every byte but the last.
// Signed integers are zig-zagged into that same encoding first —
// `x<<1`, complemented when negative — so that small magnitudes of
// either sign stay short, which a two's-complement `int64` would not.
//
// The overflow rule is the subtle part and is Go's, not a
// simplification. A 64-bit value needs at most ten groups, and the
// tenth carries only one usable bit, so a tenth byte greater than 1
// overflows even though it is a well-formed terminator. `Uvarint`
// also refuses to look at an eleventh byte at all (golang.org/issue/41185):
// reading it would be a buffer read past the longest legal encoding.
//
// Deviations from Go:
//
//   * `PutUvarint`/`PutVarint` take `&mut slice<byte>`. Go's `[]byte`
//     header points at a shared backing array, so a by-value parameter
//     still writes through to the caller; goish's `slice<byte>` owns
//     its buffer, and a by-value parameter would write to a copy that
//     is then dropped.
//   * `ReadUvarint`/`ReadVarint` take `&mut impl io::ByteReader`
//     rather than the `io.ByteReader` interface value, so a concrete
//     reader can be passed without boxing.

#![allow(non_snake_case, non_upper_case_globals)]

use crate::convert::{byte as tobyte, int as toint, uint as touint};
use crate::errors::error;
use crate::goslice::slice;
use crate::io;
use crate::types::{byte, int, uint};

extern crate alloc;
use alloc::vec::Vec;

// go: sdk 1.25.5 encoding/binary/varint.go:33-37 MaxVarintLen16
/// `binary.MaxVarintLen16` — the maximum length of a varint-encoded
/// 16-bit integer.
pub const MaxVarintLen16: int = 3;

// go: sdk 1.25.5 encoding/binary/varint.go:33-37 MaxVarintLen32
/// `binary.MaxVarintLen32` — the maximum length of a varint-encoded
/// 32-bit integer.
pub const MaxVarintLen32: int = 5;

// go: sdk 1.25.5 encoding/binary/varint.go:33-37 MaxVarintLen64
/// `binary.MaxVarintLen64` — the maximum length of a varint-encoded
/// 64-bit integer.
pub const MaxVarintLen64: int = 10;

// go: sdk 1.25.5 encoding/binary/varint.go:41-47 AppendUvarint
/// `binary.AppendUvarint(buf, x)` — append the varint-encoded form of
/// `x`, as generated by [`PutUvarint`], to `buf` and return the
/// extended buffer.
pub fn AppendUvarint(buf: slice<byte>, x: uint) -> slice<byte> {
    let mut x = x;
    let mut out: Vec<byte> = buf.__into_vec();
    // Go: for x >= 0x80 { buf = append(buf, byte(x)|0x80); x >>= 7 }
    while x >= 0x80 {
        out.push(tobyte(x) | 0x80);
        x >>= 7;
    }
    // Go: return append(buf, byte(x))
    out.push(tobyte(x));
    return slice::__from_vec(out);
}

// go: sdk 1.25.5 encoding/binary/varint.go:51-60 PutUvarint
/// `binary.PutUvarint(buf, x)` — encode `x` into `buf` and return the
/// number of bytes written. Panics if the buffer is too small.
pub fn PutUvarint(buf: &mut slice<byte>, x: uint) -> int {
    let mut x = x;
    // Go: i := 0
    let mut i: int = 0;
    // Go: for x >= 0x80 { buf[i] = byte(x) | 0x80; x >>= 7; i++ }
    while x >= 0x80 {
        buf[i] = tobyte(x) | 0x80;
        x >>= 7;
        i += 1;
    }
    // Go: buf[i] = byte(x); return i + 1
    buf[i] = tobyte(x);
    return i + 1;
}

// go: sdk 1.25.5 encoding/binary/varint.go:68-88 Uvarint
/// `binary.Uvarint(buf)` — decode a `uint64` from `buf` and return
/// that value and the number of bytes read (> 0). On error the value
/// is 0 and `n <= 0`: `n == 0` means `buf` was too small, `n < 0`
/// means the value was larger than 64 bits and `-n` is the number of
/// bytes read.
pub fn Uvarint(buf: slice<byte>) -> (uint, int) {
    // Go: var x uint64; var s uint
    let mut x: uint = 0;
    let mut s: uint = 0;
    let raw: &[byte] = &buf;
    // Go: for i, b := range buf
    let mut i: int = 0;
    while i < toint(raw.len()) {
        let b = raw[usize::try_from(i).unwrap_or(0)];
        // Go: if i == MaxVarintLen64 — catch byte reads past
        // MaxVarintLen64 (golang.org/issues/41185).
        if i == MaxVarintLen64 {
            return (0, -(i + 1));
        }
        // Go: if b < 0x80
        if b < 0x80 {
            // Go: if i == MaxVarintLen64-1 && b > 1 { return 0, -(i+1) }
            if i == MaxVarintLen64 - 1 && b > 1 {
                return (0, -(i + 1));
            }
            // Go: return x | uint64(b)<<s, i + 1
            return (x | (touint(b) << s), i + 1);
        }
        // Go: x |= uint64(b&0x7f) << s; s += 7
        x |= touint(b & 0x7f) << s;
        s += 7;
        i += 1;
    }
    // Go: return 0, 0
    return (0, 0);
}

// go: sdk 1.25.5 encoding/binary/varint.go:91-97 AppendVarint
/// `binary.AppendVarint(buf, x)` — append the varint-encoded form of
/// `x`, as generated by [`PutVarint`], to `buf` and return the
/// extended buffer.
pub fn AppendVarint(buf: slice<byte>, x: int) -> slice<byte> {
    // Go: ux := uint64(x) << 1; if x < 0 { ux = ^ux }
    let mut ux: uint = touint(x) << 1;
    if x < 0 {
        ux = !ux;
    }
    // Go: return AppendUvarint(buf, ux)
    return AppendUvarint(buf, ux);
}

// go: sdk 1.25.5 encoding/binary/varint.go:101-107 PutVarint
/// `binary.PutVarint(buf, x)` — encode `x` into `buf` and return the
/// number of bytes written. Panics if the buffer is too small.
pub fn PutVarint(buf: &mut slice<byte>, x: int) -> int {
    // Go: ux := uint64(x) << 1; if x < 0 { ux = ^ux }
    let mut ux: uint = touint(x) << 1;
    if x < 0 {
        ux = !ux;
    }
    // Go: return PutUvarint(buf, ux)
    return PutUvarint(buf, ux);
}

// go: sdk 1.25.5 encoding/binary/varint.go:115-122 Varint
/// `binary.Varint(buf)` — decode an `int64` from `buf`, with the same
/// `n` conventions as [`Uvarint`].
pub fn Varint(buf: slice<byte>) -> (int, int) {
    // Go: ux, n := Uvarint(buf) — ok to continue in presence of error.
    let (ux, n) = Uvarint(buf);
    // Go: x := int64(ux >> 1); if ux&1 != 0 { x = ^x }
    let mut x: int = toint(ux >> 1);
    if (ux & 1) != 0 {
        x = !x;
    }
    return (x, n);
}

// go: sdk 1.25.5 encoding/binary/varint.go:124-124 errOverflow
goish::var! {
    /// `binary.errOverflow` — the varint did not fit in 64 bits.
    errOverflow: error = "binary: varint overflows a 64-bit integer";
}

// go: sdk 1.25.5 encoding/binary/varint.go:130-153 ReadUvarint
/// `binary.ReadUvarint(r)` — read an encoded unsigned integer from `r`.
///
/// The error is `io::EOF` only if no bytes were read; an EOF after
/// some but not all of the bytes becomes `io::ErrUnexpectedEOF`.
pub fn ReadUvarint<R: io::ByteReader + ?Sized>(r: &mut R) -> (uint, error) {
    // Go: var x uint64; var s uint
    let mut x: uint = 0;
    let mut s: uint = 0;
    // Go: for i := 0; i < MaxVarintLen64; i++
    let mut i: int = 0;
    while i < MaxVarintLen64 {
        // Go: b, err := r.ReadByte()
        let (b, err) = r.ReadByte();
        if err != crate::nil {
            // Go: if i > 0 && err == io.EOF { err = io.ErrUnexpectedEOF }
            if i > 0 && err == io::EOF {
                return (x, io::ErrUnexpectedEOF.into());
            }
            return (x, err);
        }
        // Go: if b < 0x80
        if b < 0x80 {
            // Go: if i == MaxVarintLen64-1 && b > 1 { return x, errOverflow }
            if i == MaxVarintLen64 - 1 && b > 1 {
                return (x, errOverflow.into());
            }
            // Go: return x | uint64(b)<<s, nil
            return (x | (touint(b) << s), crate::nil.into());
        }
        // Go: x |= uint64(b&0x7f) << s; s += 7
        x |= touint(b & 0x7f) << s;
        s += 7;
        i += 1;
    }
    // Go: return x, errOverflow
    return (x, errOverflow.into());
}

// go: sdk 1.25.5 encoding/binary/varint.go:157-164 ReadVarint
/// `binary.ReadVarint(r)` — read an encoded signed integer from `r`,
/// with the same error conventions as [`ReadUvarint`].
pub fn ReadVarint<R: io::ByteReader + ?Sized>(r: &mut R) -> (int, error) {
    // Go: ux, err := ReadUvarint(r) — ok to continue in presence of error.
    let (ux, err) = ReadUvarint(r);
    // Go: x := int64(ux >> 1); if ux&1 != 0 { x = ^x }
    let mut x: int = toint(ux >> 1);
    if (ux & 1) != 0 {
        x = !x;
    }
    return (x, err);
}
