// go: file crypto/internal/fips140/mlkem/mlkem1024.go decls: DecapsulationKey1024.Bytes, TestingOnlyExpandedBytes1024, DecapsulationKey1024.EncapsulationKey, EncapsulationKey1024.Bytes, EncapsulationKey1024.bytes, GenerateKey1024, generateKey1024, GenerateKeyInternal1024, NewDecapsulationKey1024, newKeyFromSeed1024, TestingOnlyNewDecapsulationKey1024, kemKeyGen1024, kemPCT1024, EncapsulationKey1024.Encapsulate, EncapsulationKey1024.encapsulate, EncapsulationKey1024.EncapsulateInternal, kemEncaps1024, NewEncapsulationKey1024, parseEK1024, pkeEncrypt1024, DecapsulationKey1024.Decapsulate, kemDecaps1024, pkeDecrypt1024
//
// Code generated by generate1024.go. DO NOT EDIT.
//
// The ML-KEM-1024 parameter set. In Go this file is produced from
// mlkem768.go by generate1024.go, which renames every 768-specific
// identifier and widens the compression widths (4 -> 5, 10 -> 11). The
// goish port is generated the same way, from mlkem768.rs, applying
// generate1024.go's own replacement map — plus the file-local helpers
// that Go gets from composite literals (zeroDK, zeroEK, zeroNTT, empty,
// randomSeed), which need distinct names per module.
//
// Deviations are mlkem768.rs's deviations, unchanged: no struct
// embedding, drbg.Read reduced to crypto/rand.Read, fips140 stubs.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]

extern crate alloc;
use alloc::boxed::Box;
use alloc::vec::Vec;

use crate::crypto::internal::fips140;
use crate::crypto::internal::fips140::sha3;
use crate::crypto::internal::fips140::subtle;
use crate::crypto::rand;
use crate::errors;
use crate::goslice::slice;
use crate::{append, byte, error, int64};

use super::field::{
    inverseNTT, ntt, nttElement, nttMul, polyAdd, polyByteDecode, polyByteEncode, polySub,
    ringCompressAndEncode1, ringCompressAndEncode11, ringCompressAndEncode5,
    ringDecodeAndDecompress1, ringDecodeAndDecompress11, ringDecodeAndDecompress5, ringElement,
    sampleNTT, samplePolyCBD,
};
use super::mlkem768::{
    decapsulationKeySize1024, encodingSize11, encodingSize12, encodingSize5, k1024, messageSize, n,
    CiphertextSize1024, EncapsulationKeySize1024, SeedSize, SharedKeySize,
};

// Go: mlkem1024.go:154-159
//   type encryptionKey1024 struct { t [k1024]nttElement; a [k1024*k1024]nttElement }
/// The parsed and expanded form of a PKE encryption key.
#[derive(Clone, Copy)]
pub struct encryptionKey1024 {
    /// Go: `t [k1024]nttElement // ByteDecode₁₂(ek[:384k])`
    pub t: [nttElement; k1024],
    /// Go: `a [k1024 * k1024]nttElement // A[i*k1024+j] = sampleNTT(ρ, j, i)`
    pub a: [nttElement; k1024 * k1024],
}

// Go: mlkem1024.go:161-164
//   type decryptionKey1024 struct { s [k1024]nttElement }
/// The parsed and expanded form of a PKE decryption key.
#[derive(Clone, Copy)]
pub struct decryptionKey1024 {
    /// Go: `s [k1024]nttElement // ByteDecode₁₂(dk[:decryptionKeySize])`
    pub s: [nttElement; k1024],
}

// Go: mlkem1024.go:72-83
//   type DecapsulationKey1024 struct { d, z, ρ, h [32]byte; encryptionKey1024; decryptionKey1024 }
/// The secret key used to decapsulate a shared key from a ciphertext. It
/// includes various precomputed values.
#[derive(Clone, Copy)]
pub struct DecapsulationKey1024 {
    /// Go: `d [32]byte // decapsulation key seed`
    d: [byte; 32],
    /// Go: `z [32]byte // implicit rejection sampling seed`
    z: [byte; 32],
    /// Go: `ρ [32]byte // sampleNTT seed for A, stored for the encapsulation key`
    ρ: [byte; 32],
    /// Go: `h [32]byte // H(ek), stored for ML-KEM.Decaps_internal`
    h: [byte; 32],
    pub encryptionKey1024: encryptionKey1024,
    pub decryptionKey1024: decryptionKey1024,
}

// Go: mlkem1024.go:132-138
//   type EncapsulationKey1024 struct { ρ, h [32]byte; encryptionKey1024 }
/// The public key used to produce ciphertexts to be decapsulated by the
/// corresponding [DecapsulationKey1024].
#[derive(Clone, Copy)]
pub struct EncapsulationKey1024 {
    /// Go: `ρ [32]byte // sampleNTT seed for A`
    ρ: [byte; 32],
    /// Go: `h [32]byte // H(ek)`
    h: [byte; 32],
    pub encryptionKey1024: encryptionKey1024,
}

// go: none — Go gets zero values from `&DecapsulationKey1024{}`; Rust
// needs the zero polynomial spelled once for the array initialisers.
fn zeroNTT1024() -> nttElement {
    return nttElement([0; n]);
}

// go: none — Go's `&DecapsulationKey1024{}` composite literal.
fn zeroDK1024() -> DecapsulationKey1024 {
    return DecapsulationKey1024 {
        d: [0; 32],
        z: [0; 32],
        ρ: [0; 32],
        h: [0; 32],
        encryptionKey1024: encryptionKey1024 {
            t: [zeroNTT1024(); k1024],
            a: [zeroNTT1024(); k1024 * k1024],
        },
        decryptionKey1024: decryptionKey1024 { s: [zeroNTT1024(); k1024] },
    };
}

// go: none — Go's `&EncapsulationKey1024{}` composite literal.
fn zeroEK1024() -> EncapsulationKey1024 {
    return EncapsulationKey1024 {
        ρ: [0; 32],
        h: [0; 32],
        encryptionKey1024: encryptionKey1024 {
            t: [zeroNTT1024(); k1024],
            a: [zeroNTT1024(); k1024 * k1024],
        },
    };
}

// go: none — Go writes `[]byte(nil)` / `make([]byte, 0, N)` at append
// sites; this is the empty1024-slice constructor for them.
fn empty1024() -> slice<byte> {
    return slice::__from_vec(Vec::new());
}

impl DecapsulationKey1024 {
    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:30-35 DecapsulationKey1024.Bytes
    /// Return the decapsulation key as a 64-byte seed in the "d || z" form.
    ///
    /// The decapsulation key must be kept secret.
    pub fn Bytes(&self) -> slice<byte> {
        // Go: var b [SeedSize]byte; copy(b[:], dk.d[:]); copy(b[32:], dk.z[:])
        let mut b = [0u8; SeedSize];
        b[..32].copy_from_slice(&self.d);
        b[32..].copy_from_slice(&self.z);
        // Go: return b[:]
        return slice::__from_vec(b.to_vec());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:65-71 DecapsulationKey1024.EncapsulationKey
    /// Return the public encapsulation key necessary to produce
    /// ciphertexts.
    pub fn EncapsulationKey(&self) -> EncapsulationKey1024 {
        // Go: return &EncapsulationKey1024{ρ: dk.ρ, h: dk.h,
        //                                 encryptionKey1024: dk.encryptionKey1024}
        return EncapsulationKey1024 {
            ρ: self.ρ,
            h: self.h,
            encryptionKey1024: self.encryptionKey1024,
        };
    }

    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:396-405 DecapsulationKey1024.Decapsulate
    /// Generate a shared key from a ciphertext and a decapsulation key.
    /// If the ciphertext is not valid, Decapsulate returns an error.
    ///
    /// The shared key must be kept secret.
    pub fn Decapsulate(&self, ciphertext: slice<byte>) -> (slice<byte>, error) {
        // Go: if len(ciphertext) != CiphertextSize1024 { return nil, errors.New(…) }
        if ciphertext.Len() != int64(CiphertextSize1024) {
            return (empty1024(), errors::New("mlkem: invalid ciphertext length"));
        }
        // Go: c := (*[CiphertextSize1024]byte)(ciphertext)
        let raw: &[byte] = &ciphertext;
        let mut c = [0u8; CiphertextSize1024];
        c.copy_from_slice(raw);
        // Note that the hash check (step 3 of the decapsulation input check
        // from FIPS 203, Section 7.3) is foregone as a DecapsulationKey is
        // always validly generated by ML-KEM.KeyGen_internal.
        // Go: return kemDecaps1024(dk, c), nil
        return (kemDecaps1024(self, &c), crate::nil.into());
    }
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:42-61 TestingOnlyExpandedBytes1024
/// Return the decapsulation key as a byte slice using the full expanded
/// NIST encoding.
///
/// This should only be used for ACVP testing. For all other purposes
/// prefer the Bytes method that returns the (much smaller) seed.
pub fn TestingOnlyExpandedBytes1024(dk: &DecapsulationKey1024) -> slice<byte> {
    // Go: b := make([]byte, 0, decapsulationKeySize1024)
    let mut b = empty1024();

    // ByteEncode₁₂(s)
    let mut i: usize = 0;
    while i < k1024 {
        b = polyByteEncode(b, dk.decryptionKey1024.s[i]);
        i += 1;
    }

    // ByteEncode₁₂(t) || ρ
    let mut i: usize = 0;
    while i < k1024 {
        b = polyByteEncode(b, dk.encryptionKey1024.t[i]);
        i += 1;
    }
    b = append!(b, slice::__from_vec(dk.ρ.to_vec())...);

    // H(ek) || z
    b = append!(b, slice::__from_vec(dk.h.to_vec())...);
    b = append!(b, slice::__from_vec(dk.z.to_vec())...);

    return b;
}

impl EncapsulationKey1024 {
    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:82-86 EncapsulationKey1024.Bytes
    /// Return the encapsulation key as a byte slice.
    pub fn Bytes(&self) -> slice<byte> {
        // The actual logic is in a separate function to outline this allocation.
        // Go: b := make([]byte, 0, EncapsulationKeySize1024); return ek.bytes(b)
        return self.bytes(empty1024());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:88-94 EncapsulationKey1024.bytes
    fn bytes(&self, b: slice<byte>) -> slice<byte> {
        // Go: for i := range ek.t { b = polyByteEncode(b, ek.t[i]) }
        let mut b = b;
        let mut i: usize = 0;
        while i < k1024 {
            b = polyByteEncode(b, self.encryptionKey1024.t[i]);
            i += 1;
        }
        // Go: b = append(b, ek.ρ[:]...)
        b = append!(b, slice::__from_vec(self.ρ.to_vec())...);
        return b;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:274-278 EncapsulationKey1024.Encapsulate
    /// Generate a shared key and an associated ciphertext from an
    /// encapsulation key, drawing random bytes from a DRBG.
    ///
    /// The shared key must be kept secret.
    pub fn Encapsulate(&self) -> (slice<byte>, slice<byte>) {
        // The actual logic is in a separate function to outline this allocation.
        // Go: var cc [CiphertextSize1024]byte; return ek.encapsulate(&cc)
        let mut cc = [0u8; CiphertextSize1024];
        return self.encapsulate(&mut cc);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:280-287 EncapsulationKey1024.encapsulate
    fn encapsulate(&self, cc: &mut [byte; CiphertextSize1024]) -> (slice<byte>, slice<byte>) {
        // Go: var m [messageSize]byte; drbg.Read(m[:])
        let mut m = [0u8; messageSize];
        let mut mb = slice::__from_vec(m.to_vec());
        let _ = rand::Read(&mut mb);
        let mr: &[byte] = &mb;
        m.copy_from_slice(mr);
        // Note that the modulus check (step 2 of the encapsulation key check
        // from FIPS 203, Section 7.2) is performed by polyByteDecode in parseEK1024.
        fips140::RecordApproved();
        // Go: return kemEncaps1024(cc, ek, &m)
        return kemEncaps1024(cc, self, &m);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:291-294 EncapsulationKey1024.EncapsulateInternal
    /// A derandomized version of Encapsulate, exclusively for use in tests.
    pub fn EncapsulateInternal(&self, m: &[byte; 32]) -> (slice<byte>, slice<byte>) {
        // Go: cc := &[CiphertextSize1024]byte{}; return kemEncaps1024(cc, ek, m)
        let mut cc = [0u8; CiphertextSize1024];
        return kemEncaps1024(&mut cc, self, m);
    }
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:109-113 GenerateKey1024
/// Generate a new decapsulation key, drawing random bytes from a DRBG.
/// The decapsulation key must be kept secret.
pub fn GenerateKey1024() -> (Box<DecapsulationKey1024>, error) {
    // The actual logic is in a separate function to outline this allocation.
    // Go: dk := &DecapsulationKey1024{}; return generateKey1024(dk)
    let dk = Box::new(zeroDK1024());
    return generateKey1024(dk);
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:115-124 generateKey1024
fn generateKey1024(dk: Box<DecapsulationKey1024>) -> (Box<DecapsulationKey1024>, error) {
    // Go: var d [32]byte; drbg.Read(d[:]); var z [32]byte; drbg.Read(z[:])
    let mut dk = dk;
    let d = randomSeed1024();
    let z = randomSeed1024();
    // Go: kemKeyGen1024(dk, &d, &z)
    kemKeyGen1024(&mut dk, &d, &z);
    // Go: fips140.PCT("ML-KEM PCT", func() error { return kemPCT1024(dk) })
    //
    // The closure must stay lazy: PCT returns without calling it when FIPS
    // mode is off, and a full encapsulate+decapsulate round trip is not
    // something to run on every key generation by accident.
    fips140::PCT("ML-KEM PCT", || kemPCT1024(&dk));
    // Go: fips140.RecordApproved(); return dk, nil
    fips140::RecordApproved();
    return (dk, crate::nil.into());
}

// go: none — Go writes `var d [32]byte; drbg.Read(d[:])` inline at three
// call sites; this is that pair, with drbg.Read reduced to
// crypto/rand.Read as the file header explains.
fn randomSeed1024() -> [byte; 32] {
    let mut b = slice::__from_vec(alloc::vec![0u8; 32]);
    let _ = rand::Read(&mut b);
    let r: &[byte] = &b;
    let mut out = [0u8; 32];
    out.copy_from_slice(r);
    return out;
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:128-132 GenerateKeyInternal1024
/// A derandomized version of GenerateKey1024, exclusively for use in tests.
pub fn GenerateKeyInternal1024(d: &[byte; 32], z: &[byte; 32]) -> Box<DecapsulationKey1024> {
    // Go: dk := &DecapsulationKey1024{}; kemKeyGen1024(dk, d, z); return dk
    let mut dk = Box::new(zeroDK1024());
    kemKeyGen1024(&mut dk, d, z);
    return dk;
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:136-140 NewDecapsulationKey1024
/// Parse a decapsulation key from a 64-byte seed in the "d || z" form.
/// The seed must be uniformly random.
pub fn NewDecapsulationKey1024(seed: slice<byte>) -> (Box<DecapsulationKey1024>, error) {
    // The actual logic is in a separate function to outline this allocation.
    // Go: dk := &DecapsulationKey1024{}; return newKeyFromSeed1024(dk, seed)
    let dk = Box::new(zeroDK1024());
    return newKeyFromSeed1024(dk, seed);
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:142-151 newKeyFromSeed1024
fn newKeyFromSeed1024(
    dk: Box<DecapsulationKey1024>,
    seed: slice<byte>,
) -> (Box<DecapsulationKey1024>, error) {
    // Go: if len(seed) != SeedSize { return nil, errors.New("mlkem: invalid seed length") }
    if seed.Len() != int64(SeedSize) {
        return (Box::new(zeroDK1024()), errors::New("mlkem: invalid seed length"));
    }
    let mut dk = dk;
    // Go: d := (*[32]byte)(seed[:32]); z := (*[32]byte)(seed[32:])
    let raw: &[byte] = &seed;
    let mut d = [0u8; 32];
    d.copy_from_slice(&raw[..32]);
    let mut z = [0u8; 32];
    z.copy_from_slice(&raw[32..]);
    // Go: kemKeyGen1024(dk, d, z); fips140.RecordApproved(); return dk, nil
    kemKeyGen1024(&mut dk, &d, &z);
    fips140::RecordApproved();
    return (dk, crate::nil.into());
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:160-198 TestingOnlyNewDecapsulationKey1024
/// Parse a decapsulation key from its expanded NIST format.
///
/// Bytes() must not be called on the returned key, as it will not produce
/// the original seed.
///
/// This function should only be used for ACVP testing. Prefer
/// NewDecapsulationKey1024 for all other purposes.
pub fn TestingOnlyNewDecapsulationKey1024(b: slice<byte>) -> (Box<DecapsulationKey1024>, error) {
    // Go: if len(b) != decapsulationKeySize1024 { return nil, errors.New(…) }
    if b.Len() != int64(decapsulationKeySize1024) {
        return (
            Box::new(zeroDK1024()),
            errors::New("mlkem: invalid NIST decapsulation key length"),
        );
    }

    // Go: dk := &DecapsulationKey1024{}
    let mut dk = Box::new(zeroDK1024());
    let raw: &[byte] = &b;
    let mut p: usize = 0;
    // Go: for i := range dk.s { dk.s[i], err = polyByteDecode[nttElement](b[:encodingSize12]) … }
    let mut i: usize = 0;
    while i < k1024 {
        let chunk = slice::__from_vec(raw[p..p + encodingSize12].to_vec());
        let (v, err) = polyByteDecode::<nttElement>(chunk);
        if err != crate::nil {
            return (
                Box::new(zeroDK1024()),
                errors::New("mlkem: invalid secret key encoding"),
            );
        }
        dk.decryptionKey1024.s[i] = v;
        p += encodingSize12;
        i += 1;
    }

    // Go: ek, err := NewEncapsulationKey1024(b[:EncapsulationKeySize1024])
    let (ek, err) = NewEncapsulationKey1024(slice::__from_vec(
        raw[p..p + EncapsulationKeySize1024].to_vec(),
    ));
    if err != crate::nil {
        return (Box::new(zeroDK1024()), err);
    }
    // Go: dk.ρ = ek.ρ; dk.h = ek.h; dk.encryptionKey1024 = ek.encryptionKey1024
    dk.ρ = ek.ρ;
    dk.h = ek.h;
    dk.encryptionKey1024 = ek.encryptionKey1024;
    p += EncapsulationKeySize1024;

    // Go: if !bytes.Equal(dk.h[:], b[:32]) { return nil, errors.New(…) }
    if dk.h[..] != raw[p..p + 32] {
        return (
            Box::new(zeroDK1024()),
            errors::New("mlkem: inconsistent H(ek) in encoded bytes"),
        );
    }
    p += 32;

    // Go: copy(dk.z[:], b)
    dk.z.copy_from_slice(&raw[p..p + 32]);

    // Generate a random d value for use in Bytes(). This is a safety
    // mechanism that avoids returning a broken key vs a random key if this
    // function is called in contravention of the
    // TestingOnlyNewDecapsulationKey1024 function comment advising against it.
    // Go: drbg.Read(dk.d[:])
    dk.d = randomSeed1024();

    return (dk, crate::nil.into());
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:205-247 kemKeyGen1024
/// Generate a decapsulation key.
///
/// It implements ML-KEM.KeyGen_internal according to FIPS 203,
/// Algorithm 16, and K-PKE.KeyGen according to FIPS 203, Algorithm 13.
/// The two are merged to save copies and allocations.
fn kemKeyGen1024(dk: &mut DecapsulationKey1024, d: &[byte; 32], z: &[byte; 32]) {
    // Go: dk.d = *d; dk.z = *z
    dk.d = *d;
    dk.z = *z;

    // Go: g := sha3.New512(); g.Write(d[:]); g.Write([]byte{k1024})
    let mut g = sha3::New512();
    let _ = g.Write(slice::__from_vec(d.to_vec()));
    // Module dimension as a domain separator.
    let _ = g.Write(slice::__from_vec(alloc::vec![byte(k1024)]));
    // Go: G := g.Sum(make([]byte, 0, 64)); ρ, σ := G[:32], G[32:]
    let G = g.Sum(empty1024());
    let Graw: &[byte] = &G;
    let ρ: &[byte] = &Graw[..32];
    let σ: &[byte] = &Graw[32..];
    // Go: dk.ρ = [32]byte(ρ)
    dk.ρ.copy_from_slice(ρ);

    // Go: A := &dk.a
    //     for i := byte(0); i < k1024; i++ { for j := byte(0); j < k1024; j++ {
    //         A[i*k1024+j] = sampleNTT(ρ, j, i) } }
    let mut i: usize = 0;
    while i < k1024 {
        let mut j: usize = 0;
        while j < k1024 {
            dk.encryptionKey1024.a[i * k1024 + j] = sampleNTT(ρ, byte(j), byte(i));
            j += 1;
        }
        i += 1;
    }

    // Go: var N byte; s := &dk.s
    //     for i := range s { s[i] = ntt(samplePolyCBD(σ, N)); N++ }
    let mut N: byte = 0;
    let mut i: usize = 0;
    while i < k1024 {
        dk.decryptionKey1024.s[i] = ntt(samplePolyCBD(σ, N));
        N += 1;
        i += 1;
    }
    // Go: e := make([]nttElement, k1024)
    //     for i := range e { e[i] = ntt(samplePolyCBD(σ, N)); N++ }
    let mut e = [zeroNTT1024(); k1024];
    let mut i: usize = 0;
    while i < k1024 {
        e[i] = ntt(samplePolyCBD(σ, N));
        N += 1;
        i += 1;
    }

    // Go: t := &dk.t
    //     for i := range t { t[i] = e[i]; for j := range s {
    //         t[i] = polyAdd(t[i], nttMul(A[i*k1024+j], s[j])) } }
    let mut i: usize = 0;
    while i < k1024 {
        // t = A ◦ s + e
        dk.encryptionKey1024.t[i] = e[i];
        let mut j: usize = 0;
        while j < k1024 {
            dk.encryptionKey1024.t[i] = polyAdd(
                dk.encryptionKey1024.t[i],
                nttMul(dk.encryptionKey1024.a[i * k1024 + j], dk.decryptionKey1024.s[j]),
            );
            j += 1;
        }
        i += 1;
    }

    // Go: H := sha3.New256(); ek := dk.EncapsulationKey().Bytes()
    //     H.Write(ek); H.Sum(dk.h[:0])
    let mut H = sha3::New256();
    let ek = dk.EncapsulationKey().Bytes();
    let _ = H.Write(ek);
    let sum = H.Sum(empty1024());
    let sr: &[byte] = &sum;
    dk.h.copy_from_slice(&sr[..32]);
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:257-268 kemPCT1024
/// Perform a Pairwise Consistency Test per FIPS 140-3 IG 10.3.A
/// Additional Comment 1: "For key pairs generated for use with approved
/// KEMs in FIPS 203, the PCT shall consist of applying the encapsulation
/// key ek to encapsulate a shared secret K leading to ciphertext c, and
/// then applying decapsulation key dk to retrieve the same shared secret
/// K. The PCT passes if the two shared secret K values are equal. The PCT
/// shall be performed either when keys are generated/imported, prior to
/// the first exportation, or prior to the first operational use (if not
/// exported before the first use)."
///
fn kemPCT1024(dk: &DecapsulationKey1024) -> error {
    // Go: ek := dk.EncapsulationKey(); K, c := ek.Encapsulate()
    let ek = dk.EncapsulationKey();
    let (K, c) = ek.Encapsulate();
    // Go: K1, err := dk.Decapsulate(c); if err != nil { return err }
    let (K1, err) = dk.Decapsulate(c);
    if err != crate::nil {
        return err;
    }
    // Go: if subtle.ConstantTimeCompare(K, K1) != 1 { return errors.New("mlkem: PCT failed") }
    if subtle::ConstantTimeCompare(&K, &K1) != 1 {
        return errors::New("mlkem: PCT failed");
    }
    // Go: return nil
    return crate::nil.into();
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:299-307 kemEncaps1024
/// Generate a shared key and an associated ciphertext.
///
/// It implements ML-KEM.Encaps_internal according to FIPS 203,
/// Algorithm 17.
fn kemEncaps1024(
    cc: &mut [byte; CiphertextSize1024],
    ek: &EncapsulationKey1024,
    m: &[byte; messageSize],
) -> (slice<byte>, slice<byte>) {
    // Go: g := sha3.New512(); g.Write(m[:]); g.Write(ek.h[:]); G := g.Sum(nil)
    let mut g = sha3::New512();
    let _ = g.Write(slice::__from_vec(m.to_vec()));
    let _ = g.Write(slice::__from_vec(ek.h.to_vec()));
    let G = g.Sum(empty1024());
    let Graw: &[byte] = &G;
    // Go: K, r := G[:SharedKeySize], G[SharedKeySize:]
    let K = slice::__from_vec(Graw[..SharedKeySize].to_vec());
    let r: &[byte] = &Graw[SharedKeySize..];
    // Go: c = pkeEncrypt1024(cc, &ek.encryptionKey1024, m, r); return K, c
    let c = pkeEncrypt1024(cc, &ek.encryptionKey1024, m, r);
    return (K, c);
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:311-315 NewEncapsulationKey1024
/// Parse an encapsulation key from its encoded form. If the encapsulation
/// key is not valid, NewEncapsulationKey1024 returns an error.
pub fn NewEncapsulationKey1024(encapsulationKey: slice<byte>) -> (EncapsulationKey1024, error) {
    // The actual logic is in a separate function to outline this allocation.
    // Go: ek := &EncapsulationKey1024{}; return parseEK1024(ek, encapsulationKey)
    let ek = zeroEK1024();
    return parseEK1024(ek, encapsulationKey);
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:321-347 parseEK1024
/// Parse an encryption key from its encoded form.
///
/// It implements the initial stages of K-PKE.Encrypt according to
/// FIPS 203, Algorithm 14.
fn parseEK1024(ek: EncapsulationKey1024, ekPKE: slice<byte>) -> (EncapsulationKey1024, error) {
    // Go: if len(ekPKE) != EncapsulationKeySize1024 { return nil, errors.New(…) }
    if ekPKE.Len() != int64(EncapsulationKeySize1024) {
        return (
            zeroEK1024(),
            errors::New("mlkem: invalid encapsulation key length"),
        );
    }
    let mut ek = ek;

    // Go: h := sha3.New256(); h.Write(ekPKE); h.Sum(ek.h[:0])
    let mut h = sha3::New256();
    let _ = h.Write(ekPKE.clone());
    let sum = h.Sum(empty1024());
    let sr: &[byte] = &sum;
    ek.h.copy_from_slice(&sr[..32]);

    // Go: for i := range ek.t { ek.t[i], err = polyByteDecode[nttElement](ekPKE[:encodingSize12]) … }
    let raw: &[byte] = &ekPKE;
    let mut p: usize = 0;
    let mut i: usize = 0;
    while i < k1024 {
        let chunk = slice::__from_vec(raw[p..p + encodingSize12].to_vec());
        let (v, err) = polyByteDecode::<nttElement>(chunk);
        if err != crate::nil {
            return (zeroEK1024(), err);
        }
        ek.encryptionKey1024.t[i] = v;
        p += encodingSize12;
        i += 1;
    }
    // Go: copy(ek.ρ[:], ekPKE)
    ek.ρ.copy_from_slice(&raw[p..p + 32]);

    // Go: for i := byte(0); i < k1024; i++ { for j := byte(0); j < k1024; j++ {
    //         ek.a[i*k1024+j] = sampleNTT(ek.ρ[:], j, i) } }
    let ρ = ek.ρ;
    let mut i: usize = 0;
    while i < k1024 {
        let mut j: usize = 0;
        while j < k1024 {
            ek.encryptionKey1024.a[i * k1024 + j] = sampleNTT(&ρ, byte(j), byte(i));
            j += 1;
        }
        i += 1;
    }

    return (ek, crate::nil.into());
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:353-390 pkeEncrypt1024
/// Encrypt a plaintext message.
///
/// It implements K-PKE.Encrypt according to FIPS 203, Algorithm 14,
/// although the computation of t and AT is done in parseEK1024.
fn pkeEncrypt1024(
    cc: &mut [byte; CiphertextSize1024],
    ex: &encryptionKey1024,
    m: &[byte; messageSize],
    rnd: &[byte],
) -> slice<byte> {
    // Go: var N byte; r, e1 := make([]nttElement, k1024), make([]ringElement, k1024)
    let mut N: byte = 0;
    let mut r = [zeroNTT1024(); k1024];
    let mut e1 = [ringElement([0; n]); k1024];
    // Go: for i := range r { r[i] = ntt(samplePolyCBD(rnd, N)); N++ }
    let mut i: usize = 0;
    while i < k1024 {
        r[i] = ntt(samplePolyCBD(rnd, N));
        N += 1;
        i += 1;
    }
    // Go: for i := range e1 { e1[i] = samplePolyCBD(rnd, N); N++ }
    let mut i: usize = 0;
    while i < k1024 {
        e1[i] = samplePolyCBD(rnd, N);
        N += 1;
        i += 1;
    }
    // Go: e2 := samplePolyCBD(rnd, N)
    let e2 = samplePolyCBD(rnd, N);

    // Go: u := make([]ringElement, k1024) // NTT⁻¹(AT ◦ r) + e1
    let mut u = [ringElement([0; n]); k1024];
    let mut i: usize = 0;
    while i < k1024 {
        u[i] = e1[i];
        let mut j: usize = 0;
        while j < k1024 {
            // Note that i and j are inverted, as we need the transposed of A.
            u[i] = polyAdd(u[i], inverseNTT(nttMul(ex.a[j * k1024 + i], r[j])));
            j += 1;
        }
        i += 1;
    }

    // Go: μ := ringDecodeAndDecompress1(m)
    let μ = ringDecodeAndDecompress1(m);

    // Go: var vNTT nttElement // t⊺ ◦ r
    //     for i := range ex.t { vNTT = polyAdd(vNTT, nttMul(ex.t[i], r[i])) }
    let mut vNTT = zeroNTT1024();
    let mut i: usize = 0;
    while i < k1024 {
        vNTT = polyAdd(vNTT, nttMul(ex.t[i], r[i]));
        i += 1;
    }
    // Go: v := polyAdd(polyAdd(inverseNTT(vNTT), e2), μ)
    let v = polyAdd(polyAdd(inverseNTT(vNTT), e2), μ);

    // Go: c := cc[:0]
    //     for _, f := range u { c = ringCompressAndEncode11(c, f) }
    //     c = ringCompressAndEncode5(c, v)
    let mut c = empty1024();
    let mut i: usize = 0;
    while i < k1024 {
        c = ringCompressAndEncode11(c, u[i]);
        i += 1;
    }
    c = ringCompressAndEncode5(c, v);

    // Go writes through `cc[:0]`, so the caller's array holds the result;
    // goish's slices don't alias, so fill it explicitly.
    let cr: &[byte] = &c;
    cc.copy_from_slice(cr);
    return c;
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:410-428 kemDecaps1024
/// Produce a shared key from a ciphertext.
///
/// It implements ML-KEM.Decaps_internal according to FIPS 203,
/// Algorithm 18.
fn kemDecaps1024(dk: &DecapsulationKey1024, c: &[byte; CiphertextSize1024]) -> slice<byte> {
    fips140::RecordApproved();
    // Go: m := pkeDecrypt1024(&dk.decryptionKey1024, c)
    let m = pkeDecrypt1024(&dk.decryptionKey1024, c);
    // Go: g := sha3.New512(); g.Write(m[:]); g.Write(dk.h[:])
    let mut g = sha3::New512();
    let _ = g.Write(m.clone());
    let _ = g.Write(slice::__from_vec(dk.h.to_vec()));
    // Go: G := g.Sum(make([]byte, 0, 64)); Kprime, r := G[:SharedKeySize], G[SharedKeySize:]
    let G = g.Sum(empty1024());
    let Graw: &[byte] = &G;
    let Kprime = slice::__from_vec(Graw[..SharedKeySize].to_vec());
    let r: &[byte] = &Graw[SharedKeySize..];
    // Go: J := sha3.NewShake256(); J.Write(dk.z[:]); J.Write(c[:])
    let mut J = sha3::NewShake256();
    let _ = J.Write(slice::__from_vec(dk.z.to_vec()));
    let _ = J.Write(slice::__from_vec(c.to_vec()));
    // Go: Kout := make([]byte, SharedKeySize); J.Read(Kout)
    let mut KoutV: Vec<byte> = alloc::vec![0u8; SharedKeySize];
    J.Read(&mut KoutV);
    let mut Kout = slice::__from_vec(KoutV);
    // Go: var cc [CiphertextSize1024]byte
    //     c1 := pkeEncrypt1024(&cc, &dk.encryptionKey1024, (*[32]byte)(m), r)
    let mut cc = [0u8; CiphertextSize1024];
    let mraw: &[byte] = &m;
    let mut m32 = [0u8; 32];
    m32.copy_from_slice(mraw);
    let c1 = pkeEncrypt1024(&mut cc, &dk.encryptionKey1024, &m32, r);

    // Go: subtle.ConstantTimeCopy(subtle.ConstantTimeCompare(c[:], c1), Kout, Kprime)
    let cs = slice::__from_vec(c.to_vec());
    subtle::ConstantTimeCopy(
        subtle::ConstantTimeCompare(&cs, &c1),
        &mut Kout,
        &Kprime,
    );
    return Kout;
}

// go: sdk 1.25.5 crypto/internal/fips140/mlkem/mlkem1024.go:434-451 pkeDecrypt1024
/// Decrypt a ciphertext.
///
/// It implements K-PKE.Decrypt according to FIPS 203, Algorithm 15,
/// although s is retained from kemKeyGen1024.
fn pkeDecrypt1024(dx: &decryptionKey1024, c: &[byte; CiphertextSize1024]) -> slice<byte> {
    // Go: u := make([]ringElement, k1024)
    //     for i := range u { b := (*[encodingSize11]byte)(c[…]); u[i] = ringDecodeAndDecompress11(b) }
    let mut u = [ringElement([0; n]); k1024];
    let mut i: usize = 0;
    while i < k1024 {
        let mut b = [0u8; encodingSize11];
        b.copy_from_slice(&c[encodingSize11 * i..encodingSize11 * (i + 1)]);
        u[i] = ringDecodeAndDecompress11(&b);
        i += 1;
    }

    // Go: b := (*[encodingSize5]byte)(c[encodingSize11*k1024:]); v := ringDecodeAndDecompress5(b)
    let mut b = [0u8; encodingSize5];
    b.copy_from_slice(&c[encodingSize11 * k1024..]);
    let v = ringDecodeAndDecompress5(&b);

    // Go: var mask nttElement // s⊺ ◦ NTT(u)
    //     for i := range dx.s { mask = polyAdd(mask, nttMul(dx.s[i], ntt(u[i]))) }
    let mut mask = zeroNTT1024();
    let mut i: usize = 0;
    while i < k1024 {
        mask = polyAdd(mask, nttMul(dx.s[i], ntt(u[i])));
        i += 1;
    }
    // Go: w := polySub(v, inverseNTT(mask))
    let w = polySub(v, inverseNTT(mask));

    // Go: return ringCompressAndEncode1(nil, w)
    return ringCompressAndEncode1(empty1024(), w);
}
