// go: file strconv/itoa.go decls: FormatUint, FormatInt, Itoa, AppendInt, AppendUint, small, formatBits, isPowerOfTwo
//
// itoa.go — FormatUint, FormatInt, Itoa, AppendInt, AppendUint and the
// shared `formatBits` they all funnel into, plus the small-integer fast
// path and the digit tables.

extern crate alloc;

use crate::convert::{int as toint, uint as touint, uint64 as touint64};
use crate::goslice::slice;
use crate::gostring::string;
use crate::types::{byte, int, uint};

// ─── Constants ────────────────────────────────────────────────────────

// go: sdk 1.25.5 strconv/itoa.go:9-9 fastSmalls
/// Enable the fast path for small integers.
pub(crate) const fastSmalls: bool = true;

// go: sdk 1.25.5 strconv/itoa.go:66-66 nSmalls
pub(crate) const nSmalls: int = 100;

// go: sdk 1.25.5 strconv/itoa.go:68-77 smallsString
/// The two-digit decimal renderings of 00..99, back to back. `small`
/// and the base-10 path of `formatBits` both index straight into it.
pub(crate) const smallsString: &[u8] = b"00010203040506070809\
10111213141516171819\
20212223242526272829\
30313233343536373839\
40414243444546474849\
50515253545556575859\
60616263646566676869\
70717273747576777879\
80818283848586878889\
90919293949596979899";

// go: sdk 1.25.5 strconv/itoa.go:79-79 host32bit
/// Go computes this as `^uint(0)>>32 == 0`. goish's `uint` is 64-bit on
/// every target it builds for, so the 32-bit lower-digit loop in
/// `formatBits` is compiled but never taken — kept so the two files
/// stay line-for-line comparable.
pub(crate) const host32bit: bool = (uint::MAX >> 32) == 0;

// go: sdk 1.25.5 strconv/itoa.go:81-81 digits
pub(crate) const digits: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";

// ─── FormatUint / FormatInt / Itoa / AppendInt / AppendUint ───────────

// go: sdk 1.25.5 strconv/itoa.go:14-20 FormatUint
/// `strconv.FormatUint` — the string representation of `i` in the given
/// base, for 2 <= base <= 36, using lower-case letters for digit values
/// >= 10.
pub fn FormatUint(i: uint, base: int) -> string {
    if fastSmalls && i < touint(nSmalls) && base == 10 {
        return small(toint(i));
    }
    let (_, s) = formatBits(slice::new(), i, base, false, false);
    return s;
}

// go: sdk 1.25.5 strconv/itoa.go:25-31 FormatInt
/// `strconv.FormatInt` — the string representation of `i` in the given
/// base, for 2 <= base <= 36.
pub fn FormatInt(i: int, base: int) -> string {
    if fastSmalls && 0 <= i && i < nSmalls && base == 10 {
        return small(i);
    }
    let (_, s) = formatBits(slice::new(), touint64(i), base, i < 0, false);
    return s;
}

// go: sdk 1.25.5 strconv/itoa.go:34-36 Itoa
/// `strconv.Itoa` — equivalent to `FormatInt(int64(i), 10)`.
pub fn Itoa(i: int) -> string {
    return FormatInt(i, 10);
}

// go: sdk 1.25.5 strconv/itoa.go:40-46 AppendInt
/// `strconv.AppendInt` — append the string form of `i`, as generated by
/// `FormatInt`, to `dst`.
pub fn AppendInt(dst: slice<byte>, i: int, base: int) -> slice<byte> {
    if fastSmalls && 0 <= i && i < nSmalls && base == 10 {
        let mut v = dst.__into_vec();
        v.extend_from_slice(small(i).as_bytes());
        return slice::__from_vec(v);
    }
    let (d, _) = formatBits(dst, touint64(i), base, i < 0, true);
    return d;
}

// go: sdk 1.25.5 strconv/itoa.go:50-56 AppendUint
/// `strconv.AppendUint` — append the string form of `i`, as generated
/// by `FormatUint`, to `dst`.
pub fn AppendUint(dst: slice<byte>, i: uint, base: int) -> slice<byte> {
    if fastSmalls && i < touint(nSmalls) && base == 10 {
        let mut v = dst.__into_vec();
        v.extend_from_slice(small(toint(i)).as_bytes());
        return slice::__from_vec(v);
    }
    let (d, _) = formatBits(dst, i, base, false, true);
    return d;
}

// go: sdk 1.25.5 strconv/itoa.go:59-64 small
/// The string for an `i` with 0 <= i < nSmalls.
fn small(i: int) -> string {
    let i = i as usize;
    if i < 10 {
        return string::from_bytes(&digits[i..i + 1]);
    }
    return string::from_bytes(&smallsString[i * 2..i * 2 + 2]);
}

// ─── formatBits ───────────────────────────────────────────────────────

// go: sdk 1.25.5 strconv/itoa.go:88-194 formatBits
/// `formatBits` computes the string representation of `u` in the given
/// base. If `neg` is set, `u` is treated as a negative int64 value. If
/// `append_` is set the string is appended to `dst` and the resulting
/// byte slice is returned as the first result; otherwise the string is
/// returned as the second.
pub(crate) fn formatBits(
    dst: slice<byte>,
    mut u: uint,
    base: int,
    neg: bool,
    append_: bool,
) -> (slice<byte>, string) {
    if base < 2 || base > toint(digits.len()) {
        panic!("strconv: illegal AppendInt/FormatInt base");
    }
    // 2 <= base && base <= len(digits)

    let mut a = [0u8; 64 + 1]; // +1 for sign of 64bit value in base 2
    let mut i = a.len();

    if neg {
        u = u.wrapping_neg();
    }

    // convert bits
    // We use uint values where we can because those will
    // fit into a single register even on a 32bit machine.
    if base == 10 {
        // common case: use constants for / because
        // the compiler can optimize it into a multiply+shift

        if host32bit {
            // convert the lower digits using 32bit operations
            while u >= 1_000_000_000 {
                // Avoid using r = a%b in addition to q = a/b
                // since 64bit division and modulo operations
                // are calculated by runtime functions on 32bit machines.
                let q = u / 1_000_000_000;
                let mut us: uint = u - q * 1_000_000_000; // u % 1e9 fits into a uint
                let mut j = 4;
                while j > 0 {
                    let is = (us % 100 * 2) as usize;
                    us /= 100;
                    i -= 2;
                    a[i + 1] = smallsString[is + 1];
                    a[i] = smallsString[is];
                    j -= 1;
                }

                // us < 10, since it contains the last digit
                // from the initial 9-digit us.
                i -= 1;
                a[i] = smallsString[(us * 2 + 1) as usize];

                u = q;
            }
            // u < 1e9
        }

        // u guaranteed to fit into a uint
        let mut us: uint = u;
        while us >= 100 {
            let is = (us % 100 * 2) as usize;
            us /= 100;
            i -= 2;
            a[i + 1] = smallsString[is + 1];
            a[i] = smallsString[is];
        }

        // us < 100
        let is = (us * 2) as usize;
        i -= 1;
        a[i] = smallsString[is + 1];
        if us >= 10 {
            i -= 1;
            a[i] = smallsString[is];
        }
    } else if isPowerOfTwo(base) {
        // Use shifts and masks instead of / and %.
        let shift = touint(crate::math::bits::TrailingZeros(touint(base)));
        let b = touint64(base);
        let m = touint(base) - 1; // == 1<<shift - 1
        while u >= b {
            i -= 1;
            a[i] = digits[(u & m) as usize];
            u >>= shift;
        }
        // u < base
        i -= 1;
        a[i] = digits[u as usize];
    } else {
        // general case
        let b = touint64(base);
        while u >= b {
            i -= 1;
            // Avoid using r = a%b in addition to q = a/b
            // since 64bit division and modulo operations
            // are calculated by runtime functions on 32bit machines.
            let q = u / b;
            a[i] = digits[(u - q * b) as usize];
            u = q;
        }
        // u < base
        i -= 1;
        a[i] = digits[u as usize];
    }

    // add sign, if any
    if neg {
        i -= 1;
        a[i] = b'-';
    }

    if append_ {
        let mut v = dst.__into_vec();
        v.extend_from_slice(&a[i..]);
        return (slice::__from_vec(v), string::new());
    }
    return (slice::new(), string::from_bytes(&a[i..]));
}

// go: sdk 1.25.5 strconv/itoa.go:197-199 isPowerOfTwo
fn isPowerOfTwo(x: int) -> bool {
    return x & (x - 1) == 0;
}
