// runtime::mcentral::sizeclasses — size-class tables.
//
// Verbatim port of the data tables in
// `internal/runtime/gc/sizeclasses.go` (auto-generated by Go's
// `mksizeclasses.go`). 67 active classes (1..=67) plus class 0 for
// the "size 0" sentinel; class N covers up to `SIZE_TO_SIZE[N]`
// bytes, allocated from spans of `NPAGES_OF[N]` pages.
//
// Lookup rules (from `internal/runtime/gc/sizeclasses.go:84-93`):
//
//   - Sizes 1..=1024 use `SIZE_TO_CLASS_8` indexed by `(size+7)/8`.
//   - Sizes 1025..=32768 use `SIZE_TO_CLASS_128` indexed by
//     `(size-1025)/128`.
//   - Above 32768 → large path (mheap directly).

#![allow(dead_code)]

pub const NUM_SIZE_CLASSES: usize = 68;
pub const MAX_SMALL_SIZE: usize = 32768;
pub const SMALL_SIZE_DIV: usize = 8;
pub const SMALL_SIZE_MAX: usize = 1024;
pub const LARGE_SIZE_DIV: usize = 128;
pub const MAX_OBJS_PER_SPAN: usize = 1024;
pub const MIN_HEAP_ALIGN: usize = 8;

/// `SizeClassToSize[c]` — bytes per slot in class `c`.
pub static SIZE_OF_CLASS: [u16; NUM_SIZE_CLASSES] = [
    0, 8, 16, 24, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256, 288, 320,
    352, 384, 416, 448, 480, 512, 576, 640, 704, 768, 896, 1024, 1152, 1280, 1408, 1536, 1792,
    2048, 2304, 2688, 3072, 3200, 3456, 4096, 4864, 5376, 6144, 6528, 6784, 6912, 8192, 9472, 9728,
    10240, 10880, 12288, 13568, 14336, 16384, 18432, 19072, 20480, 21760, 24576, 27264, 28672,
    32768,
];

/// `SizeClassToNPages[c]` — pages per span in class `c`.
pub static NPAGES_OF_CLASS: [u8; NUM_SIZE_CLASSES] = [
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 2, 1, 2, 1, 2, 1, 3, 2, 3, 1, 3, 2, 3, 4, 5, 6, 1, 7, 6, 5, 4, 3, 5, 7, 2, 9, 7, 5, 8,
    3, 10, 7, 4,
];

/// `SizeToSizeClass8` — class lookup for sizes ≤ 1024.
/// Indexed by `(size + 7) / 8`.
pub static SIZE_TO_CLASS_8: [u8; SMALL_SIZE_MAX / SMALL_SIZE_DIV + 1] = [
    0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15,
    16, 16, 17, 17, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23,
    23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28,
    28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
    32, 32, 32, 32, 32, 32,
];

/// `SizeToSizeClass128` — class lookup for sizes 1025..=32768.
/// Indexed by `(size - 1025) / 128`.
pub static SIZE_TO_CLASS_128: [u8; (MAX_SMALL_SIZE - SMALL_SIZE_MAX) / LARGE_SIZE_DIV + 1] = [
    32, 33, 34, 35, 36, 37, 37, 38, 38, 39, 39, 40, 40, 40, 41, 41, 41, 42, 43, 43, 44, 44, 44, 44,
    44, 45, 45, 45, 45, 45, 45, 46, 46, 46, 46, 47, 47, 47, 47, 47, 47, 48, 48, 48, 49, 49, 50, 51,
    51, 51, 51, 51, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 53, 53, 54, 54, 54,
    54, 55, 55, 55, 55, 55, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 57, 57, 57, 57, 57, 57, 57,
    57, 57, 57, 58, 58, 58, 58, 58, 58, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59,
    59, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 61, 61, 61, 61, 61, 62, 62,
    62, 62, 62, 62, 62, 62, 62, 62, 62, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 65, 65, 65, 65, 65, 65, 65,
    65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67,
    67, 67, 67, 67, 67, 67, 67, 67, 67,
];

/// Map a `(size, align)` request to the smallest size class that
/// satisfies both. Returns `None` if `size > MAX_SMALL_SIZE` (caller
/// should route to mheap directly).
#[inline]
pub fn class_for(size: usize, align: usize) -> Option<u8> {
    // Round size up to the requested alignment so the slot's natural
    // alignment (which is at least its elemsize's largest power-of-2
    // factor, equal to the class's listed min-align) suffices for
    // the caller's `align` request.
    let mut eff = if size == 0 { 1 } else { size };
    if align > MIN_HEAP_ALIGN {
        eff = (eff + align - 1) & !(align - 1);
    }
    if eff > MAX_SMALL_SIZE {
        return None;
    }
    // Both lookups use Go's `divRoundUp(size, div)` semantics so that
    // a size landing exactly on a class boundary maps to that class
    // rather than the next-smaller one.
    let class = if eff <= SMALL_SIZE_MAX {
        SIZE_TO_CLASS_8[(eff + SMALL_SIZE_DIV - 1) / SMALL_SIZE_DIV]
    } else {
        let off = eff - SMALL_SIZE_MAX;
        SIZE_TO_CLASS_128[(off + LARGE_SIZE_DIV - 1) / LARGE_SIZE_DIV]
    };
    Some(class)
}
