// crc64_smoke — exercise hash/crc64 (ISO + ECMA polynomials).
// (hash/crc64/crc64.go)
//
// Checks 1-13 use the `golden` table from Go 1.25's
// hash/crc64/crc64_test.go. Checks 14-18 use values printed by a
// running Go 1.25.5 (tools/gen_crc64_ref.go, run through
// scripts/goref.sh) — they cover the slicing-by-8 fast path, both
// sides of its 2048-byte threshold for a custom polynomial, and the
// marshal/unmarshal/Clone surface, none of which the golden table
// reaches.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use goish::convert::byte as tobyte;
use goish::convert::bytes as to_bytes;
use goish::fmt;
use goish::goslice::slice;
use goish::hash::crc64;
use goish::hash::{Hash, Hash64};
use goish::io::Writer as _;
use goish::nil;
use goish::syscall;
use goish::types::{byte, uint64};

// The Go reference corpus: byte i = (i*7+3)%251, generated by
// tools/gen_crc64_ref.go and cross-checked against a running Go 1.25.5.
fn mk(n: usize) -> slice<byte> {
    let mut v: Vec<byte> = Vec::with_capacity(n);
    let mut i: usize = 0;
    while i < n {
        v.push(tobyte((i * 7 + 3) % 251));
        i += 1;
    }
    slice::<byte>::__from_vec(v)
}

fn from_hex(h: &[u8]) -> slice<byte> {
    fn nib(c: u8) -> byte {
        if c >= b'a' {
            return c - b'a' + 10;
        }
        return c - b'0';
    }
    let mut v: Vec<byte> = Vec::with_capacity(h.len() / 2);
    let mut i: usize = 0;
    while i < h.len() {
        v.push((nib(h[i]) << 4) | nib(h[i + 1]));
        i += 2;
    }
    slice::<byte>::__from_vec(v)
}

fn empty_buf() -> slice<byte> {
    slice::<byte>::__from_vec(Vec::new())
}

fn equal_bytes(a: slice<byte>, b: slice<byte>) -> bool {
    let aa: &[byte] = &a;
    let bb: &[byte] = &b;
    aa == bb
}

#[goish::main]
fn main() {
    let mut failed = 0;

    // 1. ISO Checksum("") = 0.
    {
        let tab = crc64::ISOTable();
        if crc64::Checksum(to_bytes(""), &tab) == 0 {
            fmt::Println!("[ 1] ISO empty                 PASS");
        } else {
            fmt::Println!("[ 1] ISO empty                 FAIL");
            failed += 1;
        }
    }

    // 2. ECMA Checksum("") = 0.
    {
        let tab = crc64::ECMATable();
        if crc64::Checksum(to_bytes(""), &tab) == 0 {
            fmt::Println!("[ 2] ECMA empty                PASS");
        } else {
            fmt::Println!("[ 2] ECMA empty                FAIL");
            failed += 1;
        }
    }

    // 3. ISO Checksum("a") = 0x3420000000000000.
    {
        let tab = crc64::ISOTable();
        if crc64::Checksum(to_bytes("a"), &tab) == 0x3420000000000000 {
            fmt::Println!("[ 3] ISO \"a\"                   PASS");
        } else {
            fmt::Println!("[ 3] ISO \"a\"                   FAIL");
            failed += 1;
        }
    }

    // 4. ECMA Checksum("a") = 0x330284772e652b05.
    {
        let tab = crc64::ECMATable();
        if crc64::Checksum(to_bytes("a"), &tab) == 0x330284772e652b05 {
            fmt::Println!("[ 4] ECMA \"a\"                  PASS");
        } else {
            fmt::Println!("[ 4] ECMA \"a\"                  FAIL");
            failed += 1;
        }
    }

    // 5. ECMA Checksum("abc") = 0x2cd8094a1a277627.
    {
        let tab = crc64::ECMATable();
        if crc64::Checksum(to_bytes("abc"), &tab) == 0x2cd8094a1a277627 {
            fmt::Println!("[ 5] ECMA \"abc\"                PASS");
        } else {
            fmt::Println!("[ 5] ECMA \"abc\"                FAIL");
            failed += 1;
        }
    }

    // 6. ISO Checksum("abcdefghij") = 0x7f5b6e21b002d367.
    {
        let tab = crc64::ISOTable();
        if crc64::Checksum(to_bytes("abcdefghij"), &tab) == 0x7f5b6e21b002d367 {
            fmt::Println!("[ 6] ISO \"abcdefghij\"          PASS");
        } else {
            fmt::Println!("[ 6] ISO \"abcdefghij\"          FAIL");
            failed += 1;
        }
    }

    // 7. New + streaming Write equals one-shot Checksum.
    {
        let tab = crc64::ECMATable();
        let mut h = crc64::New(tab.clone());
        let _ = h.Write(to_bytes("ab"));
        let _ = h.Write(to_bytes("c"));
        if h.Sum64() == 0x2cd8094a1a277627 {
            fmt::Println!("[ 7] ECMA streaming            PASS");
        } else {
            fmt::Println!("[ 7] ECMA streaming            FAIL");
            failed += 1;
        }
    }

    // 8. Reset zeros the running CRC.
    {
        let tab = crc64::ISOTable();
        let mut h = crc64::New(tab);
        let _ = h.Write(to_bytes("hello"));
        h.Reset();
        if h.Sum64() == 0 {
            fmt::Println!("[ 8] Reset                     PASS");
        } else {
            fmt::Println!("[ 8] Reset                     FAIL");
            failed += 1;
        }
    }

    // 9. Sum appends 8 BE bytes — ECMA "a" = 0x330284772e652b05.
    {
        let tab = crc64::ECMATable();
        let mut h = crc64::New(tab);
        let _ = h.Write(to_bytes("a"));
        let out = h.Sum(empty_buf());
        let mut want_v: Vec<byte> = Vec::new();
        want_v.push(0x33);
        want_v.push(0x02);
        want_v.push(0x84);
        want_v.push(0x77);
        want_v.push(0x2e);
        want_v.push(0x65);
        want_v.push(0x2b);
        want_v.push(0x05);
        let want = slice::<byte>::__from_vec(want_v);
        if equal_bytes(out, want) {
            fmt::Println!("[ 9] Sum BE 8-byte append      PASS");
        } else {
            fmt::Println!("[ 9] Sum BE 8-byte append      FAIL");
            failed += 1;
        }
    }

    // 10. Sum preserves dst prefix.
    {
        let tab = crc64::ECMATable();
        let mut h = crc64::New(tab);
        let _ = h.Write(to_bytes("a"));
        let dst = to_bytes("PRE:");
        let out = h.Sum(dst);
        let raw: &[byte] = &out;
        if raw.len() == 4 + 8 && &raw[0..4] == b"PRE:" && raw[4] == 0x33 && raw[11] == 0x05 {
            fmt::Println!("[10] Sum prefix                PASS");
        } else {
            fmt::Println!("[10] Sum prefix                FAIL");
            failed += 1;
        }
    }

    // 11. Update — incremental seed produces same CRC as one-shot.
    {
        let tab = crc64::ECMATable();
        let mut crc: u64 = 0;
        crc = crc64::Update(crc, &tab, to_bytes("foo"));
        crc = crc64::Update(crc, &tab, to_bytes("bar"));
        let mut h = crc64::New(tab);
        let _ = h.Write(to_bytes("foobar"));
        if crc == h.Sum64() {
            fmt::Println!("[11] Update incremental        PASS");
        } else {
            fmt::Println!("[11] Update incremental        FAIL");
            failed += 1;
        }
    }

    // 12. ISOTable / ECMATable singletons return identical entries.
    {
        let a = crc64::ISOTable();
        let b = crc64::ISOTable();
        let c = crc64::ECMATable();
        // Same poly → entries match; different poly → entries differ.
        if a.at(1) == b.at(1) && a.at(255) == b.at(255) && a.at(1) != c.at(1) {
            fmt::Println!("[12] Table singletons          PASS");
        } else {
            fmt::Println!("[12] Table singletons          FAIL");
            failed += 1;
        }
    }

    // 13. Size + BlockSize.
    {
        let tab = crc64::ISOTable();
        let h = crc64::New(tab);
        if h.Size() == crc64::Size && h.BlockSize() == 1 {
            fmt::Println!("[13] Size/BlockSize            PASS");
        } else {
            fmt::Println!("[13] Size/BlockSize            FAIL");
            failed += 1;
        }
    }

    // 14. Go-checked corpus across every branch of `update`: below the
    //     64-byte fast-path guard, at it, and either side of the
    //     2048-byte threshold that decides whether a custom polynomial
    //     gets its own slicing-by-8 helper table.
    {
        let iso = crc64::MakeTable(crc64::ISO);
        let ecma = crc64::MakeTable(crc64::ECMA);
        let custom = crc64::MakeTable(0x000000000000001B);
        // (len, ISO, ECMA, custom) — printed by a running Go 1.25.5.
        let golden: [(usize, uint64, uint64, uint64); 8] = [
            (
                0,
                0x0000000000000000,
                0x0000000000000000,
                0x0000000000000000,
            ),
            (
                1,
                0x6d40000000000000,
                0x5807db9acf80c06d,
                0xff0000000000000b,
            ),
            (
                63,
                0x428b3b675989dc63,
                0xc63ac529d35a706d,
                0xffffffffffffffe3,
            ),
            (
                64,
                0x82b28b3b675989dc,
                0xa141cade38c444ac,
                0xfffffffffffffff8,
            ),
            (
                100,
                0x3871335fd07fbad8,
                0xa1de736ebc9273bf,
                0xffffffffffffffee,
            ),
            (
                2047,
                0x22ee41e75f91d5f0,
                0x3f8a5d2170ff31b2,
                0xfffffffffffffff8,
            ),
            (
                2048,
                0xe182ee41e75f91d5,
                0x9dc2c32b640f40ea,
                0xfffffffffffffffc,
            ),
            (
                4096,
                0x8534ac161c1d9d55,
                0xae9fc0b574660eaa,
                0xfffffffffffffffa,
            ),
        ];
        let mut bad = 0;
        let mut k: usize = 0;
        while k < golden.len() {
            let (n, wiso, wecma, wcustom) = golden[k];
            let p = mk(n);
            if crc64::Checksum(p.clone(), &iso) != wiso {
                bad += 1;
            }
            if crc64::Checksum(p.clone(), &ecma) != wecma {
                bad += 1;
            }
            if crc64::Checksum(p, &custom) != wcustom {
                bad += 1;
            }
            k += 1;
        }
        if bad == 0 {
            fmt::Println!("[14] slicing-by-8 vs Go        PASS");
        } else {
            fmt::Println!("[14] slicing-by-8 vs Go        FAIL");
            failed += 1;
        }
    }

    // 15. MarshalBinary emits the exact state Go emits, table checksum
    //     and all.
    {
        let mut h = crc64::New(crc64::ECMATable());
        let _ = h.Write(to_bytes("hello world"));
        let (st, err) = h.MarshalBinary();
        let want = from_hex(b"6372630260269a52e1b7fe6553037ecdef2352da");
        let mut hi = crc64::New(crc64::ISOTable());
        let _ = hi.Write(to_bytes("hello world"));
        let (sti, _) = hi.MarshalBinary();
        let wanti = from_hex(b"6372630273ba8484bbcd5defb9cf3f572ad9ac3e");
        if err == nil && equal_bytes(st, want) && equal_bytes(sti, wanti) {
            fmt::Println!("[15] MarshalBinary vs Go       PASS");
        } else {
            fmt::Println!("[15] MarshalBinary vs Go       FAIL");
            failed += 1;
        }
    }

    // 16. UnmarshalBinary resumes a digest mid-stream.
    {
        let mut h = crc64::New(crc64::ECMATable());
        let _ = h.Write(to_bytes("hello world"));
        let (st, _) = h.MarshalBinary();
        let mut h2 = crc64::New(crc64::ECMATable());
        let err = h2.UnmarshalBinary(st);
        let _ = h2.Write(to_bytes("!!"));
        let _ = h.Write(to_bytes("!!"));
        if err == nil && h2.Sum64() == 0x7b9f09797596d885 && h.Sum64() == h2.Sum64() {
            fmt::Println!("[16] UnmarshalBinary resume    PASS");
        } else {
            fmt::Println!("[16] UnmarshalBinary resume    FAIL");
            failed += 1;
        }
    }

    // 17. A state marshaled under one polynomial is refused by another,
    //     and a corrupt header is refused before the size check.
    {
        let mut h = crc64::New(crc64::ECMATable());
        let _ = h.Write(to_bytes("hello world"));
        let (st, _) = h.MarshalBinary();
        let mut h3 = crc64::New(crc64::ISOTable());
        let cross = h3.UnmarshalBinary(st.clone());

        let raw: &[byte] = &st;
        let mut badv: Vec<byte> = raw.to_vec();
        badv[0] = b'x';
        let bad_magic = h3.UnmarshalBinary(slice::<byte>::__from_vec(badv));

        let short = slice::<byte>::__from_vec(raw[..19].to_vec());
        let bad_size = h3.UnmarshalBinary(short);

        if cross.Error() == "hash/crc64: tables do not match"
            && bad_magic.Error() == "hash/crc64: invalid hash state identifier"
            && bad_size.Error() == "hash/crc64: invalid hash state size"
        {
            fmt::Println!("[17] Unmarshal rejections      PASS");
        } else {
            fmt::Println!("[17] Unmarshal rejections      FAIL");
            failed += 1;
        }
    }

    // 18. Clone snapshots the state; writing on either side is
    //     invisible to the other.
    {
        let mut h4 = crc64::New(crc64::ECMATable());
        let _ = h4.Write(to_bytes("abc"));
        let (c, err) = h4.Clone();
        let _ = h4.Write(to_bytes("def"));
        let got = c.Sum(empty_buf());
        let want = from_hex(b"2cd8094a1a277627");
        if err == nil && equal_bytes(got, want) && h4.Sum64() == 0xd08e9f8545a700f4 {
            fmt::Println!("[18] Clone independence        PASS");
        } else {
            fmt::Println!("[18] Clone independence        FAIL");
            failed += 1;
        }
    }

    if failed == 0 {
        fmt::Println!("ok 18/18");
        syscall::Exit(0);
    } else {
        fmt::Println!("FAIL", failed, "of 18");
        syscall::Exit(1);
    }
}
