//! Pinned against Go 1.25.5: the `errors` package and `fmt.Errorf`'s
//! `%w`.
//!
//! goish's errors is 100% ported with 42 anchors and had three smokes
//! — errors_as, errors_join, errors_tree — but none was generated by
//! diffing against a running Go. They were written from intuition,
//! and two behaviours had never been compared.
//!
//! Both defects are in `fmt.Errorf` with TWO OR MORE `%w`:
//!
//!   * `errors.Is(err, second)` was FALSE. goish captured only the
//!     first %w operand, so every sentinel after the first was
//!     unreachable — silently, since Is returning false is what a
//!     non-match looks like.
//!   * `errors.Unwrap(err)` returned the first error where Go returns
//!     NIL. Go switches on the count (fmt/errors.go:24-49): one %w
//!     gives a `wrapError` with `Unwrap() error`, two or more give a
//!     `wrapErrors` with `Unwrap() []error` — which the single-error
//!     `errors.Unwrap` does not accept, so it answers nil while Is
//!     and As walk every branch.
//!
//! The rest measured clean and is pinned here because it is the
//! machinery every other error in the tree is built on: New's
//! distinctness, Join's newline rendering and nil-dropping, Is through
//! both a linear chain and a Join tree, As finding the first match,
//! and Unwrap on each shape.
//!
//! Reference generated with:
//!   CGO_ENABLED=0 scripts/goref.sh errors <errors_ref_test.go>
#![no_std]
#![no_main]
#![allow(non_snake_case)]
extern crate alloc;
extern crate goish;
use alloc::vec::Vec;
use goish::errors::{self, error, ErrorTrait};
use goish::{fmt, slice, string};

#[derive(Clone, Default)]
struct myErr {
    tag: string,
}
impl ErrorTrait for myErr {
    fn Error(&self) -> string {
        string("my:") + self.tag.clone()
    }
}

#[derive(Clone, Default)]
struct wrapOne {
    msg: string,
    err: error,
}
impl ErrorTrait for wrapOne {
    fn Error(&self) -> string {
        self.msg.clone()
    }
    fn Unwrap(&self) -> error {
        self.err.clone()
    }
}

/// Go's output, verbatim.
const GO: [&str; 20] = [
    "new-distinct               [false \"same\"]",
    "join-2                     [\"sentinel\\nother\"]",
    "join-with-nil              [\"sentinel\\nother\"]",
    "join-all-nil               [true]",
    "join-none                  [true]",
    "join-one                   [\"sentinel\"]",
    "is-through-wrap            [true false]",
    "is-through-join            [true true]",
    "is-nil-target              [true false]",
    "is-self                    [true]",
    "as-through-wrap            [true \"my:one\"]",
    "as-join-first              [true \"my:one\"]",
    "as-miss                    [false true]",
    "unwrap-wrapped             [true]",
    "unwrap-plain               [true]",
    "unwrap-join                [true]",
    "errorf-w                   [\"ctx: sentinel\" true true]",
    "errorf-two-w               [\"two: sentinel and other\" true true]",
    "errorf-two-unwrap          [true]",
    "errorf-v                   [\"no verb: sentinel\" false]",
];

static mut FAILED: i64 = 0;
static mut LINE: usize = 0;

fn show(tag: &'static str, parts: Vec<string>) {
    let mut out = string("");
    for (i, p) in parts.iter().enumerate() {
        if i > 0 {
            out = out + string(" ");
        }
        out = out + p.clone();
    }
    chk(fmt::Sprintf!("%-26s [%s]", string::from_static(tag), out));
}

/// Compare one rendered line against the Go reference, in order.
fn chk(got: string) {
    let i = unsafe { LINE };
    unsafe { LINE += 1 };
    let want = string::from_static(GO[i]);
    if got == want {
        return;
    }
    fmt::Printf!("DIFF go   : %s\n", want);
    fmt::Printf!("     goish: %s\n", got);
    unsafe { FAILED += 1 };
}
fn q(s: string) -> string {
    fmt::Sprintf!("%q", s)
}
fn b(v: bool) -> string {
    fmt::Sprintf!("%v", v)
}

#[goish::main]
fn main() {
    let sentinel = errors::New(string("sentinel"));
    let other = errors::New(string("other"));

    let a1 = errors::New(string("same"));
    let a2 = errors::New(string("same"));
    show("new-distinct", alloc::vec![b(a1 == a2), q(a1.Error())]);

    let mut two = slice::<error>::new();
    two = goish::append!(two, sentinel.clone());
    two = goish::append!(two, other.clone());
    let j = errors::Join(two);
    show("join-2", alloc::vec![q(j.Error())]);

    let mut withnil = slice::<error>::new();
    withnil = goish::append!(withnil, sentinel.clone());
    withnil = goish::append!(withnil, errors::nil);
    withnil = goish::append!(withnil, other.clone());
    show(
        "join-with-nil",
        alloc::vec![q(errors::Join(withnil).Error())],
    );

    let mut allnil = slice::<error>::new();
    allnil = goish::append!(allnil, errors::nil);
    allnil = goish::append!(allnil, errors::nil);
    show("join-all-nil", alloc::vec![b(errors::Join(allnil).IsNil())]);
    show(
        "join-none",
        alloc::vec![b(errors::Join(slice::<error>::new()).IsNil())],
    );
    let mut one = slice::<error>::new();
    one = goish::append!(one, sentinel.clone());
    show("join-one", alloc::vec![q(errors::Join(one).Error())]);

    let w = errors::Wrap(wrapOne {
        msg: string("wrapped"),
        err: sentinel.clone(),
    });
    show(
        "is-through-wrap",
        alloc::vec![
            b(errors::Is(w.clone(), sentinel.clone())),
            b(errors::Is(w.clone(), other.clone()))
        ],
    );
    show(
        "is-through-join",
        alloc::vec![
            b(errors::Is(j.clone(), sentinel.clone())),
            b(errors::Is(j.clone(), other.clone()))
        ],
    );
    show(
        "is-nil-target",
        alloc::vec![
            b(errors::Is(errors::nil, errors::nil)),
            b(errors::Is(sentinel.clone(), errors::nil))
        ],
    );
    show(
        "is-self",
        alloc::vec![b(errors::Is(sentinel.clone(), sentinel.clone()))],
    );

    let m1 = errors::Wrap(myErr { tag: string("one") });
    let m2 = errors::Wrap(myErr { tag: string("two") });
    let outer = errors::Wrap(wrapOne {
        msg: string("outer"),
        err: m1.clone(),
    });
    let got = errors::As::<myErr>(outer);
    show(
        "as-through-wrap",
        alloc::vec![
            b(got.is_some()),
            q(got.map(|g| g.Error()).unwrap_or(string("")))
        ],
    );

    let mut mj = slice::<error>::new();
    mj = goish::append!(mj, m1.clone());
    mj = goish::append!(mj, m2.clone());
    let got2 = errors::As::<myErr>(errors::Join(mj));
    show(
        "as-join-first",
        alloc::vec![
            b(got2.is_some()),
            q(got2.map(|g| g.Error()).unwrap_or(string("")))
        ],
    );

    let got3 = errors::As::<myErr>(sentinel.clone());
    show("as-miss", alloc::vec![b(got3.is_some()), b(got3.is_none())]);

    show(
        "unwrap-wrapped",
        alloc::vec![b(errors::Unwrap(w.clone()) == sentinel)],
    );
    show(
        "unwrap-plain",
        alloc::vec![b(errors::Unwrap(sentinel.clone()).IsNil())],
    );
    show(
        "unwrap-join",
        alloc::vec![b(errors::Unwrap(j.clone()).IsNil())],
    );

    let e1 = fmt::Errorf!("ctx: %w", sentinel.clone());
    show(
        "errorf-w",
        alloc::vec![
            q(e1.Error()),
            b(errors::Is(e1.clone(), sentinel.clone())),
            b(errors::Unwrap(e1.clone()) == sentinel)
        ],
    );
    let e2 = fmt::Errorf!("two: %w and %w", sentinel.clone(), other.clone());
    show(
        "errorf-two-w",
        alloc::vec![
            q(e2.Error()),
            b(errors::Is(e2.clone(), sentinel.clone())),
            b(errors::Is(e2.clone(), other.clone()))
        ],
    );
    show(
        "errorf-two-unwrap",
        alloc::vec![b(errors::Unwrap(e2.clone()).IsNil())],
    );
    let e3 = fmt::Errorf!("no verb: %v", sentinel.clone());
    show(
        "errorf-v",
        alloc::vec![q(e3.Error()), b(errors::Is(e3.clone(), sentinel.clone()))],
    );
    let failed = unsafe { FAILED };
    let n = GO.len() as i64;
    if failed == 0 {
        fmt::Printf!("errors: %d/%d match Go\n", n, n);
        goish::os::Exit(0);
    }
    fmt::Printf!("FAIL: %d/%d diverge\n", failed, n);
    goish::os::Exit(1);
}
