// fips140_tls12_smoke — the TLS 1.2 PRF (RFC 5246 §5) and extended
// master secret derivation (RFC 7627), i.e. everything the
// crypto/internal/fips140/tls12 extraction added.
//
// The SHA-256 case is the well-known "test label" PRF vector circulated
// on the IETF TLS list. The SHA-384 and SHA-512 cases use the same
// secret/seed inputs from that message, with outputs regenerated by an
// independent Python P_hash that was first pinned against the SHA-256
// vector byte-for-byte — so the reference is validated, not assumed.
//
// keyLen 12 is deliberately not a multiple of any digest size: it
// catches a pHash that squeezes whole blocks instead of truncating.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use goish::crypto::internal::fips140::sha256;
use goish::crypto::internal::fips140::sha512;
use goish::crypto::internal::fips140::tls12;
use goish::encoding::hex;
use goish::fmt;
use goish::goslice::slice;
use goish::types::byte;

static mut FAILED: bool = false;

fn check(name: &str, got: goish::string, want: &str) {
    if got == goish::string::from(want) {
        fmt::Printf!("PASS: %s\n", goish::string::from(name));
    } else {
        fmt::Printf!(
            "FAIL: %s\n  got  %s\n  want %s\n",
            goish::string::from(name),
            got,
            goish::string::from(want)
        );
        unsafe { FAILED = true };
    }
}

/// Decode hex, panicking on anything that is not an even run of hex
/// digits — a silent 0 for a bad nibble once turned a corrupted literal
/// into a plausible-looking wrong vector.
fn unhex(s: &str) -> slice<byte> {
    let b = s.as_bytes();
    if b.len() % 2 != 0 {
        panic!("unhex: odd length");
    }
    let mut out: Vec<byte> = Vec::with_capacity(b.len() / 2);
    let mut i = 0;
    while i < b.len() {
        out.push(nib(b[i]) * 16 + nib(b[i + 1]));
        i += 2;
    }
    return slice::__from_vec(out);
}

fn nib(c: u8) -> byte {
    if c >= b'0' && c <= b'9' {
        return c - b'0';
    }
    if c >= b'a' && c <= b'f' {
        return c - b'a' + 10;
    }
    panic!("unhex: not a hex digit");
}

fn hx(s: &slice<byte>) -> goish::string {
    let r: &[byte] = s;
    return hex::EncodeToString(r);
}

fn label() -> goish::string {
    return goish::string::from("test label");
}

#[goish::main]
fn main() {
    // ── PRF with SHA-256 (the published vector) ───────────────────────
    let out = tls12::PRF(
        sha256::NewHash,
        unhex("9bbe436ba940f017b17652849a71db35"),
        label(),
        unhex("a0ba9f936cda311827a6f796ffd5198c"),
        100,
    );
    check(
        "PRF SHA-256, 100 bytes",
        hx(&out),
        "e3f229ba727be17b8d122620557cd453c2aab21d07c3d495329b52d4e61edb5a\
         6b301791e90d35c9c9a46b4e14baf9af0fa022f7077def17abfd3797c0564bab\
         4fbc91666e9def9b97fce34f796789baa48082d122ee42c5a72e5a5110fff701\
         87347b66",
    );

    // ── PRF with SHA-384 ──────────────────────────────────────────────
    let out = tls12::PRF(
        sha512::NewHash384,
        unhex("b80b733d6ceefcdc71566ea48e5567df"),
        label(),
        unhex("cd665cf6a8447dd6ff8b27555edb7465"),
        148,
    );
    check(
        "PRF SHA-384, 148 bytes",
        hx(&out),
        "7b0c18e9ced410ed1804f2cfa34a336a1c14dffb4900bb5fd7942107e81c83cd\
         e9ca0faa60be9fe34f82b1233c9146a0e534cb400fed2700884f9dc236f80edd\
         8bfa961144c9e8d792eca722a7b32fc3d416d473ebc2c5fd4abfdad05d918425\
         9b5bf8cd4d90fa0d31e2dec479e4f1a26066f2eea9a69236a3e52655c9e9aee6\
         91c8f3a26854308d5eaa3be85e0990703d73e56f",
    );

    // ── PRF with SHA-512 ──────────────────────────────────────────────
    let out = tls12::PRF(
        sha512::NewHash,
        unhex("b0323523c1853599584d88568bbb05eb"),
        label(),
        unhex("d4640e12e4bcdbfb437f03e6ae418ee5"),
        196,
    );
    check(
        "PRF SHA-512, 196 bytes",
        hx(&out),
        "1261f588c798c5c201ff036e7a9cb5edcd7fe3f94c669a122a4638d7d508b283\
         042df6789875c7147e906d868bc75c45e20eb40c1cf4a1713b27371f68432592\
         f7dc8ea8ef223e12ea8507841311bf68653d0cfc4056d811f025c45ddfa6e6fe\
         c702f054b409d6f28dd0a3233e498da41a3e75c5630eedbe22fe254e33a1b0e9\
         f6b9826675bec7d01a845658dc9c397545401d40b9f46c7a400ee1b8f81ca0a6\
         0d1a397a1028bff5d2ef5066126842fb8da4197632bdb54ff6633f86bbc836e6\
         40d4d898",
    );

    // ── A keyLen that truncates mid-block ─────────────────────────────
    let out = tls12::PRF(sha256::NewHash, unhex("010203"), label(), unhex("0405"), 12);
    check(
        "PRF truncates to keyLen",
        hx(&out),
        "7edea117c898c94b7ac192ea",
    );

    check(
        "PRF keyLen 0 yields empty",
        fmt::Sprintf!(
            "%d",
            tls12::PRF(sha256::NewHash, unhex("00"), label(), unhex("00"), 0).Len()
        ),
        "0",
    );

    // ── Extended master secret (RFC 7627) ─────────────────────────────
    //
    // MasterSecret must be exactly PRF(pms, "extended master secret",
    // transcript, 48) — a wrong label or length would still produce
    // 48 well-formed-looking bytes.
    let pms = unhex(
        "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\
         202122232425262728292a2b2c2d2e2f",
    );
    let transcript = unhex("54e6289e14c7b0e7ad9acc2dfc4c1e3d027d0eef7f5c4c3fe7c292761d0e06a6");
    let ms = tls12::MasterSecret(sha256::NewHash, pms.clone(), transcript.clone());
    check(
        "MasterSecret SHA-256 is 48 bytes",
        fmt::Sprintf!("%d", ms.Len()),
        "48",
    );
    check(
        "MasterSecret SHA-256",
        hx(&ms),
        "38eec34173d3bca3feaef05244cc93c222bfd751ffa3171bc2d7f395c904ac10\
         d824a14a565873a7a37330324de2ab6c",
    );
    check(
        "MasterSecret == PRF with the RFC 7627 label",
        hx(&tls12::PRF(
            sha256::NewHash,
            pms,
            goish::string::from("extended master secret"),
            transcript,
            48,
        )),
        hx(&ms).as_ref(),
    );

    if unsafe { FAILED } {
        goish::syscall::Exit(1);
    }
    fmt::Printf!("fips140_tls12_smoke OK\n");
}
