// fips140_mlkem_field_smoke — ML-KEM field and polynomial arithmetic
// (FIPS 203), i.e. all 32 functions of crypto/internal/fips140/mlkem's
// field.go.
//
// Every expectation is ground truth generated by `scripts/goref.sh` from
// the Go implementation being ported — see AGENTS.md §10. This package
// has no published intermediate vectors (FIPS 203 publishes only
// end-to-end KeyGen/Encaps/Decaps), and its failure modes are exactly
// the kind that produce well-formed-looking wrong output: a
// misconstructed Barrett constant, an off-by-one in a bit-packing loop,
// a zeta index walked in the wrong direction.
//
// compress/decompress are checked over their ENTIRE domain (all q input
// values per d, all 2ᵈ outputs) folded into a rolling hash, rather than
// at sample points — the rounding-boundary logic is where these go wrong
// and a handful of samples would miss it.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use goish::crypto::internal::fips140::mlkem;
use goish::encoding::hex;
use goish::fmt;
use goish::goslice::slice;
use goish::types::{byte, uint16, uint32, uint64};

static mut FAILED: bool = false;

fn check(name: &str, got: goish::string, want: &str) {
    if got == goish::string::from(want) {
        fmt::Printf!("PASS: %s\n", goish::string::from(name));
    } else {
        fmt::Printf!(
            "FAIL: %s\n  got  %s\n  want %s\n",
            goish::string::from(name),
            got,
            goish::string::from(want)
        );
        unsafe { FAILED = true };
    }
}

fn hx(v: &[byte]) -> goish::string {
    return hex::EncodeToString(v);
}

/// The same deterministic ring element the Go reference builds.
fn mkRing(seed: byte) -> mlkem::ringElement {
    let mut f = mlkem::ringElement([0u16; 256]);
    let mut x: uint32 = (seed as uint32).wrapping_mul(7919).wrapping_add(13);
    let mut i = 0;
    while i < 256 {
        x = x.wrapping_mul(1103515245).wrapping_add(12345);
        f.0[i] = ((x >> 7) % 3329) as uint16;
        i += 1;
    }
    return f;
}

/// Serialise coefficients little-endian, as the reference's `pf` does.
fn coeffs(f: &[uint16; 256]) -> Vec<byte> {
    let mut b: Vec<byte> = Vec::with_capacity(512);
    let mut i = 0;
    while i < 256 {
        b.push((f[i] & 0xff) as byte);
        b.push((f[i] >> 8) as byte);
        i += 1;
    }
    return b;
}

fn arr<const N: usize>(s: &slice<byte>) -> [byte; N] {
    let r: &[byte] = s;
    let mut a = [0u8; N];
    a.copy_from_slice(&r[..N]);
    return a;
}

#[goish::main]
fn main() {
    // ── scalar field arithmetic ───────────────────────────────────────
    check(
        "fieldReduceOnce(3400)",
        fmt::Sprintf!("%d", mlkem::fieldReduceOnce(3400)),
        "71",
    );
    check(
        "fieldAdd(3000,500)",
        fmt::Sprintf!("%d", mlkem::fieldAdd(3000, 500)),
        "171",
    );
    check(
        "fieldSub(10,3000)",
        fmt::Sprintf!("%d", mlkem::fieldSub(10, 3000)),
        "339",
    );
    check(
        "fieldReduce(2217000)",
        fmt::Sprintf!("%d", mlkem::fieldReduce(2217000)),
        "3215",
    );
    check(
        "fieldMul(3000,3000)",
        fmt::Sprintf!("%d", mlkem::fieldMul(3000, 3000)),
        "1713",
    );
    check(
        "fieldMulSub(1234,10,3000)",
        fmt::Sprintf!("%d", mlkem::fieldMulSub(1234, 10, 3000)),
        "2201",
    );
    check(
        "fieldAddMul(11,22,33,44)",
        fmt::Sprintf!("%d", mlkem::fieldAddMul(11, 22, 33, 44)),
        "1694",
    );

    check(
        "fieldCheckReduced(3328) ok",
        fmt::Sprintf!("%v", mlkem::fieldCheckReduced(3328).1 == goish::nil),
        "true",
    );
    check(
        "fieldCheckReduced(3329) errors",
        fmt::Sprintf!("%v", mlkem::fieldCheckReduced(3329).1 != goish::nil),
        "true",
    );

    // ── compress / decompress over their whole domain ─────────────────
    let ds: [u8; 5] = [1, 4, 5, 10, 11];
    let wantC: [&str; 5] = [
        "476708503193217024",
        "16901543932969162752",
        "713604052264916992",
        "11444583661410754048",
        "7982625690032243712",
    ];
    let wantD: [&str; 5] = [
        "1665",
        "10387171218324576000",
        "11135531952751257472",
        "14110985617969981056",
        "61462832222520960",
    ];
    const CNAMES: [&str; 5] = [
        "compress, all of Z_q, d=1",
        "compress, all of Z_q, d=4",
        "compress, all of Z_q, d=5",
        "compress, all of Z_q, d=10",
        "compress, all of Z_q, d=11",
    ];
    const DNAMES: [&str; 5] = [
        "decompress, all 2^d, d=1",
        "decompress, all 2^d, d=4",
        "decompress, all 2^d, d=5",
        "decompress, all 2^d, d=10",
        "decompress, all 2^d, d=11",
    ];
    let mut di = 0;
    while di < 5 {
        let d = ds[di];
        let mut acc: uint64 = 0;
        let mut x: uint16 = 0;
        while x < 3329 {
            acc = acc
                .wrapping_mul(31)
                .wrapping_add(mlkem::compress(x, d) as uint64);
            x += 1;
        }
        check(CNAMES[di], fmt::Sprintf!("%d", acc), wantC[di]);

        let mut acc: uint64 = 0;
        let mut y: uint32 = 0;
        while y < (1u32 << d) {
            acc = acc
                .wrapping_mul(31)
                .wrapping_add(mlkem::decompress(y as uint16, d) as uint64);
            y += 1;
        }
        check(DNAMES[di], fmt::Sprintf!("%d", acc), wantD[di]);
        di += 1;
    }

    // ── polynomial arithmetic ─────────────────────────────────────────
    let a = mkRing(1);
    let b = mkRing(2);
    check(
        "polyAdd",
        hx(&coeffs(&mlkem::polyAdd(a, b).0)),
        WANT_POLYADD,
    );
    check(
        "polySub",
        hx(&coeffs(&mlkem::polySub(a, b).0)),
        WANT_POLYSUB,
    );

    let enc = mlkem::polyByteEncode(slice::__from_vec(Vec::new()), a);
    check("polyByteEncode", hx(&enc), WANT_ENCODE);

    let (dec, err) = mlkem::polyByteDecode::<mlkem::ringElement>(enc.clone());
    check(
        "polyByteDecode succeeds",
        fmt::Sprintf!("%v", err == goish::nil),
        "true",
    );
    check(
        "polyByteDecode round-trips",
        hx(&coeffs(&dec.0)),
        hx(&coeffs(&a.0)).as_ref(),
    );

    let (_, err) =
        mlkem::polyByteDecode::<mlkem::ringElement>(slice::__from_vec(alloc::vec![0u8; 384]));
    check(
        "polyByteDecode accepts all-zero",
        fmt::Sprintf!("%v", err == goish::nil),
        "true",
    );

    let mut badv = slice::__into_vec(enc.clone());
    badv[0] = 0xff;
    badv[1] = 0xff;
    let (_, err) = mlkem::polyByteDecode::<mlkem::ringElement>(slice::__from_vec(badv));
    check(
        "polyByteDecode rejects unreduced",
        fmt::Sprintf!("%v", err != goish::nil),
        "true",
    );
    let (_, err) =
        mlkem::polyByteDecode::<mlkem::ringElement>(slice::__from_vec(alloc::vec![0u8; 383]));
    check(
        "polyByteDecode rejects short input",
        fmt::Sprintf!("%v", err != goish::nil),
        "true",
    );

    // ── compress-and-encode at every width ────────────────────────────
    let e = slice::__from_vec(Vec::new());
    let c1 = mlkem::ringCompressAndEncode1(e.clone(), a);
    let c4 = mlkem::ringCompressAndEncode4(e.clone(), a);
    let c5 = mlkem::ringCompressAndEncode5(e.clone(), a);
    let c10 = mlkem::ringCompressAndEncode10(e.clone(), a);
    let c11 = mlkem::ringCompressAndEncode11(e, a);
    check("ringCompressAndEncode1", hx(&c1), WANT_C1);
    check("ringCompressAndEncode4", hx(&c4), WANT_C4);
    check("ringCompressAndEncode5", hx(&c5), WANT_C5);
    check("ringCompressAndEncode10", hx(&c10), WANT_C10);
    check("ringCompressAndEncode11", hx(&c11), WANT_C11);

    check(
        "ringDecodeAndDecompress1",
        hx(&coeffs(&mlkem::ringDecodeAndDecompress1(&arr::<32>(&c1)).0)),
        WANT_D1,
    );
    check(
        "ringDecodeAndDecompress4",
        hx(&coeffs(
            &mlkem::ringDecodeAndDecompress4(&arr::<128>(&c4)).0,
        )),
        WANT_D4,
    );
    check(
        "ringDecodeAndDecompress5",
        hx(&coeffs(
            &mlkem::ringDecodeAndDecompress5(&arr::<160>(&c5)).0,
        )),
        WANT_D5,
    );
    check(
        "ringDecodeAndDecompress10",
        hx(&coeffs(
            &mlkem::ringDecodeAndDecompress10(&arr::<320>(&c10)).0,
        )),
        WANT_D10,
    );
    check(
        "ringDecodeAndDecompress11",
        hx(&coeffs(
            &mlkem::ringDecodeAndDecompress11(&arr::<352>(&c11)).0,
        )),
        WANT_D11,
    );

    // ── sampling and the NTT ──────────────────────────────────────────
    let mut seed = [0u8; 32];
    let mut i = 0;
    while i < 32 {
        seed[i] = i as byte;
        i += 1;
    }
    check(
        "samplePolyCBD",
        hx(&coeffs(&mlkem::samplePolyCBD(&seed, 7).0)),
        WANT_CBD,
    );
    check("ntt", hx(&coeffs(&mlkem::ntt(a).0)), WANT_NTT);
    check(
        "inverseNTT(ntt(a)) == a",
        hx(&coeffs(&mlkem::inverseNTT(mlkem::ntt(a)).0)),
        hx(&coeffs(&a.0)).as_ref(),
    );
    check(
        "nttMul",
        hx(&coeffs(&mlkem::nttMul(mlkem::ntt(a), mlkem::ntt(b)).0)),
        WANT_NTTMUL,
    );
    check(
        "sampleNTT",
        hx(&coeffs(&mlkem::sampleNTT(&seed, 3, 5).0)),
        WANT_SAMPLENTT,
    );

    if unsafe { FAILED } {
        goish::syscall::Exit(1);
    }
    fmt::Printf!("fips140_mlkem_field_smoke OK\n");
}

// Ground truth from `scripts/goref.sh crypto/internal/fips140/mlkem`,
// i.e. printed by the Go implementation this file ports. Regenerate
// with the ref program rather than editing by hand.
const WANT_POLYADD: &str =
    "f0033000c90b7b022702c6003b02020931013807bc00fd06f500620197053104130adb09\
     2b04310b7b01070700062004100c79041205600254050d0cc7080b01540c710679090101\
     670742056f06b2049a045d08f204ff043a0b6009200b080a3707e4053700910823093508\
     6f04d100f2046204d200ad09c907c600a1058a0c6504e003260007079c099f04e00b2504\
     18099e05b808ca089e0c0208990cb7090a02610a850ca305230c180c0308430c140c3400\
     f60a5e0b3a0268034408e409d9012904b706f905a6071c0b1d0b32053801c3031607a805\
     c00c910c970ca807b7013504c5075708fa056b075a0ccf00c501e106bd05b007f5034e06\
     c101b60432010e02260125093f0cd706b706bc0caf01070b890a6101b104fc02710c0f04\
     720ca0011b00f60c3f09f5065a0808032108aa011b08d70797047b0c54094f08d708a90c\
     9e0b74031803f70a01001500fe059503da09d806800878013e0c4d085b0bb1019d09c50b\
     a0059c04a50b230309010e0c5508e607bc0972006f04e3035a00a20b7f0bad0141076703\
     3206ff062b0c3502c9076f0c92073c02f60cae0195074f01ec08cb00060451057e01050b\
     4d0cd901c104eb0cd1047f000f06d9099507b9091306b1085c00da029c076304c8076303\
     410bc5026808860a50012f049107b404a2082c077304e40949025e0ca005130b65093609\
     2906530909025d01";
const WANT_POLYSUB: &str =
    "1300d6032809fc0738098808bd08270a8007ee030907c2013107fd097800dd0141080e00\
     af04bb031f0b450232086006d704f2024b0b8f0840041f068a086709810549011e0ada0b\
     1805ea0b88031f03ad06ad01b60ad6032a0a3c095805eb048f0c1c0cd70acc0ce902d202\
     3a0c7a086a0ac70a240848027508e9080c061e0a320150003108d9088f09b501a60b3a01\
     eb0bb406240c3902e202bf08570581037409f1021608fd049e06e10c520b1400b103620a\
     a00c8b0b150cca09b804b00b590232090f0ab80552060009f609c0035e06d2042407130c\
     100428065f053f05d301560cb003d00c94082e0bc008ee09e4011006690603015108b30b\
     2008ec00c90ab30bb80cfd069f08b408640085098c004f091a06950ce503cd058e0b6600\
     74030507de0091016700f4035e09ee067901f70a3b02a9013f0187096b082e03170bcc07\
     5b017c058e08b706f808420bba00ee085a091a01980ce407700908035c0139070b04380a\
     380a0608d60b280469093704c908df0876050807300adb001f06b4001e099006c201250c\
     e00a2205720508030e04cf0bfc00ba06e507ff0bb704e400b5022703060cad02840c580a\
     0908090b2f084f06ed0ad003f60021079b03db09d40160005c07da074303f608c00a7805\
     310add03cf093807ff09ee044e03370b0704080b5003d0037605c2079a039f09230a2f03\
     3e0776041901d90a";
const WANT_ENCODE: &str =
    "823820f8c3bb307c4a7c4531d93a59630aae1304c38879302a59b76d64774d664a190754\
     f361a3ae81bfca64912892536ad23d4be3cec06c897c9ba6245c50d4b7aeb2ea943c980f\
     e3099087e5420646c0d461b2ae47117bb4c71f88b5574cb54c8921ac0a7f15a332c30b93\
     0194626e2ac0c0071ef8c869bf956acd0355e0c25f2ac3ca62b154cb4b4fa790697ea6ac\
     19d2026398c5fce6a0099447cbb3ac1dd72568c82dfb48cfc5511c3b3c4147c72c8dfabd\
     5598cf13a6ad230628711b2d7e0c06ef16816f5a140e0a4a9eb7a2d1b16f4b54ae7fb58b\
     f337adfd360cd354bfdcb84fcd14cd2b054ceb12b05ff2c3f7a93bfd8c47d3758dfdcac2\
     5c23cc9a993f8cea4ad7bac2dc5c47d4e647ec17653d65a239251a8f281e99d73bcff025\
     bdb962cef3a9026b7c8918c94ef2916cfcc147b447ed630526a679519c1f06f83f01e742\
     2b1a6778d699df878a03da8798a59c749ab0dca355f0cb0244e9aeb91a359bf28d28fcb0\
     f05b17d5ac9162aa6d600aa19d94a5c439cb33400691b161";
const WANT_C1: &str = "6552fdb026661e1589d32f6ad45518158cd9d50d3a2d7e356772f3be31292881";
const WANT_C4: &str = "2ae56f477dddf54ceb956869d2f2b6635304b0de6fdabd1abc57f7e219f6eaef3bad44be\
     85fd2a8b87757404726f81d803fac965d5394a0b225f39fd0ad7383e0fa92d6cd992d5b7\
     da19f66b0666e4f35c50b7fe045c6dfd50688ac6262b59318cd5aefbb3ff6505982f5a59\
     8dc8baacc7ed750fdb4db3ef2fb08dcdd60c0082";
const WANT_C5: &str = "b5a8ee5743dbe9adfc3d972f09576c2593ce6c694621f02bd79ecdad2f15d83af53cd973\
     ac4fb9e7b7688a50bfea693f8b850ea6761efaa3752620dc05541fb35a694b538f058478\
     258fee15bcfd0c3f3f44aa475e3393b8b6ab7447c1ba650c3476b6f13981e5ecf6e863a5\
     d9f660c53561cb8dd4329330f825bd67fdc67ebf960a6ffa42555419423c6bae0eeb9d5a\
     07776b64acdf9d00aba3ce2be30f0279";
const WANT_C10: &str = "9e7a9213e7c0bb059b3c56df2633d64101ffae3bd21ade1593f0b9f5626799904c88eb79\
     2dabca66bec03490feec938a38cdbc2f8626d74a778b68130b173b5b52dac90e89db5d56\
     11d6f580f6cd3cdfdc9682749cf3e4e3f9b43b9557b3ec6252222c82c431b89268e25c97\
     8ff96d8416ba613320f89fd4a5384029f32662ec13582b490da32e9686332cff8b2c327c\
     503d72f3f3e990faefddd5e31553b837d87b20e29e369381315b5886fc888952691ddbab\
     72526d220f7cb9ae2b627ac57f995de68cbd0bf11197f43f58cbe11ab6ef09b54f6f4e3f\
     c765b5eff57fa5a15870c6c7d9c79b05222a25569a04c42eff9ac712d1639309aaf7b538\
     2bbdee5185559306e45da9fc2678ee84625221efd75fbd6caa4a31a7b80d7c73d93095c6\
     ba03da76cd7441cdecdafbd9accf217fb332731833c66bbd1c30fa107cb04778";
const WANT_C11: &str = "3ced499c70fef76e81ad3cac761b99632da8bf77b73ba36578ae2e093e6e797167334172\
     42ba2eafcb52e5667c01d381e88f7da4461ccd78bf58346f4de9dc463413154eecd92455\
     3bb28384dbb95485b05cffcf7d5f1edfb8554aa4c5591ef9f0fcb47752de9ac75ecc9310\
     368289cbe0958a561cd7c987f9da105ad019768607fa6fd44ae1404a33cf4418f3095855\
     223518e9c252e11816ff17b988e105a547dcf8d9e920dd7fef5a6d3cc5289c37afdf0111\
     edb96664c0185bb00cb24796482a5a8bedabe44c7513f180afadcf1562f412bfcbd8c59c\
     62d725f1215e92ff815539b80ebbef11ca3e7ae5d4e770ad9aefe9f7d50c8705cef1e5cc\
     c7370b085153d2ca26fda12efe5dde95126d6c640275f76be12ce9eb2e2a61a9a906c86b\
     25e56f02cf3a3d515241b6dffed48bcda9a638a77133b09b950da6a5617d03b3cd75a615\
     a499baeeddd9582f47f9333be61b8a39c6d7f2b280a1ff011fdc4378";
const WANT_D1: &str = "810600008106000000008106810600000000810600000000810600008106000081060000\
     810681068106810681068106000000000000000081068106000081060000810681060000\
     000081060000000000008106810600000000810681060000000081068106810681060000\
     000000008106000081060000810600000000000081060000000081060000000000008106\
     810681060000000081060000810681068106810681068106000081060000000000008106\
     000081060000810681060000000000008106000081060000810681068106000081060000\
     810600008106000000000000000081068106000000000000810600008106000081060000\
     000000000000000081068106000000000000810681060000000081068106000081068106\
     810600008106000081060000810681068106000081068106000000000000000000008106\
     000081068106810600000000810600008106810600008106000000000000810681068106\
     810681068106000081060000810600008106810600000000810681068106000000008106\
     810600000000810600000000810681068106000081068106000000008106810681068106\
     000081068106810681068106000081068106000000000000810681060000000081060000\
     000081060000810600000000000000000000810600008106000000008106000000000000\
     0000000000008106";
const WANT_D4: &str = "2108a0011004610b310ce004b0054003910ab005910a910a1004310cc1094003f108610b\
     100451078106e0045107e004a001910aa001310ce004f1087002e0047002100440030000\
     0000f108610b910a310ce0042108910a910af1082108d000c109f108b0051004b005310c\
     a001610b5107d000e004310c2108610b310c610bf1087002910a210840034003610bf108\
     10048106910a310c2108a001f1088106b00581061004b0054003b00540030000a001b005\
     310ce004d00081068106910a700200002108310c5107c1091004e0041004910a51077002\
     21084003f1080000a001a001310c100451077002910a310c21080000b005910a81067002\
     610b7002310c000051072108910aa001c109e0045107910aa00151071004910ab005f108\
     2108910a5107d000e004310cf108e004e0040000e004e0044003610b7002310cc1091004\
     00001004b005f108610b310c40030000c1091004910ae004910a310c000010048106e004\
     21088106e004c109e004a001f108a00151071004d0007002c10981061004910a610b2108\
     f108310c7002f108310c310c1004e0041004000081065107310ca0012108100451071004\
     910a81068106c1092108f108c1092108b005c109910a610b1004b005310c0000f108910a\
     910a40037002f108310c610b310ca0010000f108910a8106910ac109e004910ac1090000\
     00000000a0018106";
const WANT_D5: &str = "890808021004c90b310c780448054003f90ab005910af90a1004310c5909d8025909610b\
     7804510781067804e90648050802290aa001c90be004f108080248057002100440030000\
     990c8908610b910a310ce004b907f90a910a59092108d000c109f108b00510041806310c\
     a001f90ab90738017804990c2108610b310c610b59090802910a210840034003c90b5909\
     10041806910a310cb9070802f1088106b0058106a8034805d80218064003990c38014805\
     c90be004d00081068106f90a080200008908310ce906290a10047804a803f90a51077002\
     8908d802f1080000a001a001310c10045107d802910ac90b890800001806f90a18067002\
     610bd802990c6800e9062108910a3801290a7804b907290aa001e9067804f90ab0058908\
     2108f90ae906d000e004c90bf108e004e00400004805e004d802f90a7002310c290aa803\
     00007804b005f108f90a310c4003990cc1091004910ae004f90a310c00007804e9067804\
     b90781064805290a4805a00189080802b907a803d0007002c1091806a803910af90ab907\
     8908990c7002f108990c310c78047804100468001806b907310c080221081004e9061004\
     290a81068106c109b9078908290a8908b005c109910af90aa8034805c90b00005909f90a\
     910a40037002f108310cf90ac90ba0010000f108910ae906910a290a7804290ac109990c\
     00006800a0011806";
const WANT_D10: &str = "82080202fa03bc0b310ca6047c051303d80a9305630adf0a1404310c890906032b09740b\
     6f0478074c06a60419073f05f101360aad01f60bca041409290238056a02dc034a03ed0c\
     c00c96087b0b6a0a240c0405d307ec0ab10a4f093b08fa00e509010986052e040506030c\
     d401260baf0714017c047c0c2108570b580c540b4c091802ab0af00716032903c20b2e09\
     000429066d0a030cbf07e101f7089b06bd05a806cc034f05df02fb052903ac0c62014c05\
     cc0bf404a6009b067d06cb0a18022e006208580cfc060f0a0a047804cc03cb0a1d075d02\
     6808db02fa08f40cc401c4013b0c14044707cb028e0ae00b5508fa0c1206dc0a22068002\
     710bd2027f0c6200ef061008700a45010f0a9f049f072c0ad101fc064b04e50a8005b908\
     f307d20afc06c300d304f60bdd08fa04cd04d00c2b05c004ec02030b60023e0cf809b903\
     fe0c7804d405d708fc0a2a0c5e03c30c9a09fa038e0ab004d80a2a0cdd0c7504d5067f04\
     ed0750063b05260a3805a3018f08e1019807bc03d0006002bd092c06cf039e0a030bc607\
     8908920c4c021e096b0c1d0c48047c04ed03550025069b07510cf8010708000403072e04\
     2c0a700677069d09e007a908020a7c089605cb09740a090bdc035905f00b2e004509ef0a\
     b80a51039a02e008270c100bf00b7601d30c1b09630adc06600a0f0a9c045a0ac409b30c\
     3400650090011c06";
const WANT_D11: &str = "82080302f803bc0b2f0ca7047c051403d80a9305630ae00a14042f0c880907032a09740b\
     6d0476074c06a60419074005f301360aaf01f80bca04160929023a056a02dc034c03ed0c\
     c00c96087d0b6a0a240c0605d407ea0ab10a4d093c08f900e309ff0888052e040706030c\
     d401260bad0714017c047c0c1f08590b560c540b4c091802ac0af00714032903c20b3009\
     020429066f0a020cc107e001f7089c06bf05a906ce035105e002fb052903ac0c62014c05\
     cb0bf404a70099067d06ca0a18022e0063085a0cfc060f0a0a047804ca03cb0a1d075d02\
     6808db02fa08f40cc601c6013b0c14044707cb028e0ae00b5508f90c1406da0a22068002\
     710bd2027d0c6000ef0610086f0a45010f0a9f049f072a0ad101fa064b04e50a8005bb08\
     f307d30afe06c300d304f50bdc08fa04cd04d00c2b05c004ec02010b5e02400cf609ba03\
     fe0c7804d305d708fe0a2c0c5c03c20c9a09fa038c0aae04d70a2a0cdc0c7504d3067d04\
     ed0751063d05260a3a05a2018f08e3019a07bd03ce005e02bd092a06ce039f0a030bc607\
     8908910c4e021e096b0c1f0c48047c04ed03560025069a07510cfa010708fe0301072e04\
     2a0a700678069d09e007a808030a7d089805cb09740a090bdc035a05f00b2c004409ed0a\
     b90a51039a02df08290c100bf00b7401d50c1909620ada06600a100a9e045a0ac409b30c\
     3200650091011c06";
const WANT_CBD: &str = "0000000d000d000002000100010001000000000d00000100000d000d0100ff0c000d0000\
     000000000000000002000100010000000000010001000100000d00000000000001000000\
     0100000d000d0100000d0000010000000100ff0c010001000200000d010002000000000d\
     0100000d000d010000000200010001000000000000000100000d01000000010001000100\
     000d0100ff0c010000000100000d010000000000000d01000200ff0cff0c000d0000000d\
     ff0cff0c01000000000d00000200ff0c02000100000d00000000ff0c010002000000000d\
     0100000d0000000d0200ff0c02000100000000000000000d00000100000d010001000000\
     ff0c000d000d00000000000001000000000000000100000d010001000100000001000200\
     000d00000000000000000200000d000d00000000000d000d0200010000000000000d0000\
     0000000d02000000ff0c000d0200ff0c000d000d00000000000d010000000200ff0c000d\
     010000000000000d000d0000000d0000000d0000000d00000000000d0000000001000000\
     00000000010000000000000d01000200000d000000000100000000000000000001000100\
     0000000d0000000000000000000d0000010000000100000d000001000100000d00000000\
     0000000d0100000000000000000d0000010000000000000d00000100000000000100ff0c\
     0000000d000d0000";
const WANT_NTT: &str = "32098d054408e10153066e027c033b098a02470be1057e0576072100ee041c026a0c5e00\
     57063e01d702d00452099b0c4a065609690849063a053d018a05ac067d0be70699088202\
     b8073709c7093f0b93037f0888059b05cd08ec053c084807d7051c075202e20aef0b5b00\
     22090c0caf0327065e03a6090e099b060804ff07780b250aa00bf40229018a0bd40a9800\
     0408b809d408ec04f2073d0c1104660a1f095409e40b54034601af065b002604cb08b100\
     010892063300e80aab0a8c0bfa06ce0c57051601a505d301040cd4095305a40868015602\
     1a0119058e09160bcd082507f600fc0c410b4804dd045008d50cc70a36034d054900f608\
     5e009203af0bd403700a5f05b0099e01c00c39076b0afa016d08990cc60b3c03f9006c02\
     ea0b7d07fa07a30a71062f043f0af0015b00af0a1b09b30511050404e40a120851005807\
     8709b70b3a078f0cc1028403b505160af104840017026f0af301d700d204590aea0b9301\
     f00a59065f072802fc007d009c0bb40a8b04310bd6092f039c067405a309e50698012109\
     3901fc0aee059f03cc026f0a0400a20b4b0ce5028806bc097704ad00d803b90878035b02\
     a3046f0be6006209f00a07061f067a02d102e701eb045a032f040705630260001409c30c\
     8a09ce0a29090e0a900aec08c00ac3090a060e094107940cb206b309bf023f0c080c1303\
     81032701de02b40a";
const WANT_NTTMUL: &str =
    "bb068a03ef02cd06ec0606050b0a5b046b0873080708520cb300ca04a40ad103fc069d0a\
     b1066c02b80869013e02910b150541013302ac0a820cfd00b605d901520c8504e1006f0a\
     30065c03d0087d08b606f5087703fc075b0c13017405bc02bd02a8098c00d30cb1070a02\
     d602260cbb0b1205b0076805bb0482068701a208f2018406210ae507c306990116041400\
     e30b79079305d702e5007a09350647064606f609290ae70c500ad60af304a2018401070c\
     ac049b021b07960a67047603140b9e03b60906014f00f5038d0560053902dd0a0d08de06\
     8e077d058501090bc20c9b08b00a3b03c50267012705b4046d02b3016705770afb0c8f0c\
     370bc90222053a0337080d026202f109f002ae0aca021c07f10767090101f60b060be200\
     740ae60860033b0c84076a01fa09b00be7026b00440059069300c2084e0378078a042c01\
     ee07dc05ed05670a2501fb0b77035708cf05a904cc004206e506e2059607df0c56061005\
     a6039500f8001104af09cd0908043e0218059b0330035209a8030d0a14042809de085c05\
     17023a0bed04f20b1509e108af00fd0be2098b02fa0b32011a0b6800100c4204c60c9a08\
     f1032a002f06ea097608260752083b070c027a0cb3018909df07b10ca9078d083e064a00\
     6e076c03b409de063a0ce50c9d0ac305f40aa50520000000f20917024003210610080503\
     3f041108270b0603";
const WANT_SAMPLENTT: &str =
    "9e071f00350b4e0a1d0ce508e5075a06cf08c700220b86015704f704110b40027504ce00\
     d30b9008cc05e3065908b00b2e06ee017c052e00a2065a04070c8e0c25059b0583058408\
     2d02de0a1b0cfb09a706de032905370a770c7b02430a13019c042f050d09610c3d0b8e01\
     aa009c07ff03f70914086b0cdb07250b8f02ab0a9a05450514009b069b08c20ab0059c00\
     6a0c6000bb0927045b09c507b90c9a019704f402650a600704055b0a3809a101eb084f00\
     0905490916076305c0069e0ae906370337000004bd0afd0665069e0152049e09f40c8a05\
     480a8104c30504066505de0a4b006d02cc0aac0b6003be02bd077d0be80cbc013f08e407\
     32022b001108bf03c306d9083900c8014402390cb00122014507bf02bb01670aa30b8008\
     e80c3e0a1b0b030a4e0cd6045d0aba0cd80aee068505220b16074f034e079e09300b4005\
     990ccc04ca0792084a01040a14032d09cc074101a80711061c02d9085203cf0c3a00ba01\
     d50a7b04740bc8052d0424006600d4050d02aa000701a500250b7503880b740511048d06\
     a90719055a0a8e07580cc40b1c0049068902eb03a80c6b05dd05ab01ff05f809c10c750c\
     87073c048704db060506d601da06000621019e05c70abc080304cd01e50040051406e50c\
     6700ed0a1a00a40169049500f705cc05b30c110bfa028e023b0c290ccc066c0880054008\
     4d040502ab051709";
