// gzip_smoke — exercise compress/gzip's RFC 1952 reader + writer.
//
// gzip is a variable-length header (magic 1f 8b, method, flags, mtime,
// XFL, OS, optional FEXTRA/FNAME/FCOMMENT/FHCRC fields) + raw DEFLATE
// payload + an 8-byte little-endian CRC-32/IEEE + ISIZE trailer.
//
// Coverage:
//   1..5   round-trip at NoCompression / BestSpeed / DefaultCompression
//          / BestCompression / HuffmanOnly, each over 4 inputs
//          (empty, short, highly repetitive, a few KB of mixed data).
//   6      header fields (Name, Comment, ModTime, Extra) set on the
//          Writer survive a round-trip and read back on the Reader.
//   7      multistream: two gzip members concatenated read as the
//          concatenation of their payloads.
//   8      invalid level rejected by NewWriterLevel.
//   9      corrupt magic -> ErrHeader.
//  10      corrupt trailer CRC -> ErrChecksum.
//  11      Go -> goish interop: decompress a real Go-gzip.NewWriter
//          stream (embedded as bytes, generated by the Go toolchain),
//          checking the Name/Comment header fields too.
//  12      goish -> Go interop: write a goish-compressed stream to a
//          file for the validation step to decompress with Go; also
//          assert the 3-byte magic+method prefix equals Go's.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use core::sync::atomic::{AtomicUsize, Ordering};

use goish::compress::gzip;
use goish::error;
use goish::errors;
use goish::goslice::slice;
use goish::io;
use goish::runtime::sched::schedule;
use goish::time;
use goish::types::{byte, int};
use goish::{bytes, go, syscall, Println};

const KB: usize = 1024;
const TOTAL: usize = 12;

// Linux open(2) flags not exported by goish::syscall.
const O_WRONLY: i32 = 0o1;
const O_CREAT: i32 = 0o100;
const O_TRUNC: i32 = 0o1000;

// goish -> Go interop file, read back by the validation step.
const GOISH_PRODUCED: &[u8] = b"/tmp/gzip_smoke_goish_produced.bin\0";

// The input the validation step decompresses with the Go toolchain.
const INTEROP_INPUT: &[u8] =
    b"compress/gzip interop: the quick brown fox jumps over the lazy dog. \
the quick brown fox jumps over the lazy dog. the quick brown fox jumps.";

// A real gzip stream produced by Go 1.25 `gzip.NewWriterLevel` (default
// level) compressing INTEROP_INPUT, with Name="interop.txt" and
// Comment="go-produced". Header magic is `1f 8b 08`, flags `0x18`.
const GO_STREAM: &[u8] = &[
    31, 139, 8, 24, 0, 0, 0, 0, 0, 255, 105, 110, 116, 101, 114, 111, 112, 46, 116, 120, 116, 0,
    103, 111, 45, 112, 114, 111, 100, 117, 99, 101, 100, 0, 74, 206, 207, 45, 40, 74, 45, 46, 214,
    79, 175, 202, 44, 80, 200, 204, 43, 73, 45, 202, 47, 176, 82, 40, 201, 72, 85, 40, 44, 205, 76,
    206, 86, 72, 42, 202, 47, 207, 83, 72, 203, 175, 80, 200, 42, 205, 45, 40, 86, 200, 47, 75, 45,
    2, 75, 231, 36, 86, 85, 42, 164, 228, 167, 235, 81, 73, 177, 30, 32, 0, 0, 255, 255, 25, 11,
    88, 44, 139, 0, 0, 0,
];

static FAILED: AtomicUsize = AtomicUsize::new(0);

fn fail() {
    FAILED.fetch_add(1, Ordering::AcqRel);
}

#[goish::main]
fn main() {
    go!(|| {
        run_tests();
        let f = FAILED.load(Ordering::Acquire);
        if f == 0 {
            Println!("ok 12/12");
            syscall::Exit(0);
        } else {
            Println!("FAIL", f as i64, "of 12");
            syscall::Exit(1);
        }
    });
    schedule();
}

fn run_tests() {
    test_level(1, gzip::NoCompression, b"NoCompression round-trip  ");
    test_level(2, gzip::BestSpeed, b"BestSpeed round-trip      ");
    test_level(3, gzip::DefaultCompression, b"DefaultCompression r-trip ");
    test_level(4, gzip::BestCompression, b"BestCompression round-trip");
    test_level(5, gzip::HuffmanOnly, b"HuffmanOnly round-trip    ");
    test_6_header_fields();
    test_7_multistream();
    test_8_invalid_level();
    test_9_bad_magic();
    test_10_bad_trailer();
    test_11_go_to_goish();
    test_12_goish_to_go();
}

fn from_bytes(b: &[u8]) -> slice<byte> {
    let mut v: Vec<byte> = Vec::with_capacity(b.len());
    for &x in b {
        v.push(x);
    }
    slice::__from_vec(v)
}

fn write_result(idx: u8, label: &[u8], pass: bool) {
    syscall::Write(syscall::STDOUT, b"[".as_ptr(), 1);
    let d2 = b'0' + idx % 10;
    if idx >= 10 {
        let d1 = b'0' + idx / 10;
        let buf = [d1, d2];
        syscall::Write(syscall::STDOUT, buf.as_ptr(), 2);
    } else {
        let buf = [b' ', d2];
        syscall::Write(syscall::STDOUT, buf.as_ptr(), 2);
    }
    syscall::Write(syscall::STDOUT, b"] ".as_ptr(), 2);
    syscall::Write(syscall::STDOUT, label.as_ptr(), label.len());
    if pass {
        syscall::Write(syscall::STDOUT, b" PASS\n".as_ptr(), 6);
    } else {
        syscall::Write(syscall::STDOUT, b" FAIL\n".as_ptr(), 6);
    }
}

// Compress `raw` at `level` with NewWriterLevel; return the gzip bytes.
fn compress(raw: &[u8], level: int) -> (Vec<byte>, bool) {
    let (mut w, err) = gzip::NewWriterLevel(bytes::NewBuffer(slice::new()), level);
    if !err.IsNil() {
        return (Vec::new(), false);
    }
    let (_, werr) = w.Write(from_bytes(raw));
    if !werr.IsNil() {
        return (Vec::new(), false);
    }
    if !w.Close().IsNil() {
        return (Vec::new(), false);
    }
    (drain(w.into_writer()), true)
}

// Drain a bytes::Buffer into a Vec.
fn drain(buf: bytes::Buffer) -> Vec<byte> {
    let b = buf.Bytes();
    let mut out: Vec<byte> = Vec::with_capacity(b.len() as usize);
    let mut i: int = 0;
    while i < goish::len(&b) {
        out.push(b[i]);
        i += 1;
    }
    out
}

// Decompress a gzip byte stream through goish's NewReader.
fn decompress(comp: &[u8]) -> (Vec<byte>, error) {
    let r = bytes::NewReader(from_bytes(comp));
    let (mut d, nerr) = gzip::NewReader(r);
    if !nerr.IsNil() {
        return (Vec::new(), nerr);
    }
    read_all(&mut d)
}

fn read_all<R: io::Reader>(d: &mut gzip::Reader<R>) -> (Vec<byte>, error) {
    let mut out: Vec<byte> = Vec::new();
    let mut buf = from_bytes(&[0u8; 512]);
    loop {
        let (n, err) = d.Read(&mut buf);
        let mut k: int = 0;
        while k < n {
            out.push(buf[k]);
            k += 1;
        }
        if !err.IsNil() {
            if errors::Is(err.clone(), io::EOF) {
                return (out, errors::nil);
            }
            return (out, err);
        }
    }
}

fn eq(a: &[byte], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    for i in 0..b.len() {
        if a[i] != b[i] {
            return false;
        }
    }
    true
}

// A few KB of mixed (semi-compressible) data.
fn mixed_kb() -> Vec<u8> {
    let mut v: Vec<u8> = Vec::with_capacity(4096);
    let mut x: u32 = 0x1234_5678;
    for i in 0..4096u32 {
        x = x.wrapping_mul(1_103_515_245).wrapping_add(12_345);
        let b = if i % 7 < 3 {
            (b'A' + (i % 26) as u8) as u8
        } else {
            (x >> 16) as u8
        };
        v.push(b);
    }
    v
}

// Round-trip the 4 standard inputs at one level.
fn test_level(idx: u8, level: int, label: &[u8]) {
    let kb = mixed_kb();
    let repetitive: &[u8] =
        b"abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc";
    let inputs: [&[u8]; 4] = [b"", b"hello, gzip!", repetitive, kb.as_slice()];

    let mut ok = true;
    for raw in inputs.iter() {
        let (comp, cok) = compress(raw, level);
        if !cok {
            ok = false;
            break;
        }
        let (got, err) = decompress(&comp);
        if !err.IsNil() || !eq(&got, raw) {
            ok = false;
            break;
        }
    }
    write_result(idx, label, ok);
    if !ok {
        fail();
    }
}

fn test_6_header_fields() {
    let raw: &[u8] = b"payload behind a populated gzip header";
    let name: &str = "report.csv";
    let comment: &str = "quarterly figures";
    let extra: &[u8] = &[0xde, 0xad, 0xbe, 0xef, 0x01, 0x02];
    let mtime: int = 1_700_000_000; // a fixed Unix second

    let (mut w, err) =
        gzip::NewWriterLevel(bytes::NewBuffer(slice::new()), gzip::BestCompression);
    let mut ok = err.IsNil();
    if ok {
        w.Header.Name = name.into();
        w.Header.Comment = comment.into();
        w.Header.Extra = from_bytes(extra);
        w.Header.ModTime = time::Unix(mtime, 0);
        ok = w.Write(from_bytes(raw)).1.IsNil() && w.Close().IsNil();
    }
    if ok {
        let comp = drain(w.into_writer());
        let r = bytes::NewReader(from_bytes(&comp));
        let (mut d, nerr) = gzip::NewReader(r);
        ok = nerr.IsNil();
        if ok {
            // Header fields are valid right after NewReader.
            let got_name = d.Header.Name.clone();
            let got_comment = d.Header.Comment.clone();
            ok = goish_str_eq(&got_name, name)
                && goish_str_eq(&got_comment, comment)
                && d.Header.ModTime.Unix() == mtime
                && eq_slice(&d.Header.Extra, extra);
        }
        if ok {
            let (got, e) = read_all(&mut d);
            ok = e.IsNil() && eq(&got, raw);
        }
    }
    write_result(6, b"header fields survive r-tp", ok);
    if !ok {
        fail();
    }
}

fn goish_str_eq(s: &goish::string, t: &str) -> bool {
    let a = s.as_bytes();
    let b = t.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    for i in 0..b.len() {
        if a[i] != b[i] {
            return false;
        }
    }
    true
}

fn eq_slice(s: &slice<byte>, b: &[u8]) -> bool {
    if (s.Len() as usize) != b.len() {
        return false;
    }
    let mut i: int = 0;
    while (i as usize) < b.len() {
        if s[i] != b[i as usize] {
            return false;
        }
        i += 1;
    }
    true
}

fn test_7_multistream() {
    // Two independently-gzipped members; the concatenation must read as
    // the concatenation of the two payloads.
    let p1: &[u8] = b"first gzip member payload; ";
    let p2: &[u8] = b"second gzip member payload.";
    let (c1, ok1) = compress(p1, gzip::DefaultCompression);
    let (c2, ok2) = compress(p2, gzip::BestCompression);
    let mut ok = ok1 && ok2;
    if ok {
        let mut both: Vec<u8> = Vec::new();
        both.extend_from_slice(&c1);
        both.extend_from_slice(&c2);
        let mut expect: Vec<u8> = Vec::new();
        expect.extend_from_slice(p1);
        expect.extend_from_slice(p2);
        let (got, e) = decompress(&both);
        ok = e.IsNil() && eq(&got, &expect);
    }
    write_result(7, b"multistream concatenation ", ok);
    if !ok {
        fail();
    }
}

fn test_8_invalid_level() {
    // Level 42 is out of range -> NewWriterLevel returns a non-nil error.
    let (_, err) = gzip::NewWriterLevel(bytes::NewBuffer(slice::new()), 42);
    let ok = !err.IsNil();
    write_result(8, b"invalid level rejected    ", ok);
    if !ok {
        fail();
    }
}

fn test_9_bad_magic() {
    // Corrupt the gzip magic (first byte) -> ErrHeader.
    let (mut comp, cok) = compress(b"some payload to corrupt", gzip::DefaultCompression);
    let mut ok = cok && comp.len() > 10;
    if ok {
        comp[0] ^= 0xff; // breaks gzipID1
        let (_, err) = decompress(&comp);
        ok = errors::Is(err, gzip::ErrHeader);
    }
    write_result(9, b"corrupt magic -> ErrHeader", ok);
    if !ok {
        fail();
    }
}

fn test_10_bad_trailer() {
    // Corrupt a byte of the 8-byte CRC-32 + ISIZE trailer.
    let (mut comp, cok) = compress(b"some payload to corrupt", gzip::DefaultCompression);
    let mut ok = cok && comp.len() > 8;
    if ok {
        let n = comp.len();
        comp[n - 5] ^= 0xff; // a CRC byte in the trailer
        let (_, err) = decompress(&comp);
        ok = errors::Is(err, gzip::ErrChecksum);
    }
    write_result(10, b"corrupt trailer->ErrChksum", ok);
    if !ok {
        fail();
    }
}

fn test_11_go_to_goish() {
    // Decompress a real Go-produced gzip stream with goish, and check
    // the Name/Comment header fields round-tripped from Go.
    let r = bytes::NewReader(from_bytes(GO_STREAM));
    let (mut d, nerr) = gzip::NewReader(r);
    let mut ok = nerr.IsNil();
    if ok {
        ok = goish_str_eq(&d.Header.Name, "interop.txt")
            && goish_str_eq(&d.Header.Comment, "go-produced");
    }
    if ok {
        let (got, err) = read_all(&mut d);
        ok = err.IsNil() && eq(&got, INTEROP_INPUT);
    }
    write_result(11, b"Go -> goish interop       ", ok);
    if !ok {
        fail();
    }
}

// Write `data` to a file via raw syscalls. Returns success.
fn write_file(path: &[u8], data: &[u8]) -> bool {
    let fd = syscall::Open(path.as_ptr(), O_WRONLY | O_CREAT | O_TRUNC, 0o644);
    if fd < 0 {
        return false;
    }
    let mut off = 0usize;
    let mut ok = true;
    while off < data.len() {
        let n = syscall::Write(fd, data[off..].as_ptr(), data.len() - off);
        if n <= 0 {
            ok = false;
            break;
        }
        off += n as usize;
    }
    syscall::Close(fd);
    ok
}

fn test_12_goish_to_go() {
    // Compress INTEROP_INPUT with goish at DefaultCompression, set a
    // header Name, and drop it to GOISH_PRODUCED for the validation
    // step to decompress with the Go toolchain.
    let (mut w, err) =
        gzip::NewWriterLevel(bytes::NewBuffer(slice::new()), gzip::DefaultCompression);
    let mut ok = err.IsNil();
    if ok {
        w.Header.Name = "goish.txt".into();
        ok = w.Write(from_bytes(INTEROP_INPUT)).1.IsNil() && w.Close().IsNil();
    }
    let mut comp: Vec<byte> = Vec::new();
    if ok {
        comp = drain(w.into_writer());
        ok = comp.len() > 18;
    }
    // The 3-byte magic+method prefix is fixed: 1f 8b 08.
    if ok {
        ok = comp[0] == 0x1f && comp[1] == 0x8b && comp[2] == 0x08;
    }
    if ok {
        ok = write_file(GOISH_PRODUCED, &comp);
    }
    // Local sanity: goish must round-trip its own output.
    if ok {
        let (got, e) = decompress(&comp);
        ok = e.IsNil() && eq(&got, INTEROP_INPUT);
    }
    write_result(12, b"goish -> Go interop       ", ok);
    if !ok {
        fail();
    }
}

// Reference the constant so the harness shape matches sibling examples.
const _: usize = TOTAL;
