// rand_ref_smoke — the seeded sequences, against a running Go.
// (math/rand/{rand,rng,normal,exp}.go, math/rand/v2/{rand,pcg}.go)
//
// Every expectation below is what a real Go 1.25.5 prints: the vectors
// are the output of `tools/gen_rand_ref.go` and `tools/gen_randv2_ref.go`
// run by `scripts/goref.sh`. The tables are GENERATED from that output
// rather than typed, so a transcription slip cannot make a wrong
// generator look right.
//
// A seeded generator is a DETERMINISTIC sequence, and Go's compatibility
// promise covers it: "the sequence of values generated by a given Source
// is guaranteed to remain stable". Anything that reproduces a shuffle, a
// sample, a fixture or a load pattern depends on that — and a generator
// that is off by one step still returns numbers in range, so nothing
// looks wrong until two sides compare notes.
//
// Neither package had a single provenance anchor: 49 functions in v1 and
// 24 in v2 matched Go by NAME only. That is the state `encoding/binary`
// was in when its Read and Write turned out to be stubs, and the state
// `math` was in when four of its special cases turned out to be wrong.
//
// Here the answer is that everything agrees — the ALFG's first six
// values for five seeds, all four bounded forms and their modulo bias
// handling, Float32/Float64, Perm, Shuffle, Read's byte stream, and both
// ziggurat generators (NormFloat64 and ExpFloat64) to the last bit; then
// in v2 the PCG stream, Lemire's bounded forms, and the marshalled
// generator state. That is the result worth recording, and the anchors
// are what turn it from a name match into something GOISH018 keeps
// checking.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use goish::gostring::string;
use goish::math::rand;
use goish::math::rand::v2::{self as randv2, Source};
use goish::types::{byte, int};
use goish::{fmt, slice, syscall};

fn s(x: &str) -> string {
    return string::from_bytes(x.as_bytes());
}

// go: none — goish idiom: the smokes print one PASS/FAIL line per
//     numbered check; this is that line, hoisted.
fn report(failed: &mut int, ok: bool, n: &str, what: &str) {
    if ok {
        fmt::Println!("[", n, "]", what, "PASS");
    } else {
        fmt::Println!("[", n, "]", what, "FAIL");
        *failed += 1;
    }
}

// go: none — goish idiom: report one wrong draw against Go's, saying
//     which step of the sequence went wrong — the step matters, because
//     a generator that is merely OFFSET produces the right numbers in
//     the wrong places.
fn step(ok: &mut bool, what: &str, i: usize, got: i64, want: i64) {
    if got != want {
        fmt::Println!(
            "   ",
            s(what),
            fmt::Sprintf!("step %d got %d want %d", i as int, got, want)
        );
        *ok = false;
    }
}

fn stepu(ok: &mut bool, what: &str, i: usize, got: u64, want: u64) {
    if got != want {
        fmt::Println!(
            "   ",
            s(what),
            fmt::Sprintf!("step %d got %d want %d", i as int, got, want)
        );
        *ok = false;
    }
}

fn stepf(ok: &mut bool, what: &str, i: usize, got: f64, want: f64) {
    if got != want {
        fmt::Println!(
            "   ",
            s(what),
            fmt::Sprintf!("step %d got %v want %v", i as int, got, want)
        );
        *ok = false;
    }
}

const V1_INT63: [(i64, [i64; 6]); 5] = [
    (
        1,
        [
            5577006791947779410,
            8674665223082153551,
            6129484611666145821,
            4037200794235010051,
            3916589616287113937,
            6334824724549167320,
        ],
    ),
    (
        42,
        [
            3440579354231278675,
            608747136543856411,
            5571782338101878760,
            1926012586526624009,
            404153945743547657,
            3534334367214237261,
        ],
    ),
    (
        0,
        [
            8717895732742165505,
            2259404117704393152,
            6050128673802995827,
            501233450539197794,
            3390393562759376202,
            2669985732393126063,
        ],
    ),
    (
        -1,
        [
            3644962268338389676,
            550171362161912239,
            3094056749125766625,
            5185619287625335803,
            5303699392440114477,
            2885068457955727142,
        ],
    ),
    (
        1099511627776,
        [
            5470237361722394362,
            6322525149314491254,
            1177463506020107830,
            1565541666764780662,
            7675952003761928004,
            5800323741864134101,
        ],
    ),
];

const V1_UINT32: [u32; 6] = [
    2596996162, 4039455774, 2854263694, 1879968118, 1823804162, 2949882636,
];

const V1_UINT64: [u64; 4] = [
    5577006791947779410,
    8674665223082153551,
    15352856648520921629,
    13260572831089785859,
];

const V1_INT31: [i32; 6] = [
    1298498081, 2019727887, 1427131847, 939984059, 911902081, 1474941318,
];

const V1_INT: [i64; 4] = [
    5577006791947779410,
    8674665223082153551,
    6129484611666145821,
    4037200794235010051,
];

const V1_INT63N: [(i64, [i64; 6]); 5] = [
    (1, [0, 0, 0, 0, 0, 0]),
    (2, [0, 1, 1, 1, 1, 0]),
    (10, [0, 1, 1, 1, 7, 0]),
    (1000, [410, 551, 821, 51, 937, 320]),
    (
        1099511627776,
        [
            141867941202,
            66022479439,
            856419562013,
            805227559939,
            555288552145,
            575745648856,
        ],
    ),
];

const V1_INT31N: [(i32, [i32; 6]); 5] = [
    (1, [0, 0, 0, 0, 0, 0]),
    (2, [1, 1, 1, 1, 1, 0]),
    (10, [1, 7, 7, 9, 1, 8]),
    (1000, [81, 887, 847, 59, 81, 318]),
    (
        1073741824,
        [
            224756257, 945986063, 353390023, 939984059, 911902081, 401199494,
        ],
    ),
];

const V1_INTN: [(i64, [i64; 6]); 0] = [];

const V1_FLOAT64: [f64; 5] = [
    0.6046602879796196,
    0.9405090880450124,
    0.6645600532184904,
    0.4377141871869802,
    0.4246374970712657,
];

const V1_FLOAT32: [f32; 5] = [
    0.6046603f32,
    0.9405091f32,
    0.6645601f32,
    0.4377142f32,
    0.4246375f32,
];

const V1_PERM: [(i64, &[i64]); 4] = [
    (0, &[]),
    (1, &[0]),
    (5, &[2, 1, 4, 0, 3]),
    (10, &[8, 6, 4, 5, 3, 7, 1, 9, 2, 0]),
];

const V1_SHUFFLE: [(i64, &[i64]); 4] = [
    (0, &[]),
    (1, &[0]),
    (5, &[0, 1, 4, 2, 3]),
    (10, &[2, 0, 3, 4, 1, 6, 8, 9, 5, 7]),
];

const V1_READ: [(i64, &[u8]); 6] = [
    (0, &[]),
    (1, &[192]),
    (7, &[192, 9, 19, 224, 42, 99, 228]),
    (8, &[192, 9, 19, 224, 42, 99, 228, 207]),
    (9, &[192, 9, 19, 224, 42, 99, 228, 207, 83]),
    (
        16,
        &[
            192, 9, 19, 224, 42, 99, 228, 207, 83, 45, 155, 44, 226, 130, 250, 216,
        ],
    ),
];

const V1_NORM: [f64; 5] = [
    -1.233758177597947,
    -0.12634751070237293,
    -0.5209945711531503,
    2.28571911769958,
    0.3228052526115799,
];

const V1_EXP: [f64; 5] = [
    0.5872982159059681,
    0.5372820936538049,
    1.2310533463860203,
    0.6776268958872181,
    0.04451836051028885,
];

const V2_PCG: [(u64, u64, [u64; 6]); 4] = [
    (
        1,
        2,
        [
            14192431797130687760,
            11371241257079532652,
            14470142590855381128,
            14694613213362438554,
            4321634407747778896,
            760102831717374652,
        ],
    ),
    (
        0,
        0,
        [
            4107282207882862730,
            12464933722704884221,
            6335497120186221275,
            8128828598453185623,
            7371889741448783355,
            1418823048812169170,
        ],
    ),
    (
        42,
        42,
        [
            11423875981923235010,
            6939021390147428351,
            11771167194916608150,
            9461442655400484610,
            17656514111333594935,
            4918454514787541865,
        ],
    ),
    (
        18446744073709551615,
        1,
        [
            2880816893292392925,
            10683443147829997439,
            401498593426200364,
            7374622554483866847,
            5121043495194106904,
            450775370386692021,
        ],
    ),
];

const V2_INT64: [i64; 5] = [
    4969059760275911952,
    2147869220224756844,
    5246770554000605320,
    5471241176507662746,
    4321634407747778896,
];

const V2_UINT64: [u64; 5] = [
    14192431797130687760,
    11371241257079532652,
    14470142590855381128,
    14694613213362438554,
    4321634407747778896,
];

const V2_UINT32: [u32; 5] = [3304433030, 2647573421, 3369092613, 3421356252, 1006208920];

const V2_INT32: [i32; 5] = [1652216515, 1323786710, 1684546306, 1710678126, 503104460];

const V2_INT: [i64; 5] = [
    4969059760275911952,
    2147869220224756844,
    5246770554000605320,
    5471241176507662746,
    4321634407747778896,
];

const V2_INT64N: [(i64, [i64; 6]); 5] = [
    (1, [0, 0, 0, 0, 0, 0]),
    (2, [0, 0, 0, 0, 0, 0]),
    (10, [7, 6, 7, 7, 2, 0]),
    (1000, [769, 616, 784, 796, 234, 41]),
    (
        1099511627776,
        [
            576984118544,
            743155035244,
            22300033160,
            947950109082,
            656239327568,
            547831175868,
        ],
    ),
];

const V2_UINT64N: [(u64, [u64; 6]); 5] = [
    (1, [0, 0, 0, 0, 0, 0]),
    (2, [0, 0, 0, 0, 0, 0]),
    (10, [7, 6, 7, 7, 2, 0]),
    (1000, [769, 616, 784, 796, 234, 41]),
    (
        1099511627776,
        [
            576984118544,
            743155035244,
            22300033160,
            947950109082,
            656239327568,
            547831175868,
        ],
    ),
];

const V2_UINT32N: [(u32, [u32; 6]); 5] = [
    (1, [0, 0, 0, 0, 0, 0]),
    (2, [0, 0, 0, 0, 0, 0]),
    (10, [7, 6, 7, 7, 2, 0]),
    (1000, [769, 616, 784, 796, 234, 41]),
    (
        1073741824,
        [
            384759056, 125693036, 825196680, 909820314, 183073104, 222845628,
        ],
    ),
];

const V2_INT32N: [(i32, [i32; 6]); 4] = [
    (1, [0, 0, 0, 0, 0, 0]),
    (2, [0, 0, 0, 0, 0, 0]),
    (10, [7, 6, 7, 7, 2, 0]),
    (1000, [769, 616, 784, 796, 234, 41]),
];

const V2_INTN: [(i64, [i64; 6]); 0] = [];

const V2_FLOAT64: [f64; 5] = [
    0.6764556596678251,
    0.4613862177205994,
    0.5085473976760264,
    0.4297927436037299,
    0.797802349388613,
];

const V2_FLOAT32: [f32; 5] = [
    0.95955694f32,
    0.8076733f32,
    0.8135684f32,
    0.92872405f32,
    0.97472525f32,
];

const V2_SHUFFLE: [(i64, &[i64]); 4] = [
    (0, &[]),
    (1, &[0]),
    (5, &[1, 4, 2, 0, 3]),
    (10, &[4, 2, 3, 6, 9, 1, 8, 0, 5, 7]),
];

const V2_MARSHAL: [u8; 20] = [
    112, 99, 103, 58, 226, 153, 173, 156, 43, 239, 48, 186, 155, 17, 58, 72, 55, 1, 109, 217,
];

#[goish::main]
fn main() {
    let mut failed = 0;

    // 1. v1's ALFG: the first six Int63 draws for five seeds, including
    //    0 and -1. Seed 0 is not "no seed" in Go — it is a seed like any
    //    other, and its sequence is not the unseeded one.
    {
        let mut ok = true;
        let mut k = 0usize;
        while k < V1_INT63.len() {
            let (seed, want) = V1_INT63[k];
            let mut r = rand::New(rand::NewSource(seed));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Int63", i, r.Int63(), want[i]);
                i += 1;
            }
            k += 1;
        }
        // The other widths off the same seed.
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_UINT32.len() {
            stepu(&mut ok, "Uint32", i, r.Uint32() as u64, V1_UINT32[i] as u64);
            i += 1;
        }
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_UINT64.len() {
            stepu(&mut ok, "Uint64", i, r.Uint64(), V1_UINT64[i]);
            i += 1;
        }
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_INT31.len() {
            step(&mut ok, "Int31", i, r.Int31() as i64, V1_INT31[i] as i64);
            i += 1;
        }
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_INT.len() {
            step(&mut ok, "Int", i, r.Int(), V1_INT[i]);
            i += 1;
        }
        report(&mut failed, ok, " 1", "v1: the ALFG's sequence, five seeds");
    }

    // 2. v1's bounded forms. `n` a power of two takes a mask, anything
    //    else a rejection loop, and the loop is where a port drifts:
    //    reject one value too few and the distribution is biased and the
    //    sequence is shifted.
    {
        let mut ok = true;
        let mut k = 0usize;
        while k < V1_INT63N.len() {
            let (n, want) = V1_INT63N[k];
            let mut r = rand::New(rand::NewSource(1));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Int63n", i, r.Int63n(n), want[i]);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V1_INT31N.len() {
            let (n, want) = V1_INT31N[k];
            let mut r = rand::New(rand::NewSource(1));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Int31n", i, r.Int31n(n) as i64, want[i] as i64);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V1_INTN.len() {
            let (n, want) = V1_INTN[k];
            let mut r = rand::New(rand::NewSource(7));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Intn", i, r.Intn(n), want[i]);
                i += 1;
            }
            k += 1;
        }
        report(
            &mut failed,
            ok,
            " 2",
            "v1: the bounded forms and their rejection",
        );
    }

    // 3. v1's floats, and the two ziggurat generators. NormFloat64 and
    //    ExpFloat64 draw a variable number of values per result, so a
    //    single wrong table entry desynchronises everything after it.
    {
        let mut ok = true;
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_FLOAT64.len() {
            stepf(&mut ok, "Float64", i, r.Float64(), V1_FLOAT64[i]);
            i += 1;
        }
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_FLOAT32.len() {
            stepf(
                &mut ok,
                "Float32",
                i,
                r.Float32() as f64,
                V1_FLOAT32[i] as f64,
            );
            i += 1;
        }
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_NORM.len() {
            stepf(&mut ok, "NormFloat64", i, r.NormFloat64(), V1_NORM[i]);
            i += 1;
        }
        let mut r = rand::New(rand::NewSource(1));
        let mut i = 0usize;
        while i < V1_EXP.len() {
            stepf(&mut ok, "ExpFloat64", i, r.ExpFloat64(), V1_EXP[i]);
            i += 1;
        }
        report(&mut failed, ok, " 3", "v1: floats, and both ziggurats");
    }

    // 4. v1's Perm, Shuffle and Read. A permutation is the sharpest
    //    test of all: it consumes one draw per element and any drift
    //    reorders the whole thing.
    {
        let mut ok = true;
        let mut k = 0usize;
        while k < V1_PERM.len() {
            let (n, want) = V1_PERM[k];
            let mut r = rand::New(rand::NewSource(3));
            let got = r.Perm(n);
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Perm", i, got[i], want[i]);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V1_SHUFFLE.len() {
            let (n, want) = V1_SHUFFLE[k];
            let mut r = rand::New(rand::NewSource(3));
            let mut x: slice<int> = goish::make!([]int, n);
            let mut i = 0i64;
            while i < n {
                x[i as usize] = i;
                i += 1;
            }
            let ptr = x.as_mut_ptr();
            r.Shuffle(n, |a, b| unsafe {
                core::ptr::swap(ptr.offset(a as isize), ptr.offset(b as isize))
            });
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Shuffle", i, x[i], want[i]);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V1_READ.len() {
            let (n, want) = V1_READ[k];
            let mut r = rand::New(rand::NewSource(5));
            let mut b: slice<byte> = goish::make!([]byte, n);
            let (got, err) = r.Read(&mut b);
            if got != n || !err.IsNil() {
                ok = false;
            }
            let mut i = 0usize;
            while i < want.len() {
                stepu(&mut ok, "Read", i, b[i] as u64, want[i] as u64);
                i += 1;
            }
            k += 1;
        }
        report(&mut failed, ok, " 4", "v1: Perm, Shuffle and Read");
    }

    // 5. v2's PCG, straight off the Source. A different generator from
    //    v1's entirely, so none of the numbers above appear here.
    {
        let mut ok = true;
        let mut k = 0usize;
        while k < V2_PCG.len() {
            let (a, b, want) = V2_PCG[k];
            let mut p = randv2::NewPCG(a, b);
            let mut i = 0usize;
            while i < want.len() {
                stepu(&mut ok, "PCG", i, p.Uint64(), want[i]);
                i += 1;
            }
            k += 1;
        }
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_INT64.len() {
            step(&mut ok, "v2 Int64", i, r.Int64(), V2_INT64[i]);
            i += 1;
        }
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_UINT64.len() {
            stepu(&mut ok, "v2 Uint64", i, r.Uint64(), V2_UINT64[i]);
            i += 1;
        }
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_UINT32.len() {
            stepu(
                &mut ok,
                "v2 Uint32",
                i,
                r.Uint32() as u64,
                V2_UINT32[i] as u64,
            );
            i += 1;
        }
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_INT32.len() {
            step(&mut ok, "v2 Int32", i, r.Int32() as i64, V2_INT32[i] as i64);
            i += 1;
        }
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_INT.len() {
            step(&mut ok, "v2 Int", i, r.Int(), V2_INT[i]);
            i += 1;
        }
        report(
            &mut failed,
            ok,
            " 5",
            "v2: the PCG stream and the plain draws",
        );
    }

    // 6. v2's bounded forms, which use Lemire's multiply-and-shift
    //    rather than v1's rejection loop — a different algorithm, so a
    //    port that borrows v1's arithmetic here looks right and is not.
    {
        let mut ok = true;
        let mut k = 0usize;
        while k < V2_INT64N.len() {
            let (n, want) = V2_INT64N[k];
            let mut r = randv2::New(randv2::NewPCG(1, 2));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Int64N", i, r.Int64N(n), want[i]);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V2_UINT64N.len() {
            let (n, want) = V2_UINT64N[k];
            let mut r = randv2::New(randv2::NewPCG(1, 2));
            let mut i = 0usize;
            while i < want.len() {
                stepu(&mut ok, "Uint64N", i, r.Uint64N(n), want[i]);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V2_UINT32N.len() {
            let (n, want) = V2_UINT32N[k];
            let mut r = randv2::New(randv2::NewPCG(1, 2));
            let mut i = 0usize;
            while i < want.len() {
                stepu(&mut ok, "Uint32N", i, r.Uint32N(n) as u64, want[i] as u64);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V2_INT32N.len() {
            let (n, want) = V2_INT32N[k];
            let mut r = randv2::New(randv2::NewPCG(1, 2));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "Int32N", i, r.Int32N(n) as i64, want[i] as i64);
                i += 1;
            }
            k += 1;
        }
        let mut k = 0usize;
        while k < V2_INTN.len() {
            let (n, want) = V2_INTN[k];
            let mut r = randv2::New(randv2::NewPCG(1, 2));
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "IntN", i, r.IntN(n), want[i]);
                i += 1;
            }
            k += 1;
        }
        report(&mut failed, ok, " 6", "v2: Lemire's bounded forms");
    }

    // 7. v2's floats, Shuffle, and the marshalled generator state —
    //    the bytes that make a generator resumable, and therefore the
    //    thing that has to be identical for a checkpoint to reload.
    {
        let mut ok = true;
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_FLOAT64.len() {
            stepf(&mut ok, "v2 Float64", i, r.Float64(), V2_FLOAT64[i]);
            i += 1;
        }
        let mut r = randv2::New(randv2::NewPCG(1, 2));
        let mut i = 0usize;
        while i < V2_FLOAT32.len() {
            stepf(
                &mut ok,
                "v2 Float32",
                i,
                r.Float32() as f64,
                V2_FLOAT32[i] as f64,
            );
            i += 1;
        }
        let mut k = 0usize;
        while k < V2_SHUFFLE.len() {
            let (n, want) = V2_SHUFFLE[k];
            let mut r = randv2::New(randv2::NewPCG(1, 2));
            let mut x: slice<int> = goish::make!([]int, n);
            let mut i = 0i64;
            while i < n {
                x[i as usize] = i;
                i += 1;
            }
            let ptr = x.as_mut_ptr();
            r.Shuffle(n, |a, b| unsafe {
                core::ptr::swap(ptr.offset(a as isize), ptr.offset(b as isize))
            });
            let mut i = 0usize;
            while i < want.len() {
                step(&mut ok, "v2 Shuffle", i, x[i], want[i]);
                i += 1;
            }
            k += 1;
        }
        // Go: marshal [112 99 103 58 …] — "pcg:" then the two halves of
        // the state, big-endian.
        let mut p = randv2::NewPCG(1, 2);
        let _ = p.Uint64();
        let (b, err) = p.MarshalBinary();
        if !err.IsNil() || b.len() != V2_MARSHAL.len() {
            ok = false;
        } else {
            let mut i = 0usize;
            while i < V2_MARSHAL.len() {
                stepu(
                    &mut ok,
                    "MarshalBinary",
                    i,
                    b[i] as u64,
                    V2_MARSHAL[i] as u64,
                );
                i += 1;
            }
        }
        // And it resumes: an unmarshalled generator continues where the
        // marshalled one left off, which Go's own reference shows by
        // NOT matching a freshly seeded one.
        let mut q = randv2::NewPCG(0, 0);
        if !q.UnmarshalBinary(&b).IsNil() {
            ok = false;
        }
        let mut p2 = randv2::NewPCG(1, 2);
        let _ = p2.Uint64();
        if q.Uint64() != p2.Uint64() {
            ok = false;
        }
        report(
            &mut failed,
            ok,
            " 7",
            "v2: floats, Shuffle, and a resumable state",
        );
    }

    if failed == 0 {
        fmt::Println!("ok 7/7");
        syscall::Exit(0);
    } else {
        fmt::Println!("FAIL", failed, "of 7");
        syscall::Exit(1);
    }
}
