// regexp_compile_ref_smoke — `Simplify` and `Compile`, stage 3 of §2c.
//
// Parse, simplify, compile: the AST becomes a `Prog`. This is the step
// §2c exists for. Once a match is a walk over integer program counters,
// the memo key is `(pc, pos)` — two small integers — and the
// exponential blowup of a backtracker over an AST has nowhere to live.
// The engine that walks it is stage 4.
//
// Each pattern contributes five rows: its parse, its simplification,
// the program's shape (`NumCap`, `Start`, instruction count), the
// prefix and start condition the engine will use to skip work, and the
// full instruction dump.
//
// What the rows are chosen to hold down:
//
//   `(?:a+)+` -> `a+`      simplify1's idempotence, which is why a
//                          nested quantifier does not nest a loop
//   `a{2,5}`  -> `aa(a(a(a)?)?)?`  Go's nesting, "the machine will do
//                          less work if we nest the final m copies"
//   `(?:a*)*`              star of a NULLABLE body compiles as
//                          `(f1+)?`, not as a loop — go.dev/issue/46123
//   `a*?`                  non-greedy puts the body in Arg and leaves
//                          Out as the hole; that swap IS the priority
//                          order
//   `(?i)a` vs `(?i)k`     FoldCase survives only when the rune has a
//                          fold orbit, and `InstRune1` is chosen only
//                          once it is gone
//   `a{0}`                 the empty match, without even considering a
//
// 361 rows from `scripts/goref.sh regexp/syntax
// tools/gen_regexp_compile_ref.go`.

#![no_std]
#![no_main]

extern crate alloc;
extern crate goish;

use goish::regexp::syntax;
use goish::types::int;
use goish::{fmt, string, strconv};

static mut FAILED: int = 0;
static mut RUN: int = 0;

const GO: [&str; 591] = [
    r#"  0 "a"                    parsed   "a""#,
    r#"  0 "a"                    simple   "a""#,
    r#"  0 "a"                    numcap=2 start=1 ninst=3"#,
    r#"  0 "a"                    prefix="a" complete=true startcond=0"#,
    r#"  0 "a"                    prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tmatch\n""#,
    r#"  1 "ab"                   parsed   "ab""#,
    r#"  1 "ab"                   simple   "ab""#,
    r#"  1 "ab"                   numcap=2 start=1 ninst=4"#,
    r#"  1 "ab"                   prefix="ab" complete=true startcond=0"#,
    r#"  1 "ab"                   prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"b\" -> 3\n  3\tmatch\n""#,
    r#"  2 "abc"                  parsed   "abc""#,
    r#"  2 "abc"                  simple   "abc""#,
    r#"  2 "abc"                  numcap=2 start=1 ninst=5"#,
    r#"  2 "abc"                  prefix="abc" complete=true startcond=0"#,
    r#"  2 "abc"                  prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"b\" -> 3\n  3\trune1 \"c\" -> 4\n  4\tmatch\n""#,
    r#"  3 "a|b"                  parsed   "[ab]""#,
    r#"  3 "a|b"                  simple   "[ab]""#,
    r#"  3 "a|b"                  numcap=2 start=1 ninst=3"#,
    r#"  3 "a|b"                  prefix="" complete=false startcond=0"#,
    r#"  3 "a|b"                  prog     "  0\tfail\n  1*\trune \"ab\" -> 2\n  2\tmatch\n""#,
    r#"  4 "a|b|c"                parsed   "[a-c]""#,
    r#"  4 "a|b|c"                simple   "[a-c]""#,
    r#"  4 "a|b|c"                numcap=2 start=1 ninst=3"#,
    r#"  4 "a|b|c"                prefix="" complete=false startcond=0"#,
    r#"  4 "a|b|c"                prog     "  0\tfail\n  1*\trune \"ac\" -> 2\n  2\tmatch\n""#,
    r#"  5 "(a)"                  parsed   "(a)""#,
    r#"  5 "(a)"                  simple   "(a)""#,
    r#"  5 "(a)"                  numcap=4 start=1 ninst=5"#,
    r#"  5 "(a)"                  prefix="a" complete=true startcond=0"#,
    r#"  5 "(a)"                  prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 4\n  4\tmatch\n""#,
    r#"  6 "(a)(b)"               parsed   "(a)(b)""#,
    r#"  6 "(a)(b)"               simple   "(a)(b)""#,
    r#"  6 "(a)(b)"               numcap=6 start=1 ninst=8"#,
    r#"  6 "(a)(b)"               prefix="ab" complete=true startcond=0"#,
    r#"  6 "(a)(b)"               prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 4\n  4\tcap 4 -> 5\n  5\trune1 \"b\" -> 6\n  6\tcap 5 -> 7\n  7\tmatch\n""#,
    r#"  7 "(?:a)"                parsed   "a""#,
    r#"  7 "(?:a)"                simple   "a""#,
    r#"  7 "(?:a)"                numcap=2 start=1 ninst=3"#,
    r#"  7 "(?:a)"                prefix="a" complete=true startcond=0"#,
    r#"  7 "(?:a)"                prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tmatch\n""#,
    r#"  8 "a*"                   parsed   "a*""#,
    r#"  8 "a*"                   simple   "a*""#,
    r#"  8 "a*"                   numcap=2 start=2 ninst=4"#,
    r#"  8 "a*"                   prefix="" complete=false startcond=0"#,
    r#"  8 "a*"                   prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#"  9 "a+"                   parsed   "a+""#,
    r#"  9 "a+"                   simple   "a+""#,
    r#"  9 "a+"                   numcap=2 start=1 ninst=4"#,
    r#"  9 "a+"                   prefix="a" complete=false startcond=0"#,
    r#"  9 "a+"                   prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 10 "a?"                   parsed   "a?""#,
    r#" 10 "a?"                   simple   "a?""#,
    r#" 10 "a?"                   numcap=2 start=2 ninst=4"#,
    r#" 10 "a?"                   prefix="" complete=false startcond=0"#,
    r#" 10 "a?"                   prog     "  0\tfail\n  1\trune1 \"a\" -> 3\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 11 "a*?"                  parsed   "a*?""#,
    r#" 11 "a*?"                  simple   "a*?""#,
    r#" 11 "a*?"                  numcap=2 start=2 ninst=4"#,
    r#" 11 "a*?"                  prefix="" complete=false startcond=0"#,
    r#" 11 "a*?"                  prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2*\talt -> 3, 1\n  3\tmatch\n""#,
    r#" 12 "a+?"                  parsed   "a+?""#,
    r#" 12 "a+?"                  simple   "a+?""#,
    r#" 12 "a+?"                  numcap=2 start=1 ninst=4"#,
    r#" 12 "a+?"                  prefix="a" complete=false startcond=0"#,
    r#" 12 "a+?"                  prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\talt -> 3, 1\n  3\tmatch\n""#,
    r#" 13 "a??"                  parsed   "a??""#,
    r#" 13 "a??"                  simple   "a??""#,
    r#" 13 "a??"                  numcap=2 start=2 ninst=4"#,
    r#" 13 "a??"                  prefix="" complete=false startcond=0"#,
    r#" 13 "a??"                  prog     "  0\tfail\n  1\trune1 \"a\" -> 3\n  2*\talt -> 3, 1\n  3\tmatch\n""#,
    r#" 14 "a{2}"                 parsed   "a{2}""#,
    r#" 14 "a{2}"                 simple   "aa""#,
    r#" 14 "a{2}"                 numcap=2 start=1 ninst=4"#,
    r#" 14 "a{2}"                 prefix="aa" complete=true startcond=0"#,
    r#" 14 "a{2}"                 prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"a\" -> 3\n  3\tmatch\n""#,
    r#" 15 "a{2,3}"               parsed   "a{2,3}""#,
    r#" 15 "a{2,3}"               simple   "aaa?""#,
    r#" 15 "a{2,3}"               numcap=2 start=1 ninst=6"#,
    r#" 15 "a{2,3}"               prefix="aa" complete=false startcond=0"#,
    r#" 15 "a{2,3}"               prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"a\" -> 4\n  3\trune1 \"a\" -> 5\n  4\talt -> 3, 5\n  5\tmatch\n""#,
    r#" 16 "a{2,}"                parsed   "a{2,}""#,
    r#" 16 "a{2,}"                simple   "aa+""#,
    r#" 16 "a{2,}"                numcap=2 start=1 ninst=5"#,
    r#" 16 "a{2,}"                prefix="aa" complete=false startcond=0"#,
    r#" 16 "a{2,}"                prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"a\" -> 3\n  3\talt -> 2, 4\n  4\tmatch\n""#,
    r#" 17 "a{0,3}"               parsed   "a{0,3}""#,
    r#" 17 "a{0,3}"               simple   "(?:a(?:aa?)?)?""#,
    r#" 17 "a{0,3}"               numcap=2 start=6 ninst=8"#,
    r#" 17 "a{0,3}"               prefix="" complete=false startcond=0"#,
    r#" 17 "a{0,3}"               prog     "  0\tfail\n  1\trune1 \"a\" -> 5\n  2\trune1 \"a\" -> 4\n  3\trune1 \"a\" -> 7\n  4\talt -> 3, 7\n  5\talt -> 2, 7\n  6*\talt -> 1, 7\n  7\tmatch\n""#,
    r#" 18 "a{0,}"                parsed   "a{0,}""#,
    r#" 18 "a{0,}"                simple   "a*""#,
    r#" 18 "a{0,}"                numcap=2 start=2 ninst=4"#,
    r#" 18 "a{0,}"                prefix="" complete=false startcond=0"#,
    r#" 18 "a{0,}"                prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 19 "a{1,}"                parsed   "a{1,}""#,
    r#" 19 "a{1,}"                simple   "a+""#,
    r#" 19 "a{1,}"                numcap=2 start=1 ninst=4"#,
    r#" 19 "a{1,}"                prefix="a" complete=false startcond=0"#,
    r#" 19 "a{1,}"                prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 20 "a{0}"                 parsed   "a{0}""#,
    r#" 20 "a{0}"                 simple   "(?:)""#,
    r#" 20 "a{0}"                 numcap=2 start=1 ninst=3"#,
    r#" 20 "a{0}"                 prefix="" complete=true startcond=0"#,
    r#" 20 "a{0}"                 prog     "  0\tfail\n  1*\tnop -> 2\n  2\tmatch\n""#,
    r#" 21 "a{1}"                 parsed   "a{1}""#,
    r#" 21 "a{1}"                 simple   "a""#,
    r#" 21 "a{1}"                 numcap=2 start=1 ninst=3"#,
    r#" 21 "a{1}"                 prefix="a" complete=true startcond=0"#,
    r#" 21 "a{1}"                 prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tmatch\n""#,
    r#" 22 "(a){2}"               parsed   "(a){2}""#,
    r#" 22 "(a){2}"               simple   "(a)(a)""#,
    r#" 22 "(a){2}"               numcap=4 start=1 ninst=8"#,
    r#" 22 "(a){2}"               prefix="aa" complete=true startcond=0"#,
    r#" 22 "(a){2}"               prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 4\n  4\tcap 2 -> 5\n  5\trune1 \"a\" -> 6\n  6\tcap 3 -> 7\n  7\tmatch\n""#,
    r#" 23 "(a){1,2}"             parsed   "(a){1,2}""#,
    r#" 23 "(a){1,2}"             simple   "(a)(a)?""#,
    r#" 23 "(a){1,2}"             numcap=4 start=1 ninst=9"#,
    r#" 23 "(a){1,2}"             prefix="a" complete=false startcond=0"#,
    r#" 23 "(a){1,2}"             prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 7\n  4\tcap 2 -> 5\n  5\trune1 \"a\" -> 6\n  6\tcap 3 -> 8\n  7\talt -> 4, 8\n  8\tmatch\n""#,
    r#" 24 "(a|b){2}"             parsed   "([ab]){2}""#,
    r#" 24 "(a|b){2}"             simple   "([ab])([ab])""#,
    r#" 24 "(a|b){2}"             numcap=4 start=1 ninst=8"#,
    r#" 24 "(a|b){2}"             prefix="" complete=false startcond=0"#,
    r#" 24 "(a|b){2}"             prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune \"ab\" -> 3\n  3\tcap 3 -> 4\n  4\tcap 2 -> 5\n  5\trune \"ab\" -> 6\n  6\tcap 3 -> 7\n  7\tmatch\n""#,
    r#" 25 "(?:a+)+"              parsed   "(?:a+)+""#,
    r#" 25 "(?:a+)+"              simple   "a+""#,
    r#" 25 "(?:a+)+"              numcap=2 start=1 ninst=4"#,
    r#" 25 "(?:a+)+"              prefix="a" complete=false startcond=0"#,
    r#" 25 "(?:a+)+"              prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 26 "(?:a*)*"              parsed   "(?:a*)*""#,
    r#" 26 "(?:a*)*"              simple   "a*""#,
    r#" 26 "(?:a*)*"              numcap=2 start=2 ninst=4"#,
    r#" 26 "(?:a*)*"              prefix="" complete=false startcond=0"#,
    r#" 26 "(?:a*)*"              prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 27 "(?:a?)?"              parsed   "(?:a?)?""#,
    r#" 27 "(?:a?)?"              simple   "a?""#,
    r#" 27 "(?:a?)?"              numcap=2 start=2 ninst=4"#,
    r#" 27 "(?:a?)?"              prefix="" complete=false startcond=0"#,
    r#" 27 "(?:a?)?"              prog     "  0\tfail\n  1\trune1 \"a\" -> 3\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#" 28 "(?:a+)*"              parsed   "(?:a+)*""#,
    r#" 28 "(?:a+)*"              simple   "(?:a+)*""#,
    r#" 28 "(?:a+)*"              numcap=2 start=3 ninst=5"#,
    r#" 28 "(?:a+)*"              prefix="" complete=false startcond=0"#,
    r#" 28 "(?:a+)*"              prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2\talt -> 1, 3\n  3*\talt -> 1, 4\n  4\tmatch\n""#,
    r#" 29 "(?:a*)+"              parsed   "(?:a*)+""#,
    r#" 29 "(?:a*)+"              simple   "(?:a*)+""#,
    r#" 29 "(?:a*)+"              numcap=2 start=2 ninst=5"#,
    r#" 29 "(?:a*)+"              prefix="" complete=false startcond=0"#,
    r#" 29 "(?:a*)+"              prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2*\talt -> 1, 3\n  3\talt -> 2, 4\n  4\tmatch\n""#,
    r#" 30 "(a*)*"                parsed   "(a*)*""#,
    r#" 30 "(a*)*"                simple   "(a*)*""#,
    r#" 30 "(a*)*"                numcap=4 start=6 ninst=8"#,
    r#" 30 "(a*)*"                prefix="" complete=false startcond=0"#,
    r#" 30 "(a*)*"                prog     "  0\tfail\n  1\tcap 2 -> 3\n  2\trune1 \"a\" -> 3\n  3\talt -> 2, 4\n  4\tcap 3 -> 5\n  5\talt -> 1, 7\n  6*\talt -> 1, 7\n  7\tmatch\n""#,
    r#" 31 "(a*)+"                parsed   "(a*)+""#,
    r#" 31 "(a*)+"                simple   "(a*)+""#,
    r#" 31 "(a*)+"                numcap=4 start=1 ninst=7"#,
    r#" 31 "(a*)+"                prefix="" complete=false startcond=0"#,
    r#" 31 "(a*)+"                prog     "  0\tfail\n  1*\tcap 2 -> 3\n  2\trune1 \"a\" -> 3\n  3\talt -> 2, 4\n  4\tcap 3 -> 5\n  5\talt -> 1, 6\n  6\tmatch\n""#,
    r#" 32 "(a?)*"                parsed   "(a?)*""#,
    r#" 32 "(a?)*"                simple   "(a?)*""#,
    r#" 32 "(a?)*"                numcap=4 start=6 ninst=8"#,
    r#" 32 "(a?)*"                prefix="" complete=false startcond=0"#,
    r#" 32 "(a?)*"                prog     "  0\tfail\n  1\tcap 2 -> 3\n  2\trune1 \"a\" -> 4\n  3\talt -> 2, 4\n  4\tcap 3 -> 5\n  5\talt -> 1, 7\n  6*\talt -> 1, 7\n  7\tmatch\n""#,
    r#" 33 "."                    parsed   "(?-s:.)""#,
    r#" 33 "."                    simple   "(?-s:.)""#,
    r#" 33 "."                    numcap=2 start=1 ninst=3"#,
    r#" 33 "."                    prefix="" complete=false startcond=0"#,
    r#" 33 "."                    prog     "  0\tfail\n  1*\tanynotnl -> 2\n  2\tmatch\n""#,
    r#" 34 "(?s)."                parsed   "(?s:.)""#,
    r#" 34 "(?s)."                simple   "(?s:.)""#,
    r#" 34 "(?s)."                numcap=2 start=1 ninst=3"#,
    r#" 34 "(?s)."                prefix="" complete=false startcond=0"#,
    r#" 34 "(?s)."                prog     "  0\tfail\n  1*\tany -> 2\n  2\tmatch\n""#,
    r#" 35 "^"                    parsed   "\\A""#,
    r#" 35 "^"                    simple   "\\A""#,
    r#" 35 "^"                    numcap=2 start=1 ninst=3"#,
    r#" 35 "^"                    prefix="" complete=false startcond=4"#,
    r#" 35 "^"                    prog     "  0\tfail\n  1*\tempty 4 -> 2\n  2\tmatch\n""#,
    r#" 36 "$"                    parsed   "(?-m:$)""#,
    r#" 36 "$"                    simple   "(?-m:$)""#,
    r#" 36 "$"                    numcap=2 start=1 ninst=3"#,
    r#" 36 "$"                    prefix="" complete=false startcond=8"#,
    r#" 36 "$"                    prog     "  0\tfail\n  1*\tempty 8 -> 2\n  2\tmatch\n""#,
    r#" 37 "(?m)^"                parsed   "(?m:^)""#,
    r#" 37 "(?m)^"                simple   "(?m:^)""#,
    r#" 37 "(?m)^"                numcap=2 start=1 ninst=3"#,
    r#" 37 "(?m)^"                prefix="" complete=false startcond=1"#,
    r#" 37 "(?m)^"                prog     "  0\tfail\n  1*\tempty 1 -> 2\n  2\tmatch\n""#,
    r#" 38 "(?m)$"                parsed   "(?m:$)""#,
    r#" 38 "(?m)$"                simple   "(?m:$)""#,
    r#" 38 "(?m)$"                numcap=2 start=1 ninst=3"#,
    r#" 38 "(?m)$"                prefix="" complete=false startcond=2"#,
    r#" 38 "(?m)$"                prog     "  0\tfail\n  1*\tempty 2 -> 2\n  2\tmatch\n""#,
    r#" 39 "\\A"                  parsed   "\\A""#,
    r#" 39 "\\A"                  simple   "\\A""#,
    r#" 39 "\\A"                  numcap=2 start=1 ninst=3"#,
    r#" 39 "\\A"                  prefix="" complete=false startcond=4"#,
    r#" 39 "\\A"                  prog     "  0\tfail\n  1*\tempty 4 -> 2\n  2\tmatch\n""#,
    r#" 40 "\\z"                  parsed   "\\z""#,
    r#" 40 "\\z"                  simple   "\\z""#,
    r#" 40 "\\z"                  numcap=2 start=1 ninst=3"#,
    r#" 40 "\\z"                  prefix="" complete=false startcond=8"#,
    r#" 40 "\\z"                  prog     "  0\tfail\n  1*\tempty 8 -> 2\n  2\tmatch\n""#,
    r#" 41 "\\b"                  parsed   "\\b""#,
    r#" 41 "\\b"                  simple   "\\b""#,
    r#" 41 "\\b"                  numcap=2 start=1 ninst=3"#,
    r#" 41 "\\b"                  prefix="" complete=false startcond=16"#,
    r#" 41 "\\b"                  prog     "  0\tfail\n  1*\tempty 16 -> 2\n  2\tmatch\n""#,
    r#" 42 "\\B"                  parsed   "\\B""#,
    r#" 42 "\\B"                  simple   "\\B""#,
    r#" 42 "\\B"                  numcap=2 start=1 ninst=3"#,
    r#" 42 "\\B"                  prefix="" complete=false startcond=32"#,
    r#" 42 "\\B"                  prog     "  0\tfail\n  1*\tempty 32 -> 2\n  2\tmatch\n""#,
    r#" 43 "[a-z]"                parsed   "[a-z]""#,
    r#" 43 "[a-z]"                simple   "[a-z]""#,
    r#" 43 "[a-z]"                numcap=2 start=1 ninst=3"#,
    r#" 43 "[a-z]"                prefix="" complete=false startcond=0"#,
    r#" 43 "[a-z]"                prog     "  0\tfail\n  1*\trune \"az\" -> 2\n  2\tmatch\n""#,
    r#" 44 "[^a-z]"               parsed   "[^a-z]""#,
    r#" 44 "[^a-z]"               simple   "[^a-z]""#,
    r#" 44 "[^a-z]"               numcap=2 start=1 ninst=3"#,
    r#" 44 "[^a-z]"               prefix="" complete=false startcond=0"#,
    r#" 44 "[^a-z]"               prog     "  0\tfail\n  1*\trune \"\\x00`{\\U0010ffff\" -> 2\n  2\tmatch\n""#,
    r#" 45 "[ab]"                 parsed   "[ab]""#,
    r#" 45 "[ab]"                 simple   "[ab]""#,
    r#" 45 "[ab]"                 numcap=2 start=1 ninst=3"#,
    r#" 45 "[ab]"                 prefix="" complete=false startcond=0"#,
    r#" 45 "[ab]"                 prog     "  0\tfail\n  1*\trune \"ab\" -> 2\n  2\tmatch\n""#,
    r#" 46 "[a]"                  parsed   "a""#,
    r#" 46 "[a]"                  simple   "a""#,
    r#" 46 "[a]"                  numcap=2 start=1 ninst=3"#,
    r#" 46 "[a]"                  prefix="a" complete=true startcond=0"#,
    r#" 46 "[a]"                  prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tmatch\n""#,
    r#" 47 "(?i)a"                parsed   "(?i:A)""#,
    r#" 47 "(?i)a"                simple   "(?i:A)""#,
    r#" 47 "(?i)a"                numcap=2 start=1 ninst=3"#,
    r#" 47 "(?i)a"                prefix="" complete=false startcond=0"#,
    r#" 47 "(?i)a"                prog     "  0\tfail\n  1*\trune \"A\"/i -> 2\n  2\tmatch\n""#,
    r#" 48 "(?i)k"                parsed   "(?i:K)""#,
    r#" 48 "(?i)k"                simple   "(?i:K)""#,
    r#" 48 "(?i)k"                numcap=2 start=1 ninst=3"#,
    r#" 48 "(?i)k"                prefix="" complete=false startcond=0"#,
    r#" 48 "(?i)k"                prog     "  0\tfail\n  1*\trune \"K\"/i -> 2\n  2\tmatch\n""#,
    r#" 49 "(?i)[a-z]"            parsed   "[A-Za-zſK]""#,
    r#" 49 "(?i)[a-z]"            simple   "[A-Za-zſK]""#,
    r#" 49 "(?i)[a-z]"            numcap=2 start=1 ninst=3"#,
    r#" 49 "(?i)[a-z]"            prefix="" complete=false startcond=0"#,
    r#" 49 "(?i)[a-z]"            prog     "  0\tfail\n  1*\trune \"AZaz\\u017f\\u017f\\u212a\\u212a\" -> 2\n  2\tmatch\n""#,
    r#" 50 ""                     parsed   "(?:)""#,
    r#" 50 ""                     simple   "(?:)""#,
    r#" 50 ""                     numcap=2 start=1 ninst=3"#,
    r#" 50 ""                     prefix="" complete=true startcond=0"#,
    r#" 50 ""                     prog     "  0\tfail\n  1*\tnop -> 2\n  2\tmatch\n""#,
    r#" 51 "(?:)"                 parsed   "(?:)""#,
    r#" 51 "(?:)"                 simple   "(?:)""#,
    r#" 51 "(?:)"                 numcap=2 start=1 ninst=3"#,
    r#" 51 "(?:)"                 prefix="" complete=true startcond=0"#,
    r#" 51 "(?:)"                 prog     "  0\tfail\n  1*\tnop -> 2\n  2\tmatch\n""#,
    r#" 52 "()"                   parsed   "()""#,
    r#" 52 "()"                   simple   "()""#,
    r#" 52 "()"                   numcap=4 start=1 ninst=5"#,
    r#" 52 "()"                   prefix="" complete=true startcond=0"#,
    r#" 52 "()"                   prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\tnop -> 3\n  3\tcap 3 -> 4\n  4\tmatch\n""#,
    r#" 53 "abc|abd"              parsed   "ab[cd]""#,
    r#" 53 "abc|abd"              simple   "ab[cd]""#,
    r#" 53 "abc|abd"              numcap=2 start=1 ninst=5"#,
    r#" 53 "abc|abd"              prefix="ab" complete=false startcond=0"#,
    r#" 53 "abc|abd"              prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"b\" -> 3\n  3\trune \"cd\" -> 4\n  4\tmatch\n""#,
    r#" 54 "abc|abd|aef|bcx|bcy"  parsed   "a(?:b[cd]|ef)|bc[xy]""#,
    r#" 54 "abc|abd|aef|bcx|bcy"  simple   "a(?:b[cd]|ef)|bc[xy]""#,
    r#" 54 "abc|abd|aef|bcx|bcy"  numcap=2 start=10 ninst=12"#,
    r#" 54 "abc|abd|aef|bcx|bcy"  prefix="" complete=false startcond=0"#,
    r#" 54 "abc|abd|aef|bcx|bcy"  prog     "  0\tfail\n  1\trune1 \"a\" -> 6\n  2\trune1 \"b\" -> 3\n  3\trune \"cd\" -> 11\n  4\trune1 \"e\" -> 5\n  5\trune1 \"f\" -> 11\n  6\talt -> 2, 4\n  7\trune1 \"b\" -> 8\n  8\trune1 \"c\" -> 9\n  9\trune \"xy\" -> 11\n 10*\talt -> 1, 7\n 11\tmatch\n""#,
    r#" 55 "a(b|c)d"              parsed   "a([bc])d""#,
    r#" 55 "a(b|c)d"              simple   "a([bc])d""#,
    r#" 55 "a(b|c)d"              numcap=4 start=1 ninst=7"#,
    r#" 55 "a(b|c)d"              prefix="a" complete=false startcond=0"#,
    r#" 55 "a(b|c)d"              prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tcap 2 -> 3\n  3\trune \"bc\" -> 4\n  4\tcap 3 -> 5\n  5\trune1 \"d\" -> 6\n  6\tmatch\n""#,
    r#" 56 "(a|b)*c"              parsed   "([ab])*c""#,
    r#" 56 "(a|b)*c"              simple   "([ab])*c""#,
    r#" 56 "(a|b)*c"              numcap=4 start=4 ninst=7"#,
    r#" 56 "(a|b)*c"              prefix="" complete=false startcond=0"#,
    r#" 56 "(a|b)*c"              prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune \"ab\" -> 3\n  3\tcap 3 -> 4\n  4*\talt -> 1, 5\n  5\trune1 \"c\" -> 6\n  6\tmatch\n""#,
    r#" 57 "\\d"                  parsed   "[0-9]""#,
    r#" 57 "\\d"                  simple   "[0-9]""#,
    r#" 57 "\\d"                  numcap=2 start=1 ninst=3"#,
    r#" 57 "\\d"                  prefix="" complete=false startcond=0"#,
    r#" 57 "\\d"                  prog     "  0\tfail\n  1*\trune \"09\" -> 2\n  2\tmatch\n""#,
    r#" 58 "\\D"                  parsed   "[^0-9]""#,
    r#" 58 "\\D"                  simple   "[^0-9]""#,
    r#" 58 "\\D"                  numcap=2 start=1 ninst=3"#,
    r#" 58 "\\D"                  prefix="" complete=false startcond=0"#,
    r#" 58 "\\D"                  prog     "  0\tfail\n  1*\trune \"\\x00/:\\U0010ffff\" -> 2\n  2\tmatch\n""#,
    r#" 59 "\\s"                  parsed   "[\\t\\n\\f\\r ]""#,
    r#" 59 "\\s"                  simple   "[\\t\\n\\f\\r ]""#,
    r#" 59 "\\s"                  numcap=2 start=1 ninst=3"#,
    r#" 59 "\\s"                  prefix="" complete=false startcond=0"#,
    r#" 59 "\\s"                  prog     "  0\tfail\n  1*\trune \"\\t\\n\\f\\r  \" -> 2\n  2\tmatch\n""#,
    r#" 60 "\\w"                  parsed   "[0-9A-Z_a-z]""#,
    r#" 60 "\\w"                  simple   "[0-9A-Z_a-z]""#,
    r#" 60 "\\w"                  numcap=2 start=1 ninst=3"#,
    r#" 60 "\\w"                  prefix="" complete=false startcond=0"#,
    r#" 60 "\\w"                  prog     "  0\tfail\n  1*\trune \"09AZ__az\" -> 2\n  2\tmatch\n""#,
    r#" 61 "[[:alpha:]]"          parsed   "[A-Za-z]""#,
    r#" 61 "[[:alpha:]]"          simple   "[A-Za-z]""#,
    r#" 61 "[[:alpha:]]"          numcap=2 start=1 ninst=3"#,
    r#" 61 "[[:alpha:]]"          prefix="" complete=false startcond=0"#,
    r#" 61 "[[:alpha:]]"          prog     "  0\tfail\n  1*\trune \"AZaz\" -> 2\n  2\tmatch\n""#,
    r#" 62 "x{2,5}"               parsed   "x{2,5}""#,
    r#" 62 "x{2,5}"               simple   "xx(?:x(?:xx?)?)?""#,
    r#" 62 "x{2,5}"               numcap=2 start=1 ninst=10"#,
    r#" 62 "x{2,5}"               prefix="xx" complete=false startcond=0"#,
    r#" 62 "x{2,5}"               prog     "  0\tfail\n  1*\trune1 \"x\" -> 2\n  2\trune1 \"x\" -> 8\n  3\trune1 \"x\" -> 7\n  4\trune1 \"x\" -> 6\n  5\trune1 \"x\" -> 9\n  6\talt -> 5, 9\n  7\talt -> 4, 9\n  8\talt -> 3, 9\n  9\tmatch\n""#,
    r#" 63 "x{3,}"                parsed   "x{3,}""#,
    r#" 63 "x{3,}"                simple   "xxx+""#,
    r#" 63 "x{3,}"                numcap=2 start=1 ninst=6"#,
    r#" 63 "x{3,}"                prefix="xxx" complete=false startcond=0"#,
    r#" 63 "x{3,}"                prog     "  0\tfail\n  1*\trune1 \"x\" -> 2\n  2\trune1 \"x\" -> 3\n  3\trune1 \"x\" -> 4\n  4\talt -> 3, 5\n  5\tmatch\n""#,
    r#" 64 "x{10}"                parsed   "x{10}""#,
    r#" 64 "x{10}"                simple   "xxxxxxxxxx""#,
    r#" 64 "x{10}"                numcap=2 start=1 ninst=12"#,
    r#" 64 "x{10}"                prefix="xxxxxxxxxx" complete=true startcond=0"#,
    r#" 64 "x{10}"                prog     "  0\tfail\n  1*\trune1 \"x\" -> 2\n  2\trune1 \"x\" -> 3\n  3\trune1 \"x\" -> 4\n  4\trune1 \"x\" -> 5\n  5\trune1 \"x\" -> 6\n  6\trune1 \"x\" -> 7\n  7\trune1 \"x\" -> 8\n  8\trune1 \"x\" -> 9\n  9\trune1 \"x\" -> 10\n 10\trune1 \"x\" -> 11\n 11\tmatch\n""#,
    r#" 65 "(?i)abc"              parsed   "(?i:ABC)""#,
    r#" 65 "(?i)abc"              simple   "(?i:ABC)""#,
    r#" 65 "(?i)abc"              numcap=2 start=1 ninst=5"#,
    r#" 65 "(?i)abc"              prefix="" complete=false startcond=0"#,
    r#" 65 "(?i)abc"              prog     "  0\tfail\n  1*\trune \"A\"/i -> 2\n  2\trune \"B\"/i -> 3\n  3\trune \"C\"/i -> 4\n  4\tmatch\n""#,
    r#" 66 "(?i)a|b"              parsed   "[ABab]""#,
    r#" 66 "(?i)a|b"              simple   "[ABab]""#,
    r#" 66 "(?i)a|b"              numcap=2 start=1 ninst=3"#,
    r#" 66 "(?i)a|b"              prefix="" complete=false startcond=0"#,
    r#" 66 "(?i)a|b"              prog     "  0\tfail\n  1*\trune \"ABab\" -> 2\n  2\tmatch\n""#,
    r#" 67 "a\nb"                 parsed   "a\\nb""#,
    r#" 67 "a\nb"                 simple   "a\\nb""#,
    r#" 67 "a\nb"                 numcap=2 start=1 ninst=5"#,
    r#" 67 "a\nb"                 prefix="a\nb" complete=true startcond=0"#,
    r#" 67 "a\nb"                 prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"\\n\" -> 3\n  3\trune1 \"b\" -> 4\n  4\tmatch\n""#,
    r#" 68 "\\x{4e00}"            parsed   "一""#,
    r#" 68 "\\x{4e00}"            simple   "一""#,
    r#" 68 "\\x{4e00}"            numcap=2 start=1 ninst=3"#,
    r#" 68 "\\x{4e00}"            prefix="一" complete=true startcond=0"#,
    r#" 68 "\\x{4e00}"            prog     "  0\tfail\n  1*\trune1 \"\\u4e00\" -> 2\n  2\tmatch\n""#,
    r#" 69 "😀"                    parsed   "😀""#,
    r#" 69 "😀"                    simple   "😀""#,
    r#" 69 "😀"                    numcap=2 start=1 ninst=3"#,
    r#" 69 "😀"                    prefix="😀" complete=true startcond=0"#,
    r#" 69 "😀"                    prog     "  0\tfail\n  1*\trune1 \"\\U0001f600\" -> 2\n  2\tmatch\n""#,
    r#" 70 "(a)(b)(c)"            parsed   "(a)(b)(c)""#,
    r#" 70 "(a)(b)(c)"            simple   "(a)(b)(c)""#,
    r#" 70 "(a)(b)(c)"            numcap=8 start=1 ninst=11"#,
    r#" 70 "(a)(b)(c)"            prefix="abc" complete=true startcond=0"#,
    r#" 70 "(a)(b)(c)"            prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 4\n  4\tcap 4 -> 5\n  5\trune1 \"b\" -> 6\n  6\tcap 5 -> 7\n  7\tcap 6 -> 8\n  8\trune1 \"c\" -> 9\n  9\tcap 7 -> 10\n 10\tmatch\n""#,
    r#" 71 "(?P<x>a)(?P<y>b)"     parsed   "(?P<x>a)(?P<y>b)""#,
    r#" 71 "(?P<x>a)(?P<y>b)"     simple   "(?P<x>a)(?P<y>b)""#,
    r#" 71 "(?P<x>a)(?P<y>b)"     numcap=6 start=1 ninst=8"#,
    r#" 71 "(?P<x>a)(?P<y>b)"     prefix="ab" complete=true startcond=0"#,
    r#" 71 "(?P<x>a)(?P<y>b)"     prog     "  0\tfail\n  1*\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 4\n  4\tcap 4 -> 5\n  5\trune1 \"b\" -> 6\n  6\tcap 5 -> 7\n  7\tmatch\n""#,
    r#" 72 "a**b"                 parse-error "error parsing regexp: invalid nested repetition operator: `**`""#,
    r#" 73 "(?i)1"                parsed   "1""#,
    r#" 73 "(?i)1"                simple   "1""#,
    r#" 73 "(?i)1"                numcap=2 start=1 ninst=3"#,
    r#" 73 "(?i)1"                prefix="1" complete=true startcond=0"#,
    r#" 73 "(?i)1"                prog     "  0\tfail\n  1*\trune1 \"1\" -> 2\n  2\tmatch\n""#,
    r#" 74 "(?i)_"                parsed   "_""#,
    r#" 74 "(?i)_"                simple   "_""#,
    r#" 74 "(?i)_"                numcap=2 start=1 ninst=3"#,
    r#" 74 "(?i)_"                prefix="_" complete=true startcond=0"#,
    r#" 74 "(?i)_"                prog     "  0\tfail\n  1*\trune1 \"_\" -> 2\n  2\tmatch\n""#,
    r#" 75 "(?i)-"                parsed   "-""#,
    r#" 75 "(?i)-"                simple   "-""#,
    r#" 75 "(?i)-"                numcap=2 start=1 ninst=3"#,
    r#" 75 "(?i)-"                prefix="-" complete=true startcond=0"#,
    r#" 75 "(?i)-"                prog     "  0\tfail\n  1*\trune1 \"-\" -> 2\n  2\tmatch\n""#,
    r#" 76 "(?i)[0-9]"            parsed   "[0-9]""#,
    r#" 76 "(?i)[0-9]"            simple   "[0-9]""#,
    r#" 76 "(?i)[0-9]"            numcap=2 start=1 ninst=3"#,
    r#" 76 "(?i)[0-9]"            prefix="" complete=false startcond=0"#,
    r#" 76 "(?i)[0-9]"            prog     "  0\tfail\n  1*\trune \"09\" -> 2\n  2\tmatch\n""#,
    r#" 77 "(?i)\\d"              parsed   "[0-9]""#,
    r#" 77 "(?i)\\d"              simple   "[0-9]""#,
    r#" 77 "(?i)\\d"              numcap=2 start=1 ninst=3"#,
    r#" 77 "(?i)\\d"              prefix="" complete=false startcond=0"#,
    r#" 77 "(?i)\\d"              prog     "  0\tfail\n  1*\trune \"09\" -> 2\n  2\tmatch\n""#,
    r#" 78 "(?i)aa"               parsed   "(?i:AA)""#,
    r#" 78 "(?i)aa"               simple   "(?i:AA)""#,
    r#" 78 "(?i)aa"               numcap=2 start=1 ninst=4"#,
    r#" 78 "(?i)aa"               prefix="" complete=false startcond=0"#,
    r#" 78 "(?i)aa"               prog     "  0\tfail\n  1*\trune \"A\"/i -> 2\n  2\trune \"A\"/i -> 3\n  3\tmatch\n""#,
    r#" 79 "(?i)ab"               parsed   "(?i:AB)""#,
    r#" 79 "(?i)ab"               simple   "(?i:AB)""#,
    r#" 79 "(?i)ab"               numcap=2 start=1 ninst=4"#,
    r#" 79 "(?i)ab"               prefix="" complete=false startcond=0"#,
    r#" 79 "(?i)ab"               prog     "  0\tfail\n  1*\trune \"A\"/i -> 2\n  2\trune \"B\"/i -> 3\n  3\tmatch\n""#,
    r#" 80 "(?i)."                parsed   "(?-s:.)""#,
    r#" 80 "(?i)."                simple   "(?-s:.)""#,
    r#" 80 "(?i)."                numcap=2 start=1 ninst=3"#,
    r#" 80 "(?i)."                prefix="" complete=false startcond=0"#,
    r#" 80 "(?i)."                prog     "  0\tfail\n  1*\tanynotnl -> 2\n  2\tmatch\n""#,
    r#" 81 "(?i)[a]"              parsed   "(?i:A)""#,
    r#" 81 "(?i)[a]"              simple   "(?i:A)""#,
    r#" 81 "(?i)[a]"              numcap=2 start=1 ninst=3"#,
    r#" 81 "(?i)[a]"              prefix="" complete=false startcond=0"#,
    r#" 81 "(?i)[a]"              prog     "  0\tfail\n  1*\trune \"A\"/i -> 2\n  2\tmatch\n""#,
    r#" 82 "(?i)[k]"              parsed   "[KkK]""#,
    r#" 82 "(?i)[k]"              simple   "[KkK]""#,
    r#" 82 "(?i)[k]"              numcap=2 start=1 ninst=3"#,
    r#" 82 "(?i)[k]"              prefix="" complete=false startcond=0"#,
    r#" 82 "(?i)[k]"              prog     "  0\tfail\n  1*\trune \"KKkk\\u212a\\u212a\" -> 2\n  2\tmatch\n""#,
    r#" 83 "(?i)ſ"                parsed   "(?i:S)""#,
    r#" 83 "(?i)ſ"                simple   "(?i:S)""#,
    r#" 83 "(?i)ſ"                numcap=2 start=1 ninst=3"#,
    r#" 83 "(?i)ſ"                prefix="" complete=false startcond=0"#,
    r#" 83 "(?i)ſ"                prog     "  0\tfail\n  1*\trune \"S\"/i -> 2\n  2\tmatch\n""#,
    r#" 84 "(?i)K"                parsed   "(?i:K)""#,
    r#" 84 "(?i)K"                simple   "(?i:K)""#,
    r#" 84 "(?i)K"                numcap=2 start=1 ninst=3"#,
    r#" 84 "(?i)K"                prefix="" complete=false startcond=0"#,
    r#" 84 "(?i)K"                prog     "  0\tfail\n  1*\trune \"K\"/i -> 2\n  2\tmatch\n""#,
    r#" 85 "(?i)é"                parsed   "(?i:É)""#,
    r#" 85 "(?i)é"                simple   "(?i:É)""#,
    r#" 85 "(?i)é"                numcap=2 start=1 ninst=3"#,
    r#" 85 "(?i)é"                prefix="" complete=false startcond=0"#,
    r#" 85 "(?i)é"                prog     "  0\tfail\n  1*\trune \"\\u00c9\"/i -> 2\n  2\tmatch\n""#,
    r#" 86 "1"                    parsed   "1""#,
    r#" 86 "1"                    simple   "1""#,
    r#" 86 "1"                    numcap=2 start=1 ninst=3"#,
    r#" 86 "1"                    prefix="1" complete=true startcond=0"#,
    r#" 86 "1"                    prog     "  0\tfail\n  1*\trune1 \"1\" -> 2\n  2\tmatch\n""#,
    r#" 87 "[0-9]"                parsed   "[0-9]""#,
    r#" 87 "[0-9]"                simple   "[0-9]""#,
    r#" 87 "[0-9]"                numcap=2 start=1 ninst=3"#,
    r#" 87 "[0-9]"                prefix="" complete=false startcond=0"#,
    r#" 87 "[0-9]"                prog     "  0\tfail\n  1*\trune \"09\" -> 2\n  2\tmatch\n""#,
    r#" 88 "[a]"                  parsed   "a""#,
    r#" 88 "[a]"                  simple   "a""#,
    r#" 88 "[a]"                  numcap=2 start=1 ninst=3"#,
    r#" 88 "[a]"                  prefix="a" complete=true startcond=0"#,
    r#" 88 "[a]"                  prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tmatch\n""#,
    r#" 89 "[aa]"                 parsed   "a""#,
    r#" 89 "[aa]"                 simple   "a""#,
    r#" 89 "[aa]"                 numcap=2 start=1 ninst=3"#,
    r#" 89 "[aa]"                 prefix="a" complete=true startcond=0"#,
    r#" 89 "[aa]"                 prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\tmatch\n""#,
    r#" 90 "(a|)*"                parsed   "(a|(?:))*""#,
    r#" 90 "(a|)*"                simple   "(a|(?:))*""#,
    r#" 90 "(a|)*"                numcap=4 start=7 ninst=9"#,
    r#" 90 "(a|)*"                prefix="" complete=false startcond=0"#,
    r#" 90 "(a|)*"                prog     "  0\tfail\n  1\tcap 2 -> 4\n  2\trune1 \"a\" -> 5\n  3\tnop -> 5\n  4\talt -> 2, 3\n  5\tcap 3 -> 6\n  6\talt -> 1, 8\n  7*\talt -> 1, 8\n  8\tmatch\n""#,
    r#" 91 "(|a)*"                parsed   "((?:)|a)*""#,
    r#" 91 "(|a)*"                simple   "((?:)|a)*""#,
    r#" 91 "(|a)*"                numcap=4 start=7 ninst=9"#,
    r#" 91 "(|a)*"                prefix="" complete=false startcond=0"#,
    r#" 91 "(|a)*"                prog     "  0\tfail\n  1\tcap 2 -> 4\n  2\tnop -> 5\n  3\trune1 \"a\" -> 5\n  4\talt -> 2, 3\n  5\tcap 3 -> 6\n  6\talt -> 1, 8\n  7*\talt -> 1, 8\n  8\tmatch\n""#,
    r#" 92 "((a)?)*"              parsed   "((a)?)*""#,
    r#" 92 "((a)?)*"              simple   "((a)?)*""#,
    r#" 92 "((a)?)*"              numcap=6 start=8 ninst=10"#,
    r#" 92 "((a)?)*"              prefix="" complete=false startcond=0"#,
    r#" 92 "((a)?)*"              prog     "  0\tfail\n  1\tcap 2 -> 5\n  2\tcap 4 -> 3\n  3\trune1 \"a\" -> 4\n  4\tcap 5 -> 6\n  5\talt -> 2, 6\n  6\tcap 3 -> 7\n  7\talt -> 1, 9\n  8*\talt -> 1, 9\n  9\tmatch\n""#,
    r#" 93 "(a{0,1})*"            parsed   "(a{0,1})*""#,
    r#" 93 "(a{0,1})*"            simple   "(a?)*""#,
    r#" 93 "(a{0,1})*"            numcap=4 start=6 ninst=8"#,
    r#" 93 "(a{0,1})*"            prefix="" complete=false startcond=0"#,
    r#" 93 "(a{0,1})*"            prog     "  0\tfail\n  1\tcap 2 -> 3\n  2\trune1 \"a\" -> 4\n  3\talt -> 2, 4\n  4\tcap 3 -> 5\n  5\talt -> 1, 7\n  6*\talt -> 1, 7\n  7\tmatch\n""#,
    r#" 94 "(?:){0,}"             parsed   "(?:){0,}""#,
    r#" 94 "(?:){0,}"             simple   "(?:)""#,
    r#" 94 "(?:){0,}"             numcap=2 start=1 ninst=3"#,
    r#" 94 "(?:){0,}"             prefix="" complete=true startcond=0"#,
    r#" 94 "(?:){0,}"             prog     "  0\tfail\n  1*\tnop -> 2\n  2\tmatch\n""#,
    r#" 95 "(a*b*)*"              parsed   "(a*b*)*""#,
    r#" 95 "(a*b*)*"              simple   "(a*b*)*""#,
    r#" 95 "(a*b*)*"              numcap=4 start=8 ninst=10"#,
    r#" 95 "(a*b*)*"              prefix="" complete=false startcond=0"#,
    r#" 95 "(a*b*)*"              prog     "  0\tfail\n  1\tcap 2 -> 3\n  2\trune1 \"a\" -> 3\n  3\talt -> 2, 5\n  4\trune1 \"b\" -> 5\n  5\talt -> 4, 6\n  6\tcap 3 -> 7\n  7\talt -> 1, 9\n  8*\talt -> 1, 9\n  9\tmatch\n""#,
    r#" 96 "(abc)*"               parsed   "(abc)*""#,
    r#" 96 "(abc)*"               simple   "(abc)*""#,
    r#" 96 "(abc)*"               numcap=4 start=6 ninst=8"#,
    r#" 96 "(abc)*"               prefix="" complete=false startcond=0"#,
    r#" 96 "(abc)*"               prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\trune1 \"b\" -> 4\n  4\trune1 \"c\" -> 5\n  5\tcap 3 -> 6\n  6*\talt -> 1, 7\n  7\tmatch\n""#,
    r#" 97 "([a-z])*"             parsed   "([a-z])*""#,
    r#" 97 "([a-z])*"             simple   "([a-z])*""#,
    r#" 97 "([a-z])*"             numcap=4 start=4 ninst=6"#,
    r#" 97 "([a-z])*"             prefix="" complete=false startcond=0"#,
    r#" 97 "([a-z])*"             prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune \"az\" -> 3\n  3\tcap 3 -> 4\n  4*\talt -> 1, 5\n  5\tmatch\n""#,
    r#" 98 "(\\b)*"               parsed   "(\\b)*""#,
    r#" 98 "(\\b)*"               simple   "(\\b)*""#,
    r#" 98 "(\\b)*"               numcap=4 start=5 ninst=7"#,
    r#" 98 "(\\b)*"               prefix="" complete=false startcond=0"#,
    r#" 98 "(\\b)*"               prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\tempty 16 -> 3\n  3\tcap 3 -> 4\n  4\talt -> 1, 6\n  5*\talt -> 1, 6\n  6\tmatch\n""#,
    r#" 99 "(^)*"                 parsed   "(\\A)*""#,
    r#" 99 "(^)*"                 simple   "(\\A)*""#,
    r#" 99 "(^)*"                 numcap=4 start=5 ninst=7"#,
    r#" 99 "(^)*"                 prefix="" complete=false startcond=0"#,
    r#" 99 "(^)*"                 prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\tempty 4 -> 3\n  3\tcap 3 -> 4\n  4\talt -> 1, 6\n  5*\talt -> 1, 6\n  6\tmatch\n""#,
    r#"100 "(?:a|b)*"             parsed   "[ab]*""#,
    r#"100 "(?:a|b)*"             simple   "[ab]*""#,
    r#"100 "(?:a|b)*"             numcap=2 start=2 ninst=4"#,
    r#"100 "(?:a|b)*"             prefix="" complete=false startcond=0"#,
    r#"100 "(?:a|b)*"             prog     "  0\tfail\n  1\trune \"ab\" -> 2\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#"101 "(a|b)??"              parsed   "([ab])??""#,
    r#"101 "(a|b)??"              simple   "([ab])??""#,
    r#"101 "(a|b)??"              numcap=4 start=4 ninst=6"#,
    r#"101 "(a|b)??"              prefix="" complete=false startcond=0"#,
    r#"101 "(a|b)??"              prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune \"ab\" -> 3\n  3\tcap 3 -> 5\n  4*\talt -> 5, 1\n  5\tmatch\n""#,
    r#"102 "[a-z]??"              parsed   "[a-z]??""#,
    r#"102 "[a-z]??"              simple   "[a-z]??""#,
    r#"102 "[a-z]??"              numcap=2 start=2 ninst=4"#,
    r#"102 "[a-z]??"              prefix="" complete=false startcond=0"#,
    r#"102 "[a-z]??"              prog     "  0\tfail\n  1\trune \"az\" -> 3\n  2*\talt -> 3, 1\n  3\tmatch\n""#,
    r#"103 "(?:ab)??"             parsed   "(?:ab)??""#,
    r#"103 "(?:ab)??"             simple   "(?:ab)??""#,
    r#"103 "(?:ab)??"             numcap=2 start=3 ninst=5"#,
    r#"103 "(?:ab)??"             prefix="" complete=false startcond=0"#,
    r#"103 "(?:ab)??"             prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2\trune1 \"b\" -> 4\n  3*\talt -> 4, 1\n  4\tmatch\n""#,
    r#"104 "(a)??"                parsed   "(a)??""#,
    r#"104 "(a)??"                simple   "(a)??""#,
    r#"104 "(a)??"                numcap=4 start=4 ninst=6"#,
    r#"104 "(a)??"                prefix="" complete=false startcond=0"#,
    r#"104 "(a)??"                prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 5\n  4*\talt -> 5, 1\n  5\tmatch\n""#,
    r#"105 "a{0,1}?"              parsed   "a{0,1}?""#,
    r#"105 "a{0,1}?"              simple   "a??""#,
    r#"105 "a{0,1}?"              numcap=2 start=2 ninst=4"#,
    r#"105 "a{0,1}?"              prefix="" complete=false startcond=0"#,
    r#"105 "a{0,1}?"              prog     "  0\tfail\n  1\trune1 \"a\" -> 3\n  2*\talt -> 3, 1\n  3\tmatch\n""#,
    r#"106 "a{2,3}?"              parsed   "a{2,3}?""#,
    r#"106 "a{2,3}?"              simple   "aaa??""#,
    r#"106 "a{2,3}?"              numcap=2 start=1 ninst=6"#,
    r#"106 "a{2,3}?"              prefix="aa" complete=false startcond=0"#,
    r#"106 "a{2,3}?"              prog     "  0\tfail\n  1*\trune1 \"a\" -> 2\n  2\trune1 \"a\" -> 4\n  3\trune1 \"a\" -> 5\n  4\talt -> 5, 3\n  5\tmatch\n""#,
    r#"107 "a{0,3}?"              parsed   "a{0,3}?""#,
    r#"107 "a{0,3}?"              simple   "(?:a(?:aa??)??)??""#,
    r#"107 "a{0,3}?"              numcap=2 start=6 ninst=8"#,
    r#"107 "a{0,3}?"              prefix="" complete=false startcond=0"#,
    r#"107 "a{0,3}?"              prog     "  0\tfail\n  1\trune1 \"a\" -> 5\n  2\trune1 \"a\" -> 4\n  3\trune1 \"a\" -> 7\n  4\talt -> 7, 3\n  5\talt -> 7, 2\n  6*\talt -> 7, 1\n  7\tmatch\n""#,
    r#"108 "(a|b)?"               parsed   "([ab])?""#,
    r#"108 "(a|b)?"               simple   "([ab])?""#,
    r#"108 "(a|b)?"               numcap=4 start=4 ninst=6"#,
    r#"108 "(a|b)?"               prefix="" complete=false startcond=0"#,
    r#"108 "(a|b)?"               prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune \"ab\" -> 3\n  3\tcap 3 -> 5\n  4*\talt -> 1, 5\n  5\tmatch\n""#,
    r#"109 "[a-z]?"               parsed   "[a-z]?""#,
    r#"109 "[a-z]?"               simple   "[a-z]?""#,
    r#"109 "[a-z]?"               numcap=2 start=2 ninst=4"#,
    r#"109 "[a-z]?"               prefix="" complete=false startcond=0"#,
    r#"109 "[a-z]?"               prog     "  0\tfail\n  1\trune \"az\" -> 3\n  2*\talt -> 1, 3\n  3\tmatch\n""#,
    r#"110 "(?:ab)?"              parsed   "(?:ab)?""#,
    r#"110 "(?:ab)?"              simple   "(?:ab)?""#,
    r#"110 "(?:ab)?"              numcap=2 start=3 ninst=5"#,
    r#"110 "(?:ab)?"              prefix="" complete=false startcond=0"#,
    r#"110 "(?:ab)?"              prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2\trune1 \"b\" -> 4\n  3*\talt -> 1, 4\n  4\tmatch\n""#,
    r#"111 "(a)?"                 parsed   "(a)?""#,
    r#"111 "(a)?"                 simple   "(a)?""#,
    r#"111 "(a)?"                 numcap=4 start=4 ninst=6"#,
    r#"111 "(a)?"                 prefix="" complete=false startcond=0"#,
    r#"111 "(a)?"                 prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\tcap 3 -> 5\n  4*\talt -> 1, 5\n  5\tmatch\n""#,
    r#"112 "(a*)??"               parsed   "(a*)??""#,
    r#"112 "(a*)??"               simple   "(a*)??""#,
    r#"112 "(a*)??"               numcap=4 start=5 ninst=7"#,
    r#"112 "(a*)??"               prefix="" complete=false startcond=0"#,
    r#"112 "(a*)??"               prog     "  0\tfail\n  1\tcap 2 -> 3\n  2\trune1 \"a\" -> 3\n  3\talt -> 2, 4\n  4\tcap 3 -> 6\n  5*\talt -> 6, 1\n  6\tmatch\n""#,
    r#"113 "(a+)??"               parsed   "(a+)??""#,
    r#"113 "(a+)??"               simple   "(a+)??""#,
    r#"113 "(a+)??"               numcap=4 start=5 ninst=7"#,
    r#"113 "(a+)??"               prefix="" complete=false startcond=0"#,
    r#"113 "(a+)??"               prog     "  0\tfail\n  1\tcap 2 -> 2\n  2\trune1 \"a\" -> 3\n  3\talt -> 2, 4\n  4\tcap 3 -> 6\n  5*\talt -> 6, 1\n  6\tmatch\n""#,
    r#"114 "a*?b"                 parsed   "a*?b""#,
    r#"114 "a*?b"                 simple   "a*?b""#,
    r#"114 "a*?b"                 numcap=2 start=2 ninst=5"#,
    r#"114 "a*?b"                 prefix="" complete=false startcond=0"#,
    r#"114 "a*?b"                 prog     "  0\tfail\n  1\trune1 \"a\" -> 2\n  2*\talt -> 3, 1\n  3\trune1 \"b\" -> 4\n  4\tmatch\n""#,
    r#"115 "(?:a|b)*?"            parsed   "[ab]*?""#,
    r#"115 "(?:a|b)*?"            simple   "[ab]*?""#,
    r#"115 "(?:a|b)*?"            numcap=2 start=2 ninst=4"#,
    r#"115 "(?:a|b)*?"            prefix="" complete=false startcond=0"#,
    r#"115 "(?:a|b)*?"            prog     "  0\tfail\n  1\trune \"ab\" -> 2\n  2*\talt -> 3, 1\n  3\tmatch\n""#,
    r#"116 "(?:a|b)+?"            parsed   "[ab]+?""#,
    r#"116 "(?:a|b)+?"            simple   "[ab]+?""#,
    r#"116 "(?:a|b)+?"            numcap=2 start=1 ninst=4"#,
    r#"116 "(?:a|b)+?"            prefix="" complete=false startcond=0"#,
    r#"116 "(?:a|b)+?"            prog     "  0\tfail\n  1*\trune \"ab\" -> 2\n  2\talt -> 3, 1\n  3\tmatch\n""#,
    r#"117 "x{2,5}?"              parsed   "x{2,5}?""#,
    r#"117 "x{2,5}?"              simple   "xx(?:x(?:xx??)??)??""#,
    r#"117 "x{2,5}?"              numcap=2 start=1 ninst=10"#,
    r#"117 "x{2,5}?"              prefix="xx" complete=false startcond=0"#,
    r#"117 "x{2,5}?"              prog     "  0\tfail\n  1*\trune1 \"x\" -> 2\n  2\trune1 \"x\" -> 8\n  3\trune1 \"x\" -> 7\n  4\trune1 \"x\" -> 6\n  5\trune1 \"x\" -> 9\n  6\talt -> 9, 5\n  7\talt -> 9, 4\n  8\talt -> 9, 3\n  9\tmatch\n""#,
    r#"118 "x{3,}?"               parsed   "x{3,}?""#,
    r#"118 "x{3,}?"               simple   "xxx+?""#,
    r#"118 "x{3,}?"               numcap=2 start=1 ninst=6"#,
    r#"118 "x{3,}?"               prefix="xxx" complete=false startcond=0"#,
    r#"118 "x{3,}?"               prog     "  0\tfail\n  1*\trune1 \"x\" -> 2\n  2\trune1 \"x\" -> 3\n  3\trune1 \"x\" -> 4\n  4\talt -> 5, 3\n  5\tmatch\n""#,
];

/// The corpus, decoded from the reference's own source.
const PATS: [&str; 119] = [
    "a",
    "ab",
    "abc",
    "a|b",
    "a|b|c",
    "(a)",
    "(a)(b)",
    "(?:a)",
    "a*",
    "a+",
    "a?",
    "a*?",
    "a+?",
    "a??",
    "a{2}",
    "a{2,3}",
    "a{2,}",
    "a{0,3}",
    "a{0,}",
    "a{1,}",
    "a{0}",
    "a{1}",
    "(a){2}",
    "(a){1,2}",
    "(a|b){2}",
    "(?:a+)+",
    "(?:a*)*",
    "(?:a?)?",
    "(?:a+)*",
    "(?:a*)+",
    "(a*)*",
    "(a*)+",
    "(a?)*",
    ".",
    "(?s).",
    "^",
    "$",
    "(?m)^",
    "(?m)$",
    "\\A",
    "\\z",
    "\\b",
    "\\B",
    "[a-z]",
    "[^a-z]",
    "[ab]",
    "[a]",
    "(?i)a",
    "(?i)k",
    "(?i)[a-z]",
    "",
    "(?:)",
    "()",
    "abc|abd",
    "abc|abd|aef|bcx|bcy",
    "a(b|c)d",
    "(a|b)*c",
    "\\d",
    "\\D",
    "\\s",
    "\\w",
    "[[:alpha:]]",
    "x{2,5}",
    "x{3,}",
    "x{10}",
    "(?i)abc",
    "(?i)a|b",
    "a\nb",
    "\\x{4e00}",
    "\u{1f600}",
    "(a)(b)(c)",
    "(?P<x>a)(?P<y>b)",
    "a**b",
    "(?i)1",
    "(?i)_",
    "(?i)-",
    "(?i)[0-9]",
    "(?i)\\d",
    "(?i)aa",
    "(?i)ab",
    "(?i).",
    "(?i)[a]",
    "(?i)[k]",
    "(?i)\u{17f}",
    "(?i)\u{212a}",
    "(?i)\u{e9}",
    "1",
    "[0-9]",
    "[a]",
    "[aa]",
    "(a|)*",
    "(|a)*",
    "((a)?)*",
    "(a{0,1})*",
    "(?:){0,}",
    "(a*b*)*",
    "(abc)*",
    "([a-z])*",
    "(\\b)*",
    "(^)*",
    "(?:a|b)*",
    "(a|b)??",
    "[a-z]??",
    "(?:ab)??",
    "(a)??",
    "a{0,1}?",
    "a{2,3}?",
    "a{0,3}?",
    "(a|b)?",
    "[a-z]?",
    "(?:ab)?",
    "(a)?",
    "(a*)??",
    "(a+)??",
    "a*?b",
    "(?:a|b)*?",
    "(?:a|b)+?",
    "x{2,5}?",
    "x{3,}?",
];

fn line(ln: &mut usize, got: string) {
    unsafe { RUN += 1 };
    if *ln >= GO.len() {
        fmt::Printf!("[!!] extra line %d: %q\n", *ln as int + 1, got);
        unsafe { FAILED += 1 };
        *ln += 1;
        return;
    }
    if got == GO[*ln] {
        fmt::Printf!("[ok] %s\n", got);
    } else {
        fmt::Printf!(
            "[!!] line %d\n  got  %q\n  want %q\n",
            *ln as int + 1,
            got,
            GO[*ln]
        );
        unsafe { FAILED += 1 };
    }
    *ln += 1;
}

/// `%-Ns`, padded by RUNE count as Go's fmt measures it.
fn l(s: string, w: int) -> string {
    let mut o = s;
    while goish::len(&goish::runes(o.clone())) < w {
        o = o + string::from_static(" ");
    }
    return o;
}

/// `%Nd`
fn d(v: i64, w: int) -> string {
    let mut o = strconv::Itoa(int::from(v));
    while o.Len() < w {
        o = string::from_static(" ") + o;
    }
    return o;
}

#[goish::main]
fn main() {
    let mut ln: usize = 0;

    for (i, pat) in PATS.iter().enumerate() {
        let src = string::from_static(pat);
        let head = d(i as i64, int::from(3))
            + string::from_static(" ")
            + l(strconv::Quote(src.clone()), int::from(22))
            + string::from_static(" ");

        let (re, err) = syntax::Parse(src.clone(), syntax::Perl);
        if !err.IsNil() {
            line(
                &mut ln,
                head + string::from_static("parse-error ") + strconv::Quote(err.Error()),
            );
            continue;
        }
        let re = re.MustTake();
        line(
            &mut ln,
            head.clone() + string::from_static("parsed   ") + strconv::Quote(re.String()),
        );

        let sre = re.Simplify();
        line(
            &mut ln,
            head.clone() + string::from_static("simple   ") + strconv::Quote(sre.String()),
        );

        let (prog, cerr) = syntax::Compile(&sre);
        if !cerr.IsNil() {
            line(
                &mut ln,
                head + string::from_static("compile-error ") + strconv::Quote(cerr.Error()),
            );
            continue;
        }
        line(
            &mut ln,
            head.clone()
                + string::from_static("numcap=")
                + strconv::Itoa(prog.NumCap)
                + string::from_static(" start=")
                + strconv::Itoa(prog.Start)
                + string::from_static(" ninst=")
                + strconv::Itoa(int::from(prog.Inst.len() as i64)),
        );
        let (pre, complete) = prog.Prefix();
        line(
            &mut ln,
            head.clone()
                + string::from_static("prefix=")
                + strconv::Quote(pre)
                + string::from_static(" complete=")
                + fmt::Sprintf!("%v", complete)
                + string::from_static(" startcond=")
                + strconv::Itoa(int::from(goish::int64(prog.StartCond().0))),
        );
        line(
            &mut ln,
            head + string::from_static("prog     ") + strconv::Quote(prog.String()),
        );
    }

    let run = unsafe { RUN };
    let f = unsafe { FAILED };
    if run != GO.len() as int {
        fmt::Printf!("\nFAIL ran %d of %d rows\n", run, GO.len() as int);
        goish::os::Exit(1);
    }
    if f == 0 {
        fmt::Printf!("\nok %d/%d\n", run, run);
        goish::os::Exit(0);
    }
    fmt::Printf!("\nFAIL %d\n", f);
    goish::os::Exit(1);
}
