// crypto/tls had TWO TLS 1.2 PRFs, and Go has one.
//
// Go declares `prf12` once (crypto/tls/prf.go), delegating to
// `crypto/internal/fips140/tls12.PRF`. goish declared it twice:
//
//   prf.rs::prf12      -> tls12::PRF, the ported FIPS path (hash-generic)
//   record.rs::prf12   -> a hand-rolled SHA-256-only P_hash
//
// Found by asking mechanically which free functions goish defines more
// often than Go does — the same question that turned up a fourth
// `hasPort` and a third SubjectPublicKeyInfo walk. This one derives the
// master secret and the key block, so a disagreement between the two is
// a handshake that negotiates different keys depending on which half of
// the library got there first.
//
// This table is what says they agree, and it does NOT let them agree
// with each other: every expected value came from Go 1.25.5's own
// tls12.PRF, generated by `scripts/goref.sh
// crypto/internal/fips140/tls12` and committed verbatim as
// examples/testdata/tls12_prf_ref.txt. Both goish implementations are
// checked against Go, not against one another — two copies wrong the
// same way would otherwise pass.
//
// The grid is chosen for P_hash's boundaries: keyLen below, at and
// above one HMAC-SHA256 block (32), secrets and seeds shorter and
// longer than the hash block size (64), and the empty cases for each.
#![no_std]
#![no_main]
#![allow(non_snake_case)]
extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use goish::crypto::tls;
use goish::fmt;
use goish::goslice::slice;
use goish::gostring::string;
use goish::types::{byte, int};

const REF: &str = include_str!("testdata/tls12_prf_ref.txt");

// Mirrors the reference generator's `mk`: deterministic bytes, so the
// inputs are reproducible from the row's own four numbers.
fn mk(n: int, off: int) -> Vec<byte> {
    let mut b: Vec<byte> = Vec::new();
    let mut i: int = 0;
    while i < n {
        b.push(((i * 7 + off * 31) & 0xff) as byte);
        i += 1;
    }
    return b;
}

fn label_of(li: int) -> &'static str {
    if li == 0 {
        return "master secret";
    }
    if li == 1 {
        return "key expansion";
    }
    return "";
}

fn hex_of(b: &[byte]) -> string {
    let mut s = string::from_static("");
    for &x in b.iter() {
        s = s + fmt::Sprintf!("%02x", goish::int(x));
    }
    return s;
}

static mut PASS: int = 0;
static mut FAIL: int = 0;
static mut ROWS: int = 0;

fn check(what: string, got: string, want: &str) {
    unsafe {
        if got == string::from_bytes(want.as_bytes()) {
            PASS += 1;
        } else {
            FAIL += 1;
            fmt::Printf!("FAIL %s: got %s want %s\n", what, got.clone(), want);
        }
    }
}

#[goish::main]
fn main() {
    for line in REF.split('\n') {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let mut it = line.split(' ');
        let li: int = it.next().unwrap_or("").parse::<i64>().unwrap_or(-1);
        let sl: int = it.next().unwrap_or("").parse::<i64>().unwrap_or(-1);
        let sd: int = it.next().unwrap_or("").parse::<i64>().unwrap_or(-1);
        let kl: int = it.next().unwrap_or("").parse::<i64>().unwrap_or(-1);
        let want: &str = it.next().unwrap_or("");
        if li < 0 || sl < 0 || sd < 0 || kl < 0 {
            fmt::Printf!("FAIL unparsable reference row\n");
            unsafe {
                FAIL += 1;
            }
            continue;
        }
        unsafe {
            ROWS += 1;
        }

        let secret = mk(sl, li);
        let seed = mk(sd, li + 1);
        let label = label_of(li);
        let tag = fmt::Sprintf!("li=%v sl=%v sd=%v kl=%v", li, sl, sd, kl);

        // The ported path: prf.rs -> tls12::PRF.
        let ported = tls::prf_prf12_sha256(
            slice::<byte>::__from_vec(secret.clone()),
            string::from_bytes(label.as_bytes()),
            slice::<byte>::__from_vec(seed.clone()),
            kl,
        );
        let pb: &[byte] = &ported;
        check(tag.clone() + string::from_static(" ported"), hex_of(pb), want);

        // The hand-rolled one in record.rs.
        let mut out: Vec<byte> = alloc::vec![0u8; kl as usize];
        tls::prf12(&mut out, &secret, label.as_bytes(), &seed);
        check(tag + string::from_static(" record"), hex_of(&out), want);
    }

    unsafe {
        // Rows-run gate: a reference file that failed to load, or a
        // parser that matched nothing, would otherwise print 0/0 and
        // read as a pass. See the ROADMAP note on vacuous smokes.
        let rows = ROWS;
        if rows < 300 {
            fmt::Printf!("FAIL only %v reference rows ran; expected >= 300\n", rows);
            FAIL += 1;
        }
        let (pass, fail) = (PASS, FAIL);
        fmt::Printf!(
            "tls_prf_dup_smoke: %v rows, %v checks, %v failed\n",
            rows,
            pass + fail,
            fail
        );
        if fail > 0 {
            goish::syscall::Exit(1);
        }
    }
}
