// crypto/tls — the common.go enumerations and their String() forms.
//
// Every expected string was generated by
// `scripts/goref.sh crypto/tls`, not transcribed. That matters
// especially here: `common_string.go` is `stringer`-generated and packs
// its names into concatenated constants sliced by an index table, which
// goish spells as a plain match. The encoding is deliberately not
// reproduced, so the *outputs* are what has to be identical — including
// the `Type(N)` fallbacks and the `0x%04X` version fallback, each of
// which has a case below.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use goish::crypto::tls;
use goish::fmt;
use goish::gostring::string;
use goish::types::int;

static mut PASS: int = 0;
static mut FAIL: int = 0;

fn check(what: &'static str, ok: bool) {
    unsafe {
        if ok {
            PASS += 1;
        } else {
            FAIL += 1;
            fmt::Printf!("FAIL %s\n", what);
        }
    }
}

fn check_n(what: &'static str, got: int, want: int) {
    let ok = got == want;
    if !ok {
        fmt::Printf!("FAIL %s: got %v want %v\n", what, got, want);
    }
    check(what, ok);
}

fn eq(what: &'static str, got: string, want: &'static str) {
    let ok = got == string::from_static(want);
    unsafe {
        if ok {
            PASS += 1;
        } else {
            FAIL += 1;
            fmt::Printf!("FAIL %s: got %s want %s\n", what, got.clone(), want);
        }
    }
}

#[goish::main]
fn main() {
    // ─── SignatureScheme.String ───────────────────────────────────────
    eq("PKCS1WithSHA256", tls::PKCS1WithSHA256.String(), "PKCS1WithSHA256");
    eq("PKCS1WithSHA384", tls::PKCS1WithSHA384.String(), "PKCS1WithSHA384");
    eq("PKCS1WithSHA512", tls::PKCS1WithSHA512.String(), "PKCS1WithSHA512");
    eq("PSSWithSHA256", tls::PSSWithSHA256.String(), "PSSWithSHA256");
    eq("PSSWithSHA384", tls::PSSWithSHA384.String(), "PSSWithSHA384");
    eq("PSSWithSHA512", tls::PSSWithSHA512.String(), "PSSWithSHA512");
    eq(
        "ECDSAWithP256AndSHA256",
        tls::ECDSAWithP256AndSHA256.String(),
        "ECDSAWithP256AndSHA256",
    );
    eq(
        "ECDSAWithP384AndSHA384",
        tls::ECDSAWithP384AndSHA384.String(),
        "ECDSAWithP384AndSHA384",
    );
    eq(
        "ECDSAWithP521AndSHA512",
        tls::ECDSAWithP521AndSHA512.String(),
        "ECDSAWithP521AndSHA512",
    );
    eq("Ed25519", tls::Ed25519.String(), "Ed25519");
    eq("PKCS1WithSHA1", tls::PKCS1WithSHA1.String(), "PKCS1WithSHA1");
    eq("ECDSAWithSHA1", tls::ECDSAWithSHA1.String(), "ECDSAWithSHA1");
    // Go prints the fallback in DECIMAL: 0x9999 == 39321.
    eq(
        "SignatureScheme fallback",
        tls::SignatureScheme(0x9999).String(),
        "SignatureScheme(39321)",
    );

    // ─── CurveID.String ───────────────────────────────────────────────
    eq("CurveP256", tls::CurveP256.String(), "CurveP256");
    eq("CurveP384", tls::CurveP384.String(), "CurveP384");
    eq("CurveP521", tls::CurveP521.String(), "CurveP521");
    eq("X25519", tls::X25519.String(), "X25519");
    eq("X25519MLKEM768", tls::X25519MLKEM768.String(), "X25519MLKEM768");
    eq("CurveID fallback", tls::CurveID(999).String(), "CurveID(999)");

    // ─── ClientAuthType.String ────────────────────────────────────────
    eq("NoClientCert", tls::NoClientCert.String(), "NoClientCert");
    eq("RequestClientCert", tls::RequestClientCert.String(), "RequestClientCert");
    eq(
        "RequireAnyClientCert",
        tls::RequireAnyClientCert.String(),
        "RequireAnyClientCert",
    );
    eq(
        "VerifyClientCertIfGiven",
        tls::VerifyClientCertIfGiven.String(),
        "VerifyClientCertIfGiven",
    );
    eq(
        "RequireAndVerifyClientCert",
        tls::RequireAndVerifyClientCert.String(),
        "RequireAndVerifyClientCert",
    );
    eq(
        "ClientAuthType fallback",
        tls::ClientAuthType(9).String(),
        "ClientAuthType(9)",
    );

    // ─── VersionName ──────────────────────────────────────────────────
    eq("SSLv3", tls::VersionName(tls::VersionSSL30), "SSLv3");
    eq("TLS 1.0", tls::VersionName(tls::VersionTLS10), "TLS 1.0");
    eq("TLS 1.1", tls::VersionName(tls::VersionTLS11), "TLS 1.1");
    eq("TLS 1.2", tls::VersionName(tls::VersionTLS12), "TLS 1.2");
    eq("TLS 1.3", tls::VersionName(tls::VersionTLS13), "TLS 1.3");
    // Uppercase hex, zero-padded to four digits — Go's "0x%04X".
    eq("VersionName fallback", tls::VersionName(0x0999), "0x0999");

    // ─── alert.String / alert.Error ───────────────────────────────────
    // Table hit and table miss; the miss is decimal, like Go's.
    eq(
        "alert close notify",
        tls::alert::alertCloseNotify.String(),
        "tls: close notify",
    );
    eq(
        "alert ECH required",
        tls::alert::alertECHRequired.String(),
        "tls: encrypted client hello required",
    );
    eq(
        "alert fallback",
        tls::alert::alert(200).String(),
        "tls: alert(200)",
    );
    eq(
        "AlertError wraps alert.String",
        tls::alert::AlertError(48).Error(),
        "tls: unknown certificate authority",
    );

    // ─── defaults.go — the preference ORDER, which decides what a
    //     handshake negotiates. Every value from goref.sh.
    let cp = tls::defaults_defaultCurvePreferences();
    check_n("curve prefs length", cp.Len(), 5);
    if cp.Len() == 5 {
        check_n("curve[0] X25519MLKEM768", goish::int(cp[0].0), 4588);
        check_n("curve[1] X25519", goish::int(cp[1].0), 29);
        check_n("curve[2] CurveP256", goish::int(cp[2].0), 23);
        check_n("curve[3] CurveP384", goish::int(cp[3].0), 24);
        check_n("curve[4] CurveP521", goish::int(cp[4].0), 25);
    }

    let sa = tls::defaults_defaultSupportedSignatureAlgorithms();
    check_n("sigalg length", sa.Len(), 12);
    if sa.Len() == 12 {
        // PSS-SHA256 first, SHA-1 last — the security-relevant ends.
        check_n("sigalg[0] PSSWithSHA256", goish::int(sa[0].0), 0x0804);
        check_n("sigalg[1] ECDSAWithP256AndSHA256", goish::int(sa[1].0), 0x0403);
        check_n("sigalg[2] Ed25519", goish::int(sa[2].0), 0x0807);
        check_n("sigalg[10] PKCS1WithSHA1", goish::int(sa[10].0), 0x0201);
        check_n("sigalg[11] ECDSAWithSHA1", goish::int(sa[11].0), 0x0203);
    }

    check_n("supportedCipherSuites(true) len", tls::defaults_supportedCipherSuites(true).Len(), 22);
    check_n("supportedCipherSuites(false) len", tls::defaults_supportedCipherSuites(false).Len(), 22);
    let sc = tls::defaults_supportedCipherSuites(true);
    if sc.Len() == 22 {
        check_n("aesGCM-preferred head", goish::int(sc[0]), 0xc02b);
    }
    let scn = tls::defaults_supportedCipherSuites(false);
    if scn.Len() == 22 {
        // ChaCha20 first when AES has no hardware support.
        check_n("no-AES head is ChaCha20", goish::int(scn[0]), 0xcca9);
    }

    // defaultCipherSuites drops the disabled/RSA-kex/3DES suites: 22 -> 10.
    let dc = tls::defaults_defaultCipherSuites(true);
    check_n("defaultCipherSuites(true) len", dc.Len(), 10);
    if dc.Len() == 10 {
        let want: [int; 10] = [
            0xc02b, 0xc02f, 0xc02c, 0xc030, 0xcca9, 0xcca8, 0xc009, 0xc013, 0xc00a, 0xc014,
        ];
        let mut i = 0usize;
        let mut ok = true;
        while i < 10 {
            if goish::int(dc[i]) != want[i] {
                ok = false;
            }
            i += 1;
        }
        check("defaultCipherSuites(true) exact order", ok);
    }
    check_n("defaultCipherSuites(false) len", tls::defaults_defaultCipherSuites(false).Len(), 10);

    unsafe {
        fmt::Printf!("tls_common_smoke: %v checks, %v failed\n", PASS + FAIL, FAIL);
        if FAIL > 0 {
            goish::syscall::Exit(1);
        }
    }
}
