// crypto/tls — the common.go enumerations and their String() forms.
//
// Every expected string was generated by
// `scripts/goref.sh crypto/tls`, not transcribed. That matters
// especially here: `common_string.go` is `stringer`-generated and packs
// its names into concatenated constants sliced by an index table, which
// goish spells as a plain match. The encoding is deliberately not
// reproduced, so the *outputs* are what has to be identical — including
// the `Type(N)` fallbacks and the `0x%04X` version fallback, each of
// which has a case below.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use goish::crypto::tls;
use goish::fmt;
use goish::gostring::string;
use goish::goslice::slice;
use goish::types::{byte, int};

fn hexOf(b: slice<byte>) -> string {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let raw: &[byte] = &b;
    let mut out: alloc::vec::Vec<u8> = alloc::vec::Vec::with_capacity(raw.len() * 2);
    for c in raw {
        out.push(HEX[(c >> 4) as usize]);
        out.push(HEX[(c & 0x0f) as usize]);
    }
    return string::from_bytes(&out);
}

static mut PASS: int = 0;
static mut FAIL: int = 0;

fn check(what: &'static str, ok: bool) {
    unsafe {
        if ok {
            PASS += 1;
        } else {
            FAIL += 1;
            fmt::Printf!("FAIL %s\n", what);
        }
    }
}

fn check_n(what: &'static str, got: int, want: int) {
    let ok = got == want;
    if !ok {
        fmt::Printf!("FAIL %s: got %v want %v\n", what, got, want);
    }
    check(what, ok);
}

fn eq(what: &'static str, got: string, want: &'static str) {
    let ok = got == string::from_static(want);
    unsafe {
        if ok {
            PASS += 1;
        } else {
            FAIL += 1;
            fmt::Printf!("FAIL %s: got %s want %s\n", what, got.clone(), want);
        }
    }
}

#[goish::main]
fn main() {
    // ─── SignatureScheme.String ───────────────────────────────────────
    eq("PKCS1WithSHA256", tls::PKCS1WithSHA256.String(), "PKCS1WithSHA256");
    eq("PKCS1WithSHA384", tls::PKCS1WithSHA384.String(), "PKCS1WithSHA384");
    eq("PKCS1WithSHA512", tls::PKCS1WithSHA512.String(), "PKCS1WithSHA512");
    eq("PSSWithSHA256", tls::PSSWithSHA256.String(), "PSSWithSHA256");
    eq("PSSWithSHA384", tls::PSSWithSHA384.String(), "PSSWithSHA384");
    eq("PSSWithSHA512", tls::PSSWithSHA512.String(), "PSSWithSHA512");
    eq(
        "ECDSAWithP256AndSHA256",
        tls::ECDSAWithP256AndSHA256.String(),
        "ECDSAWithP256AndSHA256",
    );
    eq(
        "ECDSAWithP384AndSHA384",
        tls::ECDSAWithP384AndSHA384.String(),
        "ECDSAWithP384AndSHA384",
    );
    eq(
        "ECDSAWithP521AndSHA512",
        tls::ECDSAWithP521AndSHA512.String(),
        "ECDSAWithP521AndSHA512",
    );
    eq("Ed25519", tls::Ed25519.String(), "Ed25519");
    eq("PKCS1WithSHA1", tls::PKCS1WithSHA1.String(), "PKCS1WithSHA1");
    eq("ECDSAWithSHA1", tls::ECDSAWithSHA1.String(), "ECDSAWithSHA1");
    // Go prints the fallback in DECIMAL: 0x9999 == 39321.
    eq(
        "SignatureScheme fallback",
        tls::SignatureScheme(0x9999).String(),
        "SignatureScheme(39321)",
    );

    // ─── CurveID.String ───────────────────────────────────────────────
    eq("CurveP256", tls::CurveP256.String(), "CurveP256");
    eq("CurveP384", tls::CurveP384.String(), "CurveP384");
    eq("CurveP521", tls::CurveP521.String(), "CurveP521");
    eq("X25519", tls::X25519.String(), "X25519");
    eq("X25519MLKEM768", tls::X25519MLKEM768.String(), "X25519MLKEM768");
    eq("CurveID fallback", tls::CurveID(999).String(), "CurveID(999)");

    // ─── ClientAuthType.String ────────────────────────────────────────
    eq("NoClientCert", tls::NoClientCert.String(), "NoClientCert");
    eq("RequestClientCert", tls::RequestClientCert.String(), "RequestClientCert");
    eq(
        "RequireAnyClientCert",
        tls::RequireAnyClientCert.String(),
        "RequireAnyClientCert",
    );
    eq(
        "VerifyClientCertIfGiven",
        tls::VerifyClientCertIfGiven.String(),
        "VerifyClientCertIfGiven",
    );
    eq(
        "RequireAndVerifyClientCert",
        tls::RequireAndVerifyClientCert.String(),
        "RequireAndVerifyClientCert",
    );
    eq(
        "ClientAuthType fallback",
        tls::ClientAuthType(9).String(),
        "ClientAuthType(9)",
    );

    // ─── VersionName ──────────────────────────────────────────────────
    eq("SSLv3", tls::VersionName(tls::VersionSSL30), "SSLv3");
    eq("TLS 1.0", tls::VersionName(tls::VersionTLS10), "TLS 1.0");
    eq("TLS 1.1", tls::VersionName(tls::VersionTLS11), "TLS 1.1");
    eq("TLS 1.2", tls::VersionName(tls::VersionTLS12), "TLS 1.2");
    eq("TLS 1.3", tls::VersionName(tls::VersionTLS13), "TLS 1.3");
    // Uppercase hex, zero-padded to four digits — Go's "0x%04X".
    eq("VersionName fallback", tls::VersionName(0x0999), "0x0999");

    // ─── alert.String / alert.Error ───────────────────────────────────
    // Table hit and table miss; the miss is decimal, like Go's.
    eq(
        "alert close notify",
        tls::alert::alertCloseNotify.String(),
        "tls: close notify",
    );
    eq(
        "alert ECH required",
        tls::alert::alertECHRequired.String(),
        "tls: encrypted client hello required",
    );
    eq(
        "alert fallback",
        tls::alert::alert(200).String(),
        "tls: alert(200)",
    );
    eq(
        "AlertError wraps alert.String",
        tls::alert::AlertError(48).Error(),
        "tls: unknown certificate authority",
    );

    // ─── defaults.go — the preference ORDER, which decides what a
    //     handshake negotiates. Every value from goref.sh.
    let cp = tls::defaults_defaultCurvePreferences();
    check_n("curve prefs length", cp.Len(), 5);
    if cp.Len() == 5 {
        check_n("curve[0] X25519MLKEM768", goish::int(cp[0].0), 4588);
        check_n("curve[1] X25519", goish::int(cp[1].0), 29);
        check_n("curve[2] CurveP256", goish::int(cp[2].0), 23);
        check_n("curve[3] CurveP384", goish::int(cp[3].0), 24);
        check_n("curve[4] CurveP521", goish::int(cp[4].0), 25);
    }

    let sa = tls::defaults_defaultSupportedSignatureAlgorithms();
    check_n("sigalg length", sa.Len(), 12);
    if sa.Len() == 12 {
        // PSS-SHA256 first, SHA-1 last — the security-relevant ends.
        check_n("sigalg[0] PSSWithSHA256", goish::int(sa[0].0), 0x0804);
        check_n("sigalg[1] ECDSAWithP256AndSHA256", goish::int(sa[1].0), 0x0403);
        check_n("sigalg[2] Ed25519", goish::int(sa[2].0), 0x0807);
        check_n("sigalg[10] PKCS1WithSHA1", goish::int(sa[10].0), 0x0201);
        check_n("sigalg[11] ECDSAWithSHA1", goish::int(sa[11].0), 0x0203);
    }

    check_n("supportedCipherSuites(true) len", tls::defaults_supportedCipherSuites(true).Len(), 22);
    check_n("supportedCipherSuites(false) len", tls::defaults_supportedCipherSuites(false).Len(), 22);
    let sc = tls::defaults_supportedCipherSuites(true);
    if sc.Len() == 22 {
        check_n("aesGCM-preferred head", goish::int(sc[0]), 0xc02b);
    }
    let scn = tls::defaults_supportedCipherSuites(false);
    if scn.Len() == 22 {
        // ChaCha20 first when AES has no hardware support.
        check_n("no-AES head is ChaCha20", goish::int(scn[0]), 0xcca9);
    }

    // defaultCipherSuites drops the disabled/RSA-kex/3DES suites: 22 -> 10.
    let dc = tls::defaults_defaultCipherSuites(true);
    check_n("defaultCipherSuites(true) len", dc.Len(), 10);
    if dc.Len() == 10 {
        let want: [int; 10] = [
            0xc02b, 0xc02f, 0xc02c, 0xc030, 0xcca9, 0xcca8, 0xc009, 0xc013, 0xc00a, 0xc014,
        ];
        let mut i = 0usize;
        let mut ok = true;
        while i < 10 {
            if goish::int(dc[i]) != want[i] {
                ok = false;
            }
            i += 1;
        }
        check("defaultCipherSuites(true) exact order", ok);
    }
    check_n("defaultCipherSuites(false) len", tls::defaults_defaultCipherSuites(false).Len(), 10);

    // ─── prf.go — the TLS 1.0/1.2 PRF. Every vector from goref.sh.
    //     A PRF that is subtly wrong still produces plausible-looking
    //     key material, so these are byte-exact or they prove nothing.
    let secret = slice::__from_vec(alloc::vec![
        0x01u8, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d
    ]);
    let seed = slice::__from_vec(alloc::vec![0xaau8, 0xbb, 0xcc, 0xdd, 0xee, 0xff]);

    let (s1, s2) = tls::prf_splitPreMasterSecret(secret.clone());
    eq("split s1", hexOf(s1), "01020304050607");
    eq("split s2", hexOf(s2), "0708090a0b0c0d");

    eq(
        "prf10 keyLen=32",
        hexOf(tls::prf_prf10(
            secret.clone(),
            string::from_static("master secret"),
            seed.clone(),
            32,
        )),
        "76a4061f1611dc509b3589e81b22d1749d193fde71bb427e8836d3f6f33b004f",
    );
    eq(
        "prf10 keyLen=20",
        hexOf(tls::prf_prf10(
            secret.clone(),
            string::from_static("key expansion"),
            seed.clone(),
            20,
        )),
        "c98bb12bae75d0beca4949d1b6ab2d399298a2e7",
    );
    eq(
        "prf12-sha256 keyLen=32",
        hexOf(tls::prf_prf12_sha256(
            secret.clone(),
            string::from_static("master secret"),
            seed.clone(),
            32,
        )),
        "a8ffb9e48646362087796fce9c1fa0d6a0fcb8676b5ac0ae06db2b6fe0d56660",
    );
    eq(
        "prf12-sha256 keyLen=48",
        hexOf(tls::prf_prf12_sha256(
            secret,
            string::from_static("extended master secret"),
            seed,
            48,
        )),
        "0ba3481482f3efeb8749fcb5212782c73fe538b631b8e560493faba22ee8ee3d0b44762c5937462f421c1630136863b2",
    );

    // ─── auth.go — signature type/hash mapping and scheme selection.
    //     All values from goref.sh.
    let (st, h, err) = tls::auth_typeAndHashFromSignatureScheme(tls::PKCS1WithSHA256);
    check_n("PKCS1WithSHA256 sigType", goish::int(st), 225);
    check_n("PKCS1WithSHA256 hash", goish::int(h.0), 5);
    check("PKCS1WithSHA256 no err", err == goish::nil);

    let (st, h, _) = tls::auth_typeAndHashFromSignatureScheme(tls::PSSWithSHA384);
    check_n("PSSWithSHA384 sigType", goish::int(st), 226);
    check_n("PSSWithSHA384 hash", goish::int(h.0), 6);

    let (st, h, _) = tls::auth_typeAndHashFromSignatureScheme(tls::ECDSAWithP521AndSHA512);
    check_n("ECDSAWithP521 sigType", goish::int(st), 227);
    check_n("ECDSAWithP521 hash", goish::int(h.0), 7);

    // Ed25519 signs the message whole: hash == directSigning == 0.
    let (st, h, _) = tls::auth_typeAndHashFromSignatureScheme(tls::Ed25519);
    check_n("Ed25519 sigType", goish::int(st), 228);
    check_n("Ed25519 hash is directSigning", goish::int(h.0), 0);

    let (_, _, err) = tls::auth_typeAndHashFromSignatureScheme(tls::SignatureScheme(0x9999));
    check("unknown scheme errors", err != goish::nil);

    // ─── handshake_messages.go — wire bytes, exact against Go.
    eq(
        "keyUpdateMsg(false)",
        hexOf(tls::msg_keyUpdate_marshal(false)),
        "1800000100",
    );
    eq(
        "keyUpdateMsg(true)",
        hexOf(tls::msg_keyUpdate_marshal(true)),
        "1800000101",
    );
    eq(
        "endOfEarlyDataMsg",
        hexOf(tls::msg_endOfEarlyData_marshal()),
        "05000000",
    );
    eq(
        "certificateStatusMsg",
        hexOf(tls::msg_certificateStatus_marshal(slice::__from_vec(alloc::vec![
            0x30u8, 0x03, 0x0a, 0x01, 0x00
        ]))),
        "160000090100000530030a0100",
    );

    // Round-trip through the parser.
    let (ok, req) = tls::msg_keyUpdate_unmarshal(tls::msg_keyUpdate_marshal(true));
    check("keyUpdate round-trip ok", ok);
    check("keyUpdate round-trip value", req);
    let (ok, resp) = tls::msg_certificateStatus_unmarshal(tls::msg_certificateStatus_marshal(
        slice::__from_vec(alloc::vec![0x30u8, 0x03, 0x0a, 0x01, 0x00]),
    ));
    check("certStatus round-trip ok", ok);
    eq("certStatus round-trip response", hexOf(resp), "30030a0100");

    // Rejections Go makes — each verified against Go, not assumed.
    let (ok, _) = tls::msg_keyUpdate_unmarshal(slice::__from_vec(alloc::vec![24u8, 0, 0, 1, 2]));
    check("keyUpdate rejects updateRequested=2", !ok);
    let (ok, _) =
        tls::msg_keyUpdate_unmarshal(slice::__from_vec(alloc::vec![24u8, 0, 0, 1, 1, 0xff]));
    check("keyUpdate rejects trailing data", !ok);
    let (ok, _) = tls::msg_certificateStatus_unmarshal(slice::__from_vec(alloc::vec![
        22u8, 0, 0, 4, 1, 0, 0, 0
    ]));
    check("certStatus rejects empty OCSP response", !ok);

    eq(
        "helloRequestMsg",
        hexOf(tls::msg_helloRequest_marshal()),
        "00000000",
    );

    // addUint64 / readUint64 split a uint64 into two big-endian uint32
    // halves; the round-trip and the exact bytes both come from Go.
    let (bytes, ok) = tls::msg_uint64_roundtrip(slice::__from_vec(alloc::vec![
        0x0123456789abcdefu64,
        0u64,
        u64::MAX
    ]));
    eq(
        "addUint64 wire bytes",
        hexOf(bytes),
        "0123456789abcdef0000000000000000ffffffffffffffff",
    );
    check("readUint64 round-trips and consumes all input", ok);

    // Three simple byte-container messages. Wire bytes and every
    // rejection below come from goref.sh.
    let body = slice::__from_vec(alloc::vec![0xdeu8, 0xad, 0xbe, 0xef]);

    let (b, ok, got) = tls::msg_simple_roundtrip(0, body.clone());
    eq("serverKeyExchangeMsg", hexOf(b.clone()), "0c000004deadbeef");
    check("serverKeyExchange round-trip", ok);
    eq("serverKeyExchange body", hexOf(got), "deadbeef");
    let raw: &[byte] = &b;
    check(
        "serverKeyExchange rejects <4 bytes",
        !tls::msg_simple_unmarshal(0, slice::__from_vec(raw[..3].to_vec())),
    );

    let (b, ok, got) = tls::msg_simple_roundtrip(1, body.clone());
    eq("clientKeyExchangeMsg", hexOf(b.clone()), "10000004deadbeef");
    check("clientKeyExchange round-trip", ok);
    eq("clientKeyExchange body", hexOf(got), "deadbeef");
    // Unlike serverKeyExchange, this one validates its uint24 length.
    let mut bad: alloc::vec::Vec<byte> = b.clone().__into_vec();
    bad[3] = 0x09;
    check(
        "clientKeyExchange rejects a wrong declared length",
        !tls::msg_simple_unmarshal(1, slice::__from_vec(bad)),
    );

    let (b, ok, got) = tls::msg_simple_roundtrip(2, body);
    eq("newSessionTicketMsg", hexOf(b.clone()), "0400000a000000000004deadbeef");
    check("newSessionTicket round-trip", ok);
    eq("newSessionTicket body", hexOf(got), "deadbeef");
    let raw: &[byte] = &b;
    check(
        "newSessionTicket rejects <10 bytes",
        !tls::msg_simple_unmarshal(2, slice::__from_vec(raw[..9].to_vec())),
    );

    // ─── cipher_suites.go's public surface. All from goref.sh.
    check_n("CipherSuites length", tls::CipherSuites().Len(), 13);
    check_n("InsecureCipherSuites length", tls::InsecureCipherSuites().Len(), 12);
    eq(
        "CipherSuiteName TLS1.3 AES128",
        tls::CipherSuiteName(0x1301),
        "TLS_AES_128_GCM_SHA256",
    );
    eq(
        "CipherSuiteName ChaCha20",
        tls::CipherSuiteName(0x1303),
        "TLS_CHACHA20_POLY1305_SHA256",
    );
    eq(
        "CipherSuiteName ECDHE-ECDSA-AES128-GCM",
        tls::CipherSuiteName(0xc02b),
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    );
    // Found via the INSECURE list, so this proves the second loop runs.
    eq(
        "CipherSuiteName RC4 (insecure list)",
        tls::CipherSuiteName(0x0005),
        "TLS_RSA_WITH_RC4_128_SHA",
    );
    eq(
        "CipherSuiteName 3DES (insecure list)",
        tls::CipherSuiteName(0x000a),
        "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
    );
    // Unknown IDs fall back to uppercase hex, not decimal.
    eq("CipherSuiteName fallback", tls::CipherSuiteName(0x9999), "0x9999");

    let first = tls::CipherSuites();
    if first.Len() == 13 {
        check_n("CipherSuites[0].ID", goish::int(first[0].ID), 0x1301);
        check("CipherSuites[0] is not insecure", !first[0].Insecure);
        check_n("CipherSuites[0] is TLS1.3-only", first[0].SupportedVersions.Len(), 1);
    }
    let ins = tls::InsecureCipherSuites();
    if ins.Len() == 12 {
        check_n("InsecureCipherSuites[0].ID", goish::int(ins[0].ID), 0x0005);
        check("InsecureCipherSuites[0] is flagged insecure", ins[0].Insecure);
        check_n("InsecureCipherSuites[0] spans TLS1.0-1.2", ins[0].SupportedVersions.Len(), 3);
    }

    // ─── key_agreement.go — the ServerKeyExchange transcript digest.
    //     Four branches, each a different algorithm; all from goref.sh.
    let sl = slice::__from_vec(alloc::vec![
        slice::__from_vec(alloc::vec![0x01u8, 0x02]),
        slice::__from_vec(alloc::vec![0x03u8]),
        slice::__from_vec(alloc::vec![0x04u8, 0x05, 0x06]),
    ]);
    eq(
        "sha1Hash over 3 slices",
        hexOf(tls::ka_sha1Hash(sl.clone())),
        "5d211bad8f4ee70e16c7d343a838fc344a1ed961",
    );
    // MD5 || SHA-1, in that order — 16 bytes then 20.
    eq(
        "md5SHA1Hash",
        hexOf(tls::ka_md5SHA1Hash(sl.clone())),
        "6ac1e56bc78f031059be7be854522c4c5d211bad8f4ee70e16c7d343a838fc344a1ed961",
    );
    eq(
        "hashForServerKeyExchange TLS1.2/SHA256",
        hexOf(tls::ka_hashForServerKeyExchange(
            226,
            goish::crypto::SHA256,
            tls::VersionTLS12,
            sl.clone(),
        )),
        "7192385c3c0605de55bb9476ce1d90748190ecb32a8eed7f5207b30cf6a1fe89",
    );
    // Ed25519 signs the message whole: the "digest" is the concatenation.
    eq(
        "hashForServerKeyExchange Ed25519 is not hashed",
        hexOf(tls::ka_hashForServerKeyExchange(
            228,
            goish::crypto::Hash(0),
            tls::VersionTLS12,
            sl.clone(),
        )),
        "010203040506",
    );
    // Before TLS 1.2 the hash is fixed by signature type, NOT by hashFunc:
    // ECDSA takes SHA-1, RSA takes MD5+SHA1, and the hashFunc argument is
    // ignored in both.
    eq(
        "hashForServerKeyExchange TLS1.1/ECDSA ignores hashFunc",
        hexOf(tls::ka_hashForServerKeyExchange(
            227,
            goish::crypto::SHA256,
            tls::VersionTLS11,
            sl.clone(),
        )),
        "5d211bad8f4ee70e16c7d343a838fc344a1ed961",
    );
    eq(
        "hashForServerKeyExchange TLS1.1/RSA ignores hashFunc",
        hexOf(tls::ka_hashForServerKeyExchange(
            225,
            goish::crypto::SHA256,
            tls::VersionTLS11,
            sl,
        )),
        "6ac1e56bc78f031059be7be854522c4c5d211bad8f4ee70e16c7d343a838fc344a1ed961",
    );

    // ─── certificateMsg — a uint24 list of uint24-prefixed DER certs.
    let certs = slice::__from_vec(alloc::vec![
        slice::__from_vec(alloc::vec![0xaau8, 0xbb]),
        slice::__from_vec(alloc::vec![0xccu8]),
    ]);
    let (b, ok, n) = tls::msg_certificate_roundtrip(certs);
    eq("certificateMsg", hexOf(b.clone()), "0b00000c000009000002aabb000001cc");
    check("certificateMsg round-trip", ok);
    check_n("certificateMsg recovered 2 certs", n, 2);

    // An empty chain is legal and round-trips.
    let (eb, eok, en) = tls::msg_certificate_roundtrip(slice::__from_vec(alloc::vec![]));
    eq("empty certificateMsg", hexOf(eb), "0b000003000000");
    check("empty certificateMsg round-trips", eok);
    check_n("empty certificateMsg has 0 certs", en, 0);

    // A ZERO-LENGTH certificate marshals but does NOT parse back: the
    // `len(d) < 4` guard trips on the trailing 3-byte entry. Go's own
    // output is not round-trippable here, and the port reproduces that
    // rather than "fixing" it. Verified against Go.
    let (zb, zok, _) = tls::msg_certificate_roundtrip(slice::__from_vec(alloc::vec![
        slice::__from_vec(alloc::vec![0xaau8, 0xbb]),
        slice::__from_vec(alloc::vec![0xccu8]),
        slice::__from_vec(alloc::vec![]),
    ]));
    eq(
        "certificateMsg with an empty entry marshals",
        hexOf(zb),
        "0b00000f00000c000002aabb000001cc000000",
    );
    check("…but Go rejects it on the way back, and so do we", !zok);

    // Rejections.
    let raw: &[byte] = &b;
    check(
        "certificateMsg rejects <7 bytes",
        !tls::msg_certificate_unmarshal(slice::__from_vec(raw[..6].to_vec())),
    );
    let mut bad: alloc::vec::Vec<byte> = b.__into_vec();
    bad[6] = 0xff;
    check(
        "certificateMsg rejects a wrong certsLen",
        !tls::msg_certificate_unmarshal(slice::__from_vec(bad)),
    );

    unsafe {
        fmt::Printf!("tls_common_smoke: %v checks, %v failed\n", PASS + FAIL, FAIL);
        if FAIL > 0 {
            goish::syscall::Exit(1);
        }
    }
}
