// crypto/x509 — the CRL and CSR decode half.
//
// Every expectation is generated by `scripts/goref.sh crypto/x509`, not
// transcribed: `CRL_DER` is the literal DER Go's `CreateRevocationList`
// produced from a fixed Ed25519 seed, and each asserted field is what
// Go's own `ParseRevocationList` / `ParseDERCRL` read back out of it.
// Parsing Go's bytes is the point — a round trip through goish's own
// encoder would pass even if both sides were wrong in the same way.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use goish::crypto::x509;
use goish::fmt;
use goish::goslice::slice;
use goish::gostring::string;
use goish::types::{byte, int};

static mut PASS: int = 0;
static mut FAIL: int = 0;

fn check(name: &str, ok: bool) {
    unsafe {
        if ok {
            PASS += 1;
        } else {
            FAIL += 1;
            fmt::Printf!("FAIL: %s\n", name);
        }
    }
}

fn eq(name: &str, got: string, want: &'static str) {
    let ok = got == string::from_static(want);
    if !ok {
        fmt::Printf!("  got=%s want=%s\n", got.clone(), want);
    }
    check(name, ok);
}

/// Go's `CreateRevocationList` output for the fixed seed — goref.sh.
const CRL_DER: &str = "3081d1308184020101300506032b657030133111300f06035504031308676f697368204341170d3137303731343032343030305a170d3230303931333132323634305a3014301202012a170d3134303531333136353332305aa02f302d301f0603551d2304183016801456475aa75463474c0285df5dbf2bcab73da65135300a0603551d140403020107300506032b6570034100d00bbd80f0a58858ed7b766b92ff6d945343718d7cff7f14fb1ed2d4c349f474fab9409927f97f2a4090f45f5a628643b85bffc8c340f150038df154bc8df10b";

fn unhex(s: &str) -> slice<byte> {
    let b = s.as_bytes();
    let mut out: Vec<byte> = Vec::new();
    let mut i = 0usize;
    while i + 1 < b.len() {
        let hi = nib(b[i]);
        let lo = nib(b[i + 1]);
        out.push((hi << 4) | lo);
        i += 2;
    }
    return slice::__from_vec(out);
}

fn nib(c: u8) -> u8 {
    if c >= b'0' && c <= b'9' {
        return c - b'0';
    }
    return c - b'a' + 10;
}

#[goish::main]
fn main() {
    let der = unhex(CRL_DER);

    // ─── ParseRevocationList ──────────────────────────────────────────
    let (rl, err) = x509::ParseRevocationList(der.clone());
    check("ParseRevocationList accepts Go's CRL", err == goish::nil);
    if let Some(rl) = rl {
        eq("Number == 7", rl.Number.Text(10), "7");
        eq(
            "Issuer.CommonName",
            rl.Issuer.CommonName.clone(),
            "goish CA",
        );
        check(
            "ThisUpdate == 1500000000",
            rl.ThisUpdate.Unix() == 1500000000,
        );
        check(
            "NextUpdate == 1600000000",
            rl.NextUpdate.Unix() == 1600000000,
        );
        check("1 revoked entry", rl.RevokedCertificateEntries.Len() == 1);
        if rl.RevokedCertificateEntries.Len() == 1 {
            let e = &rl.RevokedCertificateEntries[0];
            eq("entry0 serial == 42", e.SerialNumber.Text(10), "42");
            check(
                "entry0 time == 1400000000",
                e.RevocationTime.Unix() == 1400000000,
            );
        }
        check(
            "SignatureAlgorithm is Ed25519",
            rl.SignatureAlgorithm == x509::PureEd25519,
        );
        check("2 CRL extensions", rl.Extensions.Len() == 2);
        check("AuthorityKeyId is 20 bytes", rl.AuthorityKeyId.Len() == 20);
        // The deprecated mirror must agree with the modern list.
        check(
            "RevokedCertificates mirrors the entries",
            rl.RevokedCertificates.Len() == 1,
        );
    } else {
        check("ParseRevocationList returned a value", false);
    }

    // ─── ParseDERCRL — the asn1.Unmarshal path over the same bytes ────
    let (cl, err) = x509::ParseDERCRL(der.clone());
    check("ParseDERCRL accepts Go's CRL", err == goish::nil);
    if let Some(cl) = cl {
        check("pkix version == 1", cl.TBSCertList.Version == 1);
        check(
            "pkix 1 revoked cert",
            cl.TBSCertList.RevokedCertificates.Len() == 1,
        );
        if cl.TBSCertList.RevokedCertificates.Len() == 1 {
            eq(
                "pkix serial0 == 42",
                cl.TBSCertList.RevokedCertificates[0].SerialNumber.Text(10),
                "42",
            );
        }
    } else {
        check("ParseDERCRL returned a value", false);
    }

    // ─── Rejection: trailing data must not be accepted ────────────────
    let mut trailing: Vec<byte> = der.clone().__into_vec();
    trailing.push(0x00);
    let (_, err) = x509::ParseDERCRL(slice::__from_vec(trailing));
    check("ParseDERCRL rejects trailing data", err != goish::nil);

    // Truncation must be an error, not a panic or a silent empty CRL.
    let raw: &[byte] = &der;
    let (_, err) = x509::ParseRevocationList(slice::__from_vec(raw[..raw.len() / 2].to_vec()));
    check(
        "ParseRevocationList rejects a truncated CRL",
        err != goish::nil,
    );

    unsafe {
        // See tls_common_smoke: copy before formatting so we never take
        // a shared reference to a `static mut`.
        let (pass, fail) = (PASS, FAIL);
        fmt::Printf!(
            "x509_crl_csr_smoke: %v checks, %v failed\n",
            pass + fail,
            fail
        );
        if fail > 0 {
            goish::syscall::Exit(1);
        }
    }
}
