// zlib_smoke — exercise compress/zlib's RFC 1950 reader + writer.
//
// zlib is a 2-byte header + 4-byte big-endian Adler-32 trailer around
// a raw DEFLATE payload (compress/flate). The strong test is a
// compress -> decompress round-trip entirely through goish.
//
// Coverage:
//   1..5   round-trip at NoCompression / BestSpeed / DefaultCompression
//          / BestCompression / HuffmanOnly, each over 4 inputs
//          (empty, short, highly repetitive, a few KB of mixed data).
//   6      NewWriterLevelDict / NewReaderDict with a preset dictionary.
//   7      Flush mid-stream then continue + Close.
//   8      invalid level rejected by NewWriterLevel.
//   9      corrupted header -> ErrHeader.
//  10      corrupted trailer -> ErrChecksum.
//  11      Go -> goish interop: decompress a real Go-zlib.NewWriter
//          stream (embedded as bytes, generated by the Go toolchain).
//  12      goish -> Go interop: write a goish-compressed stream to a
//          file for the validation step to decompress with Go; also
//          assert the 2-byte header equals Go's for DefaultCompression.

#![no_std]
#![no_main]
#![allow(non_snake_case)]

extern crate alloc;
extern crate goish;

use alloc::vec::Vec;
use core::sync::atomic::{AtomicUsize, Ordering};

use goish::fmt;
use goish::compress::zlib;
use goish::error;
use goish::errors;
use goish::goslice::slice;
use goish::io;
use goish::runtime::sched::schedule;
use goish::types::{byte, int};
use goish::{bytes, go, syscall};

const TOTAL: usize = 12;

// Linux open(2) flags not exported by goish::syscall.
const O_WRONLY: i32 = 0o1;
const O_CREAT: i32 = 0o100;
const O_TRUNC: i32 = 0o1000;

// goish -> Go interop file, read back by the validation step.
const GOISH_PRODUCED: &[u8] = b"/tmp/zlib_smoke_goish_produced.bin\0";

// The input the validation step decompresses with the Go toolchain.
const INTEROP_INPUT: &[u8] =
    b"compress/zlib interop: the quick brown fox jumps over the lazy dog. \
the quick brown fox jumps over the lazy dog. the quick brown fox jumps.";

// A real zlib stream produced by Go 1.25 `zlib.NewWriter` (default
// level) compressing INTEROP_INPUT. Header is `78 9c`.
const GO_STREAM: &[u8] = &[
    120, 156, 74, 206, 207, 45, 40, 74, 45, 46, 214, 175, 202, 201, 76, 82, 200, 204, 43, 73, 45,
    202, 47, 176, 82, 40, 201, 72, 85, 40, 44, 205, 76, 206, 86, 72, 42, 202, 47, 207, 83, 72,
    203, 175, 80, 200, 42, 205, 45, 40, 86, 200, 47, 75, 45, 2, 75, 231, 36, 86, 85, 42, 164, 228,
    167, 235, 81, 73, 177, 30, 32, 0, 0, 255, 255, 27, 64, 51, 6,
];

static FAILED: AtomicUsize = AtomicUsize::new(0);

fn fail() {
    FAILED.fetch_add(1, Ordering::AcqRel);
}

#[goish::main]
fn main() {
    go!(|| {
        run_tests();
        let f = FAILED.load(Ordering::Acquire);
        if f == 0 {
            fmt::Println!("ok 12/12");
            syscall::Exit(0);
        } else {
            fmt::Println!("FAIL", f as i64, "of 12");
            syscall::Exit(1);
        }
    });
    schedule();
}

fn run_tests() {
    test_level(1, zlib::NoCompression, b"NoCompression round-trip  ");
    test_level(2, zlib::BestSpeed, b"BestSpeed round-trip      ");
    test_level(3, zlib::DefaultCompression, b"DefaultCompression r-trip ");
    test_level(4, zlib::BestCompression, b"BestCompression round-trip");
    test_level(5, zlib::HuffmanOnly, b"HuffmanOnly round-trip    ");
    test_6_dict();
    test_7_flush();
    test_8_invalid_level();
    test_9_bad_header();
    test_10_bad_trailer();
    test_11_go_to_goish();
    test_12_goish_to_go();
}

fn from_bytes(b: &[u8]) -> slice<byte> {
    let mut v: Vec<byte> = Vec::with_capacity(b.len());
    for &x in b {
        v.push(x);
    }
    slice::__from_vec(v)
}

fn write_result(idx: u8, label: &[u8], pass: bool) {
    syscall::Write(syscall::STDOUT, b"[".as_ptr(), 1);
    let d2 = b'0' + idx % 10;
    if idx >= 10 {
        let d1 = b'0' + idx / 10;
        let buf = [d1, d2];
        syscall::Write(syscall::STDOUT, buf.as_ptr(), 2);
    } else {
        let buf = [b' ', d2];
        syscall::Write(syscall::STDOUT, buf.as_ptr(), 2);
    }
    syscall::Write(syscall::STDOUT, b"] ".as_ptr(), 2);
    syscall::Write(syscall::STDOUT, label.as_ptr(), label.len());
    if pass {
        syscall::Write(syscall::STDOUT, b" PASS\n".as_ptr(), 6);
    } else {
        syscall::Write(syscall::STDOUT, b" FAIL\n".as_ptr(), 6);
    }
}

// Compress `raw` at `level` with NewWriterLevel; return the zlib bytes.
fn compress(raw: &[u8], level: int) -> (Vec<byte>, bool) {
    let (mut w, err) = zlib::NewWriterLevel(bytes::NewBuffer(slice::new()), level);
    if !err.IsNil() {
        return (Vec::new(), false);
    }
    let (_, werr) = w.Write(from_bytes(raw));
    if !werr.IsNil() {
        return (Vec::new(), false);
    }
    if !w.Close().IsNil() {
        return (Vec::new(), false);
    }
    (drain(w.into_writer()), true)
}

// Drain a bytes::Buffer into a Vec.
fn drain(buf: bytes::Buffer) -> Vec<byte> {
    let b = buf.Bytes();
    let mut out: Vec<byte> = Vec::with_capacity(b.len() as usize);
    let mut i: int = 0;
    while i < goish::len(&b) {
        out.push(b[i]);
        i += 1;
    }
    out
}

// Decompress a zlib byte stream through goish's NewReader.
fn decompress(comp: &[u8]) -> (Vec<byte>, error) {
    let r = bytes::NewReader(from_bytes(comp));
    let (mut d, nerr) = zlib::NewReader(r);
    if !nerr.IsNil() {
        return (Vec::new(), nerr);
    }
    read_all(&mut d)
}

// Decompress a zlib stream with a preset dictionary.
fn decompress_dict(comp: &[u8], dict: &[u8]) -> (Vec<byte>, error) {
    let r = bytes::NewReader(from_bytes(comp));
    let (mut d, nerr) = zlib::NewReaderDict(r, from_bytes(dict));
    if !nerr.IsNil() {
        return (Vec::new(), nerr);
    }
    read_all(&mut d)
}

fn read_all<R: io::Reader + io::ByteReader>(d: &mut zlib::Reader<R>) -> (Vec<byte>, error) {
    let mut out: Vec<byte> = Vec::new();
    let mut buf = from_bytes(&[0u8; 512]);
    loop {
        let (n, err) = d.Read(&mut buf);
        let mut k: int = 0;
        while k < n {
            out.push(buf[k]);
            k += 1;
        }
        if !err.IsNil() {
            if errors::Is(err.clone(), io::EOF) {
                return (out, errors::nil);
            }
            return (out, err);
        }
    }
}

fn eq(a: &[byte], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    for i in 0..b.len() {
        if a[i] != b[i] {
            return false;
        }
    }
    true
}

// A few KB of mixed (semi-compressible) data.
fn mixed_kb() -> Vec<u8> {
    let mut v: Vec<u8> = Vec::with_capacity(4096);
    let mut x: u32 = 0x1234_5678;
    for i in 0..4096u32 {
        x = x.wrapping_mul(1_103_515_245).wrapping_add(12_345);
        let b = if i % 7 < 3 {
            (b'A' + (i % 26) as u8) as u8
        } else {
            (x >> 16) as u8
        };
        v.push(b);
    }
    v
}

// Round-trip the 4 standard inputs at one level.
fn test_level(idx: u8, level: int, label: &[u8]) {
    let kb = mixed_kb();
    let repetitive: &[u8] =
        b"abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc";
    let inputs: [&[u8]; 4] = [b"", b"hello, zlib!", repetitive, kb.as_slice()];

    let mut ok = true;
    for raw in inputs.iter() {
        let (comp, cok) = compress(raw, level);
        if !cok {
            ok = false;
            break;
        }
        let (got, err) = decompress(&comp);
        if !err.IsNil() || !eq(&got, raw) {
            ok = false;
            break;
        }
    }
    write_result(idx, label, ok);
    if !ok {
        fail();
    }
}

fn test_6_dict() {
    let dict: &[u8] = b"the quick brown fox";
    let raw: &[u8] = b"the quick brown fox jumps over the lazy dog";

    let (mut w, err) = zlib::NewWriterLevelDict(
        bytes::NewBuffer(slice::new()),
        zlib::BestCompression,
        from_bytes(dict),
    );
    let mut ok = err.IsNil();
    if ok {
        ok = w.Write(from_bytes(raw)).1.IsNil() && w.Close().IsNil();
    }
    if ok {
        let comp = drain(w.into_writer());
        let (got, e) = decompress_dict(&comp, dict);
        ok = e.IsNil() && eq(&got, raw);
    }
    write_result(6, b"NewWriterLevelDict r-trip ", ok);
    if !ok {
        fail();
    }
}

fn test_7_flush() {
    let p1: &[u8] = b"first half before the sync flush marker; ";
    let p2: &[u8] = b"second half written after Flush returned.";

    let (mut w, err) =
        zlib::NewWriterLevel(bytes::NewBuffer(slice::new()), zlib::DefaultCompression);
    let mut ok = err.IsNil();
    if ok {
        ok = w.Write(from_bytes(p1)).1.IsNil();
    }
    if ok {
        ok = w.Flush().IsNil();
    }
    if ok {
        ok = w.Write(from_bytes(p2)).1.IsNil();
    }
    if ok {
        ok = w.Close().IsNil();
    }
    if ok {
        let comp = drain(w.into_writer());
        let mut expect: Vec<u8> = Vec::new();
        expect.extend_from_slice(p1);
        expect.extend_from_slice(p2);
        let (got, e) = decompress(&comp);
        ok = e.IsNil() && eq(&got, &expect);
    }
    write_result(7, b"Flush mid-stream + Close  ", ok);
    if !ok {
        fail();
    }
}

fn test_8_invalid_level() {
    // Level 42 is out of range -> NewWriterLevel returns a non-nil error.
    let (_, err) = zlib::NewWriterLevel(bytes::NewBuffer(slice::new()), 42);
    let ok = !err.IsNil();
    write_result(8, b"invalid level rejected    ", ok);
    if !ok {
        fail();
    }
}

fn test_9_bad_header() {
    // Corrupt the 2-byte zlib header: clobber the FCHECK so h%31 != 0.
    let (mut comp, cok) = compress(b"some payload to corrupt", zlib::DefaultCompression);
    let mut ok = cok && comp.len() > 4;
    if ok {
        comp[1] ^= 0x01; // breaks the mod-31 checksum
        let (_, err) = decompress(&comp);
        ok = errors::Is(err, zlib::ErrHeader);
    }
    write_result(9, b"corrupt header -> ErrHeader", ok);
    if !ok {
        fail();
    }
}

fn test_10_bad_trailer() {
    // Corrupt the last byte of the Adler-32 trailer.
    let (mut comp, cok) = compress(b"some payload to corrupt", zlib::DefaultCompression);
    let mut ok = cok && comp.len() > 6;
    if ok {
        let n = comp.len();
        comp[n - 1] ^= 0xff;
        let (_, err) = decompress(&comp);
        ok = errors::Is(err, zlib::ErrChecksum);
    }
    write_result(10, b"corrupt trailer->ErrChksum", ok);
    if !ok {
        fail();
    }
}

fn test_11_go_to_goish() {
    // Decompress a real Go-produced zlib stream with goish.
    let (got, err) = decompress(GO_STREAM);
    let ok = err.IsNil() && eq(&got, INTEROP_INPUT);
    write_result(11, b"Go -> goish interop       ", ok);
    if !ok {
        fail();
    }
}

// Write `data` to a file via raw syscalls. Returns success.
fn write_file(path: &[u8], data: &[u8]) -> bool {
    let fd = syscall::Open(path.as_ptr(), O_WRONLY | O_CREAT | O_TRUNC, 0o644);
    if fd < 0 {
        return false;
    }
    let mut off = 0usize;
    let mut ok = true;
    while off < data.len() {
        let n = syscall::Write(fd, data[off..].as_ptr(), data.len() - off);
        if n <= 0 {
            ok = false;
            break;
        }
        off += n as usize;
    }
    syscall::Close(fd);
    ok
}

fn test_12_goish_to_go() {
    // Compress INTEROP_INPUT with goish at DefaultCompression and drop
    // it to GOISH_PRODUCED for the validation step to decompress with Go.
    let (comp, cok) = compress(INTEROP_INPUT, zlib::DefaultCompression);
    let mut ok = cok && comp.len() > 6;
    // The 2-byte header must be byte-identical to Go's for the default
    // level (deterministic): 0x78 0x9c.
    if ok {
        ok = comp[0] == 0x78 && comp[1] == 0x9c;
    }
    if ok {
        ok = write_file(GOISH_PRODUCED, &comp);
    }
    // Local sanity: goish must round-trip its own output.
    if ok {
        let (got, err) = decompress(&comp);
        ok = err.IsNil() && eq(&got, INTEROP_INPUT);
    }
    write_result(12, b"goish -> Go interop       ", ok);
    if !ok {
        fail();
    }
}

// Reference the constant so the harness shape matches sibling examples.
const _: usize = TOTAL;
