// crypto/rsa — port of Go 1.25's `crypto/rsa` package.
//
// This is the CORE: the key data types, key generation, and the raw RSA
// primitives (`encrypt` / `decrypt`). PKCS#1 v1.5 and OAEP/PSS padding
// layers are built on top of this in later tasks.
//
// Strategy
// --------
// Go 1.25 delegates the math to an internal FIPS tree (`bigmod` — a
// constant-time multi-precision package). goish does NOT port `bigmod`.
// Instead this module is implemented on top of goish's `math/big`
// (`crate::math::big::Int`), which is the classic pre-FIPS approach the
// original `crypto/rsa` used: the public API and algorithms are the
// same, only the underlying bignum is different.
//
// Known accepted limitation: `math/big`-based modular exponentiation is
// NOT constant-time. This is fine for goish v1; nothing here claims
// otherwise. Constant-time checks that Go performs are reproduced
// best-effort with ordinary comparisons — correctness first.
//
// Mirrors crypto/rsa/rsa.go's data shapes:
//
//   type PublicKey struct { N *big.Int; E int }
//   type PrivateKey struct {
//       PublicKey               // embedded
//       D           *big.Int
//       Primes      []*big.Int
//       Precomputed PrecomputedValues
//   }

#![allow(non_snake_case)]

extern crate alloc;

use crate::error;
use crate::errors;
use crate::math::big;
use crate::slice;
use crate::types::int;

// ─── PublicKey (Go: rsa.go:68) ────────────────────────────────────────

/// A `PublicKey` represents the public part of an RSA key.
///
/// The values of `N` and `E` are not considered confidential.
#[derive(Clone, Default)]
pub struct PublicKey {
    /// Modulus.
    pub N: big::Int,
    /// Public exponent.
    pub E: int,
}

// Polymorphic-nil for `*rsa.PublicKey`. Go callers pass nil pointers
// occasionally; in goish the natural model is a default-valued struct,
// matched by the per-type Nil impls.
impl PartialEq<crate::nilval::Nil> for PublicKey {
    fn eq(&self, _: &crate::nilval::Nil) -> bool {
        self.N == crate::nilval::nil && self.E == 0
    }
}
impl PartialEq<PublicKey> for crate::nilval::Nil {
    fn eq(&self, other: &PublicKey) -> bool {
        other.N == crate::nilval::nil && other.E == 0
    }
}
impl From<crate::nilval::Nil> for PublicKey {
    fn from(_: crate::nilval::Nil) -> Self {
        PublicKey::default()
    }
}

impl PublicKey {
    /// `(*PublicKey).Size()` (Go: rsa.go:78) — modulus size in bytes.
    /// Raw signatures and ciphertexts for or by this key share this size.
    pub fn Size(&self) -> int {
        (self.N.BitLen() + 7) / 8
    }

    /// `(*PublicKey).Equal(x)` (Go: rsa.go:83) — reports whether `self`
    /// and `x` have the same value.
    pub fn Equal(&self, x: &PublicKey) -> bool {
        bigIntEqual(&self.N, &x.N) && self.E == x.E
    }
}

// ─── CRTValue / PrecomputedValues (Go: rsa.go:201-224) ────────────────

/// `CRTValue` contains the precomputed Chinese-remainder-theorem values
/// for the 3rd and subsequent primes of a multi-prime key.
#[derive(Clone, Default)]
pub struct CRTValue {
    /// `D mod (prime-1)`.
    pub Exp: big::Int,
    /// `R·Coeff ≡ 1 mod Prime`.
    pub Coeff: big::Int,
    /// Product of primes prior to this (including p and q).
    pub R: big::Int,
}

/// `PrecomputedValues` holds values that speed up RSA private-key
/// operations. It is generated by `PrivateKey::Precompute`.
#[derive(Clone, Default)]
pub struct PrecomputedValues {
    /// `D mod (P-1)`.
    pub Dp: big::Int,
    /// `D mod (Q-1)`.
    pub Dq: big::Int,
    /// `Q⁻¹ mod P`.
    pub Qinv: big::Int,
    /// CRT values for the 3rd and subsequent primes.
    ///
    /// Deprecated: still filled in by `Precompute` for backwards
    /// compatibility but not used. For ordinary 2-prime keys this stays
    /// empty; the type is defined for API parity with Go.
    pub CRTValues: slice<CRTValue>,
}

// ─── PrivateKey (Go: rsa.go:107) ──────────────────────────────────────

/// A `PrivateKey` represents an RSA key.
///
/// Go embeds `PublicKey` anonymously; goish has no struct embedding, so
/// the public part is a field literally named `PublicKey`. Read it as
/// `priv.PublicKey.N` (Go's `priv.N` reaches the same field via
/// promotion).
#[derive(Clone, Default)]
pub struct PrivateKey {
    /// Public part of the key.
    pub PublicKey: PublicKey,
    /// Private exponent.
    pub D: big::Int,
    /// Prime factors of `N`; has >= 2 elements.
    pub Primes: slice<big::Int>,
    /// Precomputed values that speed up RSA operations. Generated by
    /// `Precompute`; must not be modified afterwards.
    pub Precomputed: PrecomputedValues,
}

impl PrivateKey {
    /// `(*PrivateKey).Public()` (Go: rsa.go:119) — the public key
    /// corresponding to `self`.
    pub fn Public(&self) -> PublicKey {
        self.PublicKey.clone()
    }

    /// `(*PrivateKey).Equal(x)` (Go: rsa.go:125) — reports whether
    /// `self` and `x` have equivalent values. Ignores `Precomputed`.
    pub fn Equal(&self, x: &PrivateKey) -> bool {
        if !self.PublicKey.Equal(&x.PublicKey) || !bigIntEqual(&self.D, &x.D) {
            return false;
        }
        if self.Primes.Len() != x.Primes.Len() {
            return false;
        }
        let mut i: int = 0;
        while i < self.Primes.Len() {
            if !bigIntEqual(&self.Primes[i], &x.Primes[i]) {
                return false;
            }
            i += 1;
        }
        true
    }

    /// `(*PrivateKey).Precompute()` (Go: rsa.go:507) — perform
    /// calculations that speed up future private-key operations. Safe to
    /// run on non-validated keys. For a 2-prime key this fills `Dp`,
    /// `Dq` and `Qinv`; `CRTValues` stays empty.
    pub fn Precompute(&mut self) {
        match self.precompute() {
            Ok(pre) => self.Precomputed = pre,
            // Go: no way to report errors here — leave the key
            // unmodified; Validate will re-run precompute.
            Err(_) => {}
        }
    }

    /// `(*PrivateKey).precompute()` (Go: rsa.go:521) — the worker behind
    /// `Precompute` / `Validate`. Returns the freshly computed values or
    /// an error describing what is missing.
    fn precompute(&self) -> Result<PrecomputedValues, error> {
        if self.PublicKey.N == crate::nilval::nil {
            return Err(errors::New("crypto/rsa: missing public modulus"));
        }
        if self.D == crate::nilval::nil {
            return Err(errors::New("crypto/rsa: missing private exponent"));
        }
        if self.Primes.Len() != 2 {
            return self.precomputeLegacy();
        }

        let one = big::NewInt(1);
        let mut pre = PrecomputedValues::default();

        // Dp = D mod (P-1)
        let mut pminus1 = big::Int::new();
        pminus1.Sub(&self.Primes[0], &one);
        if pminus1.Sign() <= 0 {
            return Err(errors::New("crypto/rsa: prime factor is <= 1"));
        }
        pre.Dp.Mod(&self.D, &pminus1);

        // Dq = D mod (Q-1)
        let mut qminus1 = big::Int::new();
        qminus1.Sub(&self.Primes[1], &one);
        if qminus1.Sign() <= 0 {
            return Err(errors::New("crypto/rsa: prime factor is <= 1"));
        }
        pre.Dq.Mod(&self.D, &qminus1);

        // Qinv = Q⁻¹ mod P
        pre.Qinv.ModInverse(&self.Primes[1], &self.Primes[0]);
        // ModInverse leaves the receiver unchanged (0) when the operands
        // are not coprime.
        if pre.Qinv.Sign() == 0 {
            return Err(errors::New(
                "crypto/rsa: prime factors are not relatively prime",
            ));
        }

        pre.CRTValues = slice::<CRTValue>::new();
        Ok(pre)
    }

    /// `(*PrivateKey).precomputeLegacy()` (Go: rsa.go:569) — multi-prime
    /// (>2 primes) precompute path. Deprecated; kept for API parity.
    fn precomputeLegacy(&self) -> Result<PrecomputedValues, error> {
        let mut pre = PrecomputedValues::default();
        if self.Primes.Len() < 2 {
            // Go: a key with d alone but no primes — return empty.
            pre.CRTValues = slice::<CRTValue>::new();
            return Ok(pre);
        }

        let one = big::NewInt(1);
        let mut i: int = 0;
        while i < self.Primes.Len() {
            if self.Primes[i].Cmp(&one) <= 0 {
                return Err(errors::New("crypto/rsa: prime factor is <= 1"));
            }
            i += 1;
        }

        // Dp = D mod (P-1)
        let mut pminus1 = big::Int::new();
        pminus1.Sub(&self.Primes[0], &one);
        pre.Dp.Mod(&self.D, &pminus1);

        // Dq = D mod (Q-1)
        let mut qminus1 = big::Int::new();
        qminus1.Sub(&self.Primes[1], &one);
        pre.Dq.Mod(&self.D, &qminus1);

        // Qinv = Q⁻¹ mod P
        pre.Qinv.ModInverse(&self.Primes[1], &self.Primes[0]);
        if pre.Qinv.Sign() == 0 {
            return Err(errors::New(
                "crypto/rsa: prime factors are not relatively prime",
            ));
        }

        // CRT values for the 3rd and subsequent primes.
        let mut crt: alloc::vec::Vec<CRTValue> = alloc::vec::Vec::new();
        let mut r = big::Int::new();
        r.Mul(&self.Primes[0], &self.Primes[1]);
        let mut idx: int = 2;
        while idx < self.Primes.Len() {
            let prime = &self.Primes[idx];
            let mut v = CRTValue::default();

            // Exp = D mod (prime-1)
            let mut prime_m1 = big::Int::new();
            prime_m1.Sub(prime, &one);
            v.Exp.Mod(&self.D, &prime_m1);

            // R = product of prior primes
            v.R.Set(&r);

            // Coeff = R⁻¹ mod prime
            v.Coeff.ModInverse(&r, prime);
            if v.Coeff.Sign() == 0 {
                return Err(errors::New(
                    "crypto/rsa: prime factors are not relatively prime",
                ));
            }

            let r_next = {
                let mut t = big::Int::new();
                t.Mul(&r, prime);
                t
            };
            r = r_next;
            crt.push(v);
            idx += 1;
        }
        pre.CRTValues = slice::<CRTValue>::__from_vec(crt);
        Ok(pre)
    }

    /// `(*PrivateKey).Validate()` (Go: rsa.go:230) — basic sanity checks
    /// on the key. Returns `nil` (the polymorphic nil error) if the key
    /// is valid, or an error describing the problem.
    pub fn Validate(&self) -> error {
        if self.Primes.Len() < 2 {
            return errors::New("crypto/rsa: missing primes");
        }
        // Run the full precompute as the validity check (Go's Validate
        // does the same via priv.precompute()).
        match self.precompute() {
            Ok(_) => {}
            Err(e) => return e,
        }

        // Cross-check the key relations. Go offloads these to
        // bigmod's checkPrivateKey; we reproduce the essential ones
        // directly on big::Int.
        let one = big::NewInt(1);

        // N must equal the product of the primes.
        let mut prod = big::NewInt(1);
        let mut i: int = 0;
        while i < self.Primes.Len() {
            let mut t = big::Int::new();
            t.Mul(&prod, &self.Primes[i]);
            prod = t;
            i += 1;
        }
        if prod.Cmp(&self.PublicKey.N) != 0 {
            return errors::New("crypto/rsa: invalid modulus");
        }

        // For each prime p, e·d ≡ 1 mod (p-1).
        let mut e = big::Int::new();
        e.SetInt64(self.PublicKey.E as i64);
        let mut j: int = 0;
        while j < self.Primes.Len() {
            let mut pminus1 = big::Int::new();
            pminus1.Sub(&self.Primes[j], &one);
            // de = (e·d) mod (p-1)
            let mut ed = big::Int::new();
            ed.Mul(&e, &self.D);
            let mut de = big::Int::new();
            de.Mod(&ed, &pminus1);
            if de.Cmp(&one) != 0 {
                return errors::New("crypto/rsa: invalid exponents");
            }
            j += 1;
        }

        errors::nil
    }
}

// ─── bigIntEqual (Go: rsa.go:146) ─────────────────────────────────────

/// Reports whether `a` and `b` are equal. Go does this in (near-)
/// constant time over the byte encodings; goish compares the `big::Int`
/// values directly — equally correct, not constant-time.
fn bigIntEqual(a: &big::Int, b: &big::Int) -> bool {
    a.Cmp(b) == 0
}

// ─── Error sentinels (Go: rsa.go:495-503) ─────────────────────────────

crate::var! {
    /// `rsa.ErrMessageTooLong` — returned when a message is too large
    /// for the RSA key size (also for an over-large PSS salt).
    pub ErrMessageTooLong: error = "crypto/rsa: message too long for RSA key size";

    /// `rsa.ErrDecryption` — a failure to decrypt a message.
    /// Deliberately vague to avoid adaptive attacks.
    pub ErrDecryption: error = "crypto/rsa: decryption error";

    /// `rsa.ErrVerification` — a failure to verify a signature.
    /// Deliberately vague to avoid adaptive attacks.
    pub ErrVerification: error = "crypto/rsa: verification error";
}

// ─── Key generation (Go: rsa.go:278 + keygen.go) ──────────────────────

/// `rsa.GenerateKey(random, bits)` (Go: rsa.go:278) — generate a random
/// 2-prime RSA private key of the given bit size.
///
/// `random` is the randomness source; pass `crypto/rand`'s reader. The
/// returned key does not depend deterministically on the bytes read.
///
/// goish models Go's `(*PrivateKey, error)` return as a tuple. On
/// failure the first element is a default `PrivateKey` and the error is
/// non-nil.
///
/// Algorithm (mirrors crypto/internal/fips140/rsa/keygen.go): pick two
/// random primes `p`, `q` of sizes `(bits+1)/2` and `bits/2`; require
/// `p != q` and `BitLen(p·q) == bits`; set `E = 65537`; compute
/// `D = E⁻¹ mod λ(N)` where `λ(N) = lcm(p-1, q-1)` — retry the whole
/// process on any failure. `Precompute` is then run on the result.
pub fn GenerateKey(random: &mut dyn crate::io::Reader, bits: int) -> (PrivateKey, error) {
    if bits < 32 {
        // Go's checkKeySize rejects <1024; the internal fips keygen
        // rejects <32. We allow small keys (the smoke test uses 512)
        // but still need a usable minimum for two distinct primes.
        return (
            PrivateKey::default(),
            errors::New("crypto/rsa: key too small"),
        );
    }

    let one = big::NewInt(1);

    loop {
        // Two random primes. Go splits as (bits+1)/2 and bits/2.
        let pbits = (bits + 1) / 2;
        let qbits = bits / 2;

        let (p, perr) = randomPrime(random, pbits);
        if perr != crate::nilval::nil {
            return (PrivateKey::default(), perr);
        }
        let (q, qerr) = randomPrime(random, qbits);
        if qerr != crate::nilval::nil {
            return (PrivateKey::default(), qerr);
        }

        // p == q means the random source is broken — retry.
        if p.Cmp(&q) == 0 {
            continue;
        }

        // N = p·q
        let mut n = big::Int::new();
        n.Mul(&p, &q);
        if n.BitLen() != bits {
            // crypto/rand sets the top two bits of each prime so this
            // should not happen for 2-prime keys, but be defensive.
            continue;
        }

        // λ(N) = lcm(p-1, q-1) = (p-1)·(q-1) / gcd(p-1, q-1).
        let mut pm1 = big::Int::new();
        pm1.Sub(&p, &one);
        let mut qm1 = big::Int::new();
        qm1.Sub(&q, &one);

        let mut g = big::Int::new();
        g.GCD(crate::nilval::nil, crate::nilval::nil, &pm1, &qm1);
        if g.Sign() == 0 {
            continue;
        }
        // lcm = (pm1 / g) · qm1
        let mut prod = big::Int::new();
        prod.Mul(&pm1, &qm1);
        let mut lambda = big::Int::new();
        lambda.Div(&prod, &g);

        // E = 65537, D = E⁻¹ mod λ(N).
        let e_val: int = 65537;
        let mut e = big::Int::new();
        e.SetInt64(e_val as i64);
        let mut d = big::Int::new();
        d.ModInverse(&e, &lambda);
        if d.Sign() == 0 {
            // gcd(E, λ(N)) != 1 — 65537 divides one of p-1/q-1.
            // Probability ~1/65537; retry the whole process.
            continue;
        }
        // Sanity: e·d ≡ 1 mod λ(N).
        {
            let mut ed = big::Int::new();
            ed.Mul(&e, &d);
            let mut r = big::Int::new();
            r.Mod(&ed, &lambda);
            if r.Cmp(&one) != 0 {
                continue;
            }
        }

        let mut primes: alloc::vec::Vec<big::Int> = alloc::vec::Vec::with_capacity(2);
        primes.push(p);
        primes.push(q);

        let mut key = PrivateKey {
            PublicKey: PublicKey { N: n, E: e_val },
            D: d,
            Primes: slice::<big::Int>::__from_vec(primes),
            Precomputed: PrecomputedValues::default(),
        };
        key.Precompute();
        return (key, errors::nil);
    }
}

/// `rsa.GenerateMultiPrimeKey(random, nprimes, bits)` (Go: rsa.go:389).
///
/// goish only implements the 2-prime path: for `nprimes == 2` this
/// delegates to `GenerateKey`. Multi-prime (>2) key generation is
/// deprecated in Go and not implemented here — it returns an error.
pub fn GenerateMultiPrimeKey(
    random: &mut dyn crate::io::Reader,
    nprimes: int,
    bits: int,
) -> (PrivateKey, error) {
    if nprimes == 2 {
        return GenerateKey(random, bits);
    }
    if nprimes < 2 {
        return (
            PrivateKey::default(),
            errors::New("crypto/rsa: GenerateMultiPrimeKey: nprimes must be >= 2"),
        );
    }
    (
        PrivateKey::default(),
        errors::New("crypto/rsa: multi-prime key generation is not implemented"),
    )
}

/// Generate a random probable prime of `bits` bits whose top two bits
/// are set (so the product of two such primes is exactly `2·bits`).
///
/// Mirrors `crypto/internal/fips140/rsa/keygen.go`'s `randomPrime`: read
/// random bytes, clear the excess high bits, force the top two bits and
/// the low bit, then test primality with `ProbablyPrime`. Retry until a
/// prime is found. Not constant-time (Go's `randomPrime` isn't either).
fn randomPrime(random: &mut dyn crate::io::Reader, bits: int) -> (big::Int, error) {
    if bits < 8 {
        return (
            big::Int::new(),
            errors::New("crypto/rsa: prime size too small"),
        );
    }
    let nbytes = ((bits + 7) / 8) as usize;

    loop {
        // Draw random bytes through the supplied io.Reader.
        let mut buf: alloc::vec::Vec<crate::types::byte> = alloc::vec![0u8; nbytes];
        let mut got: int = 0;
        while (got as usize) < nbytes {
            let mut chunk = slice::<crate::types::byte>::__from_vec(alloc::vec![
                0u8;
                nbytes - got as usize
            ]);
            let (n, rerr) = random.Read(&mut chunk);
            if rerr != crate::nilval::nil {
                return (big::Int::new(), rerr);
            }
            if n <= 0 {
                return (
                    big::Int::new(),
                    errors::New("crypto/rsa: short read from random source"),
                );
            }
            let mut k: int = 0;
            while k < n {
                buf[(got + k) as usize] = chunk[k];
                k += 1;
            }
            got += n;
        }

        // Clear the most-significant excess bits down to `bits`.
        let excess = nbytes * 8 - (bits as usize);
        buf[0] &= 0b1111_1111u8 >> excess;
        // Force the top two bits so the value is large enough that the
        // product of two primes is never a bit short.
        if excess < 7 {
            buf[0] |= 0b1100_0000u8 >> excess;
        } else {
            buf[0] |= 0b0000_0001u8;
            buf[1] |= 0b1000_0000u8;
        }
        // Make the candidate odd.
        buf[nbytes - 1] |= 1;

        let mut cand = big::Int::new();
        cand.SetBytes(slice::<crate::types::byte>::__from_vec(buf.clone()));

        // 20 Miller-Rabin rounds (Go's big.ProbablyPrime convention).
        if cand.ProbablyPrime(20) {
            return (cand, errors::nil);
        }
    }
}

// ─── Raw RSA primitives ───────────────────────────────────────────────
//
// These are the module-private math used by the PKCS#1 v1.5 and OAEP/PSS
// layers built in later tasks. They operate on `big::Int` values, not
// byte slices — the padding layers handle the byte<->integer conversion.

/// Raw RSA public-key operation: `encrypt(pub, m) = m^E mod N`.
///
/// Signature: `pub(crate) fn encrypt(pub_key: &PublicKey, m: &big::Int) -> big::Int`.
///
/// The caller must ensure `0 <= m < N`; the result is reduced mod `N`.
/// Mirrors `crypto/internal/fips140/rsa/rsa.go`'s `encrypt` (which uses
/// `ExpShortVarTime` over bigmod — here plain `big::Int::Exp`).
pub(crate) fn encrypt(pub_key: &PublicKey, m: &big::Int) -> big::Int {
    let mut e = big::Int::new();
    e.SetInt64(pub_key.E as i64);
    let mut c = big::Int::new();
    c.Exp(m, &e, &pub_key.N);
    c
}

/// Raw RSA private-key operation: `decrypt(priv, random, c)` computes
/// `c^D mod N`, via the CRT path with RSA blinding.
///
/// Signature:
/// `pub(crate) fn decrypt(priv_key: &PrivateKey, random: &mut dyn crate::io::Reader,
///                        c: &big::Int) -> (big::Int, crate::error)`.
///
/// Returns `(m, nil)` on success or `(default, ErrDecryption)` if `c` is
/// out of range. Mirrors `crypto/rsa`'s historic `decrypt`:
///
///   * RSA blinding — pick a random `r` coprime to `N`, multiply the
///     ciphertext by `r^E mod N` before the private operation, and undo
///     it afterwards with `r⁻¹ mod N`. This decouples the secret
///     exponent's timing from the attacker-chosen ciphertext.
///   * CRT decrypt — `m1 = c'^Dp mod P`, `m2 = c'^Dq mod Q`,
///     `h = Qinv·(m1 - m2) mod P`, `m = m2 + h·Q`.
///
/// `Precompute` must have been run (Dp/Dq/Qinv populated); if it has not,
/// the function falls back to the plain `c^D mod N` path.
pub(crate) fn decrypt(
    priv_key: &PrivateKey,
    random: &mut dyn crate::io::Reader,
    c: &big::Int,
) -> (big::Int, error) {
    let n = &priv_key.PublicKey.N;

    // Reject ciphertext outside [0, N).
    if c.Sign() < 0 || c.Cmp(n) >= 0 {
        return (big::Int::default(), ErrDecryption.into());
    }

    // ── RSA blinding ──────────────────────────────────────────────
    // Pick random r in (1, N) with gcd(r, N) == 1; compute
    // ir = r⁻¹ mod N. Blind:  cBlinded = c · r^E mod N.
    let one = big::NewInt(1);
    let mut r = big::Int::new();
    let mut ir = big::Int::new();
    let mut blinded = false;

    // Number of bytes to draw for r — same width as the modulus.
    let nbytes = ((n.BitLen() + 7) / 8) as usize;
    if nbytes > 0 {
        let mut attempts = 0;
        while attempts < 64 {
            attempts += 1;
            let mut buf = slice::<crate::types::byte>::__from_vec(alloc::vec![0u8; nbytes]);
            let (rn, rerr) = random.Read(&mut buf);
            if rerr != crate::nilval::nil || rn <= 0 {
                // Could not get randomness — proceed without blinding.
                break;
            }
            let mut cand = big::Int::new();
            cand.SetBytes(buf);
            // r must be reduced into (1, N).
            let mut rr = big::Int::new();
            rr.Mod(&cand, n);
            if rr.Cmp(&one) <= 0 {
                continue;
            }
            // ir = r⁻¹ mod N must exist (gcd(r, N) == 1).
            let mut inv = big::Int::new();
            inv.ModInverse(&rr, n);
            if inv.Sign() == 0 {
                continue;
            }
            r.Set(&rr);
            ir.Set(&inv);
            blinded = true;
            break;
        }
    }

    // cWork = blinded ciphertext (or plain c when blinding unavailable).
    let mut c_work = big::Int::new();
    if blinded {
        // rpowe = r^E mod N
        let mut e = big::Int::new();
        e.SetInt64(priv_key.PublicKey.E as i64);
        let mut rpowe = big::Int::new();
        rpowe.Exp(&r, &e, n);
        // cWork = c · rpowe mod N
        let mut t = big::Int::new();
        t.Mul(c, &rpowe);
        c_work.Mod(&t, n);
    } else {
        c_work.Set(c);
    }

    // ── Private operation ─────────────────────────────────────────
    let pre = &priv_key.Precomputed;
    let have_crt = priv_key.Primes.Len() == 2
        && pre.Dp != crate::nilval::nil
        && pre.Dq != crate::nilval::nil
        && pre.Qinv != crate::nilval::nil;

    let mut m = big::Int::new();
    if have_crt {
        let p = &priv_key.Primes[0];
        let q = &priv_key.Primes[1];

        // m1 = cWork^Dp mod P
        let mut cp = big::Int::new();
        cp.Mod(&c_work, p);
        let mut m1 = big::Int::new();
        m1.Exp(&cp, &pre.Dp, p);

        // m2 = cWork^Dq mod Q
        let mut cq = big::Int::new();
        cq.Mod(&c_work, q);
        let mut m2 = big::Int::new();
        m2.Exp(&cq, &pre.Dq, q);

        // h = Qinv · (m1 - m2) mod P
        let mut diff = big::Int::new();
        diff.Sub(&m1, &m2);
        let mut dmod = big::Int::new();
        dmod.Mod(&diff, p); // Mod yields a non-negative result
        let mut hp = big::Int::new();
        hp.Mul(&pre.Qinv, &dmod);
        let mut h = big::Int::new();
        h.Mod(&hp, p);

        // m = m2 + h·Q
        let mut hq = big::Int::new();
        hq.Mul(&h, q);
        m.Add(&m2, &hq);
    } else {
        // Fallback: m = cWork^D mod N (no CRT). Used for keys whose
        // Precompute has not run, or deprecated multi-prime keys.
        m.Exp(&c_work, &priv_key.D, n);
    }

    // ── Unblind ───────────────────────────────────────────────────
    if blinded {
        let mut t = big::Int::new();
        t.Mul(&m, &ir);
        let mut un = big::Int::new();
        un.Mod(&t, n);
        m = un;
    }

    (m, errors::nil)
}

// ─── Test shims ───────────────────────────────────────────────────────
//
// The raw `encrypt` / `decrypt` primitives are `pub(crate)` — only the
// later PKCS#1 v1.5 and OAEP/PSS layers (inside this crate) call them.
// These thin `pub` wrappers exist solely so the e2e smoke test, which
// lives in a separate crate, can exercise the round-trip directly. They
// are not part of the Go-facing API surface.

/// Test-only public wrapper around the module-private `encrypt`.
#[doc(hidden)]
pub fn __test_encrypt(pub_key: &PublicKey, m: &big::Int) -> big::Int {
    encrypt(pub_key, m)
}

/// Test-only public wrapper around the module-private `decrypt`.
#[doc(hidden)]
pub fn __test_decrypt(
    priv_key: &PrivateKey,
    random: &mut dyn crate::io::Reader,
    c: &big::Int,
) -> (big::Int, error) {
    decrypt(priv_key, random, c)
}
