// crypto/rsa — port of Go 1.25's `crypto/rsa` package.
//
// This is the PUBLIC `crypto/rsa` surface: a thin wrapper over the
// constant-time FIPS-internal RSA implementation at
// `crate::crypto::internal::fips140::rsa`.
//
// Strategy
// --------
// Go 1.25's `crypto/rsa` package keeps the *public* key types built on
// `math/big` (`PublicKey { N *big.Int; E int }`, `PrivateKey { D, Primes
// []*big.Int }`) for backwards compatibility, but performs every actual
// RSA operation by converting the key material into the FIPS-internal
// `crypto/internal/fips140/rsa` key types (whose modulus is a
// constant-time `bigmod.Modulus`). This module mirrors that bridge
// exactly — see Go's `crypto/rsa/fips.go`.
//
// The conversion is one-directional at each call: build a fips
// `PublicKey`/`PrivateKey` from the public key's `big.Int.Bytes()`
// encodings, dispatch into `fips140::rsa`, and translate the result.
//
// Mirrors crypto/rsa/rsa.go's data shapes:
//
//   type PublicKey struct { N *big.Int; E int }
//   type PrivateKey struct {
//       PublicKey               // embedded
//       D           *big.Int
//       Primes      []*big.Int
//       Precomputed PrecomputedValues
//   }

#![allow(non_snake_case, non_upper_case_globals)]

extern crate alloc;

use crate::error;
use crate::errors;
use crate::math::big;
use crate::slice;
use crate::types::{byte, int};

use crate::crypto::internal::fips140::rsa as fips;

// ─── PublicKey (Go: rsa.go:68) ────────────────────────────────────────

/// A `PublicKey` represents the public part of an RSA key.
///
/// The values of `N` and `E` are not considered confidential.
#[derive(Clone, Default)]
pub struct PublicKey {
    /// Modulus.
    pub N: big::Int,
    /// Public exponent.
    pub E: int,
}

// Polymorphic-nil for `*rsa.PublicKey`. Go callers pass nil pointers
// occasionally; in goish the natural model is a default-valued struct,
// matched by the per-type Nil impls.
impl PartialEq<crate::nilval::Nil> for PublicKey {
    fn eq(&self, _: &crate::nilval::Nil) -> bool {
        self.N == crate::nilval::nil && self.E == 0
    }
}
impl PartialEq<PublicKey> for crate::nilval::Nil {
    fn eq(&self, other: &PublicKey) -> bool {
        other.N == crate::nilval::nil && other.E == 0
    }
}
impl From<crate::nilval::Nil> for PublicKey {
    fn from(_: crate::nilval::Nil) -> Self {
        PublicKey::default()
    }
}

impl PublicKey {
    /// `(*PublicKey).Size()` (Go: rsa.go:78) — modulus size in bytes.
    /// Raw signatures and ciphertexts for or by this key share this size.
    pub fn Size(&self) -> int {
        (self.N.BitLen() + 7) / 8
    }

    /// `(*PublicKey).Equal(x)` (Go: rsa.go:83) — reports whether `self`
    /// and `x` have the same value.
    pub fn Equal(&self, x: &PublicKey) -> bool {
        bigIntEqual(&self.N, &x.N) && self.E == x.E
    }
}

// ─── CRTValue / PrecomputedValues (Go: rsa.go:201-224) ────────────────

/// `CRTValue` contains the precomputed Chinese-remainder-theorem values
/// for the 3rd and subsequent primes of a multi-prime key.
#[derive(Clone, Default)]
pub struct CRTValue {
    /// `D mod (prime-1)`.
    pub Exp: big::Int,
    /// `R·Coeff ≡ 1 mod Prime`.
    pub Coeff: big::Int,
    /// Product of primes prior to this (including p and q).
    pub R: big::Int,
}

/// `PrecomputedValues` holds values that speed up RSA private-key
/// operations. It is generated by `PrivateKey::Precompute`.
#[derive(Clone, Default)]
pub struct PrecomputedValues {
    /// `D mod (P-1)`.
    pub Dp: big::Int,
    /// `D mod (Q-1)`.
    pub Dq: big::Int,
    /// `Q⁻¹ mod P`.
    pub Qinv: big::Int,
    /// CRT values for the 3rd and subsequent primes.
    ///
    /// Deprecated: still filled in by `Precompute` for backwards
    /// compatibility but not used. For ordinary 2-prime keys this stays
    /// empty; the type is defined for API parity with Go.
    pub CRTValues: slice<CRTValue>,
}

// ─── PrivateKey (Go: rsa.go:107) ──────────────────────────────────────

/// A `PrivateKey` represents an RSA key.
///
/// Go embeds `PublicKey` anonymously; goish has no struct embedding, so
/// the public part is a field literally named `PublicKey`. Read it as
/// `priv.PublicKey.N` (Go's `priv.N` reaches the same field via
/// promotion).
#[derive(Clone, Default)]
pub struct PrivateKey {
    /// Public part of the key.
    pub PublicKey: PublicKey,
    /// Private exponent.
    pub D: big::Int,
    /// Prime factors of `N`; has >= 2 elements.
    pub Primes: slice<big::Int>,
    /// Precomputed values that speed up RSA operations. Generated by
    /// `Precompute`; must not be modified afterwards.
    pub Precomputed: PrecomputedValues,
}

impl PrivateKey {
    /// `(*PrivateKey).Public()` (Go: rsa.go:119) — the public key
    /// corresponding to `self`.
    pub fn Public(&self) -> PublicKey {
        self.PublicKey.clone()
    }

    /// `(*PrivateKey).Equal(x)` (Go: rsa.go:125) — reports whether
    /// `self` and `x` have equivalent values. Ignores `Precomputed`.
    pub fn Equal(&self, x: &PrivateKey) -> bool {
        if !self.PublicKey.Equal(&x.PublicKey) || !bigIntEqual(&self.D, &x.D) {
            return false;
        }
        if self.Primes.Len() != x.Primes.Len() {
            return false;
        }
        let mut i: int = 0;
        while i < self.Primes.Len() {
            if !bigIntEqual(&self.Primes[i], &x.Primes[i]) {
                return false;
            }
            i += 1;
        }
        true
    }

    /// `(*PrivateKey).Precompute()` (Go: rsa.go:507) — perform
    /// calculations that speed up future private-key operations. Safe to
    /// run on non-validated keys. For a 2-prime key this fills `Dp`,
    /// `Dq` and `Qinv`; `CRTValues` stays empty.
    pub fn Precompute(&mut self) {
        match self.precompute() {
            Ok(pre) => self.Precomputed = pre,
            // Go: no way to report errors here — leave the key
            // unmodified; Validate will re-run precompute.
            Err(_) => {}
        }
    }

    /// `(*PrivateKey).precompute()` (Go: rsa.go:521) — the worker behind
    /// `Precompute` / `Validate`. Builds the FIPS-internal key (which
    /// runs the constant-time validity checks) and reads the CRT values
    /// back out of it via `Export()`.
    fn precompute(&self) -> Result<PrecomputedValues, error> {
        if self.PublicKey.N == crate::nilval::nil {
            return Err(errors::New("crypto/rsa: missing public modulus"));
        }
        if self.D == crate::nilval::nil {
            return Err(errors::New("crypto/rsa: missing private exponent"));
        }
        if self.Primes.Len() != 2 {
            return self.precomputeLegacy();
        }

        // If the CRT values are already set, validate them through the
        // FIPS constructor that takes the precomputation directly.
        let have_pre = self.Precomputed.Dp != crate::nilval::nil
            && self.Precomputed.Dq != crate::nilval::nil
            && self.Precomputed.Qinv != crate::nilval::nil;
        if have_pre {
            let (_, err) = fips::NewPrivateKeyWithPrecomputation(
                self.PublicKey.N.Bytes(),
                self.PublicKey.E,
                self.D.Bytes(),
                self.Primes[0].Bytes(),
                self.Primes[1].Bytes(),
                self.Precomputed.Dp.Bytes(),
                self.Precomputed.Dq.Bytes(),
                self.Precomputed.Qinv.Bytes(),
            );
            if err != crate::nilval::nil {
                return Err(err);
            }
            let mut pre = self.Precomputed.clone();
            pre.CRTValues = slice::<CRTValue>::new();
            return Ok(pre);
        }

        // No CRT values yet — let the FIPS constructor compute them.
        let (k, err) = fips::NewPrivateKey(
            self.PublicKey.N.Bytes(),
            self.PublicKey.E,
            self.D.Bytes(),
            self.Primes[0].Bytes(),
            self.Primes[1].Bytes(),
        );
        if err != crate::nilval::nil {
            return Err(err);
        }

        let (_n, _e, _d, _p, _q, dP, dQ, qInv) = k.Export();
        let mut pre = PrecomputedValues::default();
        pre.Dp.SetBytes(dP);
        pre.Dq.SetBytes(dQ);
        pre.Qinv.SetBytes(qInv);
        pre.CRTValues = slice::<CRTValue>::new();
        Ok(pre)
    }

    /// `(*PrivateKey).precomputeLegacy()` (Go: rsa.go:569) — multi-prime
    /// (>2 primes) precompute path. Deprecated; kept for API parity. The
    /// FIPS layer is built around 2-prime CRT keys, so the legacy path
    /// is computed directly on `big::Int` (matching Go's own legacy
    /// branch, which does the same).
    fn precomputeLegacy(&self) -> Result<PrecomputedValues, error> {
        let mut pre = PrecomputedValues::default();
        if self.Primes.Len() < 2 {
            // Go: a key with d alone but no primes — return empty.
            pre.CRTValues = slice::<CRTValue>::new();
            return Ok(pre);
        }

        let one = big::NewInt(1);
        let mut i: int = 0;
        while i < self.Primes.Len() {
            if self.Primes[i].Cmp(&one) <= 0 {
                return Err(errors::New("crypto/rsa: prime factor is <= 1"));
            }
            i += 1;
        }

        // Dp = D mod (P-1)
        let mut pminus1 = big::Int::new();
        pminus1.Sub(&self.Primes[0], &one);
        pre.Dp.Mod(&self.D, &pminus1);

        // Dq = D mod (Q-1)
        let mut qminus1 = big::Int::new();
        qminus1.Sub(&self.Primes[1], &one);
        pre.Dq.Mod(&self.D, &qminus1);

        // Qinv = Q⁻¹ mod P
        pre.Qinv.ModInverse(&self.Primes[1], &self.Primes[0]);
        if pre.Qinv.Sign() == 0 {
            return Err(errors::New(
                "crypto/rsa: prime factors are not relatively prime",
            ));
        }

        // CRT values for the 3rd and subsequent primes.
        let mut crt: alloc::vec::Vec<CRTValue> = alloc::vec::Vec::new();
        let mut r = big::Int::new();
        r.Mul(&self.Primes[0], &self.Primes[1]);
        let mut idx: int = 2;
        while idx < self.Primes.Len() {
            let prime = &self.Primes[idx];
            let mut v = CRTValue::default();

            // Exp = D mod (prime-1)
            let mut prime_m1 = big::Int::new();
            prime_m1.Sub(prime, &one);
            v.Exp.Mod(&self.D, &prime_m1);

            // R = product of prior primes
            v.R.Set(&r);

            // Coeff = R⁻¹ mod prime
            v.Coeff.ModInverse(&r, prime);
            if v.Coeff.Sign() == 0 {
                return Err(errors::New(
                    "crypto/rsa: prime factors are not relatively prime",
                ));
            }

            let r_next = {
                let mut t = big::Int::new();
                t.Mul(&r, prime);
                t
            };
            r = r_next;
            crt.push(v);
            idx += 1;
        }
        pre.CRTValues = slice::<CRTValue>::__from_vec(crt);
        Ok(pre)
    }

    /// `(*PrivateKey).Validate()` (Go: rsa.go:230) — basic sanity checks
    /// on the key. Returns `nil` (the polymorphic nil error) if the key
    /// is valid, or an error describing the problem.
    ///
    /// The actual key relations (`N == p·q`, `e·d ≡ 1 mod λ`, …) are
    /// enforced by the FIPS constructor inside `precompute`, exactly as
    /// Go's `Validate` defers to `precompute`.
    pub fn Validate(&self) -> error {
        if self.Primes.Len() < 2 {
            return errors::New("crypto/rsa: missing primes");
        }
        match self.precompute() {
            Ok(_) => errors::nil,
            Err(e) => e,
        }
    }

    /// `(*PrivateKey).Sign(rand, digest, opts)` (Go: rsa.go:158) — sign
    /// `digest` with this key. If `opts` is a `PSSOptions` the PSS
    /// algorithm is used, otherwise PKCS#1 v1.5.
    ///
    /// Implements `crypto.Signer`.
    pub fn Sign(
        &self,
        rand: &mut dyn crate::io::Reader,
        digest: slice<byte>,
        opts: &dyn crate::crypto::SignerOpts,
    ) -> (slice<byte>, error) {
        // Go switches on `opts.(*PSSOptions)`; goish has no concrete-type
        // switch over `&dyn SignerOpts`, but `PSSOptions` carries its
        // salt length via its own `HashFunc`-providing path. A caller
        // wanting PSS uses `SignPSS` directly; `Sign` here implements the
        // PKCS#1 v1.5 path of the `crypto.Signer` interface.
        SignPKCS1v15(rand, self, opts.HashFunc(), digest)
    }

    /// `(*PrivateKey).Decrypt(rand, ciphertext, opts)` (Go: rsa.go:169) —
    /// decrypt `ciphertext`. With `opts == None` or `PKCS1v15DecryptOptions`
    /// PKCS#1 v1.5 decryption is performed; with `OAEPOptions`, OAEP.
    ///
    /// Implements `crypto.Decrypter`.
    pub fn Decrypt(
        &self,
        rand: &mut dyn crate::io::Reader,
        ciphertext: slice<byte>,
        opts: Option<&crate::crypto::DecrypterOpts>,
    ) -> (slice<byte>, error) {
        let opts = match opts {
            None => return DecryptPKCS1v15(rand, self, ciphertext),
            Some(o) => o,
        };
        if let Some(o) = opts.downcast_ref::<OAEPOptions>() {
            let mgf = if o.MGFHash == 0 { o.Hash } else { o.MGFHash };
            let mut h = crate::crypto::HashNew(o.Hash);
            let mut m = crate::crypto::HashNew(mgf);
            let (fk, err) = fipsPrivateKey(self);
            if err != crate::nilval::nil {
                return (slice::<byte>::new(), err);
            }
            let (out, err) =
                fips::DecryptOAEP(h.as_mut(), m.as_mut(), &fk, ciphertext, o.Label.clone());
            h.Reset();
            m.Reset();
            return (out, mapFipsError(err));
        }
        if let Some(o) = opts.downcast_ref::<PKCS1v15DecryptOptions>() {
            let l = o.SessionKeyLen;
            if l > 0 {
                let ln = usize::try_from(l).unwrap_or(0);
                let mut plaintext =
                    slice::<byte>::__from_vec(alloc::vec![0u8; ln]);
                {
                    let (_, err) = crate::io::ReadFull(rand, &mut plaintext);
                    if err != crate::nilval::nil {
                        return (slice::<byte>::new(), err);
                    }
                }
                let err = DecryptPKCS1v15SessionKey(rand, self, ciphertext, &mut plaintext);
                if err != crate::nilval::nil {
                    return (slice::<byte>::new(), err);
                }
                return (plaintext, errors::nil);
            }
            return DecryptPKCS1v15(rand, self, ciphertext);
        }
        (
            slice::<byte>::new(),
            errors::New("crypto/rsa: invalid options for Decrypt"),
        )
    }
}

// ─── crypto.Signer / crypto.Decrypter impls ───────────────────────────

impl crate::crypto::Signer for PrivateKey {
    fn Public(&self) -> crate::crypto::PublicKey {
        alloc::boxed::Box::new(self.PublicKey.clone())
    }
    fn Sign(
        &self,
        rand: &mut dyn crate::io::Reader,
        digest: slice<byte>,
        opts: &dyn crate::crypto::SignerOpts,
    ) -> (slice<byte>, error) {
        PrivateKey::Sign(self, rand, digest, opts)
    }
}

impl crate::crypto::Decrypter for PrivateKey {
    fn Public(&self) -> crate::crypto::PublicKey {
        alloc::boxed::Box::new(self.PublicKey.clone())
    }
    fn Decrypt(
        &self,
        rand: &mut dyn crate::io::Reader,
        msg: slice<byte>,
        opts: Option<&crate::crypto::DecrypterOpts>,
    ) -> (slice<byte>, error) {
        PrivateKey::Decrypt(self, rand, msg, opts)
    }
}

// ─── Option bags (Go: rsa.go:91, pkcs1v15.go:19, pkcs1v15.go:30) ──────

/// `OAEPOptions` (Go: rsa.go:93) — options for OAEP decryption through
/// the `crypto.Decrypter` interface.
#[derive(Clone, Default)]
pub struct OAEPOptions {
    /// Hash function used when generating the mask.
    pub Hash: crate::crypto::Hash,
    /// Hash function used for MGF1. If zero, `Hash` is used instead.
    pub MGFHash: crate::crypto::Hash,
    /// Arbitrary label; must equal the value used when encrypting.
    pub Label: slice<byte>,
}

// `PSSSaltLengthAuto` / `PSSSaltLengthEqualsHash` (Go: pkcs1v15.go:18).

/// Causes the PSS salt to be as large as possible when signing, and to
/// be auto-detected when verifying.
pub const PSSSaltLengthAuto: int = 0;
/// Causes the PSS salt length to equal the hash length.
pub const PSSSaltLengthEqualsHash: int = -1;

/// `PSSOptions` (Go: pkcs1v15.go:31) — options for creating and
/// verifying PSS signatures.
#[derive(Clone, Default)]
pub struct PSSOptions {
    /// Length of the salt: a positive byte count, or one of the
    /// `PSSSaltLength` constants.
    pub SaltLength: int,
    /// Hash function used to generate the digest. If non-zero it
    /// overrides the hash passed to `SignPSS`.
    pub Hash: crate::crypto::Hash,
}

impl PSSOptions {
    /// `(*PSSOptions).HashFunc()` (Go: pkcs1v15.go:44) — returns
    /// `opts.Hash` so `PSSOptions` satisfies `crypto.SignerOpts`.
    pub fn HashFunc(&self) -> crate::crypto::Hash {
        self.Hash
    }

    /// `(*PSSOptions).saltLength()` (Go: pkcs1v15.go:48).
    fn saltLength(&self) -> int {
        self.SaltLength
    }
}

impl crate::crypto::SignerOpts for PSSOptions {
    fn HashFunc(&self) -> crate::crypto::Hash {
        self.Hash
    }
}

/// `PKCS1v15DecryptOptions` (Go: pkcs1v15.go:21) — options for PKCS#1
/// v1.5 decryption through the `crypto.Decrypter` interface.
#[derive(Clone, Default)]
pub struct PKCS1v15DecryptOptions {
    /// Length of the session key being decrypted. If non-zero, a padding
    /// error during decryption returns a random plaintext of this length
    /// rather than an error — in constant time.
    pub SessionKeyLen: int,
}

// ─── bigIntEqual (Go: rsa.go:146) ─────────────────────────────────────

/// Reports whether `a` and `b` are equal.
fn bigIntEqual(a: &big::Int, b: &big::Int) -> bool {
    a.Cmp(b) == 0
}

// ─── Error sentinels (Go: rsa.go:495-503) ─────────────────────────────
//
// Defined fresh here (rather than re-exporting the fips140 sentinels) so
// the public package owns its own identity-stable markers. The bridge
// functions translate the fips errors into these via `mapFipsError`,
// matching Go's `fipsError` in crypto/rsa/fips.go.

crate::var! {
    /// `rsa.ErrMessageTooLong` — returned when a message is too large
    /// for the RSA key size (also for an over-large PSS salt).
    pub ErrMessageTooLong: error = "crypto/rsa: message too long for RSA key size";

    /// `rsa.ErrDecryption` — a failure to decrypt a message.
    /// Deliberately vague to avoid adaptive attacks.
    pub ErrDecryption: error = "crypto/rsa: decryption error";

    /// `rsa.ErrVerification` — a failure to verify a signature.
    /// Deliberately vague to avoid adaptive attacks.
    pub ErrVerification: error = "crypto/rsa: verification error";
}

/// `fipsError` (Go: fips.go:383) — translate a `fips140/rsa` sentinel
/// into the matching public `crypto/rsa` sentinel; pass other errors
/// through unchanged.
fn mapFipsError(err: error) -> error {
    if err == crate::nilval::nil {
        return errors::nil;
    }
    if errors::Is(err.clone(), fips::ErrDecryption) {
        return ErrDecryption.into();
    }
    if errors::Is(err.clone(), fips::ErrVerification) {
        return ErrVerification.into();
    }
    if errors::Is(err.clone(), fips::ErrMessageTooLong) {
        return ErrMessageTooLong.into();
    }
    err
}

// ─── public ↔ fips conversion bridge (Go: rsa.go:624-641) ─────────────

/// `fipsPublicKey` (Go: rsa.go:624) — build a FIPS-internal `PublicKey`
/// from this public key's `big.Int` material.
fn fipsPublicKey(pub_: &PublicKey) -> (fips::PublicKey, error) {
    if pub_.N == crate::nilval::nil {
        let (k, _) = fips::NewPublicKey(slice::<byte>::new(), pub_.E);
        return (k, errors::New("crypto/rsa: missing public modulus"));
    }
    fips::NewPublicKey(pub_.N.Bytes(), pub_.E)
}

/// `fipsPrivateKey` (Go: rsa.go:632) — build a FIPS-internal
/// `PrivateKey`. Uses the precomputed CRT values when present, otherwise
/// recomputes them, exactly like Go's `fipsPrivateKey` → `precompute`.
fn fipsPrivateKey(priv_: &PrivateKey) -> (fips::PrivateKey, error) {
    if priv_.PublicKey.N == crate::nilval::nil {
        return (
            fips::PrivateKey::default(),
            errors::New("crypto/rsa: missing public modulus"),
        );
    }
    if priv_.D == crate::nilval::nil {
        return (
            fips::PrivateKey::default(),
            errors::New("crypto/rsa: missing private exponent"),
        );
    }

    if priv_.Primes.Len() == 2 {
        let have_pre = priv_.Precomputed.Dp != crate::nilval::nil
            && priv_.Precomputed.Dq != crate::nilval::nil
            && priv_.Precomputed.Qinv != crate::nilval::nil;
        if have_pre {
            return fips::NewPrivateKeyWithPrecomputation(
                priv_.PublicKey.N.Bytes(),
                priv_.PublicKey.E,
                priv_.D.Bytes(),
                priv_.Primes[0].Bytes(),
                priv_.Primes[1].Bytes(),
                priv_.Precomputed.Dp.Bytes(),
                priv_.Precomputed.Dq.Bytes(),
                priv_.Precomputed.Qinv.Bytes(),
            );
        }
        return fips::NewPrivateKey(
            priv_.PublicKey.N.Bytes(),
            priv_.PublicKey.E,
            priv_.D.Bytes(),
            priv_.Primes[0].Bytes(),
            priv_.Primes[1].Bytes(),
        );
    }

    // Deprecated multi-prime (or d-only) key: CRT-less FIPS key.
    fips::NewPrivateKeyWithoutCRT(
        priv_.PublicKey.N.Bytes(),
        priv_.PublicKey.E,
        priv_.D.Bytes(),
    )
}

impl Default for fips::PrivateKey {
    fn default() -> Self {
        // A FIPS PrivateKey has no public `Default`; build a trivially
        // invalid one via the CRT-less constructor over an empty modulus
        // (it returns an error key, never used — `fipsPrivateKey` only
        // hits this branch alongside a non-nil error).
        let (k, _) = fips::NewPrivateKeyWithoutCRT(
            slice::<byte>::new(),
            0,
            slice::<byte>::new(),
        );
        k
    }
}

// ─── Key generation (Go: rsa.go:278) ──────────────────────────────────

/// `rsa.GenerateKey(random, bits)` (Go: rsa.go:278) — generate a random
/// 2-prime RSA private key of the given bit size.
///
/// Delegates to `fips140::rsa::GenerateKey`, then `Export()`s the result
/// and rebuilds the public `*big.Int` fields.
///
/// `random` is the randomness source; pass `crypto/rand`'s reader.
pub fn GenerateKey(random: &mut dyn crate::io::Reader, bits: int) -> (PrivateKey, error) {
    let (mut k, mut err) = fips::GenerateKey(random, bits);
    // Toy-sized keys have a non-negligible chance of hitting two hard
    // failure cases (p == q, d <= 2^(nlen/2)); Go reruns up to 8×.
    if bits < 256 && err != crate::nilval::nil {
        let mut i: int = 1;
        while i < 8 && err != crate::nilval::nil {
            let (k2, e2) = fips::GenerateKey(random, bits);
            k = k2;
            err = e2;
            i += 1;
        }
    }
    if err != crate::nilval::nil {
        return (PrivateKey::default(), err);
    }

    let (n, e, d, p, q, dP, dQ, qInv) = k.Export();

    let mut nN = big::Int::new();
    nN.SetBytes(n);
    let mut dD = big::Int::new();
    dD.SetBytes(d);
    let mut pP = big::Int::new();
    pP.SetBytes(p);
    let mut qQ = big::Int::new();
    qQ.SetBytes(q);
    let mut dp = big::Int::new();
    dp.SetBytes(dP);
    let mut dq = big::Int::new();
    dq.SetBytes(dQ);
    let mut qi = big::Int::new();
    qi.SetBytes(qInv);

    let mut primes: alloc::vec::Vec<big::Int> = alloc::vec::Vec::with_capacity(2);
    primes.push(pP);
    primes.push(qQ);

    let key = PrivateKey {
        PublicKey: PublicKey { N: nN, E: e },
        D: dD,
        Primes: slice::<big::Int>::__from_vec(primes),
        Precomputed: PrecomputedValues {
            Dp: dp,
            Dq: dq,
            Qinv: qi,
            CRTValues: slice::<CRTValue>::new(),
        },
    };
    (key, errors::nil)
}

/// `rsa.GenerateMultiPrimeKey(random, nprimes, bits)` (Go: rsa.go:389).
///
/// For `nprimes == 2` this delegates to `GenerateKey`. Multi-prime (>2)
/// key generation is deprecated in Go and not implemented here — it
/// returns an error.
pub fn GenerateMultiPrimeKey(
    random: &mut dyn crate::io::Reader,
    nprimes: int,
    bits: int,
) -> (PrivateKey, error) {
    if nprimes == 2 {
        return GenerateKey(random, bits);
    }
    if nprimes < 2 {
        return (
            PrivateKey::default(),
            errors::New("crypto/rsa: GenerateMultiPrimeKey: nprimes must be >= 2"),
        );
    }
    (
        PrivateKey::default(),
        errors::New("crypto/rsa: multi-prime key generation is not implemented"),
    )
}

// ─── PKCS#1 v1.5 (Go: pkcs1v15.go) ────────────────────────────────────

/// `rsa.EncryptPKCS1v15(random, pub, msg)` (Go: pkcs1v15.go:42) —
/// encrypt `msg` with RSA and PKCS#1 v1.5 padding. `msg` must be no
/// longer than the modulus size minus 11 bytes.
pub fn EncryptPKCS1v15(
    random: &mut dyn crate::io::Reader,
    pub_: &PublicKey,
    msg: slice<byte>,
) -> (slice<byte>, error) {
    let (fk, err) = fipsPublicKey(pub_);
    if err != crate::nilval::nil {
        return (slice::<byte>::new(), err);
    }
    let (out, err) = fips::EncryptPKCS1v15(random, &fk, msg);
    (out, mapFipsError(err))
}

/// `rsa.DecryptPKCS1v15(random, priv, ciphertext)` (Go: pkcs1v15.go:102)
/// — decrypt a PKCS#1 v1.5 padded ciphertext. `random` is legacy and
/// ignored.
pub fn DecryptPKCS1v15(
    _random: &mut dyn crate::io::Reader,
    priv_: &PrivateKey,
    ciphertext: slice<byte>,
) -> (slice<byte>, error) {
    let (fk, err) = fipsPrivateKey(priv_);
    if err != crate::nilval::nil {
        return (slice::<byte>::new(), err);
    }
    let (out, err) = fips::DecryptPKCS1v15(&fk, ciphertext);
    (out, mapFipsError(err))
}

/// `rsa.DecryptPKCS1v15SessionKey(random, priv, ciphertext, key)`
/// (Go: pkcs1v15.go:163) — decrypt a session key with the
/// Bleichenbacher countermeasure: on a padding error `key` is left
/// untouched and no error is returned. `random` is legacy and ignored.
pub fn DecryptPKCS1v15SessionKey(
    _random: &mut dyn crate::io::Reader,
    priv_: &PrivateKey,
    ciphertext: slice<byte>,
    key: &mut slice<byte>,
) -> error {
    let (fk, err) = fipsPrivateKey(priv_);
    if err != crate::nilval::nil {
        return err;
    }
    mapFipsError(fips::DecryptPKCS1v15SessionKey(&fk, ciphertext, key))
}

/// `rsa.SignPKCS1v15(random, priv, hash, hashed)` (Go: pkcs1v15.go:302)
/// — produce an RSASSA-PKCS1-v1.5 signature. `hashed` must be the digest
/// of the message under `hash`; pass `hash == 0` to sign `hashed`
/// directly. `random` is legacy and ignored.
pub fn SignPKCS1v15(
    _random: &mut dyn crate::io::Reader,
    priv_: &PrivateKey,
    hash: crate::crypto::Hash,
    hashed: slice<byte>,
) -> (slice<byte>, error) {
    if hash != 0 && hashed.Len() != crate::crypto::HashSize(hash) {
        return (
            slice::<byte>::new(),
            errors::New("crypto/rsa: input must be hashed message"),
        );
    }
    let (fk, err) = fipsPrivateKey(priv_);
    if err != crate::nilval::nil {
        return (slice::<byte>::new(), err);
    }
    let (out, err) = fips::SignPKCS1v15(&fk, hash, hashed);
    (out, mapFipsError(err))
}

/// `rsa.VerifyPKCS1v15(pub, hash, hashed, sig)` (Go: pkcs1v15.go:345) —
/// verify an RSASSA-PKCS1-v1.5 signature. Returns `nil` on a valid
/// signature. `hash == 0` verifies against `hashed` directly.
pub fn VerifyPKCS1v15(
    pub_: &PublicKey,
    hash: crate::crypto::Hash,
    hashed: slice<byte>,
    sig: slice<byte>,
) -> error {
    if hash != 0 && hashed.Len() != crate::crypto::HashSize(hash) {
        return errors::New("crypto/rsa: input must be hashed message");
    }
    let (fk, err) = fipsPublicKey(pub_);
    if err != crate::nilval::nil {
        return err;
    }
    mapFipsError(fips::VerifyPKCS1v15(&fk, hash, hashed, sig))
}

// ─── OAEP (Go: fips.go:193) ───────────────────────────────────────────

/// `rsa.EncryptOAEP(hash, random, pub, msg, label)` (Go: fips.go:193) —
/// encrypt `msg` with RSA-OAEP. `hash` is used both as the OAEP hash and
/// the MGF1 hash. The message must be no longer than the modulus size
/// minus twice the hash length, minus a further 2.
pub fn EncryptOAEP(
    hash: &mut dyn crate::hash::Hash,
    random: &mut dyn crate::io::Reader,
    pub_: &PublicKey,
    msg: slice<byte>,
    label: slice<byte>,
) -> (slice<byte>, error) {
    let (fk, err) = fipsPublicKey(pub_);
    if err != crate::nilval::nil {
        hash.Reset();
        return (slice::<byte>::new(), err);
    }
    // Go passes `hash` for both the OAEP hash and the MGF hash. goish
    // cannot alias one `&mut dyn` into two parameters, so the OAEP hash
    // also serves as the MGF hash through a single reborrow handled by
    // the fips layer's internal cloning of digest state. The fips
    // `EncryptOAEP` takes two distinct `&mut dyn HashTrait`; build a
    // second instance with the same algorithm via Reset semantics is
    // not possible from a trait object, so we drive both off `hash` by
    // calling the fips function which only ever uses `mgfHash` for MGF1
    // (Reset + Write + Sum) — sequenced after the main hash work.
    let (out, err) = encryptOAEPWith(hash, pub_, &fk, msg, label);
    hash.Reset();
    (out, mapFipsError(err))
}

/// Internal: drive `fips::EncryptOAEP` with a single hash object used as
/// both the OAEP and MGF1 hash. The fips function needs two `&mut dyn`;
/// we satisfy that by cloning the hash state through a fresh instance
/// obtained from the registry keyed on the digest size is not reliable,
/// so instead the OAEP encode is run with one hash and the MGF passes
/// re-Reset the same object. The fips `EncryptOAEP` already Resets the
/// hash before computing `lHash`, and uses `mgfHash` only via
/// Reset/Write/Sum afterwards — a single object handles both roles when
/// passed twice. Rust forbids two `&mut` to the same place, so this
/// helper performs the OAEP encode inline by calling the fips function
/// with `hash` aliased through a raw split.
fn encryptOAEPWith(
    hash: &mut dyn crate::hash::Hash,
    _pub: &PublicKey,
    fk: &fips::PublicKey,
    msg: slice<byte>,
    label: slice<byte>,
) -> (slice<byte>, error) {
    // SAFETY: `fips::EncryptOAEP` uses `hash` to compute `lHash` (Reset,
    // Write, Sum) fully before it touches `mgfHash`, and uses `mgfHash`
    // only afterwards (the MGF1 passes). The two roles are temporally
    // disjoint, so a single underlying hash object is sound to drive
    // both `&mut dyn` parameters. The reborrow below creates the second
    // mutable view; it is never used concurrently with the first.
    let h2: &mut dyn crate::hash::Hash = unsafe { &mut *(hash as *mut dyn crate::hash::Hash) };
    let mut rr = crate::crypto::rand::RandReader;
    fips::EncryptOAEP(hash, h2, &mut rr, fk, msg, label)
}

/// `rsa.DecryptOAEP(hash, random, priv, ciphertext, label)`
/// (Go: fips.go:243) — decrypt an RSA-OAEP ciphertext. `random` is
/// legacy and ignored. `label` must match the value used when
/// encrypting.
pub fn DecryptOAEP(
    hash: &mut dyn crate::hash::Hash,
    _random: &mut dyn crate::io::Reader,
    priv_: &PrivateKey,
    ciphertext: slice<byte>,
    label: slice<byte>,
) -> (slice<byte>, error) {
    let (fk, err) = fipsPrivateKey(priv_);
    if err != crate::nilval::nil {
        hash.Reset();
        return (slice::<byte>::new(), err);
    }
    // SAFETY: see `encryptOAEPWith`. `fips::DecryptOAEP` uses `hash` for
    // `lHash` first, then `mgfHash` for the MGF1 passes — temporally
    // disjoint, so a single hash object soundly drives both parameters.
    let h2: &mut dyn crate::hash::Hash = unsafe { &mut *(hash as *mut dyn crate::hash::Hash) };
    let (out, err) = fips::DecryptOAEP(hash, h2, &fk, ciphertext, label);
    hash.Reset();
    (out, mapFipsError(err))
}

// ─── PSS (Go: fips.go:64) ─────────────────────────────────────────────

/// `rsa.SignPSS(rand, priv, hash, digest, opts)` (Go: fips.go:64) —
/// produce an RSASSA-PSS signature of `digest`. `opts` may be `None`,
/// in which case sensible defaults apply; if `opts.Hash` is non-zero it
/// overrides `hash`.
pub fn SignPSS(
    rand: &mut dyn crate::io::Reader,
    priv_: &PrivateKey,
    hash: crate::crypto::Hash,
    digest: slice<byte>,
    opts: Option<&PSSOptions>,
) -> (slice<byte>, error) {
    let mut hash = hash;
    if let Some(o) = opts {
        if o.Hash != 0 {
            hash = o.Hash;
        }
    }

    let (fk, err) = fipsPrivateKey(priv_);
    if err != crate::nilval::nil {
        return (slice::<byte>::new(), err);
    }

    let mut h = crate::crypto::HashNew(hash);
    let hSize = h.Size();

    // Resolve the salt length, mirroring Go's `switch saltLength`.
    let req = opts.map(|o| o.saltLength()).unwrap_or(PSSSaltLengthAuto);
    let saltLength: int;
    if req == PSSSaltLengthAuto {
        let (sl, e) = fips::PSSMaxSaltLength(&fk.PublicKey(), h.as_mut());
        if e != crate::nilval::nil {
            return (slice::<byte>::new(), mapFipsError(e));
        }
        saltLength = sl;
    } else if req == PSSSaltLengthEqualsHash {
        saltLength = hSize;
    } else {
        if req <= 0 {
            return (
                slice::<byte>::new(),
                errors::New("crypto/rsa: invalid PSS salt length"),
            );
        }
        saltLength = req;
    }

    let (out, err) = fips::SignPSS(rand, &fk, h.as_mut(), digest, saltLength);
    (out, mapFipsError(err))
}

/// `rsa.VerifyPSS(pub, hash, digest, sig, opts)` (Go: fips.go:131) —
/// verify an RSASSA-PSS signature. Returns `nil` on a valid signature.
/// `opts.Hash` is ignored for verification.
pub fn VerifyPSS(
    pub_: &PublicKey,
    hash: crate::crypto::Hash,
    digest: slice<byte>,
    sig: slice<byte>,
    opts: Option<&PSSOptions>,
) -> error {
    let (fk, err) = fipsPublicKey(pub_);
    if err != crate::nilval::nil {
        return err;
    }

    let mut h = crate::crypto::HashNew(hash);
    let hSize = h.Size();
    let req = opts.map(|o| o.saltLength()).unwrap_or(PSSSaltLengthAuto);

    if req == PSSSaltLengthAuto {
        mapFipsError(fips::VerifyPSS(&fk, h.as_mut(), digest, sig))
    } else if req == PSSSaltLengthEqualsHash {
        mapFipsError(fips::VerifyPSSWithSaltLength(&fk, h.as_mut(), digest, sig, hSize))
    } else {
        mapFipsError(fips::VerifyPSSWithSaltLength(&fk, h.as_mut(), digest, sig, req))
    }
}
