// go: file crypto/internal/fips140/nistec/fiat/p224_invert.go decls: P224Element.Invert
//
// Code generated by addchain. DO NOT EDIT.
//
// Translated from Go by scripts/fiat_invert_to_rust.py. A transposed
// operand or an off-by-one loop bound here produces a wrong inverse
// silently, so the translation is mechanical and its parser raises on
// anything it does not recognise. Regenerate with scripts/fiat_gen.py.

#![allow(non_snake_case)]

use super::p224::P224Element;
use crate::types::int;

impl P224Element {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p224_invert.go:12-87 Invert
    /// Set e = 1/x, and return e.
    ///
    /// If x == 0, Invert returns e = 0.
    pub fn Invert(&mut self, x: &P224Element) -> &mut Self {
    // Inversion is implemented as exponentiation with exponent p − 2.
    // The sequence of 11 multiplications and 223 squarings is derived from the
    // following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
    //
    //	_10     = 2*1
    //	_11     = 1 + _10
    //	_110    = 2*_11
    //	_111    = 1 + _110
    //	_111000 = _111 << 3
    //	_111111 = _111 + _111000
    //	x12     = _111111 << 6 + _111111
    //	x14     = x12 << 2 + _11
    //	x17     = x14 << 3 + _111
    //	x31     = x17 << 14 + x14
    //	x48     = x31 << 17 + x17
    //	x96     = x48 << 48 + x48
    //	x127    = x96 << 31 + x31
    //	return    x127 << 97 + x96
    //
        let mut z = P224Element::New();
        z.Set(*self);
        let mut t0 = P224Element::New();
        let mut t1 = P224Element::New();
        let mut t2 = P224Element::New();
        z.Square(*x);
        t0.Mul(*x, z);
        z.Square(t0);
        z.Mul(*x, z);
        t1.Square(z);
        // Go: for s := 1; s < 3; s++
        let mut s: int = 1;
        while s < 3 {
            t1.Square(t1);
            s += 1;
        }
        t1.Mul(z, t1);
        t2.Square(t1);
        // Go: for s := 1; s < 6; s++
        let mut s: int = 1;
        while s < 6 {
            t2.Square(t2);
            s += 1;
        }
        t1.Mul(t1, t2);
        // Go: for s := 0; s < 2; s++
        let mut s: int = 0;
        while s < 2 {
            t1.Square(t1);
            s += 1;
        }
        t0.Mul(t0, t1);
        t1.Square(t0);
        // Go: for s := 1; s < 3; s++
        let mut s: int = 1;
        while s < 3 {
            t1.Square(t1);
            s += 1;
        }
        z.Mul(z, t1);
        t1.Square(z);
        // Go: for s := 1; s < 14; s++
        let mut s: int = 1;
        while s < 14 {
            t1.Square(t1);
            s += 1;
        }
        t0.Mul(t0, t1);
        t1.Square(t0);
        // Go: for s := 1; s < 17; s++
        let mut s: int = 1;
        while s < 17 {
            t1.Square(t1);
            s += 1;
        }
        z.Mul(z, t1);
        t1.Square(z);
        // Go: for s := 1; s < 48; s++
        let mut s: int = 1;
        while s < 48 {
            t1.Square(t1);
            s += 1;
        }
        z.Mul(z, t1);
        t1.Square(z);
        // Go: for s := 1; s < 31; s++
        let mut s: int = 1;
        while s < 31 {
            t1.Square(t1);
            s += 1;
        }
        t0.Mul(t0, t1);
        // Go: for s := 0; s < 97; s++
        let mut s: int = 0;
        while s < 97 {
            t0.Square(t0);
            s += 1;
        }
        z.Mul(z, t0);
        return self.Set(z);
    }
}
