// go: file crypto/internal/fips140/nistec/fiat/p256.go decls: P256Element.One, P256Element.Equal, P256Element.IsZero, P256Element.Set, P256Element.Bytes, P256Element.bytes, P256Element.SetBytes, P256Element.Add, P256Element.Sub, P256Element.Mul, P256Element.Square, P256Element.Select, p256InvertEndianness
//
// Code generated by generate.go. DO NOT EDIT.
//
// Deviation from p256[go] @ Go 1.25.5: Go takes every field-element
// operand as `*P256Element` and freely aliases the receiver
// (`e.Add(e, t)`). P256Element is `[u64; 4]` and therefore Copy, so
// operands are taken **by value** — which costs one register copy and
// makes the aliasing call sites Go relies on translate directly. Passing
// `&P256Element` instead would make `e.Add(e, t)` a borrow error at
// every nistec call site.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]

extern crate alloc;
use alloc::vec::Vec;

use super::p256_fiat64::*;
use crate::crypto::internal::fips140::subtle;
use crate::errors;
use crate::goslice::slice;
use crate::types::byte;
use crate::{error, int, uint64};

// Go: p256.go:14-21
//   type P256Element struct { x p256MontgomeryDomainFieldElement }
/// An integer modulo 2^256 - 2^224 + 2^192 + 2^96 - 1.
///
/// The zero value is a valid zero element.
#[derive(Clone, Copy, Default)]
pub struct P256Element {
    /// Values are represented internally always in the Montgomery domain,
    /// and converted in Bytes and SetBytes.
    pub(crate) x: [u64; 4],
}

/// Go: `const p256ElementLen = 32`
pub const p256ElementLen: usize = 32;

/// Go: `type p256UntypedFieldElement = [4]uint64`
pub type p256UntypedFieldElement = [u64; 4];

impl P256Element {
    // go: none — Go gets the zero value from `new(P256Element)`.
    pub fn New() -> Self {
        return P256Element { x: [0; 4] };
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:27-31 P256Element.One
    /// Set e = 1, and return e.
    pub fn One(&mut self) -> &mut Self {
        p256SetOne(&mut self.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:33-38 P256Element.Equal
    /// Return 1 if e == t, and zero otherwise.
    pub fn Equal(&self, t: P256Element) -> int {
        let eBytes = self.Bytes();
        let tBytes = t.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &tBytes);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:40-45 P256Element.IsZero
    /// Return 1 if e == 0, and zero otherwise.
    pub fn IsZero(&self) -> int {
        let zero = slice::__from_vec(alloc::vec![0u8; p256ElementLen]);
        let eBytes = self.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &zero);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:47-51 P256Element.Set
    /// Set e = t, and return e.
    pub fn Set(&mut self, t: P256Element) -> &mut Self {
        self.x = t.x;
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:53-59 P256Element.Bytes
    /// Return the 32-byte big-endian encoding of e.
    pub fn Bytes(&self) -> slice<byte> {
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; p256ElementLen];
        return self.bytes(&mut out);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:61-67 P256Element.bytes
    fn bytes(&self, out: &mut [byte; p256ElementLen]) -> slice<byte> {
        let mut tmp: [u64; 4] = [0; 4];
        p256FromMontgomery(&mut tmp, &self.x);
        p256ToBytes(out, &tmp);
        p256InvertEndianness(out);
        return slice::__from_vec(out.to_vec());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:69-92 P256Element.SetBytes
    /// Set e = v, where v is a big-endian 32-byte encoding, and return e.
    /// If v is not 32 bytes or it encodes a value higher than
    /// 2^256 - 2^224 + 2^192 + 2^96 - 1, SetBytes returns an error and e is unchanged.
    pub fn SetBytes(&mut self, v: slice<byte>) -> error {
        // Go: if len(v) != p256ElementLen { return nil, errors.New(…) }
        if v.Len() != int(p256ElementLen) {
            return errors::New("invalid P256Element encoding");
        }

        // Check for non-canonical encodings (p + k, 2p + k, etc.) by
        // comparing to the encoding of -1 mod p, so p - 1, the highest
        // canonical encoding.
        let mut one = P256Element::New();
        one.One();
        let mut minusOne = P256Element::New();
        minusOne.Sub(P256Element::New(), one);
        let minusOneEncoding = minusOne.Bytes();
        if subtle::ConstantTimeLessOrEqBytes(&v, &minusOneEncoding) == 0 {
            return errors::New("invalid P256Element encoding");
        }

        // Go: var in [p256ElementLen]byte; copy(in[:], v); p256InvertEndianness(in[:])
        let mut inp = [0u8; p256ElementLen];
        let raw: &[byte] = &v;
        inp.copy_from_slice(raw);
        p256InvertEndianness(&mut inp);
        let mut tmp: [u64; 4] = [0; 4];
        p256FromBytes(&mut tmp, &inp);
        p256ToMontgomery(&mut self.x, &tmp);
        return crate::nil.into();
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:94-98 P256Element.Add
    /// Set e = t1 + t2, and return e.
    pub fn Add(&mut self, t1: P256Element, t2: P256Element) -> &mut Self {
        p256Add(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:100-104 P256Element.Sub
    /// Set e = t1 - t2, and return e.
    pub fn Sub(&mut self, t1: P256Element, t2: P256Element) -> &mut Self {
        p256Sub(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:106-110 P256Element.Mul
    /// Set e = t1 * t2, and return e.
    pub fn Mul(&mut self, t1: P256Element, t2: P256Element) -> &mut Self {
        p256Mul(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:112-116 P256Element.Square
    /// Set e = t * t, and return e.
    pub fn Square(&mut self, t: P256Element) -> &mut Self {
        p256Square(&mut self.x, &t.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:118-123 P256Element.Select
    /// Set v to a if cond == 1, and to b if cond == 0.
    pub fn Select(&mut self, a: P256Element, b: P256Element, cond: int) -> &mut Self {
        p256Selectznz(&mut self.x, uint64(cond), &b.x, &a.x);
        return self;
    }
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256.go:125-129 p256InvertEndianness
pub(crate) fn p256InvertEndianness(v: &mut [byte]) {
    // Go: for i := 0; i < len(v)/2; i++ { v[i], v[len(v)-1-i] = v[len(v)-1-i], v[i] }
    let mut i: usize = 0;
    while i < v.len() / 2 {
        let j = v.len() - 1 - i;
        let t = v[i];
        v[i] = v[j];
        v[j] = t;
        i += 1;
    }
}

// Silence the unused-import warning when Vec is only reached via vec!.
const _: fn() -> Vec<byte> = Vec::new;
