// go: file crypto/internal/fips140/nistec/fiat/p256_invert.go decls: P256Element.Invert
//
// Code generated by addchain. DO NOT EDIT.
//
// Translated from Go by scripts/fiat_invert_to_rust.py. A transposed
// operand or an off-by-one loop bound here produces a wrong inverse
// silently, so the translation is mechanical and its parser raises on
// anything it does not recognise. Regenerate with scripts/fiat_gen.py.

#![allow(non_snake_case)]

use super::p256::P256Element;
use crate::types::int;

impl P256Element {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_invert.go:12-84 Invert
    /// Set e = 1/x, and return e.
    ///
    /// If x == 0, Invert returns e = 0.
    pub fn Invert(&mut self, x: &P256Element) -> &mut Self {
    // Inversion is implemented as exponentiation with exponent p − 2.
    // The sequence of 12 multiplications and 255 squarings is derived from the
    // following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
    //
    //	_10     = 2*1
    //	_11     = 1 + _10
    //	_110    = 2*_11
    //	_111    = 1 + _110
    //	_111000 = _111 << 3
    //	_111111 = _111 + _111000
    //	x12     = _111111 << 6 + _111111
    //	x15     = x12 << 3 + _111
    //	x16     = 2*x15 + 1
    //	x32     = x16 << 16 + x16
    //	i53     = x32 << 15
    //	x47     = x15 + i53
    //	i263    = ((i53 << 17 + 1) << 143 + x47) << 47
    //	return    (x47 + i263) << 2 + 1
    //
        let mut z = P256Element::New();
        z.Set(*self);
        let mut t0 = P256Element::New();
        let mut t1 = P256Element::New();
        z.Square(*x);
        z.Mul(*x, z);
        z.Square(z);
        z.Mul(*x, z);
        t0.Square(z);
        // Go: for s := 1; s < 3; s++
        let mut s: int = 1;
        while s < 3 {
            t0.Square(t0);
            s += 1;
        }
        t0.Mul(z, t0);
        t1.Square(t0);
        // Go: for s := 1; s < 6; s++
        let mut s: int = 1;
        while s < 6 {
            t1.Square(t1);
            s += 1;
        }
        t0.Mul(t0, t1);
        // Go: for s := 0; s < 3; s++
        let mut s: int = 0;
        while s < 3 {
            t0.Square(t0);
            s += 1;
        }
        z.Mul(z, t0);
        t0.Square(z);
        t0.Mul(*x, t0);
        t1.Square(t0);
        // Go: for s := 1; s < 16; s++
        let mut s: int = 1;
        while s < 16 {
            t1.Square(t1);
            s += 1;
        }
        t0.Mul(t0, t1);
        // Go: for s := 0; s < 15; s++
        let mut s: int = 0;
        while s < 15 {
            t0.Square(t0);
            s += 1;
        }
        z.Mul(z, t0);
        // Go: for s := 0; s < 17; s++
        let mut s: int = 0;
        while s < 17 {
            t0.Square(t0);
            s += 1;
        }
        t0.Mul(*x, t0);
        // Go: for s := 0; s < 143; s++
        let mut s: int = 0;
        while s < 143 {
            t0.Square(t0);
            s += 1;
        }
        t0.Mul(z, t0);
        // Go: for s := 0; s < 47; s++
        let mut s: int = 0;
        while s < 47 {
            t0.Square(t0);
            s += 1;
        }
        z.Mul(z, t0);
        // Go: for s := 0; s < 2; s++
        let mut s: int = 0;
        while s < 2 {
            z.Square(z);
            s += 1;
        }
        z.Mul(*x, z);
        return self.Set(z);
    }
}
