// go: file crypto/internal/fips140/nistec/fiat/p256_fiat64.go decls: p256CmovznzU64, p256Mul, p256Square, p256Add, p256Sub, p256SetOne, p256FromMontgomery, p256ToMontgomery, p256Selectznz, p256ToBytes, p256FromBytes
//
// Code generated by Fiat Cryptography. DO NOT EDIT.
//
// Translated from Go by scripts/fiat64_to_rust.py, which parses the
// closed grammar these generated files use and raises on anything it does
// not recognise — it can fail to translate, but not silently
// mistranslate. Regenerate with `scripts/fiat_gen.py`; do not hand-edit.
//
// curve description: p256   |   machine_wordsize = 64   |   limbs = 4
//
// Two shape changes, both forced:
//
//   * Go's uint64 arithmetic wraps; Rust's panics in debug builds. Every
//     `+` is wrapping_add and every `*` is wrapping_mul.
//   * `p256CmovznzU64` returns its result rather than writing through an
//     `out1 *uint64`. The out-parameter is a fiat-crypto calling
//     convention, not part of the algorithm.
//
// `p256Uint1`/`p256Int1` and the Montgomery/NonMontgomery element types are
// all defined in Go as `uint64`, `int64` and `[4]uint64` respectively,
// so every conversion between them is a value-level no-op and is elided.

#![allow(non_snake_case, non_camel_case_types)]
// The parenthesisation mirrors the Go source, which is itself machine
// output; stripping it would make the two harder to diff.
#![allow(unused_parens)]
//
// goishlint:ignore GOISH020 — `p256CmovznzU64` returns its result where Go
// writes it through an `out1 *uint64` first parameter, so the arity is 3
// against Go's 4. The out-parameter is a fiat-crypto calling convention.

use crate::math::bits;
use crate::{uint64, uint8};

/// Go: `type p256Uint1 uint64` — "We use uint64 instead of a more narrow
/// type for performance reasons."
pub(super) type p256Uint1 = u64;

/// Go: `type p256Int1 int64`. Declared by Fiat Cryptography but not used
/// by any function it generates, here or in Go.
#[allow(dead_code)]
pub(super) type p256Int1 = i64;

/// Go: `type p256MontgomeryDomainFieldElement [4]uint64` — a field
/// element in the Montgomery domain.
pub(super) type p256MontgomeryDomainFieldElement = [u64; 4];

/// Go: `type p256NonMontgomeryDomainFieldElement [4]uint64` — a field
/// element NOT in the Montgomery domain.
pub(super) type p256NonMontgomeryDomainFieldElement = [u64; 4];

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:71-75 p256CmovznzU64
/// A single-word conditional move: `if arg1 = 0 then arg2
/// else arg3`.
///
/// Go writes the result through `out1 *uint64`; that is a
/// fiat-crypto calling convention, not part of the
/// algorithm, so this returns it instead.
pub(super) fn p256CmovznzU64(arg1: u64, arg2: u64, arg3: u64) -> u64 {
    let x1 = ((uint64(arg1)).wrapping_mul(0xffffffffffffffff));
    let x2 = ((x1 & arg3) | ((!x1) & arg2));
    return x2;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:88-363 p256Mul
pub(super) fn p256Mul(
    out1: &mut p256MontgomeryDomainFieldElement,
    arg1: &p256MontgomeryDomainFieldElement,
    arg2: &p256MontgomeryDomainFieldElement,
) {
    let x1 = arg1[1];
    let x2 = arg1[2];
    let x3 = arg1[3];
    let x4 = arg1[0];
    let (x6, x5) = bits::Mul64(x4, arg2[3]);
    let (x8, x7) = bits::Mul64(x4, arg2[2]);
    let (x10, x9) = bits::Mul64(x4, arg2[1]);
    let (x12, x11) = bits::Mul64(x4, arg2[0]);
    let (x13, x14) = bits::Add64(x12, x9, uint64(0x0));
    let (x15, x16) = bits::Add64(x10, x7, uint64(uint64(x14)));
    let (x17, x18) = bits::Add64(x8, x5, uint64(uint64(x16)));
    let x19 = ((uint64(uint64(x18))).wrapping_add(x6));
    let (x21, x20) = bits::Mul64(x11, 0xffffffff00000001);
    let (x23, x22) = bits::Mul64(x11, 0xffffffff);
    let (x25, x24) = bits::Mul64(x11, 0xffffffffffffffff);
    let (x26, x27) = bits::Add64(x25, x22, uint64(0x0));
    let x28 = ((uint64(uint64(x27))).wrapping_add(x23));
    let (_, x30) = bits::Add64(x11, x24, uint64(0x0));
    let (x31, x32) = bits::Add64(x13, x26, uint64(uint64(x30)));
    let (x33, x34) = bits::Add64(x15, x28, uint64(uint64(x32)));
    let (x35, x36) = bits::Add64(x17, x20, uint64(uint64(x34)));
    let (x37, x38) = bits::Add64(x19, x21, uint64(uint64(x36)));
    let (x40, x39) = bits::Mul64(x1, arg2[3]);
    let (x42, x41) = bits::Mul64(x1, arg2[2]);
    let (x44, x43) = bits::Mul64(x1, arg2[1]);
    let (x46, x45) = bits::Mul64(x1, arg2[0]);
    let (x47, x48) = bits::Add64(x46, x43, uint64(0x0));
    let (x49, x50) = bits::Add64(x44, x41, uint64(uint64(x48)));
    let (x51, x52) = bits::Add64(x42, x39, uint64(uint64(x50)));
    let x53 = ((uint64(uint64(x52))).wrapping_add(x40));
    let (x54, x55) = bits::Add64(x31, x45, uint64(0x0));
    let (x56, x57) = bits::Add64(x33, x47, uint64(uint64(x55)));
    let (x58, x59) = bits::Add64(x35, x49, uint64(uint64(x57)));
    let (x60, x61) = bits::Add64(x37, x51, uint64(uint64(x59)));
    let (x62, x63) = bits::Add64(uint64(uint64(x38)), x53, uint64(uint64(x61)));
    let (x65, x64) = bits::Mul64(x54, 0xffffffff00000001);
    let (x67, x66) = bits::Mul64(x54, 0xffffffff);
    let (x69, x68) = bits::Mul64(x54, 0xffffffffffffffff);
    let (x70, x71) = bits::Add64(x69, x66, uint64(0x0));
    let x72 = ((uint64(uint64(x71))).wrapping_add(x67));
    let (_, x74) = bits::Add64(x54, x68, uint64(0x0));
    let (x75, x76) = bits::Add64(x56, x70, uint64(uint64(x74)));
    let (x77, x78) = bits::Add64(x58, x72, uint64(uint64(x76)));
    let (x79, x80) = bits::Add64(x60, x64, uint64(uint64(x78)));
    let (x81, x82) = bits::Add64(x62, x65, uint64(uint64(x80)));
    let x83 = ((uint64(uint64(x82))).wrapping_add(uint64(uint64(x63))));
    let (x85, x84) = bits::Mul64(x2, arg2[3]);
    let (x87, x86) = bits::Mul64(x2, arg2[2]);
    let (x89, x88) = bits::Mul64(x2, arg2[1]);
    let (x91, x90) = bits::Mul64(x2, arg2[0]);
    let (x92, x93) = bits::Add64(x91, x88, uint64(0x0));
    let (x94, x95) = bits::Add64(x89, x86, uint64(uint64(x93)));
    let (x96, x97) = bits::Add64(x87, x84, uint64(uint64(x95)));
    let x98 = ((uint64(uint64(x97))).wrapping_add(x85));
    let (x99, x100) = bits::Add64(x75, x90, uint64(0x0));
    let (x101, x102) = bits::Add64(x77, x92, uint64(uint64(x100)));
    let (x103, x104) = bits::Add64(x79, x94, uint64(uint64(x102)));
    let (x105, x106) = bits::Add64(x81, x96, uint64(uint64(x104)));
    let (x107, x108) = bits::Add64(x83, x98, uint64(uint64(x106)));
    let (x110, x109) = bits::Mul64(x99, 0xffffffff00000001);
    let (x112, x111) = bits::Mul64(x99, 0xffffffff);
    let (x114, x113) = bits::Mul64(x99, 0xffffffffffffffff);
    let (x115, x116) = bits::Add64(x114, x111, uint64(0x0));
    let x117 = ((uint64(uint64(x116))).wrapping_add(x112));
    let (_, x119) = bits::Add64(x99, x113, uint64(0x0));
    let (x120, x121) = bits::Add64(x101, x115, uint64(uint64(x119)));
    let (x122, x123) = bits::Add64(x103, x117, uint64(uint64(x121)));
    let (x124, x125) = bits::Add64(x105, x109, uint64(uint64(x123)));
    let (x126, x127) = bits::Add64(x107, x110, uint64(uint64(x125)));
    let x128 = ((uint64(uint64(x127))).wrapping_add(uint64(uint64(x108))));
    let (x130, x129) = bits::Mul64(x3, arg2[3]);
    let (x132, x131) = bits::Mul64(x3, arg2[2]);
    let (x134, x133) = bits::Mul64(x3, arg2[1]);
    let (x136, x135) = bits::Mul64(x3, arg2[0]);
    let (x137, x138) = bits::Add64(x136, x133, uint64(0x0));
    let (x139, x140) = bits::Add64(x134, x131, uint64(uint64(x138)));
    let (x141, x142) = bits::Add64(x132, x129, uint64(uint64(x140)));
    let x143 = ((uint64(uint64(x142))).wrapping_add(x130));
    let (x144, x145) = bits::Add64(x120, x135, uint64(0x0));
    let (x146, x147) = bits::Add64(x122, x137, uint64(uint64(x145)));
    let (x148, x149) = bits::Add64(x124, x139, uint64(uint64(x147)));
    let (x150, x151) = bits::Add64(x126, x141, uint64(uint64(x149)));
    let (x152, x153) = bits::Add64(x128, x143, uint64(uint64(x151)));
    let (x155, x154) = bits::Mul64(x144, 0xffffffff00000001);
    let (x157, x156) = bits::Mul64(x144, 0xffffffff);
    let (x159, x158) = bits::Mul64(x144, 0xffffffffffffffff);
    let (x160, x161) = bits::Add64(x159, x156, uint64(0x0));
    let x162 = ((uint64(uint64(x161))).wrapping_add(x157));
    let (_, x164) = bits::Add64(x144, x158, uint64(0x0));
    let (x165, x166) = bits::Add64(x146, x160, uint64(uint64(x164)));
    let (x167, x168) = bits::Add64(x148, x162, uint64(uint64(x166)));
    let (x169, x170) = bits::Add64(x150, x154, uint64(uint64(x168)));
    let (x171, x172) = bits::Add64(x152, x155, uint64(uint64(x170)));
    let x173 = ((uint64(uint64(x172))).wrapping_add(uint64(uint64(x153))));
    let (x174, x175) = bits::Sub64(x165, 0xffffffffffffffff, uint64(0x0));
    let (x176, x177) = bits::Sub64(x167, 0xffffffff, uint64(uint64(x175)));
    let (x178, x179) = bits::Sub64(x169, uint64(0x0), uint64(uint64(x177)));
    let (x180, x181) = bits::Sub64(x171, 0xffffffff00000001, uint64(uint64(x179)));
    let (_, x183) = bits::Sub64(x173, uint64(0x0), uint64(uint64(x181)));
    let x184 = p256CmovznzU64(uint64(x183), x174, x165);
    let x185 = p256CmovznzU64(uint64(x183), x176, x167);
    let x186 = p256CmovznzU64(uint64(x183), x178, x169);
    let x187 = p256CmovznzU64(uint64(x183), x180, x171);
    out1[0] = x184;
    out1[1] = x185;
    out1[2] = x186;
    out1[3] = x187;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:375-650 p256Square
pub(super) fn p256Square(
    out1: &mut p256MontgomeryDomainFieldElement,
    arg1: &p256MontgomeryDomainFieldElement,
) {
    let x1 = arg1[1];
    let x2 = arg1[2];
    let x3 = arg1[3];
    let x4 = arg1[0];
    let (x6, x5) = bits::Mul64(x4, arg1[3]);
    let (x8, x7) = bits::Mul64(x4, arg1[2]);
    let (x10, x9) = bits::Mul64(x4, arg1[1]);
    let (x12, x11) = bits::Mul64(x4, arg1[0]);
    let (x13, x14) = bits::Add64(x12, x9, uint64(0x0));
    let (x15, x16) = bits::Add64(x10, x7, uint64(uint64(x14)));
    let (x17, x18) = bits::Add64(x8, x5, uint64(uint64(x16)));
    let x19 = ((uint64(uint64(x18))).wrapping_add(x6));
    let (x21, x20) = bits::Mul64(x11, 0xffffffff00000001);
    let (x23, x22) = bits::Mul64(x11, 0xffffffff);
    let (x25, x24) = bits::Mul64(x11, 0xffffffffffffffff);
    let (x26, x27) = bits::Add64(x25, x22, uint64(0x0));
    let x28 = ((uint64(uint64(x27))).wrapping_add(x23));
    let (_, x30) = bits::Add64(x11, x24, uint64(0x0));
    let (x31, x32) = bits::Add64(x13, x26, uint64(uint64(x30)));
    let (x33, x34) = bits::Add64(x15, x28, uint64(uint64(x32)));
    let (x35, x36) = bits::Add64(x17, x20, uint64(uint64(x34)));
    let (x37, x38) = bits::Add64(x19, x21, uint64(uint64(x36)));
    let (x40, x39) = bits::Mul64(x1, arg1[3]);
    let (x42, x41) = bits::Mul64(x1, arg1[2]);
    let (x44, x43) = bits::Mul64(x1, arg1[1]);
    let (x46, x45) = bits::Mul64(x1, arg1[0]);
    let (x47, x48) = bits::Add64(x46, x43, uint64(0x0));
    let (x49, x50) = bits::Add64(x44, x41, uint64(uint64(x48)));
    let (x51, x52) = bits::Add64(x42, x39, uint64(uint64(x50)));
    let x53 = ((uint64(uint64(x52))).wrapping_add(x40));
    let (x54, x55) = bits::Add64(x31, x45, uint64(0x0));
    let (x56, x57) = bits::Add64(x33, x47, uint64(uint64(x55)));
    let (x58, x59) = bits::Add64(x35, x49, uint64(uint64(x57)));
    let (x60, x61) = bits::Add64(x37, x51, uint64(uint64(x59)));
    let (x62, x63) = bits::Add64(uint64(uint64(x38)), x53, uint64(uint64(x61)));
    let (x65, x64) = bits::Mul64(x54, 0xffffffff00000001);
    let (x67, x66) = bits::Mul64(x54, 0xffffffff);
    let (x69, x68) = bits::Mul64(x54, 0xffffffffffffffff);
    let (x70, x71) = bits::Add64(x69, x66, uint64(0x0));
    let x72 = ((uint64(uint64(x71))).wrapping_add(x67));
    let (_, x74) = bits::Add64(x54, x68, uint64(0x0));
    let (x75, x76) = bits::Add64(x56, x70, uint64(uint64(x74)));
    let (x77, x78) = bits::Add64(x58, x72, uint64(uint64(x76)));
    let (x79, x80) = bits::Add64(x60, x64, uint64(uint64(x78)));
    let (x81, x82) = bits::Add64(x62, x65, uint64(uint64(x80)));
    let x83 = ((uint64(uint64(x82))).wrapping_add(uint64(uint64(x63))));
    let (x85, x84) = bits::Mul64(x2, arg1[3]);
    let (x87, x86) = bits::Mul64(x2, arg1[2]);
    let (x89, x88) = bits::Mul64(x2, arg1[1]);
    let (x91, x90) = bits::Mul64(x2, arg1[0]);
    let (x92, x93) = bits::Add64(x91, x88, uint64(0x0));
    let (x94, x95) = bits::Add64(x89, x86, uint64(uint64(x93)));
    let (x96, x97) = bits::Add64(x87, x84, uint64(uint64(x95)));
    let x98 = ((uint64(uint64(x97))).wrapping_add(x85));
    let (x99, x100) = bits::Add64(x75, x90, uint64(0x0));
    let (x101, x102) = bits::Add64(x77, x92, uint64(uint64(x100)));
    let (x103, x104) = bits::Add64(x79, x94, uint64(uint64(x102)));
    let (x105, x106) = bits::Add64(x81, x96, uint64(uint64(x104)));
    let (x107, x108) = bits::Add64(x83, x98, uint64(uint64(x106)));
    let (x110, x109) = bits::Mul64(x99, 0xffffffff00000001);
    let (x112, x111) = bits::Mul64(x99, 0xffffffff);
    let (x114, x113) = bits::Mul64(x99, 0xffffffffffffffff);
    let (x115, x116) = bits::Add64(x114, x111, uint64(0x0));
    let x117 = ((uint64(uint64(x116))).wrapping_add(x112));
    let (_, x119) = bits::Add64(x99, x113, uint64(0x0));
    let (x120, x121) = bits::Add64(x101, x115, uint64(uint64(x119)));
    let (x122, x123) = bits::Add64(x103, x117, uint64(uint64(x121)));
    let (x124, x125) = bits::Add64(x105, x109, uint64(uint64(x123)));
    let (x126, x127) = bits::Add64(x107, x110, uint64(uint64(x125)));
    let x128 = ((uint64(uint64(x127))).wrapping_add(uint64(uint64(x108))));
    let (x130, x129) = bits::Mul64(x3, arg1[3]);
    let (x132, x131) = bits::Mul64(x3, arg1[2]);
    let (x134, x133) = bits::Mul64(x3, arg1[1]);
    let (x136, x135) = bits::Mul64(x3, arg1[0]);
    let (x137, x138) = bits::Add64(x136, x133, uint64(0x0));
    let (x139, x140) = bits::Add64(x134, x131, uint64(uint64(x138)));
    let (x141, x142) = bits::Add64(x132, x129, uint64(uint64(x140)));
    let x143 = ((uint64(uint64(x142))).wrapping_add(x130));
    let (x144, x145) = bits::Add64(x120, x135, uint64(0x0));
    let (x146, x147) = bits::Add64(x122, x137, uint64(uint64(x145)));
    let (x148, x149) = bits::Add64(x124, x139, uint64(uint64(x147)));
    let (x150, x151) = bits::Add64(x126, x141, uint64(uint64(x149)));
    let (x152, x153) = bits::Add64(x128, x143, uint64(uint64(x151)));
    let (x155, x154) = bits::Mul64(x144, 0xffffffff00000001);
    let (x157, x156) = bits::Mul64(x144, 0xffffffff);
    let (x159, x158) = bits::Mul64(x144, 0xffffffffffffffff);
    let (x160, x161) = bits::Add64(x159, x156, uint64(0x0));
    let x162 = ((uint64(uint64(x161))).wrapping_add(x157));
    let (_, x164) = bits::Add64(x144, x158, uint64(0x0));
    let (x165, x166) = bits::Add64(x146, x160, uint64(uint64(x164)));
    let (x167, x168) = bits::Add64(x148, x162, uint64(uint64(x166)));
    let (x169, x170) = bits::Add64(x150, x154, uint64(uint64(x168)));
    let (x171, x172) = bits::Add64(x152, x155, uint64(uint64(x170)));
    let x173 = ((uint64(uint64(x172))).wrapping_add(uint64(uint64(x153))));
    let (x174, x175) = bits::Sub64(x165, 0xffffffffffffffff, uint64(0x0));
    let (x176, x177) = bits::Sub64(x167, 0xffffffff, uint64(uint64(x175)));
    let (x178, x179) = bits::Sub64(x169, uint64(0x0), uint64(uint64(x177)));
    let (x180, x181) = bits::Sub64(x171, 0xffffffff00000001, uint64(uint64(x179)));
    let (_, x183) = bits::Sub64(x173, uint64(0x0), uint64(uint64(x181)));
    let x184 = p256CmovznzU64(uint64(x183), x174, x165);
    let x185 = p256CmovznzU64(uint64(x183), x176, x167);
    let x186 = p256CmovznzU64(uint64(x183), x178, x169);
    let x187 = p256CmovznzU64(uint64(x183), x180, x171);
    out1[0] = x184;
    out1[1] = x185;
    out1[2] = x186;
    out1[3] = x187;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:663-702 p256Add
pub(super) fn p256Add(
    out1: &mut p256MontgomeryDomainFieldElement,
    arg1: &p256MontgomeryDomainFieldElement,
    arg2: &p256MontgomeryDomainFieldElement,
) {
    let (x1, x2) = bits::Add64(arg1[0], arg2[0], uint64(0x0));
    let (x3, x4) = bits::Add64(arg1[1], arg2[1], uint64(uint64(x2)));
    let (x5, x6) = bits::Add64(arg1[2], arg2[2], uint64(uint64(x4)));
    let (x7, x8) = bits::Add64(arg1[3], arg2[3], uint64(uint64(x6)));
    let (x9, x10) = bits::Sub64(x1, 0xffffffffffffffff, uint64(0x0));
    let (x11, x12) = bits::Sub64(x3, 0xffffffff, uint64(uint64(x10)));
    let (x13, x14) = bits::Sub64(x5, uint64(0x0), uint64(uint64(x12)));
    let (x15, x16) = bits::Sub64(x7, 0xffffffff00000001, uint64(uint64(x14)));
    let (_, x18) = bits::Sub64(uint64(uint64(x8)), uint64(0x0), uint64(uint64(x16)));
    let x19 = p256CmovznzU64(uint64(x18), x9, x1);
    let x20 = p256CmovznzU64(uint64(x18), x11, x3);
    let x21 = p256CmovznzU64(uint64(x18), x13, x5);
    let x22 = p256CmovznzU64(uint64(x18), x15, x7);
    out1[0] = x19;
    out1[1] = x20;
    out1[2] = x21;
    out1[3] = x22;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:715-745 p256Sub
pub(super) fn p256Sub(
    out1: &mut p256MontgomeryDomainFieldElement,
    arg1: &p256MontgomeryDomainFieldElement,
    arg2: &p256MontgomeryDomainFieldElement,
) {
    let (x1, x2) = bits::Sub64(arg1[0], arg2[0], uint64(0x0));
    let (x3, x4) = bits::Sub64(arg1[1], arg2[1], uint64(uint64(x2)));
    let (x5, x6) = bits::Sub64(arg1[2], arg2[2], uint64(uint64(x4)));
    let (x7, x8) = bits::Sub64(arg1[3], arg2[3], uint64(uint64(x6)));
    let x9 = p256CmovznzU64(uint64(x8), uint64(0x0), 0xffffffffffffffff);
    let (x10, x11) = bits::Add64(x1, x9, uint64(0x0));
    let (x12, x13) = bits::Add64(x3, (x9 & 0xffffffff), uint64(uint64(x11)));
    let (x14, x15) = bits::Add64(x5, uint64(0x0), uint64(uint64(x13)));
    let (x16, _) = bits::Add64(x7, (x9 & 0xffffffff00000001), uint64(uint64(x15)));
    out1[0] = x10;
    out1[1] = x12;
    out1[2] = x14;
    out1[3] = x16;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:753-758 p256SetOne
pub(super) fn p256SetOne(out1: &mut p256MontgomeryDomainFieldElement) {
    out1[0] = uint64(0x1);
    out1[1] = 0xffffffff00000000;
    out1[2] = 0xffffffffffffffff;
    out1[3] = 0xfffffffe;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:770-906 p256FromMontgomery
pub(super) fn p256FromMontgomery(
    out1: &mut p256NonMontgomeryDomainFieldElement,
    arg1: &p256MontgomeryDomainFieldElement,
) {
    let x1 = arg1[0];
    let (x3, x2) = bits::Mul64(x1, 0xffffffff00000001);
    let (x5, x4) = bits::Mul64(x1, 0xffffffff);
    let (x7, x6) = bits::Mul64(x1, 0xffffffffffffffff);
    let (x8, x9) = bits::Add64(x7, x4, uint64(0x0));
    let (_, x11) = bits::Add64(x1, x6, uint64(0x0));
    let (x12, x13) = bits::Add64(uint64(0x0), x8, uint64(uint64(x11)));
    let (x14, x15) = bits::Add64(x12, arg1[1], uint64(0x0));
    let (x17, x16) = bits::Mul64(x14, 0xffffffff00000001);
    let (x19, x18) = bits::Mul64(x14, 0xffffffff);
    let (x21, x20) = bits::Mul64(x14, 0xffffffffffffffff);
    let (x22, x23) = bits::Add64(x21, x18, uint64(0x0));
    let (_, x25) = bits::Add64(x14, x20, uint64(0x0));
    let (x26, x27) = bits::Add64(
        ((uint64(uint64(x15))).wrapping_add(
            ((uint64(uint64(x13))).wrapping_add(((uint64(uint64(x9))).wrapping_add(x5)))),
        )),
        x22,
        uint64(uint64(x25)),
    );
    let (x28, x29) = bits::Add64(
        x2,
        ((uint64(uint64(x23))).wrapping_add(x19)),
        uint64(uint64(x27)),
    );
    let (x30, x31) = bits::Add64(x3, x16, uint64(uint64(x29)));
    let (x32, x33) = bits::Add64(x26, arg1[2], uint64(0x0));
    let (x34, x35) = bits::Add64(x28, uint64(0x0), uint64(uint64(x33)));
    let (x36, x37) = bits::Add64(x30, uint64(0x0), uint64(uint64(x35)));
    let (x39, x38) = bits::Mul64(x32, 0xffffffff00000001);
    let (x41, x40) = bits::Mul64(x32, 0xffffffff);
    let (x43, x42) = bits::Mul64(x32, 0xffffffffffffffff);
    let (x44, x45) = bits::Add64(x43, x40, uint64(0x0));
    let (_, x47) = bits::Add64(x32, x42, uint64(0x0));
    let (x48, x49) = bits::Add64(x34, x44, uint64(uint64(x47)));
    let (x50, x51) = bits::Add64(
        x36,
        ((uint64(uint64(x45))).wrapping_add(x41)),
        uint64(uint64(x49)),
    );
    let (x52, x53) = bits::Add64(
        ((uint64(uint64(x37))).wrapping_add(((uint64(uint64(x31))).wrapping_add(x17)))),
        x38,
        uint64(uint64(x51)),
    );
    let (x54, x55) = bits::Add64(x48, arg1[3], uint64(0x0));
    let (x56, x57) = bits::Add64(x50, uint64(0x0), uint64(uint64(x55)));
    let (x58, x59) = bits::Add64(x52, uint64(0x0), uint64(uint64(x57)));
    let (x61, x60) = bits::Mul64(x54, 0xffffffff00000001);
    let (x63, x62) = bits::Mul64(x54, 0xffffffff);
    let (x65, x64) = bits::Mul64(x54, 0xffffffffffffffff);
    let (x66, x67) = bits::Add64(x65, x62, uint64(0x0));
    let (_, x69) = bits::Add64(x54, x64, uint64(0x0));
    let (x70, x71) = bits::Add64(x56, x66, uint64(uint64(x69)));
    let (x72, x73) = bits::Add64(
        x58,
        ((uint64(uint64(x67))).wrapping_add(x63)),
        uint64(uint64(x71)),
    );
    let (x74, x75) = bits::Add64(
        ((uint64(uint64(x59))).wrapping_add(((uint64(uint64(x53))).wrapping_add(x39)))),
        x60,
        uint64(uint64(x73)),
    );
    let x76 = ((uint64(uint64(x75))).wrapping_add(x61));
    let (x77, x78) = bits::Sub64(x70, 0xffffffffffffffff, uint64(0x0));
    let (x79, x80) = bits::Sub64(x72, 0xffffffff, uint64(uint64(x78)));
    let (x81, x82) = bits::Sub64(x74, uint64(0x0), uint64(uint64(x80)));
    let (x83, x84) = bits::Sub64(x76, 0xffffffff00000001, uint64(uint64(x82)));
    let (_, x86) = bits::Sub64(uint64(0x0), uint64(0x0), uint64(uint64(x84)));
    let x87 = p256CmovznzU64(uint64(x86), x77, x70);
    let x88 = p256CmovznzU64(uint64(x86), x79, x72);
    let x89 = p256CmovznzU64(uint64(x86), x81, x74);
    let x90 = p256CmovznzU64(uint64(x86), x83, x76);
    out1[0] = x87;
    out1[1] = x88;
    out1[2] = x89;
    out1[3] = x90;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:918-1173 p256ToMontgomery
pub(super) fn p256ToMontgomery(
    out1: &mut p256MontgomeryDomainFieldElement,
    arg1: &p256NonMontgomeryDomainFieldElement,
) {
    let x1 = arg1[1];
    let x2 = arg1[2];
    let x3 = arg1[3];
    let x4 = arg1[0];
    let (x6, x5) = bits::Mul64(x4, 0x4fffffffd);
    let (x8, x7) = bits::Mul64(x4, 0xfffffffffffffffe);
    let (x10, x9) = bits::Mul64(x4, 0xfffffffbffffffff);
    let (x12, x11) = bits::Mul64(x4, 0x3);
    let (x13, x14) = bits::Add64(x12, x9, uint64(0x0));
    let (x15, x16) = bits::Add64(x10, x7, uint64(uint64(x14)));
    let (x17, x18) = bits::Add64(x8, x5, uint64(uint64(x16)));
    let (x20, x19) = bits::Mul64(x11, 0xffffffff00000001);
    let (x22, x21) = bits::Mul64(x11, 0xffffffff);
    let (x24, x23) = bits::Mul64(x11, 0xffffffffffffffff);
    let (x25, x26) = bits::Add64(x24, x21, uint64(0x0));
    let (_, x28) = bits::Add64(x11, x23, uint64(0x0));
    let (x29, x30) = bits::Add64(x13, x25, uint64(uint64(x28)));
    let (x31, x32) = bits::Add64(
        x15,
        ((uint64(uint64(x26))).wrapping_add(x22)),
        uint64(uint64(x30)),
    );
    let (x33, x34) = bits::Add64(x17, x19, uint64(uint64(x32)));
    let (x35, x36) = bits::Add64(
        ((uint64(uint64(x18))).wrapping_add(x6)),
        x20,
        uint64(uint64(x34)),
    );
    let (x38, x37) = bits::Mul64(x1, 0x4fffffffd);
    let (x40, x39) = bits::Mul64(x1, 0xfffffffffffffffe);
    let (x42, x41) = bits::Mul64(x1, 0xfffffffbffffffff);
    let (x44, x43) = bits::Mul64(x1, 0x3);
    let (x45, x46) = bits::Add64(x44, x41, uint64(0x0));
    let (x47, x48) = bits::Add64(x42, x39, uint64(uint64(x46)));
    let (x49, x50) = bits::Add64(x40, x37, uint64(uint64(x48)));
    let (x51, x52) = bits::Add64(x29, x43, uint64(0x0));
    let (x53, x54) = bits::Add64(x31, x45, uint64(uint64(x52)));
    let (x55, x56) = bits::Add64(x33, x47, uint64(uint64(x54)));
    let (x57, x58) = bits::Add64(x35, x49, uint64(uint64(x56)));
    let (x60, x59) = bits::Mul64(x51, 0xffffffff00000001);
    let (x62, x61) = bits::Mul64(x51, 0xffffffff);
    let (x64, x63) = bits::Mul64(x51, 0xffffffffffffffff);
    let (x65, x66) = bits::Add64(x64, x61, uint64(0x0));
    let (_, x68) = bits::Add64(x51, x63, uint64(0x0));
    let (x69, x70) = bits::Add64(x53, x65, uint64(uint64(x68)));
    let (x71, x72) = bits::Add64(
        x55,
        ((uint64(uint64(x66))).wrapping_add(x62)),
        uint64(uint64(x70)),
    );
    let (x73, x74) = bits::Add64(x57, x59, uint64(uint64(x72)));
    let (x75, x76) = bits::Add64(
        (((uint64(uint64(x58))).wrapping_add(uint64(uint64(x36))))
            .wrapping_add(((uint64(uint64(x50))).wrapping_add(x38)))),
        x60,
        uint64(uint64(x74)),
    );
    let (x78, x77) = bits::Mul64(x2, 0x4fffffffd);
    let (x80, x79) = bits::Mul64(x2, 0xfffffffffffffffe);
    let (x82, x81) = bits::Mul64(x2, 0xfffffffbffffffff);
    let (x84, x83) = bits::Mul64(x2, 0x3);
    let (x85, x86) = bits::Add64(x84, x81, uint64(0x0));
    let (x87, x88) = bits::Add64(x82, x79, uint64(uint64(x86)));
    let (x89, x90) = bits::Add64(x80, x77, uint64(uint64(x88)));
    let (x91, x92) = bits::Add64(x69, x83, uint64(0x0));
    let (x93, x94) = bits::Add64(x71, x85, uint64(uint64(x92)));
    let (x95, x96) = bits::Add64(x73, x87, uint64(uint64(x94)));
    let (x97, x98) = bits::Add64(x75, x89, uint64(uint64(x96)));
    let (x100, x99) = bits::Mul64(x91, 0xffffffff00000001);
    let (x102, x101) = bits::Mul64(x91, 0xffffffff);
    let (x104, x103) = bits::Mul64(x91, 0xffffffffffffffff);
    let (x105, x106) = bits::Add64(x104, x101, uint64(0x0));
    let (_, x108) = bits::Add64(x91, x103, uint64(0x0));
    let (x109, x110) = bits::Add64(x93, x105, uint64(uint64(x108)));
    let (x111, x112) = bits::Add64(
        x95,
        ((uint64(uint64(x106))).wrapping_add(x102)),
        uint64(uint64(x110)),
    );
    let (x113, x114) = bits::Add64(x97, x99, uint64(uint64(x112)));
    let (x115, x116) = bits::Add64(
        (((uint64(uint64(x98))).wrapping_add(uint64(uint64(x76))))
            .wrapping_add(((uint64(uint64(x90))).wrapping_add(x78)))),
        x100,
        uint64(uint64(x114)),
    );
    let (x118, x117) = bits::Mul64(x3, 0x4fffffffd);
    let (x120, x119) = bits::Mul64(x3, 0xfffffffffffffffe);
    let (x122, x121) = bits::Mul64(x3, 0xfffffffbffffffff);
    let (x124, x123) = bits::Mul64(x3, 0x3);
    let (x125, x126) = bits::Add64(x124, x121, uint64(0x0));
    let (x127, x128) = bits::Add64(x122, x119, uint64(uint64(x126)));
    let (x129, x130) = bits::Add64(x120, x117, uint64(uint64(x128)));
    let (x131, x132) = bits::Add64(x109, x123, uint64(0x0));
    let (x133, x134) = bits::Add64(x111, x125, uint64(uint64(x132)));
    let (x135, x136) = bits::Add64(x113, x127, uint64(uint64(x134)));
    let (x137, x138) = bits::Add64(x115, x129, uint64(uint64(x136)));
    let (x140, x139) = bits::Mul64(x131, 0xffffffff00000001);
    let (x142, x141) = bits::Mul64(x131, 0xffffffff);
    let (x144, x143) = bits::Mul64(x131, 0xffffffffffffffff);
    let (x145, x146) = bits::Add64(x144, x141, uint64(0x0));
    let (_, x148) = bits::Add64(x131, x143, uint64(0x0));
    let (x149, x150) = bits::Add64(x133, x145, uint64(uint64(x148)));
    let (x151, x152) = bits::Add64(
        x135,
        ((uint64(uint64(x146))).wrapping_add(x142)),
        uint64(uint64(x150)),
    );
    let (x153, x154) = bits::Add64(x137, x139, uint64(uint64(x152)));
    let (x155, x156) = bits::Add64(
        (((uint64(uint64(x138))).wrapping_add(uint64(uint64(x116))))
            .wrapping_add(((uint64(uint64(x130))).wrapping_add(x118)))),
        x140,
        uint64(uint64(x154)),
    );
    let (x157, x158) = bits::Sub64(x149, 0xffffffffffffffff, uint64(0x0));
    let (x159, x160) = bits::Sub64(x151, 0xffffffff, uint64(uint64(x158)));
    let (x161, x162) = bits::Sub64(x153, uint64(0x0), uint64(uint64(x160)));
    let (x163, x164) = bits::Sub64(x155, 0xffffffff00000001, uint64(uint64(x162)));
    let (_, x166) = bits::Sub64(uint64(uint64(x156)), uint64(0x0), uint64(uint64(x164)));
    let x167 = p256CmovznzU64(uint64(x166), x157, x149);
    let x168 = p256CmovznzU64(uint64(x166), x159, x151);
    let x169 = p256CmovznzU64(uint64(x166), x161, x153);
    let x170 = p256CmovznzU64(uint64(x166), x163, x155);
    out1[0] = x167;
    out1[1] = x168;
    out1[2] = x169;
    out1[3] = x170;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:1190-1203 p256Selectznz
pub(super) fn p256Selectznz(
    out1: &mut [u64; 4],
    arg1: p256Uint1,
    arg2: &[u64; 4],
    arg3: &[u64; 4],
) {
    let x1 = p256CmovznzU64(arg1, arg2[0], arg3[0]);
    let x2 = p256CmovznzU64(arg1, arg2[1], arg3[1]);
    let x3 = p256CmovznzU64(arg1, arg2[2], arg3[2]);
    let x4 = p256CmovznzU64(arg1, arg2[3], arg3[3]);
    out1[0] = x1;
    out1[1] = x2;
    out1[2] = x3;
    out1[3] = x4;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:1222-1315 p256ToBytes
pub(super) fn p256ToBytes(out1: &mut [u8; 32], arg1: &[u64; 4]) {
    let x1 = arg1[3];
    let x2 = arg1[2];
    let x3 = arg1[1];
    let x4 = arg1[0];
    let x5 = (uint8(x4) & 0xff);
    let x6 = (x4 >> 8);
    let x7 = (uint8(x6) & 0xff);
    let x8 = (x6 >> 8);
    let x9 = (uint8(x8) & 0xff);
    let x10 = (x8 >> 8);
    let x11 = (uint8(x10) & 0xff);
    let x12 = (x10 >> 8);
    let x13 = (uint8(x12) & 0xff);
    let x14 = (x12 >> 8);
    let x15 = (uint8(x14) & 0xff);
    let x16 = (x14 >> 8);
    let x17 = (uint8(x16) & 0xff);
    let x18 = uint8((x16 >> 8));
    let x19 = (uint8(x3) & 0xff);
    let x20 = (x3 >> 8);
    let x21 = (uint8(x20) & 0xff);
    let x22 = (x20 >> 8);
    let x23 = (uint8(x22) & 0xff);
    let x24 = (x22 >> 8);
    let x25 = (uint8(x24) & 0xff);
    let x26 = (x24 >> 8);
    let x27 = (uint8(x26) & 0xff);
    let x28 = (x26 >> 8);
    let x29 = (uint8(x28) & 0xff);
    let x30 = (x28 >> 8);
    let x31 = (uint8(x30) & 0xff);
    let x32 = uint8((x30 >> 8));
    let x33 = (uint8(x2) & 0xff);
    let x34 = (x2 >> 8);
    let x35 = (uint8(x34) & 0xff);
    let x36 = (x34 >> 8);
    let x37 = (uint8(x36) & 0xff);
    let x38 = (x36 >> 8);
    let x39 = (uint8(x38) & 0xff);
    let x40 = (x38 >> 8);
    let x41 = (uint8(x40) & 0xff);
    let x42 = (x40 >> 8);
    let x43 = (uint8(x42) & 0xff);
    let x44 = (x42 >> 8);
    let x45 = (uint8(x44) & 0xff);
    let x46 = uint8((x44 >> 8));
    let x47 = (uint8(x1) & 0xff);
    let x48 = (x1 >> 8);
    let x49 = (uint8(x48) & 0xff);
    let x50 = (x48 >> 8);
    let x51 = (uint8(x50) & 0xff);
    let x52 = (x50 >> 8);
    let x53 = (uint8(x52) & 0xff);
    let x54 = (x52 >> 8);
    let x55 = (uint8(x54) & 0xff);
    let x56 = (x54 >> 8);
    let x57 = (uint8(x56) & 0xff);
    let x58 = (x56 >> 8);
    let x59 = (uint8(x58) & 0xff);
    let x60 = uint8((x58 >> 8));
    out1[0] = x5;
    out1[1] = x7;
    out1[2] = x9;
    out1[3] = x11;
    out1[4] = x13;
    out1[5] = x15;
    out1[6] = x17;
    out1[7] = x18;
    out1[8] = x19;
    out1[9] = x21;
    out1[10] = x23;
    out1[11] = x25;
    out1[12] = x27;
    out1[13] = x29;
    out1[14] = x31;
    out1[15] = x32;
    out1[16] = x33;
    out1[17] = x35;
    out1[18] = x37;
    out1[19] = x39;
    out1[20] = x41;
    out1[21] = x43;
    out1[22] = x45;
    out1[23] = x46;
    out1[24] = x47;
    out1[25] = x49;
    out1[26] = x51;
    out1[27] = x53;
    out1[28] = x55;
    out1[29] = x57;
    out1[30] = x59;
    out1[31] = x60;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p256_fiat64.go:1335-1400 p256FromBytes
pub(super) fn p256FromBytes(out1: &mut [u64; 4], arg1: &[u8; 32]) {
    let x1 = (uint64(arg1[31]) << 56);
    let x2 = (uint64(arg1[30]) << 48);
    let x3 = (uint64(arg1[29]) << 40);
    let x4 = (uint64(arg1[28]) << 32);
    let x5 = (uint64(arg1[27]) << 24);
    let x6 = (uint64(arg1[26]) << 16);
    let x7 = (uint64(arg1[25]) << 8);
    let x8 = arg1[24];
    let x9 = (uint64(arg1[23]) << 56);
    let x10 = (uint64(arg1[22]) << 48);
    let x11 = (uint64(arg1[21]) << 40);
    let x12 = (uint64(arg1[20]) << 32);
    let x13 = (uint64(arg1[19]) << 24);
    let x14 = (uint64(arg1[18]) << 16);
    let x15 = (uint64(arg1[17]) << 8);
    let x16 = arg1[16];
    let x17 = (uint64(arg1[15]) << 56);
    let x18 = (uint64(arg1[14]) << 48);
    let x19 = (uint64(arg1[13]) << 40);
    let x20 = (uint64(arg1[12]) << 32);
    let x21 = (uint64(arg1[11]) << 24);
    let x22 = (uint64(arg1[10]) << 16);
    let x23 = (uint64(arg1[9]) << 8);
    let x24 = arg1[8];
    let x25 = (uint64(arg1[7]) << 56);
    let x26 = (uint64(arg1[6]) << 48);
    let x27 = (uint64(arg1[5]) << 40);
    let x28 = (uint64(arg1[4]) << 32);
    let x29 = (uint64(arg1[3]) << 24);
    let x30 = (uint64(arg1[2]) << 16);
    let x31 = (uint64(arg1[1]) << 8);
    let x32 = arg1[0];
    let x33 = ((x31).wrapping_add(uint64(x32)));
    let x34 = ((x30).wrapping_add(x33));
    let x35 = ((x29).wrapping_add(x34));
    let x36 = ((x28).wrapping_add(x35));
    let x37 = ((x27).wrapping_add(x36));
    let x38 = ((x26).wrapping_add(x37));
    let x39 = ((x25).wrapping_add(x38));
    let x40 = ((x23).wrapping_add(uint64(x24)));
    let x41 = ((x22).wrapping_add(x40));
    let x42 = ((x21).wrapping_add(x41));
    let x43 = ((x20).wrapping_add(x42));
    let x44 = ((x19).wrapping_add(x43));
    let x45 = ((x18).wrapping_add(x44));
    let x46 = ((x17).wrapping_add(x45));
    let x47 = ((x15).wrapping_add(uint64(x16)));
    let x48 = ((x14).wrapping_add(x47));
    let x49 = ((x13).wrapping_add(x48));
    let x50 = ((x12).wrapping_add(x49));
    let x51 = ((x11).wrapping_add(x50));
    let x52 = ((x10).wrapping_add(x51));
    let x53 = ((x9).wrapping_add(x52));
    let x54 = ((x7).wrapping_add(uint64(x8)));
    let x55 = ((x6).wrapping_add(x54));
    let x56 = ((x5).wrapping_add(x55));
    let x57 = ((x4).wrapping_add(x56));
    let x58 = ((x3).wrapping_add(x57));
    let x59 = ((x2).wrapping_add(x58));
    let x60 = ((x1).wrapping_add(x59));
    out1[0] = x39;
    out1[1] = x46;
    out1[2] = x53;
    out1[3] = x60;
}
