// go: file crypto/internal/fips140/nistec/fiat/p384_fiat64.go decls: p384CmovznzU64, p384Mul, p384Square, p384Add, p384Sub, p384SetOne, p384FromMontgomery, p384ToMontgomery, p384Selectznz, p384ToBytes, p384FromBytes
//
// Code generated by Fiat Cryptography. DO NOT EDIT.
//
// Translated from Go by scripts/fiat64_to_rust.py, which parses the
// closed grammar these generated files use and raises on anything it does
// not recognise — it can fail to translate, but not silently
// mistranslate. Regenerate with `scripts/fiat_gen.py`; do not hand-edit.
//
// curve description: p384   |   machine_wordsize = 64   |   limbs = 6
//
// Two shape changes, both forced:
//
//   * Go's uint64 arithmetic wraps; Rust's panics in debug builds. Every
//     `+` is wrapping_add and every `*` is wrapping_mul.
//   * `p384CmovznzU64` returns its result rather than writing through an
//     `out1 *uint64`. The out-parameter is a fiat-crypto calling
//     convention, not part of the algorithm.
//
// `p384Uint1`/`p384Int1` and the Montgomery/NonMontgomery element types are
// all defined in Go as `uint64`, `int64` and `[6]uint64` respectively,
// so every conversion between them is a value-level no-op and is elided.

#![allow(non_snake_case, non_camel_case_types)]
// The parenthesisation mirrors the Go source, which is itself machine
// output; stripping it would make the two harder to diff.
#![allow(unused_parens)]
//
// goishlint:ignore GOISH020 — `p384CmovznzU64` returns its result where Go
// writes it through an `out1 *uint64` first parameter, so the arity is 3
// against Go's 4. The out-parameter is a fiat-crypto calling convention.

use crate::math::bits;
use crate::{uint64, uint8};

/// Go: `type p384Uint1 uint64` — "We use uint64 instead of a more narrow
/// type for performance reasons."
pub(super) type p384Uint1 = u64;

/// Go: `type p384Int1 int64`. Declared by Fiat Cryptography but not used
/// by any function it generates, here or in Go.
#[allow(dead_code)]
pub(super) type p384Int1 = i64;

/// Go: `type p384MontgomeryDomainFieldElement [6]uint64` — a field
/// element in the Montgomery domain.
pub(super) type p384MontgomeryDomainFieldElement = [u64; 6];

/// Go: `type p384NonMontgomeryDomainFieldElement [6]uint64` — a field
/// element NOT in the Montgomery domain.
pub(super) type p384NonMontgomeryDomainFieldElement = [u64; 6];

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:71-75 p384CmovznzU64
/// A single-word conditional move: `if arg1 = 0 then arg2
/// else arg3`.
///
/// Go writes the result through `out1 *uint64`; that is a
/// fiat-crypto calling convention, not part of the
/// algorithm, so this returns it instead.
pub(super) fn p384CmovznzU64(arg1: u64, arg2: u64, arg3: u64) -> u64 {
    let x1 = ((uint64(arg1)).wrapping_mul(0xffffffffffffffff));
    let x2 = ((x1 & arg3) | ((!x1) & arg2));
    return x2;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:88-783 p384Mul
pub(super) fn p384Mul(
    out1: &mut p384MontgomeryDomainFieldElement,
    arg1: &p384MontgomeryDomainFieldElement,
    arg2: &p384MontgomeryDomainFieldElement,
) {
    let x1 = arg1[1];
    let x2 = arg1[2];
    let x3 = arg1[3];
    let x4 = arg1[4];
    let x5 = arg1[5];
    let x6 = arg1[0];
    let (x8, x7) = bits::Mul64(x6, arg2[5]);
    let (x10, x9) = bits::Mul64(x6, arg2[4]);
    let (x12, x11) = bits::Mul64(x6, arg2[3]);
    let (x14, x13) = bits::Mul64(x6, arg2[2]);
    let (x16, x15) = bits::Mul64(x6, arg2[1]);
    let (x18, x17) = bits::Mul64(x6, arg2[0]);
    let (x19, x20) = bits::Add64(x18, x15, uint64(0x0));
    let (x21, x22) = bits::Add64(x16, x13, uint64(uint64(x20)));
    let (x23, x24) = bits::Add64(x14, x11, uint64(uint64(x22)));
    let (x25, x26) = bits::Add64(x12, x9, uint64(uint64(x24)));
    let (x27, x28) = bits::Add64(x10, x7, uint64(uint64(x26)));
    let x29 = ((uint64(uint64(x28))).wrapping_add(x8));
    let (_, x30) = bits::Mul64(x17, 0x100000001);
    let (x33, x32) = bits::Mul64(x30, 0xffffffffffffffff);
    let (x35, x34) = bits::Mul64(x30, 0xffffffffffffffff);
    let (x37, x36) = bits::Mul64(x30, 0xffffffffffffffff);
    let (x39, x38) = bits::Mul64(x30, 0xfffffffffffffffe);
    let (x41, x40) = bits::Mul64(x30, 0xffffffff00000000);
    let (x43, x42) = bits::Mul64(x30, 0xffffffff);
    let (x44, x45) = bits::Add64(x43, x40, uint64(0x0));
    let (x46, x47) = bits::Add64(x41, x38, uint64(uint64(x45)));
    let (x48, x49) = bits::Add64(x39, x36, uint64(uint64(x47)));
    let (x50, x51) = bits::Add64(x37, x34, uint64(uint64(x49)));
    let (x52, x53) = bits::Add64(x35, x32, uint64(uint64(x51)));
    let x54 = ((uint64(uint64(x53))).wrapping_add(x33));
    let (_, x56) = bits::Add64(x17, x42, uint64(0x0));
    let (x57, x58) = bits::Add64(x19, x44, uint64(uint64(x56)));
    let (x59, x60) = bits::Add64(x21, x46, uint64(uint64(x58)));
    let (x61, x62) = bits::Add64(x23, x48, uint64(uint64(x60)));
    let (x63, x64) = bits::Add64(x25, x50, uint64(uint64(x62)));
    let (x65, x66) = bits::Add64(x27, x52, uint64(uint64(x64)));
    let (x67, x68) = bits::Add64(x29, x54, uint64(uint64(x66)));
    let (x70, x69) = bits::Mul64(x1, arg2[5]);
    let (x72, x71) = bits::Mul64(x1, arg2[4]);
    let (x74, x73) = bits::Mul64(x1, arg2[3]);
    let (x76, x75) = bits::Mul64(x1, arg2[2]);
    let (x78, x77) = bits::Mul64(x1, arg2[1]);
    let (x80, x79) = bits::Mul64(x1, arg2[0]);
    let (x81, x82) = bits::Add64(x80, x77, uint64(0x0));
    let (x83, x84) = bits::Add64(x78, x75, uint64(uint64(x82)));
    let (x85, x86) = bits::Add64(x76, x73, uint64(uint64(x84)));
    let (x87, x88) = bits::Add64(x74, x71, uint64(uint64(x86)));
    let (x89, x90) = bits::Add64(x72, x69, uint64(uint64(x88)));
    let x91 = ((uint64(uint64(x90))).wrapping_add(x70));
    let (x92, x93) = bits::Add64(x57, x79, uint64(0x0));
    let (x94, x95) = bits::Add64(x59, x81, uint64(uint64(x93)));
    let (x96, x97) = bits::Add64(x61, x83, uint64(uint64(x95)));
    let (x98, x99) = bits::Add64(x63, x85, uint64(uint64(x97)));
    let (x100, x101) = bits::Add64(x65, x87, uint64(uint64(x99)));
    let (x102, x103) = bits::Add64(x67, x89, uint64(uint64(x101)));
    let (x104, x105) = bits::Add64(uint64(uint64(x68)), x91, uint64(uint64(x103)));
    let (_, x106) = bits::Mul64(x92, 0x100000001);
    let (x109, x108) = bits::Mul64(x106, 0xffffffffffffffff);
    let (x111, x110) = bits::Mul64(x106, 0xffffffffffffffff);
    let (x113, x112) = bits::Mul64(x106, 0xffffffffffffffff);
    let (x115, x114) = bits::Mul64(x106, 0xfffffffffffffffe);
    let (x117, x116) = bits::Mul64(x106, 0xffffffff00000000);
    let (x119, x118) = bits::Mul64(x106, 0xffffffff);
    let (x120, x121) = bits::Add64(x119, x116, uint64(0x0));
    let (x122, x123) = bits::Add64(x117, x114, uint64(uint64(x121)));
    let (x124, x125) = bits::Add64(x115, x112, uint64(uint64(x123)));
    let (x126, x127) = bits::Add64(x113, x110, uint64(uint64(x125)));
    let (x128, x129) = bits::Add64(x111, x108, uint64(uint64(x127)));
    let x130 = ((uint64(uint64(x129))).wrapping_add(x109));
    let (_, x132) = bits::Add64(x92, x118, uint64(0x0));
    let (x133, x134) = bits::Add64(x94, x120, uint64(uint64(x132)));
    let (x135, x136) = bits::Add64(x96, x122, uint64(uint64(x134)));
    let (x137, x138) = bits::Add64(x98, x124, uint64(uint64(x136)));
    let (x139, x140) = bits::Add64(x100, x126, uint64(uint64(x138)));
    let (x141, x142) = bits::Add64(x102, x128, uint64(uint64(x140)));
    let (x143, x144) = bits::Add64(x104, x130, uint64(uint64(x142)));
    let x145 = ((uint64(uint64(x144))).wrapping_add(uint64(uint64(x105))));
    let (x147, x146) = bits::Mul64(x2, arg2[5]);
    let (x149, x148) = bits::Mul64(x2, arg2[4]);
    let (x151, x150) = bits::Mul64(x2, arg2[3]);
    let (x153, x152) = bits::Mul64(x2, arg2[2]);
    let (x155, x154) = bits::Mul64(x2, arg2[1]);
    let (x157, x156) = bits::Mul64(x2, arg2[0]);
    let (x158, x159) = bits::Add64(x157, x154, uint64(0x0));
    let (x160, x161) = bits::Add64(x155, x152, uint64(uint64(x159)));
    let (x162, x163) = bits::Add64(x153, x150, uint64(uint64(x161)));
    let (x164, x165) = bits::Add64(x151, x148, uint64(uint64(x163)));
    let (x166, x167) = bits::Add64(x149, x146, uint64(uint64(x165)));
    let x168 = ((uint64(uint64(x167))).wrapping_add(x147));
    let (x169, x170) = bits::Add64(x133, x156, uint64(0x0));
    let (x171, x172) = bits::Add64(x135, x158, uint64(uint64(x170)));
    let (x173, x174) = bits::Add64(x137, x160, uint64(uint64(x172)));
    let (x175, x176) = bits::Add64(x139, x162, uint64(uint64(x174)));
    let (x177, x178) = bits::Add64(x141, x164, uint64(uint64(x176)));
    let (x179, x180) = bits::Add64(x143, x166, uint64(uint64(x178)));
    let (x181, x182) = bits::Add64(x145, x168, uint64(uint64(x180)));
    let (_, x183) = bits::Mul64(x169, 0x100000001);
    let (x186, x185) = bits::Mul64(x183, 0xffffffffffffffff);
    let (x188, x187) = bits::Mul64(x183, 0xffffffffffffffff);
    let (x190, x189) = bits::Mul64(x183, 0xffffffffffffffff);
    let (x192, x191) = bits::Mul64(x183, 0xfffffffffffffffe);
    let (x194, x193) = bits::Mul64(x183, 0xffffffff00000000);
    let (x196, x195) = bits::Mul64(x183, 0xffffffff);
    let (x197, x198) = bits::Add64(x196, x193, uint64(0x0));
    let (x199, x200) = bits::Add64(x194, x191, uint64(uint64(x198)));
    let (x201, x202) = bits::Add64(x192, x189, uint64(uint64(x200)));
    let (x203, x204) = bits::Add64(x190, x187, uint64(uint64(x202)));
    let (x205, x206) = bits::Add64(x188, x185, uint64(uint64(x204)));
    let x207 = ((uint64(uint64(x206))).wrapping_add(x186));
    let (_, x209) = bits::Add64(x169, x195, uint64(0x0));
    let (x210, x211) = bits::Add64(x171, x197, uint64(uint64(x209)));
    let (x212, x213) = bits::Add64(x173, x199, uint64(uint64(x211)));
    let (x214, x215) = bits::Add64(x175, x201, uint64(uint64(x213)));
    let (x216, x217) = bits::Add64(x177, x203, uint64(uint64(x215)));
    let (x218, x219) = bits::Add64(x179, x205, uint64(uint64(x217)));
    let (x220, x221) = bits::Add64(x181, x207, uint64(uint64(x219)));
    let x222 = ((uint64(uint64(x221))).wrapping_add(uint64(uint64(x182))));
    let (x224, x223) = bits::Mul64(x3, arg2[5]);
    let (x226, x225) = bits::Mul64(x3, arg2[4]);
    let (x228, x227) = bits::Mul64(x3, arg2[3]);
    let (x230, x229) = bits::Mul64(x3, arg2[2]);
    let (x232, x231) = bits::Mul64(x3, arg2[1]);
    let (x234, x233) = bits::Mul64(x3, arg2[0]);
    let (x235, x236) = bits::Add64(x234, x231, uint64(0x0));
    let (x237, x238) = bits::Add64(x232, x229, uint64(uint64(x236)));
    let (x239, x240) = bits::Add64(x230, x227, uint64(uint64(x238)));
    let (x241, x242) = bits::Add64(x228, x225, uint64(uint64(x240)));
    let (x243, x244) = bits::Add64(x226, x223, uint64(uint64(x242)));
    let x245 = ((uint64(uint64(x244))).wrapping_add(x224));
    let (x246, x247) = bits::Add64(x210, x233, uint64(0x0));
    let (x248, x249) = bits::Add64(x212, x235, uint64(uint64(x247)));
    let (x250, x251) = bits::Add64(x214, x237, uint64(uint64(x249)));
    let (x252, x253) = bits::Add64(x216, x239, uint64(uint64(x251)));
    let (x254, x255) = bits::Add64(x218, x241, uint64(uint64(x253)));
    let (x256, x257) = bits::Add64(x220, x243, uint64(uint64(x255)));
    let (x258, x259) = bits::Add64(x222, x245, uint64(uint64(x257)));
    let (_, x260) = bits::Mul64(x246, 0x100000001);
    let (x263, x262) = bits::Mul64(x260, 0xffffffffffffffff);
    let (x265, x264) = bits::Mul64(x260, 0xffffffffffffffff);
    let (x267, x266) = bits::Mul64(x260, 0xffffffffffffffff);
    let (x269, x268) = bits::Mul64(x260, 0xfffffffffffffffe);
    let (x271, x270) = bits::Mul64(x260, 0xffffffff00000000);
    let (x273, x272) = bits::Mul64(x260, 0xffffffff);
    let (x274, x275) = bits::Add64(x273, x270, uint64(0x0));
    let (x276, x277) = bits::Add64(x271, x268, uint64(uint64(x275)));
    let (x278, x279) = bits::Add64(x269, x266, uint64(uint64(x277)));
    let (x280, x281) = bits::Add64(x267, x264, uint64(uint64(x279)));
    let (x282, x283) = bits::Add64(x265, x262, uint64(uint64(x281)));
    let x284 = ((uint64(uint64(x283))).wrapping_add(x263));
    let (_, x286) = bits::Add64(x246, x272, uint64(0x0));
    let (x287, x288) = bits::Add64(x248, x274, uint64(uint64(x286)));
    let (x289, x290) = bits::Add64(x250, x276, uint64(uint64(x288)));
    let (x291, x292) = bits::Add64(x252, x278, uint64(uint64(x290)));
    let (x293, x294) = bits::Add64(x254, x280, uint64(uint64(x292)));
    let (x295, x296) = bits::Add64(x256, x282, uint64(uint64(x294)));
    let (x297, x298) = bits::Add64(x258, x284, uint64(uint64(x296)));
    let x299 = ((uint64(uint64(x298))).wrapping_add(uint64(uint64(x259))));
    let (x301, x300) = bits::Mul64(x4, arg2[5]);
    let (x303, x302) = bits::Mul64(x4, arg2[4]);
    let (x305, x304) = bits::Mul64(x4, arg2[3]);
    let (x307, x306) = bits::Mul64(x4, arg2[2]);
    let (x309, x308) = bits::Mul64(x4, arg2[1]);
    let (x311, x310) = bits::Mul64(x4, arg2[0]);
    let (x312, x313) = bits::Add64(x311, x308, uint64(0x0));
    let (x314, x315) = bits::Add64(x309, x306, uint64(uint64(x313)));
    let (x316, x317) = bits::Add64(x307, x304, uint64(uint64(x315)));
    let (x318, x319) = bits::Add64(x305, x302, uint64(uint64(x317)));
    let (x320, x321) = bits::Add64(x303, x300, uint64(uint64(x319)));
    let x322 = ((uint64(uint64(x321))).wrapping_add(x301));
    let (x323, x324) = bits::Add64(x287, x310, uint64(0x0));
    let (x325, x326) = bits::Add64(x289, x312, uint64(uint64(x324)));
    let (x327, x328) = bits::Add64(x291, x314, uint64(uint64(x326)));
    let (x329, x330) = bits::Add64(x293, x316, uint64(uint64(x328)));
    let (x331, x332) = bits::Add64(x295, x318, uint64(uint64(x330)));
    let (x333, x334) = bits::Add64(x297, x320, uint64(uint64(x332)));
    let (x335, x336) = bits::Add64(x299, x322, uint64(uint64(x334)));
    let (_, x337) = bits::Mul64(x323, 0x100000001);
    let (x340, x339) = bits::Mul64(x337, 0xffffffffffffffff);
    let (x342, x341) = bits::Mul64(x337, 0xffffffffffffffff);
    let (x344, x343) = bits::Mul64(x337, 0xffffffffffffffff);
    let (x346, x345) = bits::Mul64(x337, 0xfffffffffffffffe);
    let (x348, x347) = bits::Mul64(x337, 0xffffffff00000000);
    let (x350, x349) = bits::Mul64(x337, 0xffffffff);
    let (x351, x352) = bits::Add64(x350, x347, uint64(0x0));
    let (x353, x354) = bits::Add64(x348, x345, uint64(uint64(x352)));
    let (x355, x356) = bits::Add64(x346, x343, uint64(uint64(x354)));
    let (x357, x358) = bits::Add64(x344, x341, uint64(uint64(x356)));
    let (x359, x360) = bits::Add64(x342, x339, uint64(uint64(x358)));
    let x361 = ((uint64(uint64(x360))).wrapping_add(x340));
    let (_, x363) = bits::Add64(x323, x349, uint64(0x0));
    let (x364, x365) = bits::Add64(x325, x351, uint64(uint64(x363)));
    let (x366, x367) = bits::Add64(x327, x353, uint64(uint64(x365)));
    let (x368, x369) = bits::Add64(x329, x355, uint64(uint64(x367)));
    let (x370, x371) = bits::Add64(x331, x357, uint64(uint64(x369)));
    let (x372, x373) = bits::Add64(x333, x359, uint64(uint64(x371)));
    let (x374, x375) = bits::Add64(x335, x361, uint64(uint64(x373)));
    let x376 = ((uint64(uint64(x375))).wrapping_add(uint64(uint64(x336))));
    let (x378, x377) = bits::Mul64(x5, arg2[5]);
    let (x380, x379) = bits::Mul64(x5, arg2[4]);
    let (x382, x381) = bits::Mul64(x5, arg2[3]);
    let (x384, x383) = bits::Mul64(x5, arg2[2]);
    let (x386, x385) = bits::Mul64(x5, arg2[1]);
    let (x388, x387) = bits::Mul64(x5, arg2[0]);
    let (x389, x390) = bits::Add64(x388, x385, uint64(0x0));
    let (x391, x392) = bits::Add64(x386, x383, uint64(uint64(x390)));
    let (x393, x394) = bits::Add64(x384, x381, uint64(uint64(x392)));
    let (x395, x396) = bits::Add64(x382, x379, uint64(uint64(x394)));
    let (x397, x398) = bits::Add64(x380, x377, uint64(uint64(x396)));
    let x399 = ((uint64(uint64(x398))).wrapping_add(x378));
    let (x400, x401) = bits::Add64(x364, x387, uint64(0x0));
    let (x402, x403) = bits::Add64(x366, x389, uint64(uint64(x401)));
    let (x404, x405) = bits::Add64(x368, x391, uint64(uint64(x403)));
    let (x406, x407) = bits::Add64(x370, x393, uint64(uint64(x405)));
    let (x408, x409) = bits::Add64(x372, x395, uint64(uint64(x407)));
    let (x410, x411) = bits::Add64(x374, x397, uint64(uint64(x409)));
    let (x412, x413) = bits::Add64(x376, x399, uint64(uint64(x411)));
    let (_, x414) = bits::Mul64(x400, 0x100000001);
    let (x417, x416) = bits::Mul64(x414, 0xffffffffffffffff);
    let (x419, x418) = bits::Mul64(x414, 0xffffffffffffffff);
    let (x421, x420) = bits::Mul64(x414, 0xffffffffffffffff);
    let (x423, x422) = bits::Mul64(x414, 0xfffffffffffffffe);
    let (x425, x424) = bits::Mul64(x414, 0xffffffff00000000);
    let (x427, x426) = bits::Mul64(x414, 0xffffffff);
    let (x428, x429) = bits::Add64(x427, x424, uint64(0x0));
    let (x430, x431) = bits::Add64(x425, x422, uint64(uint64(x429)));
    let (x432, x433) = bits::Add64(x423, x420, uint64(uint64(x431)));
    let (x434, x435) = bits::Add64(x421, x418, uint64(uint64(x433)));
    let (x436, x437) = bits::Add64(x419, x416, uint64(uint64(x435)));
    let x438 = ((uint64(uint64(x437))).wrapping_add(x417));
    let (_, x440) = bits::Add64(x400, x426, uint64(0x0));
    let (x441, x442) = bits::Add64(x402, x428, uint64(uint64(x440)));
    let (x443, x444) = bits::Add64(x404, x430, uint64(uint64(x442)));
    let (x445, x446) = bits::Add64(x406, x432, uint64(uint64(x444)));
    let (x447, x448) = bits::Add64(x408, x434, uint64(uint64(x446)));
    let (x449, x450) = bits::Add64(x410, x436, uint64(uint64(x448)));
    let (x451, x452) = bits::Add64(x412, x438, uint64(uint64(x450)));
    let x453 = ((uint64(uint64(x452))).wrapping_add(uint64(uint64(x413))));
    let (x454, x455) = bits::Sub64(x441, 0xffffffff, uint64(0x0));
    let (x456, x457) = bits::Sub64(x443, 0xffffffff00000000, uint64(uint64(x455)));
    let (x458, x459) = bits::Sub64(x445, 0xfffffffffffffffe, uint64(uint64(x457)));
    let (x460, x461) = bits::Sub64(x447, 0xffffffffffffffff, uint64(uint64(x459)));
    let (x462, x463) = bits::Sub64(x449, 0xffffffffffffffff, uint64(uint64(x461)));
    let (x464, x465) = bits::Sub64(x451, 0xffffffffffffffff, uint64(uint64(x463)));
    let (_, x467) = bits::Sub64(x453, uint64(0x0), uint64(uint64(x465)));
    let x468 = p384CmovznzU64(uint64(x467), x454, x441);
    let x469 = p384CmovznzU64(uint64(x467), x456, x443);
    let x470 = p384CmovznzU64(uint64(x467), x458, x445);
    let x471 = p384CmovznzU64(uint64(x467), x460, x447);
    let x472 = p384CmovznzU64(uint64(x467), x462, x449);
    let x473 = p384CmovznzU64(uint64(x467), x464, x451);
    out1[0] = x468;
    out1[1] = x469;
    out1[2] = x470;
    out1[3] = x471;
    out1[4] = x472;
    out1[5] = x473;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:795-1490 p384Square
pub(super) fn p384Square(
    out1: &mut p384MontgomeryDomainFieldElement,
    arg1: &p384MontgomeryDomainFieldElement,
) {
    let x1 = arg1[1];
    let x2 = arg1[2];
    let x3 = arg1[3];
    let x4 = arg1[4];
    let x5 = arg1[5];
    let x6 = arg1[0];
    let (x8, x7) = bits::Mul64(x6, arg1[5]);
    let (x10, x9) = bits::Mul64(x6, arg1[4]);
    let (x12, x11) = bits::Mul64(x6, arg1[3]);
    let (x14, x13) = bits::Mul64(x6, arg1[2]);
    let (x16, x15) = bits::Mul64(x6, arg1[1]);
    let (x18, x17) = bits::Mul64(x6, arg1[0]);
    let (x19, x20) = bits::Add64(x18, x15, uint64(0x0));
    let (x21, x22) = bits::Add64(x16, x13, uint64(uint64(x20)));
    let (x23, x24) = bits::Add64(x14, x11, uint64(uint64(x22)));
    let (x25, x26) = bits::Add64(x12, x9, uint64(uint64(x24)));
    let (x27, x28) = bits::Add64(x10, x7, uint64(uint64(x26)));
    let x29 = ((uint64(uint64(x28))).wrapping_add(x8));
    let (_, x30) = bits::Mul64(x17, 0x100000001);
    let (x33, x32) = bits::Mul64(x30, 0xffffffffffffffff);
    let (x35, x34) = bits::Mul64(x30, 0xffffffffffffffff);
    let (x37, x36) = bits::Mul64(x30, 0xffffffffffffffff);
    let (x39, x38) = bits::Mul64(x30, 0xfffffffffffffffe);
    let (x41, x40) = bits::Mul64(x30, 0xffffffff00000000);
    let (x43, x42) = bits::Mul64(x30, 0xffffffff);
    let (x44, x45) = bits::Add64(x43, x40, uint64(0x0));
    let (x46, x47) = bits::Add64(x41, x38, uint64(uint64(x45)));
    let (x48, x49) = bits::Add64(x39, x36, uint64(uint64(x47)));
    let (x50, x51) = bits::Add64(x37, x34, uint64(uint64(x49)));
    let (x52, x53) = bits::Add64(x35, x32, uint64(uint64(x51)));
    let x54 = ((uint64(uint64(x53))).wrapping_add(x33));
    let (_, x56) = bits::Add64(x17, x42, uint64(0x0));
    let (x57, x58) = bits::Add64(x19, x44, uint64(uint64(x56)));
    let (x59, x60) = bits::Add64(x21, x46, uint64(uint64(x58)));
    let (x61, x62) = bits::Add64(x23, x48, uint64(uint64(x60)));
    let (x63, x64) = bits::Add64(x25, x50, uint64(uint64(x62)));
    let (x65, x66) = bits::Add64(x27, x52, uint64(uint64(x64)));
    let (x67, x68) = bits::Add64(x29, x54, uint64(uint64(x66)));
    let (x70, x69) = bits::Mul64(x1, arg1[5]);
    let (x72, x71) = bits::Mul64(x1, arg1[4]);
    let (x74, x73) = bits::Mul64(x1, arg1[3]);
    let (x76, x75) = bits::Mul64(x1, arg1[2]);
    let (x78, x77) = bits::Mul64(x1, arg1[1]);
    let (x80, x79) = bits::Mul64(x1, arg1[0]);
    let (x81, x82) = bits::Add64(x80, x77, uint64(0x0));
    let (x83, x84) = bits::Add64(x78, x75, uint64(uint64(x82)));
    let (x85, x86) = bits::Add64(x76, x73, uint64(uint64(x84)));
    let (x87, x88) = bits::Add64(x74, x71, uint64(uint64(x86)));
    let (x89, x90) = bits::Add64(x72, x69, uint64(uint64(x88)));
    let x91 = ((uint64(uint64(x90))).wrapping_add(x70));
    let (x92, x93) = bits::Add64(x57, x79, uint64(0x0));
    let (x94, x95) = bits::Add64(x59, x81, uint64(uint64(x93)));
    let (x96, x97) = bits::Add64(x61, x83, uint64(uint64(x95)));
    let (x98, x99) = bits::Add64(x63, x85, uint64(uint64(x97)));
    let (x100, x101) = bits::Add64(x65, x87, uint64(uint64(x99)));
    let (x102, x103) = bits::Add64(x67, x89, uint64(uint64(x101)));
    let (x104, x105) = bits::Add64(uint64(uint64(x68)), x91, uint64(uint64(x103)));
    let (_, x106) = bits::Mul64(x92, 0x100000001);
    let (x109, x108) = bits::Mul64(x106, 0xffffffffffffffff);
    let (x111, x110) = bits::Mul64(x106, 0xffffffffffffffff);
    let (x113, x112) = bits::Mul64(x106, 0xffffffffffffffff);
    let (x115, x114) = bits::Mul64(x106, 0xfffffffffffffffe);
    let (x117, x116) = bits::Mul64(x106, 0xffffffff00000000);
    let (x119, x118) = bits::Mul64(x106, 0xffffffff);
    let (x120, x121) = bits::Add64(x119, x116, uint64(0x0));
    let (x122, x123) = bits::Add64(x117, x114, uint64(uint64(x121)));
    let (x124, x125) = bits::Add64(x115, x112, uint64(uint64(x123)));
    let (x126, x127) = bits::Add64(x113, x110, uint64(uint64(x125)));
    let (x128, x129) = bits::Add64(x111, x108, uint64(uint64(x127)));
    let x130 = ((uint64(uint64(x129))).wrapping_add(x109));
    let (_, x132) = bits::Add64(x92, x118, uint64(0x0));
    let (x133, x134) = bits::Add64(x94, x120, uint64(uint64(x132)));
    let (x135, x136) = bits::Add64(x96, x122, uint64(uint64(x134)));
    let (x137, x138) = bits::Add64(x98, x124, uint64(uint64(x136)));
    let (x139, x140) = bits::Add64(x100, x126, uint64(uint64(x138)));
    let (x141, x142) = bits::Add64(x102, x128, uint64(uint64(x140)));
    let (x143, x144) = bits::Add64(x104, x130, uint64(uint64(x142)));
    let x145 = ((uint64(uint64(x144))).wrapping_add(uint64(uint64(x105))));
    let (x147, x146) = bits::Mul64(x2, arg1[5]);
    let (x149, x148) = bits::Mul64(x2, arg1[4]);
    let (x151, x150) = bits::Mul64(x2, arg1[3]);
    let (x153, x152) = bits::Mul64(x2, arg1[2]);
    let (x155, x154) = bits::Mul64(x2, arg1[1]);
    let (x157, x156) = bits::Mul64(x2, arg1[0]);
    let (x158, x159) = bits::Add64(x157, x154, uint64(0x0));
    let (x160, x161) = bits::Add64(x155, x152, uint64(uint64(x159)));
    let (x162, x163) = bits::Add64(x153, x150, uint64(uint64(x161)));
    let (x164, x165) = bits::Add64(x151, x148, uint64(uint64(x163)));
    let (x166, x167) = bits::Add64(x149, x146, uint64(uint64(x165)));
    let x168 = ((uint64(uint64(x167))).wrapping_add(x147));
    let (x169, x170) = bits::Add64(x133, x156, uint64(0x0));
    let (x171, x172) = bits::Add64(x135, x158, uint64(uint64(x170)));
    let (x173, x174) = bits::Add64(x137, x160, uint64(uint64(x172)));
    let (x175, x176) = bits::Add64(x139, x162, uint64(uint64(x174)));
    let (x177, x178) = bits::Add64(x141, x164, uint64(uint64(x176)));
    let (x179, x180) = bits::Add64(x143, x166, uint64(uint64(x178)));
    let (x181, x182) = bits::Add64(x145, x168, uint64(uint64(x180)));
    let (_, x183) = bits::Mul64(x169, 0x100000001);
    let (x186, x185) = bits::Mul64(x183, 0xffffffffffffffff);
    let (x188, x187) = bits::Mul64(x183, 0xffffffffffffffff);
    let (x190, x189) = bits::Mul64(x183, 0xffffffffffffffff);
    let (x192, x191) = bits::Mul64(x183, 0xfffffffffffffffe);
    let (x194, x193) = bits::Mul64(x183, 0xffffffff00000000);
    let (x196, x195) = bits::Mul64(x183, 0xffffffff);
    let (x197, x198) = bits::Add64(x196, x193, uint64(0x0));
    let (x199, x200) = bits::Add64(x194, x191, uint64(uint64(x198)));
    let (x201, x202) = bits::Add64(x192, x189, uint64(uint64(x200)));
    let (x203, x204) = bits::Add64(x190, x187, uint64(uint64(x202)));
    let (x205, x206) = bits::Add64(x188, x185, uint64(uint64(x204)));
    let x207 = ((uint64(uint64(x206))).wrapping_add(x186));
    let (_, x209) = bits::Add64(x169, x195, uint64(0x0));
    let (x210, x211) = bits::Add64(x171, x197, uint64(uint64(x209)));
    let (x212, x213) = bits::Add64(x173, x199, uint64(uint64(x211)));
    let (x214, x215) = bits::Add64(x175, x201, uint64(uint64(x213)));
    let (x216, x217) = bits::Add64(x177, x203, uint64(uint64(x215)));
    let (x218, x219) = bits::Add64(x179, x205, uint64(uint64(x217)));
    let (x220, x221) = bits::Add64(x181, x207, uint64(uint64(x219)));
    let x222 = ((uint64(uint64(x221))).wrapping_add(uint64(uint64(x182))));
    let (x224, x223) = bits::Mul64(x3, arg1[5]);
    let (x226, x225) = bits::Mul64(x3, arg1[4]);
    let (x228, x227) = bits::Mul64(x3, arg1[3]);
    let (x230, x229) = bits::Mul64(x3, arg1[2]);
    let (x232, x231) = bits::Mul64(x3, arg1[1]);
    let (x234, x233) = bits::Mul64(x3, arg1[0]);
    let (x235, x236) = bits::Add64(x234, x231, uint64(0x0));
    let (x237, x238) = bits::Add64(x232, x229, uint64(uint64(x236)));
    let (x239, x240) = bits::Add64(x230, x227, uint64(uint64(x238)));
    let (x241, x242) = bits::Add64(x228, x225, uint64(uint64(x240)));
    let (x243, x244) = bits::Add64(x226, x223, uint64(uint64(x242)));
    let x245 = ((uint64(uint64(x244))).wrapping_add(x224));
    let (x246, x247) = bits::Add64(x210, x233, uint64(0x0));
    let (x248, x249) = bits::Add64(x212, x235, uint64(uint64(x247)));
    let (x250, x251) = bits::Add64(x214, x237, uint64(uint64(x249)));
    let (x252, x253) = bits::Add64(x216, x239, uint64(uint64(x251)));
    let (x254, x255) = bits::Add64(x218, x241, uint64(uint64(x253)));
    let (x256, x257) = bits::Add64(x220, x243, uint64(uint64(x255)));
    let (x258, x259) = bits::Add64(x222, x245, uint64(uint64(x257)));
    let (_, x260) = bits::Mul64(x246, 0x100000001);
    let (x263, x262) = bits::Mul64(x260, 0xffffffffffffffff);
    let (x265, x264) = bits::Mul64(x260, 0xffffffffffffffff);
    let (x267, x266) = bits::Mul64(x260, 0xffffffffffffffff);
    let (x269, x268) = bits::Mul64(x260, 0xfffffffffffffffe);
    let (x271, x270) = bits::Mul64(x260, 0xffffffff00000000);
    let (x273, x272) = bits::Mul64(x260, 0xffffffff);
    let (x274, x275) = bits::Add64(x273, x270, uint64(0x0));
    let (x276, x277) = bits::Add64(x271, x268, uint64(uint64(x275)));
    let (x278, x279) = bits::Add64(x269, x266, uint64(uint64(x277)));
    let (x280, x281) = bits::Add64(x267, x264, uint64(uint64(x279)));
    let (x282, x283) = bits::Add64(x265, x262, uint64(uint64(x281)));
    let x284 = ((uint64(uint64(x283))).wrapping_add(x263));
    let (_, x286) = bits::Add64(x246, x272, uint64(0x0));
    let (x287, x288) = bits::Add64(x248, x274, uint64(uint64(x286)));
    let (x289, x290) = bits::Add64(x250, x276, uint64(uint64(x288)));
    let (x291, x292) = bits::Add64(x252, x278, uint64(uint64(x290)));
    let (x293, x294) = bits::Add64(x254, x280, uint64(uint64(x292)));
    let (x295, x296) = bits::Add64(x256, x282, uint64(uint64(x294)));
    let (x297, x298) = bits::Add64(x258, x284, uint64(uint64(x296)));
    let x299 = ((uint64(uint64(x298))).wrapping_add(uint64(uint64(x259))));
    let (x301, x300) = bits::Mul64(x4, arg1[5]);
    let (x303, x302) = bits::Mul64(x4, arg1[4]);
    let (x305, x304) = bits::Mul64(x4, arg1[3]);
    let (x307, x306) = bits::Mul64(x4, arg1[2]);
    let (x309, x308) = bits::Mul64(x4, arg1[1]);
    let (x311, x310) = bits::Mul64(x4, arg1[0]);
    let (x312, x313) = bits::Add64(x311, x308, uint64(0x0));
    let (x314, x315) = bits::Add64(x309, x306, uint64(uint64(x313)));
    let (x316, x317) = bits::Add64(x307, x304, uint64(uint64(x315)));
    let (x318, x319) = bits::Add64(x305, x302, uint64(uint64(x317)));
    let (x320, x321) = bits::Add64(x303, x300, uint64(uint64(x319)));
    let x322 = ((uint64(uint64(x321))).wrapping_add(x301));
    let (x323, x324) = bits::Add64(x287, x310, uint64(0x0));
    let (x325, x326) = bits::Add64(x289, x312, uint64(uint64(x324)));
    let (x327, x328) = bits::Add64(x291, x314, uint64(uint64(x326)));
    let (x329, x330) = bits::Add64(x293, x316, uint64(uint64(x328)));
    let (x331, x332) = bits::Add64(x295, x318, uint64(uint64(x330)));
    let (x333, x334) = bits::Add64(x297, x320, uint64(uint64(x332)));
    let (x335, x336) = bits::Add64(x299, x322, uint64(uint64(x334)));
    let (_, x337) = bits::Mul64(x323, 0x100000001);
    let (x340, x339) = bits::Mul64(x337, 0xffffffffffffffff);
    let (x342, x341) = bits::Mul64(x337, 0xffffffffffffffff);
    let (x344, x343) = bits::Mul64(x337, 0xffffffffffffffff);
    let (x346, x345) = bits::Mul64(x337, 0xfffffffffffffffe);
    let (x348, x347) = bits::Mul64(x337, 0xffffffff00000000);
    let (x350, x349) = bits::Mul64(x337, 0xffffffff);
    let (x351, x352) = bits::Add64(x350, x347, uint64(0x0));
    let (x353, x354) = bits::Add64(x348, x345, uint64(uint64(x352)));
    let (x355, x356) = bits::Add64(x346, x343, uint64(uint64(x354)));
    let (x357, x358) = bits::Add64(x344, x341, uint64(uint64(x356)));
    let (x359, x360) = bits::Add64(x342, x339, uint64(uint64(x358)));
    let x361 = ((uint64(uint64(x360))).wrapping_add(x340));
    let (_, x363) = bits::Add64(x323, x349, uint64(0x0));
    let (x364, x365) = bits::Add64(x325, x351, uint64(uint64(x363)));
    let (x366, x367) = bits::Add64(x327, x353, uint64(uint64(x365)));
    let (x368, x369) = bits::Add64(x329, x355, uint64(uint64(x367)));
    let (x370, x371) = bits::Add64(x331, x357, uint64(uint64(x369)));
    let (x372, x373) = bits::Add64(x333, x359, uint64(uint64(x371)));
    let (x374, x375) = bits::Add64(x335, x361, uint64(uint64(x373)));
    let x376 = ((uint64(uint64(x375))).wrapping_add(uint64(uint64(x336))));
    let (x378, x377) = bits::Mul64(x5, arg1[5]);
    let (x380, x379) = bits::Mul64(x5, arg1[4]);
    let (x382, x381) = bits::Mul64(x5, arg1[3]);
    let (x384, x383) = bits::Mul64(x5, arg1[2]);
    let (x386, x385) = bits::Mul64(x5, arg1[1]);
    let (x388, x387) = bits::Mul64(x5, arg1[0]);
    let (x389, x390) = bits::Add64(x388, x385, uint64(0x0));
    let (x391, x392) = bits::Add64(x386, x383, uint64(uint64(x390)));
    let (x393, x394) = bits::Add64(x384, x381, uint64(uint64(x392)));
    let (x395, x396) = bits::Add64(x382, x379, uint64(uint64(x394)));
    let (x397, x398) = bits::Add64(x380, x377, uint64(uint64(x396)));
    let x399 = ((uint64(uint64(x398))).wrapping_add(x378));
    let (x400, x401) = bits::Add64(x364, x387, uint64(0x0));
    let (x402, x403) = bits::Add64(x366, x389, uint64(uint64(x401)));
    let (x404, x405) = bits::Add64(x368, x391, uint64(uint64(x403)));
    let (x406, x407) = bits::Add64(x370, x393, uint64(uint64(x405)));
    let (x408, x409) = bits::Add64(x372, x395, uint64(uint64(x407)));
    let (x410, x411) = bits::Add64(x374, x397, uint64(uint64(x409)));
    let (x412, x413) = bits::Add64(x376, x399, uint64(uint64(x411)));
    let (_, x414) = bits::Mul64(x400, 0x100000001);
    let (x417, x416) = bits::Mul64(x414, 0xffffffffffffffff);
    let (x419, x418) = bits::Mul64(x414, 0xffffffffffffffff);
    let (x421, x420) = bits::Mul64(x414, 0xffffffffffffffff);
    let (x423, x422) = bits::Mul64(x414, 0xfffffffffffffffe);
    let (x425, x424) = bits::Mul64(x414, 0xffffffff00000000);
    let (x427, x426) = bits::Mul64(x414, 0xffffffff);
    let (x428, x429) = bits::Add64(x427, x424, uint64(0x0));
    let (x430, x431) = bits::Add64(x425, x422, uint64(uint64(x429)));
    let (x432, x433) = bits::Add64(x423, x420, uint64(uint64(x431)));
    let (x434, x435) = bits::Add64(x421, x418, uint64(uint64(x433)));
    let (x436, x437) = bits::Add64(x419, x416, uint64(uint64(x435)));
    let x438 = ((uint64(uint64(x437))).wrapping_add(x417));
    let (_, x440) = bits::Add64(x400, x426, uint64(0x0));
    let (x441, x442) = bits::Add64(x402, x428, uint64(uint64(x440)));
    let (x443, x444) = bits::Add64(x404, x430, uint64(uint64(x442)));
    let (x445, x446) = bits::Add64(x406, x432, uint64(uint64(x444)));
    let (x447, x448) = bits::Add64(x408, x434, uint64(uint64(x446)));
    let (x449, x450) = bits::Add64(x410, x436, uint64(uint64(x448)));
    let (x451, x452) = bits::Add64(x412, x438, uint64(uint64(x450)));
    let x453 = ((uint64(uint64(x452))).wrapping_add(uint64(uint64(x413))));
    let (x454, x455) = bits::Sub64(x441, 0xffffffff, uint64(0x0));
    let (x456, x457) = bits::Sub64(x443, 0xffffffff00000000, uint64(uint64(x455)));
    let (x458, x459) = bits::Sub64(x445, 0xfffffffffffffffe, uint64(uint64(x457)));
    let (x460, x461) = bits::Sub64(x447, 0xffffffffffffffff, uint64(uint64(x459)));
    let (x462, x463) = bits::Sub64(x449, 0xffffffffffffffff, uint64(uint64(x461)));
    let (x464, x465) = bits::Sub64(x451, 0xffffffffffffffff, uint64(uint64(x463)));
    let (_, x467) = bits::Sub64(x453, uint64(0x0), uint64(uint64(x465)));
    let x468 = p384CmovznzU64(uint64(x467), x454, x441);
    let x469 = p384CmovznzU64(uint64(x467), x456, x443);
    let x470 = p384CmovznzU64(uint64(x467), x458, x445);
    let x471 = p384CmovznzU64(uint64(x467), x460, x447);
    let x472 = p384CmovznzU64(uint64(x467), x462, x449);
    let x473 = p384CmovznzU64(uint64(x467), x464, x451);
    out1[0] = x468;
    out1[1] = x469;
    out1[2] = x470;
    out1[3] = x471;
    out1[4] = x472;
    out1[5] = x473;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:1503-1560 p384Add
pub(super) fn p384Add(
    out1: &mut p384MontgomeryDomainFieldElement,
    arg1: &p384MontgomeryDomainFieldElement,
    arg2: &p384MontgomeryDomainFieldElement,
) {
    let (x1, x2) = bits::Add64(arg1[0], arg2[0], uint64(0x0));
    let (x3, x4) = bits::Add64(arg1[1], arg2[1], uint64(uint64(x2)));
    let (x5, x6) = bits::Add64(arg1[2], arg2[2], uint64(uint64(x4)));
    let (x7, x8) = bits::Add64(arg1[3], arg2[3], uint64(uint64(x6)));
    let (x9, x10) = bits::Add64(arg1[4], arg2[4], uint64(uint64(x8)));
    let (x11, x12) = bits::Add64(arg1[5], arg2[5], uint64(uint64(x10)));
    let (x13, x14) = bits::Sub64(x1, 0xffffffff, uint64(0x0));
    let (x15, x16) = bits::Sub64(x3, 0xffffffff00000000, uint64(uint64(x14)));
    let (x17, x18) = bits::Sub64(x5, 0xfffffffffffffffe, uint64(uint64(x16)));
    let (x19, x20) = bits::Sub64(x7, 0xffffffffffffffff, uint64(uint64(x18)));
    let (x21, x22) = bits::Sub64(x9, 0xffffffffffffffff, uint64(uint64(x20)));
    let (x23, x24) = bits::Sub64(x11, 0xffffffffffffffff, uint64(uint64(x22)));
    let (_, x26) = bits::Sub64(uint64(uint64(x12)), uint64(0x0), uint64(uint64(x24)));
    let x27 = p384CmovznzU64(uint64(x26), x13, x1);
    let x28 = p384CmovznzU64(uint64(x26), x15, x3);
    let x29 = p384CmovznzU64(uint64(x26), x17, x5);
    let x30 = p384CmovznzU64(uint64(x26), x19, x7);
    let x31 = p384CmovznzU64(uint64(x26), x21, x9);
    let x32 = p384CmovznzU64(uint64(x26), x23, x11);
    out1[0] = x27;
    out1[1] = x28;
    out1[2] = x29;
    out1[3] = x30;
    out1[4] = x31;
    out1[5] = x32;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:1573-1617 p384Sub
pub(super) fn p384Sub(
    out1: &mut p384MontgomeryDomainFieldElement,
    arg1: &p384MontgomeryDomainFieldElement,
    arg2: &p384MontgomeryDomainFieldElement,
) {
    let (x1, x2) = bits::Sub64(arg1[0], arg2[0], uint64(0x0));
    let (x3, x4) = bits::Sub64(arg1[1], arg2[1], uint64(uint64(x2)));
    let (x5, x6) = bits::Sub64(arg1[2], arg2[2], uint64(uint64(x4)));
    let (x7, x8) = bits::Sub64(arg1[3], arg2[3], uint64(uint64(x6)));
    let (x9, x10) = bits::Sub64(arg1[4], arg2[4], uint64(uint64(x8)));
    let (x11, x12) = bits::Sub64(arg1[5], arg2[5], uint64(uint64(x10)));
    let x13 = p384CmovznzU64(uint64(x12), uint64(0x0), 0xffffffffffffffff);
    let (x14, x15) = bits::Add64(x1, (x13 & 0xffffffff), uint64(0x0));
    let (x16, x17) = bits::Add64(x3, (x13 & 0xffffffff00000000), uint64(uint64(x15)));
    let (x18, x19) = bits::Add64(x5, (x13 & 0xfffffffffffffffe), uint64(uint64(x17)));
    let (x20, x21) = bits::Add64(x7, x13, uint64(uint64(x19)));
    let (x22, x23) = bits::Add64(x9, x13, uint64(uint64(x21)));
    let (x24, _) = bits::Add64(x11, x13, uint64(uint64(x23)));
    out1[0] = x14;
    out1[1] = x16;
    out1[2] = x18;
    out1[3] = x20;
    out1[4] = x22;
    out1[5] = x24;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:1625-1632 p384SetOne
pub(super) fn p384SetOne(out1: &mut p384MontgomeryDomainFieldElement) {
    out1[0] = 0xffffffff00000001;
    out1[1] = 0xffffffff;
    out1[2] = uint64(0x1);
    out1[3] = uint64(0x0);
    out1[4] = uint64(0x0);
    out1[5] = uint64(0x0);
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:1644-2104 p384FromMontgomery
pub(super) fn p384FromMontgomery(
    out1: &mut p384NonMontgomeryDomainFieldElement,
    arg1: &p384MontgomeryDomainFieldElement,
) {
    let x1 = arg1[0];
    let (_, x2) = bits::Mul64(x1, 0x100000001);
    let (x5, x4) = bits::Mul64(x2, 0xffffffffffffffff);
    let (x7, x6) = bits::Mul64(x2, 0xffffffffffffffff);
    let (x9, x8) = bits::Mul64(x2, 0xffffffffffffffff);
    let (x11, x10) = bits::Mul64(x2, 0xfffffffffffffffe);
    let (x13, x12) = bits::Mul64(x2, 0xffffffff00000000);
    let (x15, x14) = bits::Mul64(x2, 0xffffffff);
    let (x16, x17) = bits::Add64(x15, x12, uint64(0x0));
    let (x18, x19) = bits::Add64(x13, x10, uint64(uint64(x17)));
    let (x20, x21) = bits::Add64(x11, x8, uint64(uint64(x19)));
    let (x22, x23) = bits::Add64(x9, x6, uint64(uint64(x21)));
    let (x24, x25) = bits::Add64(x7, x4, uint64(uint64(x23)));
    let (_, x27) = bits::Add64(x1, x14, uint64(0x0));
    let (x28, x29) = bits::Add64(uint64(0x0), x16, uint64(uint64(x27)));
    let (x30, x31) = bits::Add64(uint64(0x0), x18, uint64(uint64(x29)));
    let (x32, x33) = bits::Add64(uint64(0x0), x20, uint64(uint64(x31)));
    let (x34, x35) = bits::Add64(uint64(0x0), x22, uint64(uint64(x33)));
    let (x36, x37) = bits::Add64(uint64(0x0), x24, uint64(uint64(x35)));
    let (x38, x39) = bits::Add64(
        uint64(0x0),
        ((uint64(uint64(x25))).wrapping_add(x5)),
        uint64(uint64(x37)),
    );
    let (x40, x41) = bits::Add64(x28, arg1[1], uint64(0x0));
    let (x42, x43) = bits::Add64(x30, uint64(0x0), uint64(uint64(x41)));
    let (x44, x45) = bits::Add64(x32, uint64(0x0), uint64(uint64(x43)));
    let (x46, x47) = bits::Add64(x34, uint64(0x0), uint64(uint64(x45)));
    let (x48, x49) = bits::Add64(x36, uint64(0x0), uint64(uint64(x47)));
    let (x50, x51) = bits::Add64(x38, uint64(0x0), uint64(uint64(x49)));
    let (_, x52) = bits::Mul64(x40, 0x100000001);
    let (x55, x54) = bits::Mul64(x52, 0xffffffffffffffff);
    let (x57, x56) = bits::Mul64(x52, 0xffffffffffffffff);
    let (x59, x58) = bits::Mul64(x52, 0xffffffffffffffff);
    let (x61, x60) = bits::Mul64(x52, 0xfffffffffffffffe);
    let (x63, x62) = bits::Mul64(x52, 0xffffffff00000000);
    let (x65, x64) = bits::Mul64(x52, 0xffffffff);
    let (x66, x67) = bits::Add64(x65, x62, uint64(0x0));
    let (x68, x69) = bits::Add64(x63, x60, uint64(uint64(x67)));
    let (x70, x71) = bits::Add64(x61, x58, uint64(uint64(x69)));
    let (x72, x73) = bits::Add64(x59, x56, uint64(uint64(x71)));
    let (x74, x75) = bits::Add64(x57, x54, uint64(uint64(x73)));
    let (_, x77) = bits::Add64(x40, x64, uint64(0x0));
    let (x78, x79) = bits::Add64(x42, x66, uint64(uint64(x77)));
    let (x80, x81) = bits::Add64(x44, x68, uint64(uint64(x79)));
    let (x82, x83) = bits::Add64(x46, x70, uint64(uint64(x81)));
    let (x84, x85) = bits::Add64(x48, x72, uint64(uint64(x83)));
    let (x86, x87) = bits::Add64(x50, x74, uint64(uint64(x85)));
    let (x88, x89) = bits::Add64(
        ((uint64(uint64(x51))).wrapping_add(uint64(uint64(x39)))),
        ((uint64(uint64(x75))).wrapping_add(x55)),
        uint64(uint64(x87)),
    );
    let (x90, x91) = bits::Add64(x78, arg1[2], uint64(0x0));
    let (x92, x93) = bits::Add64(x80, uint64(0x0), uint64(uint64(x91)));
    let (x94, x95) = bits::Add64(x82, uint64(0x0), uint64(uint64(x93)));
    let (x96, x97) = bits::Add64(x84, uint64(0x0), uint64(uint64(x95)));
    let (x98, x99) = bits::Add64(x86, uint64(0x0), uint64(uint64(x97)));
    let (x100, x101) = bits::Add64(x88, uint64(0x0), uint64(uint64(x99)));
    let (_, x102) = bits::Mul64(x90, 0x100000001);
    let (x105, x104) = bits::Mul64(x102, 0xffffffffffffffff);
    let (x107, x106) = bits::Mul64(x102, 0xffffffffffffffff);
    let (x109, x108) = bits::Mul64(x102, 0xffffffffffffffff);
    let (x111, x110) = bits::Mul64(x102, 0xfffffffffffffffe);
    let (x113, x112) = bits::Mul64(x102, 0xffffffff00000000);
    let (x115, x114) = bits::Mul64(x102, 0xffffffff);
    let (x116, x117) = bits::Add64(x115, x112, uint64(0x0));
    let (x118, x119) = bits::Add64(x113, x110, uint64(uint64(x117)));
    let (x120, x121) = bits::Add64(x111, x108, uint64(uint64(x119)));
    let (x122, x123) = bits::Add64(x109, x106, uint64(uint64(x121)));
    let (x124, x125) = bits::Add64(x107, x104, uint64(uint64(x123)));
    let (_, x127) = bits::Add64(x90, x114, uint64(0x0));
    let (x128, x129) = bits::Add64(x92, x116, uint64(uint64(x127)));
    let (x130, x131) = bits::Add64(x94, x118, uint64(uint64(x129)));
    let (x132, x133) = bits::Add64(x96, x120, uint64(uint64(x131)));
    let (x134, x135) = bits::Add64(x98, x122, uint64(uint64(x133)));
    let (x136, x137) = bits::Add64(x100, x124, uint64(uint64(x135)));
    let (x138, x139) = bits::Add64(
        ((uint64(uint64(x101))).wrapping_add(uint64(uint64(x89)))),
        ((uint64(uint64(x125))).wrapping_add(x105)),
        uint64(uint64(x137)),
    );
    let (x140, x141) = bits::Add64(x128, arg1[3], uint64(0x0));
    let (x142, x143) = bits::Add64(x130, uint64(0x0), uint64(uint64(x141)));
    let (x144, x145) = bits::Add64(x132, uint64(0x0), uint64(uint64(x143)));
    let (x146, x147) = bits::Add64(x134, uint64(0x0), uint64(uint64(x145)));
    let (x148, x149) = bits::Add64(x136, uint64(0x0), uint64(uint64(x147)));
    let (x150, x151) = bits::Add64(x138, uint64(0x0), uint64(uint64(x149)));
    let (_, x152) = bits::Mul64(x140, 0x100000001);
    let (x155, x154) = bits::Mul64(x152, 0xffffffffffffffff);
    let (x157, x156) = bits::Mul64(x152, 0xffffffffffffffff);
    let (x159, x158) = bits::Mul64(x152, 0xffffffffffffffff);
    let (x161, x160) = bits::Mul64(x152, 0xfffffffffffffffe);
    let (x163, x162) = bits::Mul64(x152, 0xffffffff00000000);
    let (x165, x164) = bits::Mul64(x152, 0xffffffff);
    let (x166, x167) = bits::Add64(x165, x162, uint64(0x0));
    let (x168, x169) = bits::Add64(x163, x160, uint64(uint64(x167)));
    let (x170, x171) = bits::Add64(x161, x158, uint64(uint64(x169)));
    let (x172, x173) = bits::Add64(x159, x156, uint64(uint64(x171)));
    let (x174, x175) = bits::Add64(x157, x154, uint64(uint64(x173)));
    let (_, x177) = bits::Add64(x140, x164, uint64(0x0));
    let (x178, x179) = bits::Add64(x142, x166, uint64(uint64(x177)));
    let (x180, x181) = bits::Add64(x144, x168, uint64(uint64(x179)));
    let (x182, x183) = bits::Add64(x146, x170, uint64(uint64(x181)));
    let (x184, x185) = bits::Add64(x148, x172, uint64(uint64(x183)));
    let (x186, x187) = bits::Add64(x150, x174, uint64(uint64(x185)));
    let (x188, x189) = bits::Add64(
        ((uint64(uint64(x151))).wrapping_add(uint64(uint64(x139)))),
        ((uint64(uint64(x175))).wrapping_add(x155)),
        uint64(uint64(x187)),
    );
    let (x190, x191) = bits::Add64(x178, arg1[4], uint64(0x0));
    let (x192, x193) = bits::Add64(x180, uint64(0x0), uint64(uint64(x191)));
    let (x194, x195) = bits::Add64(x182, uint64(0x0), uint64(uint64(x193)));
    let (x196, x197) = bits::Add64(x184, uint64(0x0), uint64(uint64(x195)));
    let (x198, x199) = bits::Add64(x186, uint64(0x0), uint64(uint64(x197)));
    let (x200, x201) = bits::Add64(x188, uint64(0x0), uint64(uint64(x199)));
    let (_, x202) = bits::Mul64(x190, 0x100000001);
    let (x205, x204) = bits::Mul64(x202, 0xffffffffffffffff);
    let (x207, x206) = bits::Mul64(x202, 0xffffffffffffffff);
    let (x209, x208) = bits::Mul64(x202, 0xffffffffffffffff);
    let (x211, x210) = bits::Mul64(x202, 0xfffffffffffffffe);
    let (x213, x212) = bits::Mul64(x202, 0xffffffff00000000);
    let (x215, x214) = bits::Mul64(x202, 0xffffffff);
    let (x216, x217) = bits::Add64(x215, x212, uint64(0x0));
    let (x218, x219) = bits::Add64(x213, x210, uint64(uint64(x217)));
    let (x220, x221) = bits::Add64(x211, x208, uint64(uint64(x219)));
    let (x222, x223) = bits::Add64(x209, x206, uint64(uint64(x221)));
    let (x224, x225) = bits::Add64(x207, x204, uint64(uint64(x223)));
    let (_, x227) = bits::Add64(x190, x214, uint64(0x0));
    let (x228, x229) = bits::Add64(x192, x216, uint64(uint64(x227)));
    let (x230, x231) = bits::Add64(x194, x218, uint64(uint64(x229)));
    let (x232, x233) = bits::Add64(x196, x220, uint64(uint64(x231)));
    let (x234, x235) = bits::Add64(x198, x222, uint64(uint64(x233)));
    let (x236, x237) = bits::Add64(x200, x224, uint64(uint64(x235)));
    let (x238, x239) = bits::Add64(
        ((uint64(uint64(x201))).wrapping_add(uint64(uint64(x189)))),
        ((uint64(uint64(x225))).wrapping_add(x205)),
        uint64(uint64(x237)),
    );
    let (x240, x241) = bits::Add64(x228, arg1[5], uint64(0x0));
    let (x242, x243) = bits::Add64(x230, uint64(0x0), uint64(uint64(x241)));
    let (x244, x245) = bits::Add64(x232, uint64(0x0), uint64(uint64(x243)));
    let (x246, x247) = bits::Add64(x234, uint64(0x0), uint64(uint64(x245)));
    let (x248, x249) = bits::Add64(x236, uint64(0x0), uint64(uint64(x247)));
    let (x250, x251) = bits::Add64(x238, uint64(0x0), uint64(uint64(x249)));
    let (_, x252) = bits::Mul64(x240, 0x100000001);
    let (x255, x254) = bits::Mul64(x252, 0xffffffffffffffff);
    let (x257, x256) = bits::Mul64(x252, 0xffffffffffffffff);
    let (x259, x258) = bits::Mul64(x252, 0xffffffffffffffff);
    let (x261, x260) = bits::Mul64(x252, 0xfffffffffffffffe);
    let (x263, x262) = bits::Mul64(x252, 0xffffffff00000000);
    let (x265, x264) = bits::Mul64(x252, 0xffffffff);
    let (x266, x267) = bits::Add64(x265, x262, uint64(0x0));
    let (x268, x269) = bits::Add64(x263, x260, uint64(uint64(x267)));
    let (x270, x271) = bits::Add64(x261, x258, uint64(uint64(x269)));
    let (x272, x273) = bits::Add64(x259, x256, uint64(uint64(x271)));
    let (x274, x275) = bits::Add64(x257, x254, uint64(uint64(x273)));
    let (_, x277) = bits::Add64(x240, x264, uint64(0x0));
    let (x278, x279) = bits::Add64(x242, x266, uint64(uint64(x277)));
    let (x280, x281) = bits::Add64(x244, x268, uint64(uint64(x279)));
    let (x282, x283) = bits::Add64(x246, x270, uint64(uint64(x281)));
    let (x284, x285) = bits::Add64(x248, x272, uint64(uint64(x283)));
    let (x286, x287) = bits::Add64(x250, x274, uint64(uint64(x285)));
    let (x288, x289) = bits::Add64(
        ((uint64(uint64(x251))).wrapping_add(uint64(uint64(x239)))),
        ((uint64(uint64(x275))).wrapping_add(x255)),
        uint64(uint64(x287)),
    );
    let (x290, x291) = bits::Sub64(x278, 0xffffffff, uint64(0x0));
    let (x292, x293) = bits::Sub64(x280, 0xffffffff00000000, uint64(uint64(x291)));
    let (x294, x295) = bits::Sub64(x282, 0xfffffffffffffffe, uint64(uint64(x293)));
    let (x296, x297) = bits::Sub64(x284, 0xffffffffffffffff, uint64(uint64(x295)));
    let (x298, x299) = bits::Sub64(x286, 0xffffffffffffffff, uint64(uint64(x297)));
    let (x300, x301) = bits::Sub64(x288, 0xffffffffffffffff, uint64(uint64(x299)));
    let (_, x303) = bits::Sub64(uint64(uint64(x289)), uint64(0x0), uint64(uint64(x301)));
    let x304 = p384CmovznzU64(uint64(x303), x290, x278);
    let x305 = p384CmovznzU64(uint64(x303), x292, x280);
    let x306 = p384CmovznzU64(uint64(x303), x294, x282);
    let x307 = p384CmovznzU64(uint64(x303), x296, x284);
    let x308 = p384CmovznzU64(uint64(x303), x298, x286);
    let x309 = p384CmovznzU64(uint64(x303), x300, x288);
    out1[0] = x304;
    out1[1] = x305;
    out1[2] = x306;
    out1[3] = x307;
    out1[4] = x308;
    out1[5] = x309;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:2116-2725 p384ToMontgomery
pub(super) fn p384ToMontgomery(
    out1: &mut p384MontgomeryDomainFieldElement,
    arg1: &p384NonMontgomeryDomainFieldElement,
) {
    let x1 = arg1[1];
    let x2 = arg1[2];
    let x3 = arg1[3];
    let x4 = arg1[4];
    let x5 = arg1[5];
    let x6 = arg1[0];
    let (x8, x7) = bits::Mul64(x6, 0x200000000);
    let (x10, x9) = bits::Mul64(x6, 0xfffffffe00000000);
    let (x12, x11) = bits::Mul64(x6, 0x200000000);
    let (x14, x13) = bits::Mul64(x6, 0xfffffffe00000001);
    let (x15, x16) = bits::Add64(x14, x11, uint64(0x0));
    let (x17, x18) = bits::Add64(x12, x9, uint64(uint64(x16)));
    let (x19, x20) = bits::Add64(x10, x7, uint64(uint64(x18)));
    let (x21, x22) = bits::Add64(x8, x6, uint64(uint64(x20)));
    let (_, x23) = bits::Mul64(x13, 0x100000001);
    let (x26, x25) = bits::Mul64(x23, 0xffffffffffffffff);
    let (x28, x27) = bits::Mul64(x23, 0xffffffffffffffff);
    let (x30, x29) = bits::Mul64(x23, 0xffffffffffffffff);
    let (x32, x31) = bits::Mul64(x23, 0xfffffffffffffffe);
    let (x34, x33) = bits::Mul64(x23, 0xffffffff00000000);
    let (x36, x35) = bits::Mul64(x23, 0xffffffff);
    let (x37, x38) = bits::Add64(x36, x33, uint64(0x0));
    let (x39, x40) = bits::Add64(x34, x31, uint64(uint64(x38)));
    let (x41, x42) = bits::Add64(x32, x29, uint64(uint64(x40)));
    let (x43, x44) = bits::Add64(x30, x27, uint64(uint64(x42)));
    let (x45, x46) = bits::Add64(x28, x25, uint64(uint64(x44)));
    let (_, x48) = bits::Add64(x13, x35, uint64(0x0));
    let (x49, x50) = bits::Add64(x15, x37, uint64(uint64(x48)));
    let (x51, x52) = bits::Add64(x17, x39, uint64(uint64(x50)));
    let (x53, x54) = bits::Add64(x19, x41, uint64(uint64(x52)));
    let (x55, x56) = bits::Add64(x21, x43, uint64(uint64(x54)));
    let (x57, x58) = bits::Add64(uint64(uint64(x22)), x45, uint64(uint64(x56)));
    let (x59, x60) = bits::Add64(
        uint64(0x0),
        ((uint64(uint64(x46))).wrapping_add(x26)),
        uint64(uint64(x58)),
    );
    let (x62, x61) = bits::Mul64(x1, 0x200000000);
    let (x64, x63) = bits::Mul64(x1, 0xfffffffe00000000);
    let (x66, x65) = bits::Mul64(x1, 0x200000000);
    let (x68, x67) = bits::Mul64(x1, 0xfffffffe00000001);
    let (x69, x70) = bits::Add64(x68, x65, uint64(0x0));
    let (x71, x72) = bits::Add64(x66, x63, uint64(uint64(x70)));
    let (x73, x74) = bits::Add64(x64, x61, uint64(uint64(x72)));
    let (x75, x76) = bits::Add64(x62, x1, uint64(uint64(x74)));
    let (x77, x78) = bits::Add64(x49, x67, uint64(0x0));
    let (x79, x80) = bits::Add64(x51, x69, uint64(uint64(x78)));
    let (x81, x82) = bits::Add64(x53, x71, uint64(uint64(x80)));
    let (x83, x84) = bits::Add64(x55, x73, uint64(uint64(x82)));
    let (x85, x86) = bits::Add64(x57, x75, uint64(uint64(x84)));
    let (x87, x88) = bits::Add64(x59, uint64(uint64(x76)), uint64(uint64(x86)));
    let (_, x89) = bits::Mul64(x77, 0x100000001);
    let (x92, x91) = bits::Mul64(x89, 0xffffffffffffffff);
    let (x94, x93) = bits::Mul64(x89, 0xffffffffffffffff);
    let (x96, x95) = bits::Mul64(x89, 0xffffffffffffffff);
    let (x98, x97) = bits::Mul64(x89, 0xfffffffffffffffe);
    let (x100, x99) = bits::Mul64(x89, 0xffffffff00000000);
    let (x102, x101) = bits::Mul64(x89, 0xffffffff);
    let (x103, x104) = bits::Add64(x102, x99, uint64(0x0));
    let (x105, x106) = bits::Add64(x100, x97, uint64(uint64(x104)));
    let (x107, x108) = bits::Add64(x98, x95, uint64(uint64(x106)));
    let (x109, x110) = bits::Add64(x96, x93, uint64(uint64(x108)));
    let (x111, x112) = bits::Add64(x94, x91, uint64(uint64(x110)));
    let (_, x114) = bits::Add64(x77, x101, uint64(0x0));
    let (x115, x116) = bits::Add64(x79, x103, uint64(uint64(x114)));
    let (x117, x118) = bits::Add64(x81, x105, uint64(uint64(x116)));
    let (x119, x120) = bits::Add64(x83, x107, uint64(uint64(x118)));
    let (x121, x122) = bits::Add64(x85, x109, uint64(uint64(x120)));
    let (x123, x124) = bits::Add64(x87, x111, uint64(uint64(x122)));
    let (x125, x126) = bits::Add64(
        ((uint64(uint64(x88))).wrapping_add(uint64(uint64(x60)))),
        ((uint64(uint64(x112))).wrapping_add(x92)),
        uint64(uint64(x124)),
    );
    let (x128, x127) = bits::Mul64(x2, 0x200000000);
    let (x130, x129) = bits::Mul64(x2, 0xfffffffe00000000);
    let (x132, x131) = bits::Mul64(x2, 0x200000000);
    let (x134, x133) = bits::Mul64(x2, 0xfffffffe00000001);
    let (x135, x136) = bits::Add64(x134, x131, uint64(0x0));
    let (x137, x138) = bits::Add64(x132, x129, uint64(uint64(x136)));
    let (x139, x140) = bits::Add64(x130, x127, uint64(uint64(x138)));
    let (x141, x142) = bits::Add64(x128, x2, uint64(uint64(x140)));
    let (x143, x144) = bits::Add64(x115, x133, uint64(0x0));
    let (x145, x146) = bits::Add64(x117, x135, uint64(uint64(x144)));
    let (x147, x148) = bits::Add64(x119, x137, uint64(uint64(x146)));
    let (x149, x150) = bits::Add64(x121, x139, uint64(uint64(x148)));
    let (x151, x152) = bits::Add64(x123, x141, uint64(uint64(x150)));
    let (x153, x154) = bits::Add64(x125, uint64(uint64(x142)), uint64(uint64(x152)));
    let (_, x155) = bits::Mul64(x143, 0x100000001);
    let (x158, x157) = bits::Mul64(x155, 0xffffffffffffffff);
    let (x160, x159) = bits::Mul64(x155, 0xffffffffffffffff);
    let (x162, x161) = bits::Mul64(x155, 0xffffffffffffffff);
    let (x164, x163) = bits::Mul64(x155, 0xfffffffffffffffe);
    let (x166, x165) = bits::Mul64(x155, 0xffffffff00000000);
    let (x168, x167) = bits::Mul64(x155, 0xffffffff);
    let (x169, x170) = bits::Add64(x168, x165, uint64(0x0));
    let (x171, x172) = bits::Add64(x166, x163, uint64(uint64(x170)));
    let (x173, x174) = bits::Add64(x164, x161, uint64(uint64(x172)));
    let (x175, x176) = bits::Add64(x162, x159, uint64(uint64(x174)));
    let (x177, x178) = bits::Add64(x160, x157, uint64(uint64(x176)));
    let (_, x180) = bits::Add64(x143, x167, uint64(0x0));
    let (x181, x182) = bits::Add64(x145, x169, uint64(uint64(x180)));
    let (x183, x184) = bits::Add64(x147, x171, uint64(uint64(x182)));
    let (x185, x186) = bits::Add64(x149, x173, uint64(uint64(x184)));
    let (x187, x188) = bits::Add64(x151, x175, uint64(uint64(x186)));
    let (x189, x190) = bits::Add64(x153, x177, uint64(uint64(x188)));
    let (x191, x192) = bits::Add64(
        ((uint64(uint64(x154))).wrapping_add(uint64(uint64(x126)))),
        ((uint64(uint64(x178))).wrapping_add(x158)),
        uint64(uint64(x190)),
    );
    let (x194, x193) = bits::Mul64(x3, 0x200000000);
    let (x196, x195) = bits::Mul64(x3, 0xfffffffe00000000);
    let (x198, x197) = bits::Mul64(x3, 0x200000000);
    let (x200, x199) = bits::Mul64(x3, 0xfffffffe00000001);
    let (x201, x202) = bits::Add64(x200, x197, uint64(0x0));
    let (x203, x204) = bits::Add64(x198, x195, uint64(uint64(x202)));
    let (x205, x206) = bits::Add64(x196, x193, uint64(uint64(x204)));
    let (x207, x208) = bits::Add64(x194, x3, uint64(uint64(x206)));
    let (x209, x210) = bits::Add64(x181, x199, uint64(0x0));
    let (x211, x212) = bits::Add64(x183, x201, uint64(uint64(x210)));
    let (x213, x214) = bits::Add64(x185, x203, uint64(uint64(x212)));
    let (x215, x216) = bits::Add64(x187, x205, uint64(uint64(x214)));
    let (x217, x218) = bits::Add64(x189, x207, uint64(uint64(x216)));
    let (x219, x220) = bits::Add64(x191, uint64(uint64(x208)), uint64(uint64(x218)));
    let (_, x221) = bits::Mul64(x209, 0x100000001);
    let (x224, x223) = bits::Mul64(x221, 0xffffffffffffffff);
    let (x226, x225) = bits::Mul64(x221, 0xffffffffffffffff);
    let (x228, x227) = bits::Mul64(x221, 0xffffffffffffffff);
    let (x230, x229) = bits::Mul64(x221, 0xfffffffffffffffe);
    let (x232, x231) = bits::Mul64(x221, 0xffffffff00000000);
    let (x234, x233) = bits::Mul64(x221, 0xffffffff);
    let (x235, x236) = bits::Add64(x234, x231, uint64(0x0));
    let (x237, x238) = bits::Add64(x232, x229, uint64(uint64(x236)));
    let (x239, x240) = bits::Add64(x230, x227, uint64(uint64(x238)));
    let (x241, x242) = bits::Add64(x228, x225, uint64(uint64(x240)));
    let (x243, x244) = bits::Add64(x226, x223, uint64(uint64(x242)));
    let (_, x246) = bits::Add64(x209, x233, uint64(0x0));
    let (x247, x248) = bits::Add64(x211, x235, uint64(uint64(x246)));
    let (x249, x250) = bits::Add64(x213, x237, uint64(uint64(x248)));
    let (x251, x252) = bits::Add64(x215, x239, uint64(uint64(x250)));
    let (x253, x254) = bits::Add64(x217, x241, uint64(uint64(x252)));
    let (x255, x256) = bits::Add64(x219, x243, uint64(uint64(x254)));
    let (x257, x258) = bits::Add64(
        ((uint64(uint64(x220))).wrapping_add(uint64(uint64(x192)))),
        ((uint64(uint64(x244))).wrapping_add(x224)),
        uint64(uint64(x256)),
    );
    let (x260, x259) = bits::Mul64(x4, 0x200000000);
    let (x262, x261) = bits::Mul64(x4, 0xfffffffe00000000);
    let (x264, x263) = bits::Mul64(x4, 0x200000000);
    let (x266, x265) = bits::Mul64(x4, 0xfffffffe00000001);
    let (x267, x268) = bits::Add64(x266, x263, uint64(0x0));
    let (x269, x270) = bits::Add64(x264, x261, uint64(uint64(x268)));
    let (x271, x272) = bits::Add64(x262, x259, uint64(uint64(x270)));
    let (x273, x274) = bits::Add64(x260, x4, uint64(uint64(x272)));
    let (x275, x276) = bits::Add64(x247, x265, uint64(0x0));
    let (x277, x278) = bits::Add64(x249, x267, uint64(uint64(x276)));
    let (x279, x280) = bits::Add64(x251, x269, uint64(uint64(x278)));
    let (x281, x282) = bits::Add64(x253, x271, uint64(uint64(x280)));
    let (x283, x284) = bits::Add64(x255, x273, uint64(uint64(x282)));
    let (x285, x286) = bits::Add64(x257, uint64(uint64(x274)), uint64(uint64(x284)));
    let (_, x287) = bits::Mul64(x275, 0x100000001);
    let (x290, x289) = bits::Mul64(x287, 0xffffffffffffffff);
    let (x292, x291) = bits::Mul64(x287, 0xffffffffffffffff);
    let (x294, x293) = bits::Mul64(x287, 0xffffffffffffffff);
    let (x296, x295) = bits::Mul64(x287, 0xfffffffffffffffe);
    let (x298, x297) = bits::Mul64(x287, 0xffffffff00000000);
    let (x300, x299) = bits::Mul64(x287, 0xffffffff);
    let (x301, x302) = bits::Add64(x300, x297, uint64(0x0));
    let (x303, x304) = bits::Add64(x298, x295, uint64(uint64(x302)));
    let (x305, x306) = bits::Add64(x296, x293, uint64(uint64(x304)));
    let (x307, x308) = bits::Add64(x294, x291, uint64(uint64(x306)));
    let (x309, x310) = bits::Add64(x292, x289, uint64(uint64(x308)));
    let (_, x312) = bits::Add64(x275, x299, uint64(0x0));
    let (x313, x314) = bits::Add64(x277, x301, uint64(uint64(x312)));
    let (x315, x316) = bits::Add64(x279, x303, uint64(uint64(x314)));
    let (x317, x318) = bits::Add64(x281, x305, uint64(uint64(x316)));
    let (x319, x320) = bits::Add64(x283, x307, uint64(uint64(x318)));
    let (x321, x322) = bits::Add64(x285, x309, uint64(uint64(x320)));
    let (x323, x324) = bits::Add64(
        ((uint64(uint64(x286))).wrapping_add(uint64(uint64(x258)))),
        ((uint64(uint64(x310))).wrapping_add(x290)),
        uint64(uint64(x322)),
    );
    let (x326, x325) = bits::Mul64(x5, 0x200000000);
    let (x328, x327) = bits::Mul64(x5, 0xfffffffe00000000);
    let (x330, x329) = bits::Mul64(x5, 0x200000000);
    let (x332, x331) = bits::Mul64(x5, 0xfffffffe00000001);
    let (x333, x334) = bits::Add64(x332, x329, uint64(0x0));
    let (x335, x336) = bits::Add64(x330, x327, uint64(uint64(x334)));
    let (x337, x338) = bits::Add64(x328, x325, uint64(uint64(x336)));
    let (x339, x340) = bits::Add64(x326, x5, uint64(uint64(x338)));
    let (x341, x342) = bits::Add64(x313, x331, uint64(0x0));
    let (x343, x344) = bits::Add64(x315, x333, uint64(uint64(x342)));
    let (x345, x346) = bits::Add64(x317, x335, uint64(uint64(x344)));
    let (x347, x348) = bits::Add64(x319, x337, uint64(uint64(x346)));
    let (x349, x350) = bits::Add64(x321, x339, uint64(uint64(x348)));
    let (x351, x352) = bits::Add64(x323, uint64(uint64(x340)), uint64(uint64(x350)));
    let (_, x353) = bits::Mul64(x341, 0x100000001);
    let (x356, x355) = bits::Mul64(x353, 0xffffffffffffffff);
    let (x358, x357) = bits::Mul64(x353, 0xffffffffffffffff);
    let (x360, x359) = bits::Mul64(x353, 0xffffffffffffffff);
    let (x362, x361) = bits::Mul64(x353, 0xfffffffffffffffe);
    let (x364, x363) = bits::Mul64(x353, 0xffffffff00000000);
    let (x366, x365) = bits::Mul64(x353, 0xffffffff);
    let (x367, x368) = bits::Add64(x366, x363, uint64(0x0));
    let (x369, x370) = bits::Add64(x364, x361, uint64(uint64(x368)));
    let (x371, x372) = bits::Add64(x362, x359, uint64(uint64(x370)));
    let (x373, x374) = bits::Add64(x360, x357, uint64(uint64(x372)));
    let (x375, x376) = bits::Add64(x358, x355, uint64(uint64(x374)));
    let (_, x378) = bits::Add64(x341, x365, uint64(0x0));
    let (x379, x380) = bits::Add64(x343, x367, uint64(uint64(x378)));
    let (x381, x382) = bits::Add64(x345, x369, uint64(uint64(x380)));
    let (x383, x384) = bits::Add64(x347, x371, uint64(uint64(x382)));
    let (x385, x386) = bits::Add64(x349, x373, uint64(uint64(x384)));
    let (x387, x388) = bits::Add64(x351, x375, uint64(uint64(x386)));
    let (x389, x390) = bits::Add64(
        ((uint64(uint64(x352))).wrapping_add(uint64(uint64(x324)))),
        ((uint64(uint64(x376))).wrapping_add(x356)),
        uint64(uint64(x388)),
    );
    let (x391, x392) = bits::Sub64(x379, 0xffffffff, uint64(0x0));
    let (x393, x394) = bits::Sub64(x381, 0xffffffff00000000, uint64(uint64(x392)));
    let (x395, x396) = bits::Sub64(x383, 0xfffffffffffffffe, uint64(uint64(x394)));
    let (x397, x398) = bits::Sub64(x385, 0xffffffffffffffff, uint64(uint64(x396)));
    let (x399, x400) = bits::Sub64(x387, 0xffffffffffffffff, uint64(uint64(x398)));
    let (x401, x402) = bits::Sub64(x389, 0xffffffffffffffff, uint64(uint64(x400)));
    let (_, x404) = bits::Sub64(uint64(uint64(x390)), uint64(0x0), uint64(uint64(x402)));
    let x405 = p384CmovznzU64(uint64(x404), x391, x379);
    let x406 = p384CmovznzU64(uint64(x404), x393, x381);
    let x407 = p384CmovznzU64(uint64(x404), x395, x383);
    let x408 = p384CmovznzU64(uint64(x404), x397, x385);
    let x409 = p384CmovznzU64(uint64(x404), x399, x387);
    let x410 = p384CmovznzU64(uint64(x404), x401, x389);
    out1[0] = x405;
    out1[1] = x406;
    out1[2] = x407;
    out1[3] = x408;
    out1[4] = x409;
    out1[5] = x410;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:2742-2761 p384Selectznz
pub(super) fn p384Selectznz(
    out1: &mut [u64; 6],
    arg1: p384Uint1,
    arg2: &[u64; 6],
    arg3: &[u64; 6],
) {
    let x1 = p384CmovznzU64(arg1, arg2[0], arg3[0]);
    let x2 = p384CmovznzU64(arg1, arg2[1], arg3[1]);
    let x3 = p384CmovznzU64(arg1, arg2[2], arg3[2]);
    let x4 = p384CmovznzU64(arg1, arg2[3], arg3[3]);
    let x5 = p384CmovznzU64(arg1, arg2[4], arg3[4]);
    let x6 = p384CmovznzU64(arg1, arg2[5], arg3[5]);
    out1[0] = x1;
    out1[1] = x2;
    out1[2] = x3;
    out1[3] = x4;
    out1[4] = x5;
    out1[5] = x6;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:2780-2919 p384ToBytes
pub(super) fn p384ToBytes(out1: &mut [u8; 48], arg1: &[u64; 6]) {
    let x1 = arg1[5];
    let x2 = arg1[4];
    let x3 = arg1[3];
    let x4 = arg1[2];
    let x5 = arg1[1];
    let x6 = arg1[0];
    let x7 = (uint8(x6) & 0xff);
    let x8 = (x6 >> 8);
    let x9 = (uint8(x8) & 0xff);
    let x10 = (x8 >> 8);
    let x11 = (uint8(x10) & 0xff);
    let x12 = (x10 >> 8);
    let x13 = (uint8(x12) & 0xff);
    let x14 = (x12 >> 8);
    let x15 = (uint8(x14) & 0xff);
    let x16 = (x14 >> 8);
    let x17 = (uint8(x16) & 0xff);
    let x18 = (x16 >> 8);
    let x19 = (uint8(x18) & 0xff);
    let x20 = uint8((x18 >> 8));
    let x21 = (uint8(x5) & 0xff);
    let x22 = (x5 >> 8);
    let x23 = (uint8(x22) & 0xff);
    let x24 = (x22 >> 8);
    let x25 = (uint8(x24) & 0xff);
    let x26 = (x24 >> 8);
    let x27 = (uint8(x26) & 0xff);
    let x28 = (x26 >> 8);
    let x29 = (uint8(x28) & 0xff);
    let x30 = (x28 >> 8);
    let x31 = (uint8(x30) & 0xff);
    let x32 = (x30 >> 8);
    let x33 = (uint8(x32) & 0xff);
    let x34 = uint8((x32 >> 8));
    let x35 = (uint8(x4) & 0xff);
    let x36 = (x4 >> 8);
    let x37 = (uint8(x36) & 0xff);
    let x38 = (x36 >> 8);
    let x39 = (uint8(x38) & 0xff);
    let x40 = (x38 >> 8);
    let x41 = (uint8(x40) & 0xff);
    let x42 = (x40 >> 8);
    let x43 = (uint8(x42) & 0xff);
    let x44 = (x42 >> 8);
    let x45 = (uint8(x44) & 0xff);
    let x46 = (x44 >> 8);
    let x47 = (uint8(x46) & 0xff);
    let x48 = uint8((x46 >> 8));
    let x49 = (uint8(x3) & 0xff);
    let x50 = (x3 >> 8);
    let x51 = (uint8(x50) & 0xff);
    let x52 = (x50 >> 8);
    let x53 = (uint8(x52) & 0xff);
    let x54 = (x52 >> 8);
    let x55 = (uint8(x54) & 0xff);
    let x56 = (x54 >> 8);
    let x57 = (uint8(x56) & 0xff);
    let x58 = (x56 >> 8);
    let x59 = (uint8(x58) & 0xff);
    let x60 = (x58 >> 8);
    let x61 = (uint8(x60) & 0xff);
    let x62 = uint8((x60 >> 8));
    let x63 = (uint8(x2) & 0xff);
    let x64 = (x2 >> 8);
    let x65 = (uint8(x64) & 0xff);
    let x66 = (x64 >> 8);
    let x67 = (uint8(x66) & 0xff);
    let x68 = (x66 >> 8);
    let x69 = (uint8(x68) & 0xff);
    let x70 = (x68 >> 8);
    let x71 = (uint8(x70) & 0xff);
    let x72 = (x70 >> 8);
    let x73 = (uint8(x72) & 0xff);
    let x74 = (x72 >> 8);
    let x75 = (uint8(x74) & 0xff);
    let x76 = uint8((x74 >> 8));
    let x77 = (uint8(x1) & 0xff);
    let x78 = (x1 >> 8);
    let x79 = (uint8(x78) & 0xff);
    let x80 = (x78 >> 8);
    let x81 = (uint8(x80) & 0xff);
    let x82 = (x80 >> 8);
    let x83 = (uint8(x82) & 0xff);
    let x84 = (x82 >> 8);
    let x85 = (uint8(x84) & 0xff);
    let x86 = (x84 >> 8);
    let x87 = (uint8(x86) & 0xff);
    let x88 = (x86 >> 8);
    let x89 = (uint8(x88) & 0xff);
    let x90 = uint8((x88 >> 8));
    out1[0] = x7;
    out1[1] = x9;
    out1[2] = x11;
    out1[3] = x13;
    out1[4] = x15;
    out1[5] = x17;
    out1[6] = x19;
    out1[7] = x20;
    out1[8] = x21;
    out1[9] = x23;
    out1[10] = x25;
    out1[11] = x27;
    out1[12] = x29;
    out1[13] = x31;
    out1[14] = x33;
    out1[15] = x34;
    out1[16] = x35;
    out1[17] = x37;
    out1[18] = x39;
    out1[19] = x41;
    out1[20] = x43;
    out1[21] = x45;
    out1[22] = x47;
    out1[23] = x48;
    out1[24] = x49;
    out1[25] = x51;
    out1[26] = x53;
    out1[27] = x55;
    out1[28] = x57;
    out1[29] = x59;
    out1[30] = x61;
    out1[31] = x62;
    out1[32] = x63;
    out1[33] = x65;
    out1[34] = x67;
    out1[35] = x69;
    out1[36] = x71;
    out1[37] = x73;
    out1[38] = x75;
    out1[39] = x76;
    out1[40] = x77;
    out1[41] = x79;
    out1[42] = x81;
    out1[43] = x83;
    out1[44] = x85;
    out1[45] = x87;
    out1[46] = x89;
    out1[47] = x90;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_fiat64.go:2939-3036 p384FromBytes
pub(super) fn p384FromBytes(out1: &mut [u64; 6], arg1: &[u8; 48]) {
    let x1 = (uint64(arg1[47]) << 56);
    let x2 = (uint64(arg1[46]) << 48);
    let x3 = (uint64(arg1[45]) << 40);
    let x4 = (uint64(arg1[44]) << 32);
    let x5 = (uint64(arg1[43]) << 24);
    let x6 = (uint64(arg1[42]) << 16);
    let x7 = (uint64(arg1[41]) << 8);
    let x8 = arg1[40];
    let x9 = (uint64(arg1[39]) << 56);
    let x10 = (uint64(arg1[38]) << 48);
    let x11 = (uint64(arg1[37]) << 40);
    let x12 = (uint64(arg1[36]) << 32);
    let x13 = (uint64(arg1[35]) << 24);
    let x14 = (uint64(arg1[34]) << 16);
    let x15 = (uint64(arg1[33]) << 8);
    let x16 = arg1[32];
    let x17 = (uint64(arg1[31]) << 56);
    let x18 = (uint64(arg1[30]) << 48);
    let x19 = (uint64(arg1[29]) << 40);
    let x20 = (uint64(arg1[28]) << 32);
    let x21 = (uint64(arg1[27]) << 24);
    let x22 = (uint64(arg1[26]) << 16);
    let x23 = (uint64(arg1[25]) << 8);
    let x24 = arg1[24];
    let x25 = (uint64(arg1[23]) << 56);
    let x26 = (uint64(arg1[22]) << 48);
    let x27 = (uint64(arg1[21]) << 40);
    let x28 = (uint64(arg1[20]) << 32);
    let x29 = (uint64(arg1[19]) << 24);
    let x30 = (uint64(arg1[18]) << 16);
    let x31 = (uint64(arg1[17]) << 8);
    let x32 = arg1[16];
    let x33 = (uint64(arg1[15]) << 56);
    let x34 = (uint64(arg1[14]) << 48);
    let x35 = (uint64(arg1[13]) << 40);
    let x36 = (uint64(arg1[12]) << 32);
    let x37 = (uint64(arg1[11]) << 24);
    let x38 = (uint64(arg1[10]) << 16);
    let x39 = (uint64(arg1[9]) << 8);
    let x40 = arg1[8];
    let x41 = (uint64(arg1[7]) << 56);
    let x42 = (uint64(arg1[6]) << 48);
    let x43 = (uint64(arg1[5]) << 40);
    let x44 = (uint64(arg1[4]) << 32);
    let x45 = (uint64(arg1[3]) << 24);
    let x46 = (uint64(arg1[2]) << 16);
    let x47 = (uint64(arg1[1]) << 8);
    let x48 = arg1[0];
    let x49 = ((x47).wrapping_add(uint64(x48)));
    let x50 = ((x46).wrapping_add(x49));
    let x51 = ((x45).wrapping_add(x50));
    let x52 = ((x44).wrapping_add(x51));
    let x53 = ((x43).wrapping_add(x52));
    let x54 = ((x42).wrapping_add(x53));
    let x55 = ((x41).wrapping_add(x54));
    let x56 = ((x39).wrapping_add(uint64(x40)));
    let x57 = ((x38).wrapping_add(x56));
    let x58 = ((x37).wrapping_add(x57));
    let x59 = ((x36).wrapping_add(x58));
    let x60 = ((x35).wrapping_add(x59));
    let x61 = ((x34).wrapping_add(x60));
    let x62 = ((x33).wrapping_add(x61));
    let x63 = ((x31).wrapping_add(uint64(x32)));
    let x64 = ((x30).wrapping_add(x63));
    let x65 = ((x29).wrapping_add(x64));
    let x66 = ((x28).wrapping_add(x65));
    let x67 = ((x27).wrapping_add(x66));
    let x68 = ((x26).wrapping_add(x67));
    let x69 = ((x25).wrapping_add(x68));
    let x70 = ((x23).wrapping_add(uint64(x24)));
    let x71 = ((x22).wrapping_add(x70));
    let x72 = ((x21).wrapping_add(x71));
    let x73 = ((x20).wrapping_add(x72));
    let x74 = ((x19).wrapping_add(x73));
    let x75 = ((x18).wrapping_add(x74));
    let x76 = ((x17).wrapping_add(x75));
    let x77 = ((x15).wrapping_add(uint64(x16)));
    let x78 = ((x14).wrapping_add(x77));
    let x79 = ((x13).wrapping_add(x78));
    let x80 = ((x12).wrapping_add(x79));
    let x81 = ((x11).wrapping_add(x80));
    let x82 = ((x10).wrapping_add(x81));
    let x83 = ((x9).wrapping_add(x82));
    let x84 = ((x7).wrapping_add(uint64(x8)));
    let x85 = ((x6).wrapping_add(x84));
    let x86 = ((x5).wrapping_add(x85));
    let x87 = ((x4).wrapping_add(x86));
    let x88 = ((x3).wrapping_add(x87));
    let x89 = ((x2).wrapping_add(x88));
    let x90 = ((x1).wrapping_add(x89));
    out1[0] = x55;
    out1[1] = x62;
    out1[2] = x69;
    out1[3] = x76;
    out1[4] = x83;
    out1[5] = x90;
}
