// go: file crypto/internal/fips140/nistec/fiat/p384_invert.go decls: P384Element.Invert
//
// Code generated by addchain. DO NOT EDIT.
//
// Translated from Go by scripts/fiat_invert_to_rust.py. A transposed
// operand or an off-by-one loop bound here produces a wrong inverse
// silently, so the translation is mechanical and its parser raises on
// anything it does not recognise. Regenerate with scripts/fiat_gen.py.

#![allow(non_snake_case)]

use super::p384::P384Element;
use crate::types::int;

impl P384Element {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384_invert.go:12-102 P384Element.Invert
    /// Set e = 1/x, and return e.
    ///
    /// If x == 0, Invert returns e = 0.
    pub fn Invert(&mut self, x: &P384Element) -> &mut Self {
        // Inversion is implemented as exponentiation with exponent p − 2.
        // The sequence of 15 multiplications and 383 squarings is derived from the
        // following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
        //
        //	_10     = 2*1
        //	_11     = 1 + _10
        //	_110    = 2*_11
        //	_111    = 1 + _110
        //	_111000 = _111 << 3
        //	_111111 = _111 + _111000
        //	x12     = _111111 << 6 + _111111
        //	x24     = x12 << 12 + x12
        //	x30     = x24 << 6 + _111111
        //	x31     = 2*x30 + 1
        //	x32     = 2*x31 + 1
        //	x63     = x32 << 31 + x31
        //	x126    = x63 << 63 + x63
        //	x252    = x126 << 126 + x126
        //	x255    = x252 << 3 + _111
        //	i397    = ((x255 << 33 + x32) << 94 + x30) << 2
        //	return    1 + i397
        //
        let mut z = P384Element::New();
        z.Set(*self);
        let mut t0 = P384Element::New();
        let mut t1 = P384Element::New();
        let mut t2 = P384Element::New();
        let mut t3 = P384Element::New();
        z.Square(*x);
        z.Mul(*x, z);
        z.Square(z);
        t1.Mul(*x, z);
        z.Square(t1);
        // Go: for s := 1; s < 3; s++
        let mut s: int = 1;
        while s < 3 {
            z.Square(z);
            s += 1;
        }
        z.Mul(t1, z);
        t0.Square(z);
        // Go: for s := 1; s < 6; s++
        let mut s: int = 1;
        while s < 6 {
            t0.Square(t0);
            s += 1;
        }
        t0.Mul(z, t0);
        t2.Square(t0);
        // Go: for s := 1; s < 12; s++
        let mut s: int = 1;
        while s < 12 {
            t2.Square(t2);
            s += 1;
        }
        t0.Mul(t0, t2);
        // Go: for s := 0; s < 6; s++
        let mut s: int = 0;
        while s < 6 {
            t0.Square(t0);
            s += 1;
        }
        z.Mul(z, t0);
        t0.Square(z);
        t2.Mul(*x, t0);
        t0.Square(t2);
        t0.Mul(*x, t0);
        t3.Square(t0);
        // Go: for s := 1; s < 31; s++
        let mut s: int = 1;
        while s < 31 {
            t3.Square(t3);
            s += 1;
        }
        t2.Mul(t2, t3);
        t3.Square(t2);
        // Go: for s := 1; s < 63; s++
        let mut s: int = 1;
        while s < 63 {
            t3.Square(t3);
            s += 1;
        }
        t2.Mul(t2, t3);
        t3.Square(t2);
        // Go: for s := 1; s < 126; s++
        let mut s: int = 1;
        while s < 126 {
            t3.Square(t3);
            s += 1;
        }
        t2.Mul(t2, t3);
        // Go: for s := 0; s < 3; s++
        let mut s: int = 0;
        while s < 3 {
            t2.Square(t2);
            s += 1;
        }
        t1.Mul(t1, t2);
        // Go: for s := 0; s < 33; s++
        let mut s: int = 0;
        while s < 33 {
            t1.Square(t1);
            s += 1;
        }
        t0.Mul(t0, t1);
        // Go: for s := 0; s < 94; s++
        let mut s: int = 0;
        while s < 94 {
            t0.Square(t0);
            s += 1;
        }
        z.Mul(z, t0);
        // Go: for s := 0; s < 2; s++
        let mut s: int = 0;
        while s < 2 {
            z.Square(z);
            s += 1;
        }
        z.Mul(*x, z);
        return self.Set(z);
    }
}
