// go: file crypto/internal/fips140/nistec/fiat/p384.go decls: P384Element.One, P384Element.Equal, P384Element.IsZero, P384Element.Set, P384Element.Bytes, P384Element.bytes, P384Element.SetBytes, P384Element.Add, P384Element.Sub, P384Element.Mul, P384Element.Square, P384Element.Select, p384InvertEndianness
//
// Code generated by generate.go. DO NOT EDIT.
//
// Deviation from p384[go] @ Go 1.25.5: Go takes every field-element
// operand as `*P384Element` and freely aliases the receiver
// (`e.Add(e, t)`). P384Element is `[u64; 6]` and therefore Copy, so
// operands are taken **by value** — which costs one register copy and
// makes the aliasing call sites Go relies on translate directly. Passing
// `&P384Element` instead would make `e.Add(e, t)` a borrow error at
// every nistec call site.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]

extern crate alloc;
use alloc::vec::Vec;

use super::p384_fiat64::*;
use crate::crypto::internal::fips140::subtle;
use crate::errors;
use crate::goslice::slice;
use crate::types::byte;
use crate::{error, int, uint64};

// Go: p384.go:14-21
//   type P384Element struct { x p384MontgomeryDomainFieldElement }
/// An integer modulo 2^384 - 2^128 - 2^96 + 2^32 - 1.
///
/// The zero value is a valid zero element.
#[derive(Clone, Copy, Default)]
pub struct P384Element {
    /// Values are represented internally always in the Montgomery domain,
    /// and converted in Bytes and SetBytes.
    pub(crate) x: [u64; 6],
}

/// Go: `const p384ElementLen = 48`
pub const p384ElementLen: usize = 48;

/// Go: `type p384UntypedFieldElement = [6]uint64`
pub type p384UntypedFieldElement = [u64; 6];

impl P384Element {
    // go: none — Go gets the zero value from `new(P384Element)`.
    pub fn New() -> Self {
        return P384Element { x: [0; 6] };
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:27-31 P384Element.One
    /// Set e = 1, and return e.
    pub fn One(&mut self) -> &mut Self {
        p384SetOne(&mut self.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:33-38 P384Element.Equal
    /// Return 1 if e == t, and zero otherwise.
    pub fn Equal(&self, t: P384Element) -> int {
        let eBytes = self.Bytes();
        let tBytes = t.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &tBytes);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:40-45 P384Element.IsZero
    /// Return 1 if e == 0, and zero otherwise.
    pub fn IsZero(&self) -> int {
        let zero = slice::__from_vec(alloc::vec![0u8; p384ElementLen]);
        let eBytes = self.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &zero);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:47-51 P384Element.Set
    /// Set e = t, and return e.
    pub fn Set(&mut self, t: P384Element) -> &mut Self {
        self.x = t.x;
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:53-59 P384Element.Bytes
    /// Return the 48-byte big-endian encoding of e.
    pub fn Bytes(&self) -> slice<byte> {
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; p384ElementLen];
        return self.bytes(&mut out);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:61-67 P384Element.bytes
    fn bytes(&self, out: &mut [byte; p384ElementLen]) -> slice<byte> {
        let mut tmp: [u64; 6] = [0; 6];
        p384FromMontgomery(&mut tmp, &self.x);
        p384ToBytes(out, &tmp);
        p384InvertEndianness(out);
        return slice::__from_vec(out.to_vec());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:69-92 P384Element.SetBytes
    /// Set e = v, where v is a big-endian 48-byte encoding, and return e.
    /// If v is not 48 bytes or it encodes a value higher than
    /// 2^384 - 2^128 - 2^96 + 2^32 - 1, SetBytes returns an error and e is unchanged.
    pub fn SetBytes(&mut self, v: slice<byte>) -> error {
        // Go: if len(v) != p384ElementLen { return nil, errors.New(…) }
        if v.Len() != int(p384ElementLen) {
            return errors::New("invalid P384Element encoding");
        }

        // Check for non-canonical encodings (p + k, 2p + k, etc.) by
        // comparing to the encoding of -1 mod p, so p - 1, the highest
        // canonical encoding.
        let mut one = P384Element::New();
        one.One();
        let mut minusOne = P384Element::New();
        minusOne.Sub(P384Element::New(), one);
        let minusOneEncoding = minusOne.Bytes();
        if subtle::ConstantTimeLessOrEqBytes(&v, &minusOneEncoding) == 0 {
            return errors::New("invalid P384Element encoding");
        }

        // Go: var in [p384ElementLen]byte; copy(in[:], v); p384InvertEndianness(in[:])
        let mut inp = [0u8; p384ElementLen];
        let raw: &[byte] = &v;
        inp.copy_from_slice(raw);
        p384InvertEndianness(&mut inp);
        let mut tmp: [u64; 6] = [0; 6];
        p384FromBytes(&mut tmp, &inp);
        p384ToMontgomery(&mut self.x, &tmp);
        return crate::nil.into();
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:94-98 P384Element.Add
    /// Set e = t1 + t2, and return e.
    pub fn Add(&mut self, t1: P384Element, t2: P384Element) -> &mut Self {
        p384Add(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:100-104 P384Element.Sub
    /// Set e = t1 - t2, and return e.
    pub fn Sub(&mut self, t1: P384Element, t2: P384Element) -> &mut Self {
        p384Sub(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:106-110 P384Element.Mul
    /// Set e = t1 * t2, and return e.
    pub fn Mul(&mut self, t1: P384Element, t2: P384Element) -> &mut Self {
        p384Mul(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:112-116 P384Element.Square
    /// Set e = t * t, and return e.
    pub fn Square(&mut self, t: P384Element) -> &mut Self {
        p384Square(&mut self.x, &t.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:118-123 P384Element.Select
    /// Set v to a if cond == 1, and to b if cond == 0.
    pub fn Select(&mut self, a: P384Element, b: P384Element, cond: int) -> &mut Self {
        p384Selectznz(&mut self.x, uint64(cond), &b.x, &a.x);
        return self;
    }
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p384.go:125-129 p384InvertEndianness
pub(crate) fn p384InvertEndianness(v: &mut [byte]) {
    // Go: for i := 0; i < len(v)/2; i++ { v[i], v[len(v)-1-i] = v[len(v)-1-i], v[i] }
    let mut i: usize = 0;
    while i < v.len() / 2 {
        let j = v.len() - 1 - i;
        let t = v[i];
        v[i] = v[j];
        v[j] = t;
        i += 1;
    }
}

// Silence the unused-import warning when Vec is only reached via vec!.
const _: fn() -> Vec<byte> = Vec::new;
