// go: file crypto/internal/fips140/nistec/fiat/p521.go decls: P521Element.One, P521Element.Equal, P521Element.IsZero, P521Element.Set, P521Element.Bytes, P521Element.bytes, P521Element.SetBytes, P521Element.Add, P521Element.Sub, P521Element.Mul, P521Element.Square, P521Element.Select, p521InvertEndianness
//
// Code generated by generate.go. DO NOT EDIT.
//
// Deviation from p521[go] @ Go 1.25.5: Go takes every field-element
// operand as `*P521Element` and freely aliases the receiver
// (`e.Add(e, t)`). P521Element is `[u64; 9]` and therefore Copy, so
// operands are taken **by value** — which costs one register copy and
// makes the aliasing call sites Go relies on translate directly. Passing
// `&P521Element` instead would make `e.Add(e, t)` a borrow error at
// every nistec call site.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]

extern crate alloc;
use alloc::vec::Vec;

use super::p521_fiat64::*;
use crate::crypto::internal::fips140::subtle;
use crate::errors;
use crate::goslice::slice;
use crate::types::byte;
use crate::{error, int, uint64};

// Go: p521.go:14-21
//   type P521Element struct { x p521MontgomeryDomainFieldElement }
/// An integer modulo 2^521 - 1.
///
/// The zero value is a valid zero element.
#[derive(Clone, Copy, Default)]
pub struct P521Element {
    /// Values are represented internally always in the Montgomery domain,
    /// and converted in Bytes and SetBytes.
    pub(crate) x: [u64; 9],
}

/// Go: `const p521ElementLen = 66`
pub const p521ElementLen: usize = 66;

/// Go: `type p521UntypedFieldElement = [9]uint64`
pub type p521UntypedFieldElement = [u64; 9];

impl P521Element {
    // go: none — Go gets the zero value from `new(P521Element)`.
    pub fn New() -> Self {
        return P521Element { x: [0; 9] };
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:27-31 One
    /// Set e = 1, and return e.
    pub fn One(&mut self) -> &mut Self {
        p521SetOne(&mut self.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:33-38 Equal
    /// Return 1 if e == t, and zero otherwise.
    pub fn Equal(&self, t: P521Element) -> int {
        let eBytes = self.Bytes();
        let tBytes = t.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &tBytes);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:40-45 IsZero
    /// Return 1 if e == 0, and zero otherwise.
    pub fn IsZero(&self) -> int {
        let zero = slice::__from_vec(alloc::vec![0u8; p521ElementLen]);
        let eBytes = self.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &zero);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:47-51 Set
    /// Set e = t, and return e.
    pub fn Set(&mut self, t: P521Element) -> &mut Self {
        self.x = t.x;
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:53-59 Bytes
    /// Return the 66-byte big-endian encoding of e.
    pub fn Bytes(&self) -> slice<byte> {
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; p521ElementLen];
        return self.bytes(&mut out);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:61-67 bytes
    fn bytes(&self, out: &mut [byte; p521ElementLen]) -> slice<byte> {
        let mut tmp: [u64; 9] = [0; 9];
        p521FromMontgomery(&mut tmp, &self.x);
        p521ToBytes(out, &tmp);
        p521InvertEndianness(out);
        return slice::__from_vec(out.to_vec());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:69-92 SetBytes
    /// Set e = v, where v is a big-endian 66-byte encoding, and return e.
    /// If v is not 66 bytes or it encodes a value higher than
    /// 2^521 - 1, SetBytes returns an error and e is unchanged.
    pub fn SetBytes(&mut self, v: slice<byte>) -> error {
        // Go: if len(v) != p521ElementLen { return nil, errors.New(…) }
        if v.Len() != int(p521ElementLen) {
            return errors::New("invalid P521Element encoding");
        }

        // Check for non-canonical encodings (p + k, 2p + k, etc.) by
        // comparing to the encoding of -1 mod p, so p - 1, the highest
        // canonical encoding.
        let mut one = P521Element::New();
        one.One();
        let mut minusOne = P521Element::New();
        minusOne.Sub(P521Element::New(), one);
        let minusOneEncoding = minusOne.Bytes();
        if subtle::ConstantTimeLessOrEqBytes(&v, &minusOneEncoding) == 0 {
            return errors::New("invalid P521Element encoding");
        }

        // Go: var in [p521ElementLen]byte; copy(in[:], v); p521InvertEndianness(in[:])
        let mut inp = [0u8; p521ElementLen];
        let raw: &[byte] = &v;
        inp.copy_from_slice(raw);
        p521InvertEndianness(&mut inp);
        let mut tmp: [u64; 9] = [0; 9];
        p521FromBytes(&mut tmp, &inp);
        p521ToMontgomery(&mut self.x, &tmp);
        return crate::nil.into();
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:94-98 Add
    /// Set e = t1 + t2, and return e.
    pub fn Add(&mut self, t1: P521Element, t2: P521Element) -> &mut Self {
        p521Add(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:100-104 Sub
    /// Set e = t1 - t2, and return e.
    pub fn Sub(&mut self, t1: P521Element, t2: P521Element) -> &mut Self {
        p521Sub(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:106-110 Mul
    /// Set e = t1 * t2, and return e.
    pub fn Mul(&mut self, t1: P521Element, t2: P521Element) -> &mut Self {
        p521Mul(&mut self.x, &t1.x, &t2.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:112-116 Square
    /// Set e = t * t, and return e.
    pub fn Square(&mut self, t: P521Element) -> &mut Self {
        p521Square(&mut self.x, &t.x);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:118-123 Select
    /// Set v to a if cond == 1, and to b if cond == 0.
    pub fn Select(&mut self, a: P521Element, b: P521Element, cond: int) -> &mut Self {
        p521Selectznz(&mut self.x, uint64(cond), &b.x, &a.x);
        return self;
    }
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/p521.go:125-129 p521InvertEndianness
pub(crate) fn p521InvertEndianness(v: &mut [byte]) {
    // Go: for i := 0; i < len(v)/2; i++ { v[i], v[len(v)-1-i] = v[len(v)-1-i], v[i] }
    let mut i: usize = 0;
    while i < v.len() / 2 {
        let j = v.len() - 1 - i;
        let t = v[i];
        v[i] = v[j];
        v[j] = t;
        i += 1;
    }
}

// Silence the unused-import warning when Vec is only reached via vec!.
const _: fn() -> Vec<byte> = Vec::new;
