// reflect — Go's `reflect` package, first slice.
//
//   Go                                   goish
//   ──────────────────────────────────   ──────────────────────────────────
//   t := reflect.TypeOf(p)               let t = reflect::TypeOf(&p);
//   t.Name()                             t.Name()
//   t.Kind()                             t.Kind()
//   t.NumField()                         t.NumField()
//   f := t.Field(0)                      let f = t.Field(0);
//   f.Name                               f.Name
//   f.Tag.Get("json")                    f.Tag.Get("json")
//   v, ok := f.Tag.Lookup("xml")         let (v, ok) = f.Tag.Lookup("xml");
//
// Backing: per-struct static `Type` descriptors generated by the
// `#[goish::reflect]` proc-macro. Built-in primitives (bool, int, byte,
// rune, uint, float32, float64, string) get `Reflect` impls in this file.
//
// First slice covers Type/StructField/StructTag and their accessors.
// `Value` (actual data introspection), generic Reflect for slice/map,
// and json integration follow in later iterations.
//
// v1 deviations from Go:
//
//   * `Kind::Int` corresponds to i64 (= goish `int`); there's no separate
//     `Kind::Int64` because `int` IS `i64`. Same for `Kind::Uint` (= u64).
//   * `StructField.Type` is `fn() -> Type` (late binding). Go's
//     `StructField.Type` is a `reflect.Type` interface value, evaluated
//     lazily under the hood. Goish uses the explicit fn-pointer form.
//   * `Reflect` is an opt-in trait. User structs add `#[goish::reflect]`;
//     primitives have impls in this file. Convention: every goish-defined
//     `type X struct` should carry `#[goish::reflect]`.

#![allow(non_snake_case, non_upper_case_globals)]

extern crate alloc;

use alloc::boxed::Box;
use alloc::vec::Vec;

use crate::goslice::slice;
use crate::gostring::string;
use crate::types::{byte, float32, float64, int, rune, uint};

// ─── Kind ─────────────────────────────────────────────────────────────

/// Mirrors `reflect.Kind`. Numeric ordering matches Go where possible
/// (Invalid = 0; Bool = 1; …) so debug-printing comes out the same.
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Kind {
    Invalid = 0,
    Bool = 1,
    Int = 2,
    Int8 = 3,
    Int16 = 4,
    Int32 = 5,
    Uint = 6,
    Uint8 = 7,
    Uint16 = 8,
    Uint32 = 9,
    Float32 = 10,
    Float64 = 11,
    String = 12,
    Slice = 13,
    Map = 14,
    Struct = 15,
    Pointer = 16,
}

impl Kind {
    /// Mirrors Go's `Kind.String()` — lowercase Go type name.
    pub fn String(&self) -> string {
        let s = match self {
            Kind::Invalid => "invalid",
            Kind::Bool => "bool",
            Kind::Int => "int",
            Kind::Int8 => "int8",
            Kind::Int16 => "int16",
            Kind::Int32 => "int32",
            Kind::Uint => "uint",
            Kind::Uint8 => "uint8",
            Kind::Uint16 => "uint16",
            Kind::Uint32 => "uint32",
            Kind::Float32 => "float32",
            Kind::Float64 => "float64",
            Kind::String => "string",
            Kind::Slice => "slice",
            Kind::Map => "map",
            Kind::Struct => "struct",
            Kind::Pointer => "ptr",
        };
        string::from_static(s)
    }
}

// ─── StructTag ────────────────────────────────────────────────────────

/// Mirrors `reflect.StructTag`. Holds the raw tag string verbatim
/// (e.g. `r#"json:"name" xml:"name,attr""#`) and parses on demand.
///
/// Constructors are `__new` (private path) so `#[goish::reflect]` can
/// embed it in static descriptors.
#[derive(Clone, Copy)]
pub struct StructTag {
    raw: &'static str,
}

impl StructTag {
    /// Internal constructor used by the `#[goish::reflect]` macro and
    /// by built-in Reflect impls. Empty string means "no tag".
    #[doc(hidden)]
    pub const fn __new(raw: &'static str) -> Self {
        Self { raw }
    }

    /// `Get(key)` — value for `key`, empty string if missing.
    /// Mirrors Go's `StructTag.Get`.
    pub fn Get(&self, key: &str) -> string {
        let (v, _) = self.Lookup(key);
        v
    }

    /// `Lookup(key)` — `(value, ok)`. `ok` distinguishes "absent" from
    /// "present with empty value". Verbatim port of Go 1.25
    /// `reflect.StructTag.Lookup` (reflect/type.go:1056).
    pub fn Lookup(&self, key: &str) -> (string, bool) {
        let mut tag = self.raw.as_bytes();

        while !tag.is_empty() {
            // Skip leading space.
            let mut i = 0;
            while i < tag.len() && tag[i] == b' ' {
                i += 1;
            }
            tag = &tag[i..];
            if tag.is_empty() {
                break;
            }

            // Scan to colon. A space, quote, or control char is a syntax error.
            i = 0;
            while i < tag.len()
                && tag[i] > b' '
                && tag[i] != b':'
                && tag[i] != b'"'
                && tag[i] != 0x7f
            {
                i += 1;
            }
            if i == 0 || i + 1 >= tag.len() || tag[i] != b':' || tag[i + 1] != b'"' {
                break;
            }
            let name = &tag[..i];
            tag = &tag[i + 1..];

            // Scan quoted string.
            i = 1;
            while i < tag.len() && tag[i] != b'"' {
                if tag[i] == b'\\' {
                    i += 1;
                }
                i += 1;
            }
            if i >= tag.len() {
                break;
            }
            let qvalue = &tag[..i + 1];
            tag = &tag[i + 1..];

            if key.as_bytes() == name {
                if let Some(v) = unquote_tag_value(qvalue) {
                    return (v, true);
                }
                break;
            }
        }
        (string::new(), false)
    }
}

/// Strip surrounding `"` and apply Go string-literal escape rules to the
/// inside. Returns `None` on malformed input (mirrors strconv.Unquote err).
fn unquote_tag_value(q: &[u8]) -> Option<string> {
    if q.len() < 2 || q[0] != b'"' || q[q.len() - 1] != b'"' {
        return None;
    }
    let inner = &q[1..q.len() - 1];
    let mut out: alloc::vec::Vec<u8> = alloc::vec::Vec::with_capacity(inner.len());
    let mut i = 0;
    while i < inner.len() {
        let c = inner[i];
        if c != b'\\' {
            out.push(c);
            i += 1;
            continue;
        }
        // escape sequence
        i += 1;
        if i >= inner.len() {
            return None;
        }
        match inner[i] {
            b'"' => out.push(b'"'),
            b'\\' => out.push(b'\\'),
            b'/' => out.push(b'/'),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'a' => out.push(0x07),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0C),
            b'v' => out.push(0x0B),
            b'0' => out.push(0),
            b'\'' => out.push(b'\''),
            // \xNN / \uNNNN are not parsed in v1 — tag values almost
            // never use them in practice. Add when needed.
            _ => return None,
        }
        i += 1;
    }
    Some(string::__from_vec(out))
}

// ─── StructField ──────────────────────────────────────────────────────

/// Mirrors `reflect.StructField`. Held by value inside a `Type`'s field
/// table. `Type` is a fn pointer for late binding (breaks recursion when
/// a struct field type is itself a Reflect type that hasn't been defined
/// when the descriptor is built).
#[derive(Clone, Copy)]
pub struct StructField {
    pub Name: &'static str,
    pub Tag: StructTag,
    pub Type: fn() -> Type,
}

// ─── Type ─────────────────────────────────────────────────────────────

/// Mirrors `reflect.Type`. The struct is value-typed; `TypeOf` returns
/// it by value (cheap — a few words). `elem` and `key` carry late-bound
/// element/key descriptors for Slice / Map / Pointer kinds.
#[derive(Clone, Copy)]
pub struct Type {
    kind: Kind,
    name: &'static str,
    fields: &'static [StructField],
    elem: Option<fn() -> Type>,
    key: Option<fn() -> Type>,
}

impl Type {
    /// Internal constructor for `#[goish::reflect]` and built-in impls.
    #[doc(hidden)]
    pub const fn __new(
        kind: Kind,
        name: &'static str,
        fields: &'static [StructField],
    ) -> Self {
        Self {
            kind,
            name,
            fields,
            elem: None,
            key: None,
        }
    }

    /// Builder hook for slice/pointer/map element types.
    #[doc(hidden)]
    pub const fn __with_elem(self, e: fn() -> Type) -> Self {
        Self { elem: Some(e), ..self }
    }

    /// Builder hook for map key types.
    #[doc(hidden)]
    pub const fn __with_key(self, k: fn() -> Type) -> Self {
        Self { key: Some(k), ..self }
    }

    /// `Name()` — declared type name, or `""` for unnamed types.
    pub fn Name(&self) -> &'static str {
        self.name
    }

    /// `Kind()` — kind tag.
    pub fn Kind(&self) -> Kind {
        self.kind
    }

    /// `NumField()` — number of struct fields. Panics in Go for non-struct
    /// kinds; here we return 0 (less surprising for boilerplate code).
    pub fn NumField(&self) -> int {
        self.fields.len() as int
    }

    /// `Field(i)` — i-th struct field. Panics if out of range.
    pub fn Field(&self, i: int) -> StructField {
        if i < 0 || (i as usize) >= self.fields.len() {
            panic!("reflect: Field index out of bounds");
        }
        self.fields[i as usize]
    }

    /// `FieldByName(name)` — `(field, ok)`. Linear scan.
    pub fn FieldByName(&self, name: &str) -> (StructField, bool) {
        for f in self.fields {
            if f.Name.as_bytes() == name.as_bytes() {
                return (*f, true);
            }
        }
        (
            StructField {
                Name: "",
                Tag: StructTag::__new(""),
                Type: || Type::__new(Kind::Invalid, "", &[]),
            },
            false,
        )
    }

    /// `Elem()` — element type for Slice / Map / Pointer. Panics for
    /// other kinds, mirroring Go.
    pub fn Elem(&self) -> Type {
        match self.elem {
            Some(f) => f(),
            None => panic!("reflect: Elem of type that has no element"),
        }
    }

    /// `Key()` — key type for Map. Panics for other kinds.
    pub fn Key(&self) -> Type {
        match self.key {
            Some(f) => f(),
            None => panic!("reflect: Key of non-map type"),
        }
    }

    /// `Comparable()` — Go semantics. Primitives + Pointer + (Struct of
    /// comparables) are comparable; Slice and Map are not.
    pub fn Comparable(&self) -> bool {
        match self.kind {
            Kind::Bool
            | Kind::Int
            | Kind::Int8
            | Kind::Int16
            | Kind::Int32
            | Kind::Uint
            | Kind::Uint8
            | Kind::Uint16
            | Kind::Uint32
            | Kind::Float32
            | Kind::Float64
            | Kind::String
            | Kind::Pointer => true,
            Kind::Slice | Kind::Map => false,
            Kind::Struct => self.fields.iter().all(|f| (f.Type)().Comparable()),
            Kind::Invalid => false,
        }
    }

    /// `AssignableTo(u)` — v1 simplification: Kind must match; for named
    /// types Name must match; for slice/map element & key types must be
    /// recursively assignable. (Go's full interface-satisfaction logic
    /// is out of scope until goish gains an interface type.)
    pub fn AssignableTo(&self, u: &Type) -> bool {
        if self.kind != u.kind {
            return false;
        }
        if !self.name.is_empty() || !u.name.is_empty() {
            return self.name == u.name;
        }
        match self.kind {
            Kind::Slice => {
                if self.elem.is_none() || u.elem.is_none() {
                    return false;
                }
                self.Elem().AssignableTo(&u.Elem())
            }
            Kind::Map => {
                if self.elem.is_none() || u.elem.is_none() || self.key.is_none() || u.key.is_none() {
                    return false;
                }
                self.Key().AssignableTo(&u.Key()) && self.Elem().AssignableTo(&u.Elem())
            }
            _ => true,
        }
    }

    /// `String()` — readable type name. `[]int`, `map[string]int`,
    /// `*Person`, `Person`, `int`, etc. Mirrors Go's `Type.String()`.
    pub fn String(&self) -> string {
        match self.kind {
            Kind::Slice => {
                let mut out: alloc::vec::Vec<u8> = b"[]".to_vec();
                if let Some(e) = self.elem {
                    out.extend_from_slice(e().String().as_bytes());
                }
                string::__from_vec(out)
            }
            Kind::Map => {
                let mut out: alloc::vec::Vec<u8> = b"map[".to_vec();
                if let Some(k) = self.key {
                    out.extend_from_slice(k().String().as_bytes());
                }
                out.push(b']');
                if let Some(e) = self.elem {
                    out.extend_from_slice(e().String().as_bytes());
                }
                string::__from_vec(out)
            }
            Kind::Pointer => {
                let mut out: alloc::vec::Vec<u8> = b"*".to_vec();
                if let Some(e) = self.elem {
                    out.extend_from_slice(e().String().as_bytes());
                }
                string::__from_vec(out)
            }
            _ => {
                if self.name.is_empty() {
                    self.kind.String()
                } else {
                    string::from_static(self.name)
                }
            }
        }
    }
}

// ─── Value ────────────────────────────────────────────────────────────
//
// Read-only value introspection. Unlike Go's `reflect.Value` (fat
// pointer over the original storage), goish's `Value` is a deep-cloned
// enum — every `ValueOf(&x)` walks `x` once and copies its data into
// the variant. Trade: copies on construction; gain: no unsafe pointer
// arithmetic, no offset_of needed, lifetime-free at the user surface.
//
// Mutation (`SetBool`, `SetString`, etc.) requires the pointer-form and
// is deferred to a later iteration.

/// Mirrors `reflect.Value` (read-only).
#[derive(Clone)]
pub enum Value {
    Invalid,
    Bool(bool),
    Int(int),
    Int8(i8),
    Int16(i16),
    Int32(i32), // covers rune
    Uint(uint),
    Uint8(u8), // covers byte
    Uint16(u16),
    Uint32(u32),
    Float32(float32),
    Float64(float64),
    String(string),
    Slice {
        elem_type: fn() -> Type,
        items: Vec<Value>,
    },
    Map {
        key_type: fn() -> Type,
        value_type: fn() -> Type,
        /// (key, value) pairs in stable order. Goish's `map<K,V>` is
        /// BTreeMap-backed, so this list is key-sorted; that's also the
        /// order we use for json.Marshal output.
        entries: Vec<(Value, Value)>,
    },
    Struct {
        ty: Type,
        fields: Vec<Value>,
    },
    Pointer(Box<Value>),
}

impl Value {
    /// `Kind()` — runtime tag.
    pub fn Kind(&self) -> Kind {
        match self {
            Value::Invalid => Kind::Invalid,
            Value::Bool(_) => Kind::Bool,
            Value::Int(_) => Kind::Int,
            Value::Int8(_) => Kind::Int8,
            Value::Int16(_) => Kind::Int16,
            Value::Int32(_) => Kind::Int32,
            Value::Uint(_) => Kind::Uint,
            Value::Uint8(_) => Kind::Uint8,
            Value::Uint16(_) => Kind::Uint16,
            Value::Uint32(_) => Kind::Uint32,
            Value::Float32(_) => Kind::Float32,
            Value::Float64(_) => Kind::Float64,
            Value::String(_) => Kind::String,
            Value::Slice { .. } => Kind::Slice,
            Value::Map { .. } => Kind::Map,
            Value::Struct { .. } => Kind::Struct,
            Value::Pointer(_) => Kind::Pointer,
        }
    }

    /// `Type()` — descriptor of this value's type.
    pub fn Type(&self) -> Type {
        match self {
            Value::Struct { ty, .. } => *ty,
            Value::Slice { elem_type, .. } => {
                Type::__new(Kind::Slice, "", &[]).__with_elem(*elem_type)
            }
            Value::Map { key_type, value_type, .. } => Type::__new(Kind::Map, "", &[])
                .__with_key(*key_type)
                .__with_elem(*value_type),
            _ => Type::__new(self.Kind(), self.Kind().__static_name(), &[]),
        }
    }

    /// `IsValid()` — false for the zero-Value (`Value::Invalid`).
    pub fn IsValid(&self) -> bool {
        !matches!(self, Value::Invalid)
    }

    /// `IsZero()` — true if the value is its type's zero value. Mirrors
    /// Go's `reflect.Value.IsZero`.
    pub fn IsZero(&self) -> bool {
        match self {
            Value::Invalid => true,
            Value::Bool(b) => !*b,
            Value::Int(n) => *n == 0,
            Value::Int8(n) => *n == 0,
            Value::Int16(n) => *n == 0,
            Value::Int32(n) => *n == 0,
            Value::Uint(n) => *n == 0,
            Value::Uint8(n) => *n == 0,
            Value::Uint16(n) => *n == 0,
            Value::Uint32(n) => *n == 0,
            Value::Float32(f) => *f == 0.0,
            Value::Float64(f) => *f == 0.0,
            Value::String(s) => s.as_bytes().is_empty(),
            Value::Slice { items, .. } => items.is_empty(),
            Value::Map { entries, .. } => entries.is_empty(),
            Value::Struct { fields, .. } => fields.iter().all(Value::IsZero),
            Value::Pointer(_) => false,
        }
    }

    /// `Bool()` — panics if Kind != Bool.
    pub fn Bool(&self) -> bool {
        match self {
            Value::Bool(b) => *b,
            _ => panic!("reflect.Value.Bool of non-bool"),
        }
    }

    /// `Int()` — typed accessor for any signed-int kind. Panics otherwise.
    pub fn Int(&self) -> int {
        match self {
            Value::Int(n) => *n,
            Value::Int8(n) => *n as int,
            Value::Int16(n) => *n as int,
            Value::Int32(n) => *n as int,
            _ => panic!("reflect.Value.Int of non-int"),
        }
    }

    /// `Uint()` — any unsigned-int kind. Panics otherwise.
    pub fn Uint(&self) -> uint {
        match self {
            Value::Uint(n) => *n,
            Value::Uint8(n) => *n as uint,
            Value::Uint16(n) => *n as uint,
            Value::Uint32(n) => *n as uint,
            _ => panic!("reflect.Value.Uint of non-uint"),
        }
    }

    /// `Float()` — float32 or float64. Panics otherwise.
    pub fn Float(&self) -> float64 {
        match self {
            Value::Float32(f) => *f as float64,
            Value::Float64(f) => *f,
            _ => panic!("reflect.Value.Float of non-float"),
        }
    }

    /// `String()` — string value, or kind label for non-strings (matches
    /// Go: `reflect.Value.String` returns `"<int Value>"` for non-string).
    pub fn String(&self) -> string {
        match self {
            Value::String(s) => s.clone(),
            _ => self.Kind().String(),
        }
    }

    /// `Len()` — element count for slice/string/map. Panics otherwise.
    pub fn Len(&self) -> int {
        match self {
            Value::Slice { items, .. } => items.len() as int,
            Value::String(s) => s.as_bytes().len() as int,
            Value::Map { entries, .. } => entries.len() as int,
            _ => panic!("reflect.Value.Len of non-slice/string/map"),
        }
    }

    /// `Cap()` — capacity for slice. Goish slices are deep-cloned and
    /// don't track capacity separately from length, so `Cap == Len`.
    /// Panics for non-slice (matches Go for non-Array/Chan/Slice).
    pub fn Cap(&self) -> int {
        match self {
            Value::Slice { items, .. } => items.len() as int,
            _ => panic!("reflect.Value.Cap of non-slice"),
        }
    }

    /// `IsNil()` — Go semantics for nil-able kinds:
    ///   * Pointer: inner is `Value::Invalid`
    ///   * Slice / Map: always `false` in goish v1 (we don't track nil
    ///     vs empty distinctly; an empty slice is non-nil-empty)
    ///   * Other kinds: panic
    pub fn IsNil(&self) -> bool {
        match self {
            Value::Slice { .. } => false,
            Value::Map { .. } => false,
            Value::Pointer(inner) => matches!(**inner, Value::Invalid),
            _ => panic!("reflect.Value.IsNil: type does not allow nil"),
        }
    }

    /// `Bytes()` — convert a `Value::Slice` whose element kind is
    /// `Uint8` into a `slice<byte>`. Panics otherwise.
    pub fn Bytes(&self) -> slice<byte> {
        match self {
            Value::Slice { items, elem_type } if elem_type().Kind() == Kind::Uint8 => {
                let mut out: Vec<byte> = Vec::with_capacity(items.len());
                for item in items {
                    out.push(match item {
                        Value::Uint8(b) => *b,
                        _ => 0,
                    });
                }
                slice::__from_vec(out)
            }
            _ => panic!("reflect.Value.Bytes of non-byte slice"),
        }
    }

    /// `Slice(low, high)` — sub-slice via reflect. Mirrors Go's
    /// `Value.Slice` for slice/string. Panics for other kinds.
    pub fn Slice(&self, low: int, high: int) -> Value {
        match self {
            Value::Slice { elem_type, items } => {
                let lo = low as usize;
                let hi = high as usize;
                let sub = items[lo..hi].to_vec();
                Value::Slice {
                    elem_type: *elem_type,
                    items: sub,
                }
            }
            Value::String(s) => {
                let bytes = s.as_bytes();
                let lo = low as usize;
                let hi = high as usize;
                Value::String(string::from_bytes(&bytes[lo..hi]))
            }
            _ => panic!("reflect.Value.Slice of non-slice/string"),
        }
    }

    /// `Slice3(low, high, max)` — explicit-cap variant. Goish slices are
    /// deep-cloned, so the cap argument is ignored; semantically
    /// identical to `Slice(low, high)`.
    pub fn Slice3(&self, low: int, high: int, _max: int) -> Value {
        self.Slice(low, high)
    }

    /// `MapKeys()` — keys in stable (sorted) order. Panics if not Map.
    pub fn MapKeys(&self) -> Vec<Value> {
        match self {
            Value::Map { entries, .. } => entries.iter().map(|(k, _)| k.clone()).collect(),
            _ => panic!("reflect.Value.MapKeys of non-map"),
        }
    }

    /// `MapIndex(key)` — value for key, or `Value::Invalid` if absent.
    /// Linear scan for v1 (entries are sorted; we could binary-search
    /// over comparable keys, but v1 keeps it straightforward).
    pub fn MapIndex(&self, key: &Value) -> Value {
        match self {
            Value::Map { entries, .. } => {
                for (k, v) in entries {
                    if value_eq(k, key) {
                        return v.clone();
                    }
                }
                Value::Invalid
            }
            _ => panic!("reflect.Value.MapIndex of non-map"),
        }
    }

    /// `Index(i)` — i-th element of a slice. Panics if not Slice.
    pub fn Index(&self, i: int) -> Value {
        match self {
            Value::Slice { items, .. } => items[i as usize].clone(),
            _ => panic!("reflect.Value.Index of non-slice"),
        }
    }

    /// `NumField()` — struct field count. Panics if not Struct.
    pub fn NumField(&self) -> int {
        match self {
            Value::Struct { ty, .. } => ty.NumField(),
            _ => panic!("reflect.Value.NumField of non-struct"),
        }
    }

    /// `Field(i)` — i-th field of a struct. Panics if not Struct.
    pub fn Field(&self, i: int) -> Value {
        match self {
            Value::Struct { fields, .. } => fields[i as usize].clone(),
            _ => panic!("reflect.Value.Field of non-struct"),
        }
    }

    /// `FieldByName(name)` — looks up by name. Returns `Value::Invalid`
    /// if not found.
    pub fn FieldByName(&self, name: &str) -> Value {
        match self {
            Value::Struct { ty, fields } => {
                for i in 0..ty.fields.len() {
                    if ty.fields[i].Name.as_bytes() == name.as_bytes() {
                        return fields[i].clone();
                    }
                }
                Value::Invalid
            }
            _ => panic!("reflect.Value.FieldByName of non-struct"),
        }
    }
}

/// Structural equality for use by `MapIndex`. Compares by Kind and
/// payload. Sufficient for json-shaped lookups (string keys); for
/// general use the `reflect.DeepEqual` port (later iteration) will be
/// the public API.
fn value_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Invalid, Value::Invalid) => true,
        (Value::Bool(x), Value::Bool(y)) => x == y,
        (Value::Int(x), Value::Int(y)) => x == y,
        (Value::Int8(x), Value::Int8(y)) => x == y,
        (Value::Int16(x), Value::Int16(y)) => x == y,
        (Value::Int32(x), Value::Int32(y)) => x == y,
        (Value::Uint(x), Value::Uint(y)) => x == y,
        (Value::Uint8(x), Value::Uint8(y)) => x == y,
        (Value::Uint16(x), Value::Uint16(y)) => x == y,
        (Value::Uint32(x), Value::Uint32(y)) => x == y,
        (Value::Float32(x), Value::Float32(y)) => x == y,
        (Value::Float64(x), Value::Float64(y)) => x == y,
        (Value::String(x), Value::String(y)) => x == y,
        _ => false,
    }
}

impl Kind {
    fn __static_name(&self) -> &'static str {
        match self {
            Kind::Invalid => "",
            Kind::Bool => "bool",
            Kind::Int => "int",
            Kind::Int8 => "int8",
            Kind::Int16 => "int16",
            Kind::Int32 => "int32",
            Kind::Uint => "uint",
            Kind::Uint8 => "uint8",
            Kind::Uint16 => "uint16",
            Kind::Uint32 => "uint32",
            Kind::Float32 => "float32",
            Kind::Float64 => "float64",
            Kind::String => "string",
            Kind::Slice => "",
            Kind::Map => "",
            Kind::Struct => "",
            Kind::Pointer => "",
        }
    }
}

// ─── Reflect trait ────────────────────────────────────────────────────

/// Trait implemented by every type whose `reflect.TypeOf` is supported.
/// Built-in primitives have impls in this file; user structs get them
/// from `#[goish::reflect]`.
pub trait Reflect {
    /// Returns the descriptor by value. Cheap — just a few words.
    fn __reflect_type() -> Type;

    /// Returns a deep-cloned `Value` mirror of `self`. Used by
    /// `reflect::ValueOf` and tag-driven `json.Marshal`.
    fn __reflect_value(&self) -> Value;
}

/// `reflect.TypeOf(v)` — descriptor for `v`'s static type.
pub fn TypeOf<T: Reflect + ?Sized>(_: &T) -> Type {
    T::__reflect_type()
}

/// `reflect.ValueOf(v)` — read-only `Value` mirror of `v`.
pub fn ValueOf<T: Reflect + ?Sized>(v: &T) -> Value {
    v.__reflect_value()
}

// ─── FromReflectValue — typed setter dispatch ─────────────────────────
//
// Mirrors `json::FromValue` but over `reflect::Value`. Used by macro-
// emitted `Settable::__reflect_set_field` implementations to safely
// extract the typed payload from a Value at runtime.

pub trait FromReflectValue: Sized {
    fn from_reflect_value(v: Value) -> (Self, crate::errors::error);
}

macro_rules! impl_from_reflect {
    ($t:ty, $variant:ident, $name:expr) => {
        impl FromReflectValue for $t {
            fn from_reflect_value(v: Value) -> (Self, crate::errors::error) {
                match v {
                    Value::$variant(x) => (x, crate::nil),
                    _ => (
                        <$t as Default>::default(),
                        crate::errors::New(concat!("reflect: expected ", $name)),
                    ),
                }
            }
        }
    };
}

impl_from_reflect!(bool, Bool, "bool");
impl_from_reflect!(int, Int, "int");
impl_from_reflect!(i8, Int8, "int8");
impl_from_reflect!(i16, Int16, "int16");
impl_from_reflect!(rune, Int32, "int32");
impl_from_reflect!(uint, Uint, "uint");
impl_from_reflect!(byte, Uint8, "uint8");
impl_from_reflect!(u16, Uint16, "uint16");
impl_from_reflect!(u32, Uint32, "uint32");
impl_from_reflect!(float32, Float32, "float32");
impl_from_reflect!(float64, Float64, "float64");
impl_from_reflect!(string, String, "string");

impl<T: FromReflectValue + Clone + Default> FromReflectValue for slice<T> {
    fn from_reflect_value(v: Value) -> (Self, crate::errors::error) {
        match v {
            Value::Slice { items, .. } => {
                let mut out: Vec<T> = Vec::with_capacity(items.len());
                for item in items {
                    let (elem, err) = T::from_reflect_value(item);
                    if err != crate::nil {
                        return (slice::__from_vec(Vec::new()), err);
                    }
                    out.push(elem);
                }
                (slice::__from_vec(out), crate::nil)
            }
            _ => (
                slice::__from_vec(Vec::new()),
                crate::errors::New("reflect: expected slice"),
            ),
        }
    }
}

impl<K, V> FromReflectValue for crate::gomap::map<K, V>
where
    K: FromReflectValue + Ord + Default + Clone,
    V: FromReflectValue + Default + Clone,
{
    fn from_reflect_value(v: Value) -> (Self, crate::errors::error) {
        match v {
            Value::Map { entries, .. } => {
                let mut out = crate::gomap::map::<K, V>::new();
                for (kv, vv) in entries {
                    let (k, err) = K::from_reflect_value(kv);
                    if err != crate::nil {
                        return (crate::gomap::map::<K, V>::new(), err);
                    }
                    let (v, err) = V::from_reflect_value(vv);
                    if err != crate::nil {
                        return (crate::gomap::map::<K, V>::new(), err);
                    }
                    out.Set(k, v);
                }
                (out, crate::nil)
            }
            _ => (
                crate::gomap::map::<K, V>::new(),
                crate::errors::New("reflect: expected map"),
            ),
        }
    }
}

// ─── Mutation: SetField / SetFieldByName ──────────────────────────────
//
// Goish doesn't expose Go's `Value.Field(i).SetInt(99)` chain directly
// (that requires per-field offsets + bounded unsafe). Instead, the
// `#[goish::reflect]` macro emits a `Settable` impl per struct that
// dispatches a typed setter per field index. The free functions below
// route through that protocol — type-checked, no unsafe.
//
//   reflect::SetField(&mut p, 1, Value::Int(99))
//   reflect::SetFieldByName(&mut p, "Name", Value::String(string("a")))

/// Trait emitted by `#[goish::reflect]` for user structs. Allows
/// runtime "write field i with this Value" without unsafe.
pub trait Settable {
    /// Assigns `v` into the i-th field. Returns `nil` on success or a
    /// type-mismatch / out-of-range error.
    fn __reflect_set_field(&mut self, idx: int, v: Value) -> crate::errors::error;
}

/// `reflect.SetField(&mut t, idx, v)` — write `v` into the i-th field.
pub fn SetField<T: Settable>(target: &mut T, idx: int, v: Value) -> crate::errors::error {
    target.__reflect_set_field(idx, v)
}

/// `reflect.SetFieldByName(&mut t, name, v)` — look up the field by
/// declared name and write `v` into it. Returns an error if the field
/// is not found.
pub fn SetFieldByName<T: Settable + Reflect>(
    target: &mut T,
    name: &str,
    v: Value,
) -> crate::errors::error {
    let ty = T::__reflect_type();
    for i in 0..ty.NumField() {
        if ty.Field(i).Name.as_bytes() == name.as_bytes() {
            return target.__reflect_set_field(i, v);
        }
    }
    crate::errors::New("reflect.SetFieldByName: field not found")
}

/// `reflect.DeepEqual(x, y)` — structural equality between any two
/// reflectable values. Mirrors Go 1.25 `reflect.DeepEqual`:
///
///   * primitives compare with `==` (NaN != NaN, matching Go)
///   * slices: same length + element-wise DeepEqual
///   * maps: same length + every key has a deeply-equal value
///   * structs: same struct name + element-wise DeepEqual
///   * Invalid == Invalid
///   * different Kinds → unequal
///
/// Goish's `Value` is an acyclic deep-clone, so the visited-set
/// short-circuit Go's implementation needs (for cyclic pointer/map
/// graphs) is unnecessary here.
pub fn DeepEqual<T, U>(x: &T, y: &U) -> bool
where
    T: Reflect + ?Sized,
    U: Reflect + ?Sized,
{
    deep_value_equal(&ValueOf(x), &ValueOf(y))
}

fn deep_value_equal(a: &Value, b: &Value) -> bool {
    if a.Kind() != b.Kind() {
        return false;
    }
    match (a, b) {
        (Value::Invalid, Value::Invalid) => true,
        (Value::Bool(x), Value::Bool(y)) => x == y,
        (Value::Int(x), Value::Int(y)) => x == y,
        (Value::Int8(x), Value::Int8(y)) => x == y,
        (Value::Int16(x), Value::Int16(y)) => x == y,
        (Value::Int32(x), Value::Int32(y)) => x == y,
        (Value::Uint(x), Value::Uint(y)) => x == y,
        (Value::Uint8(x), Value::Uint8(y)) => x == y,
        (Value::Uint16(x), Value::Uint16(y)) => x == y,
        (Value::Uint32(x), Value::Uint32(y)) => x == y,
        // NaN != NaN, matching Go.
        (Value::Float32(x), Value::Float32(y)) => x == y,
        (Value::Float64(x), Value::Float64(y)) => x == y,
        (Value::String(x), Value::String(y)) => x == y,
        (Value::Slice { items: ai, .. }, Value::Slice { items: bi, .. }) => {
            if ai.len() != bi.len() {
                return false;
            }
            ai.iter()
                .zip(bi.iter())
                .all(|(x, y)| deep_value_equal(x, y))
        }
        (Value::Map { entries: ae, .. }, Value::Map { entries: be, .. }) => {
            if ae.len() != be.len() {
                return false;
            }
            // Go semantics: each key in a must map to a deeply-equal value
            // in b. Keys are sorted in our representation, but matching
            // by lookup keeps us correct even if invariants drift.
            for (ka, va) in ae {
                let mut matched = false;
                for (kb, vb) in be {
                    if deep_value_equal(ka, kb) {
                        if !deep_value_equal(va, vb) {
                            return false;
                        }
                        matched = true;
                        break;
                    }
                }
                if !matched {
                    return false;
                }
            }
            true
        }
        (
            Value::Struct { fields: af, ty: ta },
            Value::Struct { fields: bf, ty: tb },
        ) => {
            // Distinct named struct types are never deeply equal — even
            // if their field shapes coincide.
            if ta.Name() != tb.Name() {
                return false;
            }
            if af.len() != bf.len() {
                return false;
            }
            af.iter()
                .zip(bf.iter())
                .all(|(x, y)| deep_value_equal(x, y))
        }
        (Value::Pointer(pa), Value::Pointer(pb)) => deep_value_equal(pa, pb),
        _ => false,
    }
}

// ─── Built-in Reflect impls ───────────────────────────────────────────

macro_rules! impl_primitive_reflect {
    ($t:ty, $kind:expr, $name:literal, $variant:ident, $($conv:tt)*) => {
        impl Reflect for $t {
            #[inline]
            fn __reflect_type() -> Type {
                Type::__new($kind, $name, &[])
            }
            #[inline]
            fn __reflect_value(&self) -> Value {
                Value::$variant($($conv)*(*self))
            }
        }
    };
}

// Identity conversion (no-op).
fn id<T>(x: T) -> T { x }

impl_primitive_reflect!(bool, Kind::Bool, "bool", Bool, id);
impl_primitive_reflect!(int, Kind::Int, "int", Int, id);
impl_primitive_reflect!(i8, Kind::Int8, "int8", Int8, id);
impl_primitive_reflect!(i16, Kind::Int16, "int16", Int16, id);
// rune = i32, so the i32 impl covers both the explicit-int32 and the
// rune use — same as Go where `type rune = int32` shares Kind::Int32.
impl_primitive_reflect!(rune, Kind::Int32, "int32", Int32, id);
impl_primitive_reflect!(uint, Kind::Uint, "uint", Uint, id);
// byte = u8, mirrors Go (`type byte = uint8`).
impl_primitive_reflect!(byte, Kind::Uint8, "uint8", Uint8, id);
impl_primitive_reflect!(u16, Kind::Uint16, "uint16", Uint16, id);
impl_primitive_reflect!(u32, Kind::Uint32, "uint32", Uint32, id);
impl_primitive_reflect!(float32, Kind::Float32, "float32", Float32, id);
impl_primitive_reflect!(float64, Kind::Float64, "float64", Float64, id);

// `string` doesn't fit the macro (Clone, not Copy); spell it out.
impl Reflect for string {
    #[inline]
    fn __reflect_type() -> Type {
        Type::__new(Kind::String, "string", &[])
    }
    #[inline]
    fn __reflect_value(&self) -> Value {
        Value::String(self.clone())
    }
}

// ─── slice<T: Reflect> — generic Reflect impl ─────────────────────────
//
// The Type descriptor itself doesn't carry the element kind in v1
// (kept off Type to avoid generic-static issues). The element's `Type`
// is reachable via the Slice variant's `elem_type` fn pointer.

impl<T: Reflect + Clone> Reflect for slice<T> {
    fn __reflect_type() -> Type {
        Type::__new(Kind::Slice, "", &[]).__with_elem(<T as Reflect>::__reflect_type)
    }
    fn __reflect_value(&self) -> Value {
        let mut items: Vec<Value> = Vec::with_capacity(self.Len() as usize);
        for i in 0..self.Len() {
            items.push((self[i]).__reflect_value());
        }
        Value::Slice {
            elem_type: <T as Reflect>::__reflect_type,
            items,
        }
    }
}

// ─── map<K, V: Reflect> — generic Reflect impl ────────────────────────
//
// Goish's map<K,V> is BTreeMap-backed, so __iter() walks keys in sorted
// order. We preserve that order in the Map variant, which means
// json.Marshal output is deterministic for free.

use crate::gomap::map as gomap_map;

impl<K, V> Reflect for gomap_map<K, V>
where
    K: Reflect + Ord + Default + Clone,
    V: Reflect + Default + Clone,
{
    fn __reflect_type() -> Type {
        Type::__new(Kind::Map, "", &[])
            .__with_key(<K as Reflect>::__reflect_type)
            .__with_elem(<V as Reflect>::__reflect_type)
    }
    fn __reflect_value(&self) -> Value {
        let mut entries: Vec<(Value, Value)> = Vec::with_capacity(self.Len() as usize);
        for (k, v) in self.__iter() {
            entries.push((k.__reflect_value(), v.__reflect_value()));
        }
        Value::Map {
            key_type: <K as Reflect>::__reflect_type,
            value_type: <V as Reflect>::__reflect_type,
            entries,
        }
    }
}
