#!/usr/bin/env python3
"""fiat_gen — emit goish's crypto/internal/fips140/nistec/fiat.

In Go, fiat/pNNN.go is generated by fiat/generate.go and pNNN_fiat64.go by
Fiat Cryptography itself; the four curves differ only in name, byte length
and limb count. goish mirrors that: this script emits the four wrappers
from one template and shells out to fiat64_to_rust.py for the arithmetic.

    scripts/fiat_gen.py            # rewrites src/crypto/.../nistec/fiat/
"""
import os
import re
import subprocess
import sys

GOFIAT = os.path.join(
    subprocess.run(['go', 'env', 'GOROOT'], capture_output=True, text=True).stdout.strip(),
    'src/crypto/internal/fips140/nistec/fiat')
OUT = 'src/crypto/internal/fips140/nistec/fiat'

CURVES = [
    # lower, Upper, byte length, limbs, modulus text
    ('p224', 'P224', 28, 4, '2^224 - 2^96 + 1'),
    ('p256', 'P256', 32, 4, '2^256 - 2^224 + 2^192 + 2^96 - 1'),
    ('p384', 'P384', 48, 6, '2^384 - 2^128 - 2^96 + 2^32 - 1'),
    ('p521', 'P521', 66, 9, '2^521 - 1'),
]

WRAPPER = '''// go: file crypto/internal/fips140/nistec/fiat/{c}.go decls: {C}Element.One, {C}Element.Equal, {C}Element.IsZero, {C}Element.Set, {C}Element.Bytes, {C}Element.bytes, {C}Element.SetBytes, {C}Element.Add, {C}Element.Sub, {C}Element.Mul, {C}Element.Square, {C}Element.Select, {c}InvertEndianness
//
// Code generated by generate.go. DO NOT EDIT.
//
// Deviation from {c}[go] @ Go 1.25.5: Go takes every field-element
// operand as `*{C}Element` and freely aliases the receiver
// (`e.Add(e, t)`). {C}Element is `[u64; {n}]` and therefore Copy, so
// operands are taken **by value** — which costs one register copy and
// makes the aliasing call sites Go relies on translate directly. Passing
// `&{C}Element` instead would make `e.Add(e, t)` a borrow error at
// every nistec call site.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]

extern crate alloc;
use alloc::vec::Vec;

use super::{c}_fiat64::*;
use crate::crypto::internal::fips140::subtle;
use crate::errors;
use crate::goslice::slice;
use crate::types::byte;
use crate::{{error, int, uint64}};

// Go: {c}.go:14-21
//   type {C}Element struct {{ x {c}MontgomeryDomainFieldElement }}
/// An integer modulo {m}.
///
/// The zero value is a valid zero element.
#[derive(Clone, Copy, Default)]
pub struct {C}Element {{
    /// Values are represented internally always in the Montgomery domain,
    /// and converted in Bytes and SetBytes.
    pub(crate) x: [u64; {n}],
}}

/// Go: `const {c}ElementLen = {L}`
pub const {c}ElementLen: usize = {L};

/// Go: `type {c}UntypedFieldElement = [{n}]uint64`
pub type {c}UntypedFieldElement = [u64; {n}];

impl {C}Element {{
    // go: none — Go gets the zero value from `new({C}Element)`.
    pub fn New() -> Self {{
        return {C}Element {{ x: [0; {n}] }};
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:27-31 One
    /// Set e = 1, and return e.
    pub fn One(&mut self) -> &mut Self {{
        {c}SetOne(&mut self.x);
        return self;
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:33-38 Equal
    /// Return 1 if e == t, and zero otherwise.
    pub fn Equal(&self, t: {C}Element) -> int {{
        let eBytes = self.Bytes();
        let tBytes = t.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &tBytes);
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:40-45 IsZero
    /// Return 1 if e == 0, and zero otherwise.
    pub fn IsZero(&self) -> int {{
        let zero = slice::__from_vec(alloc::vec![0u8; {c}ElementLen]);
        let eBytes = self.Bytes();
        return subtle::ConstantTimeCompare(&eBytes, &zero);
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:47-51 Set
    /// Set e = t, and return e.
    pub fn Set(&mut self, t: {C}Element) -> &mut Self {{
        self.x = t.x;
        return self;
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:53-59 Bytes
    /// Return the {L}-byte big-endian encoding of e.
    pub fn Bytes(&self) -> slice<byte> {{
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; {c}ElementLen];
        return self.bytes(&mut out);
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:61-67 bytes
    fn bytes(&self, out: &mut [byte; {c}ElementLen]) -> slice<byte> {{
        let mut tmp: [u64; {n}] = [0; {n}];
        {c}FromMontgomery(&mut tmp, &self.x);
        {c}ToBytes(out, &tmp);
        {c}InvertEndianness(out);
        return slice::__from_vec(out.to_vec());
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:69-92 SetBytes
    /// Set e = v, where v is a big-endian {L}-byte encoding, and return e.
    /// If v is not {L} bytes or it encodes a value higher than
    /// {m}, SetBytes returns an error and e is unchanged.
    pub fn SetBytes(&mut self, v: slice<byte>) -> error {{
        // Go: if len(v) != {c}ElementLen {{ return nil, errors.New(…) }}
        if v.Len() != int({c}ElementLen) {{
            return errors::New("invalid {C}Element encoding");
        }}

        // Check for non-canonical encodings (p + k, 2p + k, etc.) by
        // comparing to the encoding of -1 mod p, so p - 1, the highest
        // canonical encoding.
        let mut one = {C}Element::New();
        one.One();
        let mut minusOne = {C}Element::New();
        minusOne.Sub({C}Element::New(), one);
        let minusOneEncoding = minusOne.Bytes();
        if subtle::ConstantTimeLessOrEqBytes(&v, &minusOneEncoding) == 0 {{
            return errors::New("invalid {C}Element encoding");
        }}

        // Go: var in [{c}ElementLen]byte; copy(in[:], v); {c}InvertEndianness(in[:])
        let mut inp = [0u8; {c}ElementLen];
        let raw: &[byte] = &v;
        inp.copy_from_slice(raw);
        {c}InvertEndianness(&mut inp);
        let mut tmp: [u64; {n}] = [0; {n}];
        {c}FromBytes(&mut tmp, &inp);
        {c}ToMontgomery(&mut self.x, &tmp);
        return crate::nil.into();
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:94-98 Add
    /// Set e = t1 + t2, and return e.
    pub fn Add(&mut self, t1: {C}Element, t2: {C}Element) -> &mut Self {{
        {c}Add(&mut self.x, &t1.x, &t2.x);
        return self;
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:100-104 Sub
    /// Set e = t1 - t2, and return e.
    pub fn Sub(&mut self, t1: {C}Element, t2: {C}Element) -> &mut Self {{
        {c}Sub(&mut self.x, &t1.x, &t2.x);
        return self;
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:106-110 Mul
    /// Set e = t1 * t2, and return e.
    pub fn Mul(&mut self, t1: {C}Element, t2: {C}Element) -> &mut Self {{
        {c}Mul(&mut self.x, &t1.x, &t2.x);
        return self;
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:112-116 Square
    /// Set e = t * t, and return e.
    pub fn Square(&mut self, t: {C}Element) -> &mut Self {{
        {c}Square(&mut self.x, &t.x);
        return self;
    }}

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:118-123 Select
    /// Set v to a if cond == 1, and to b if cond == 0.
    pub fn Select(&mut self, a: {C}Element, b: {C}Element, cond: int) -> &mut Self {{
        {c}Selectznz(&mut self.x, uint64(cond), &b.x, &a.x);
        return self;
    }}
}}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/fiat/{c}.go:125-129 {c}InvertEndianness
pub(crate) fn {c}InvertEndianness(v: &mut [byte]) {{
    // Go: for i := 0; i < len(v)/2; i++ {{ v[i], v[len(v)-1-i] = v[len(v)-1-i], v[i] }}
    let mut i: usize = 0;
    while i < v.len() / 2 {{
        let j = v.len() - 1 - i;
        let t = v[i];
        v[i] = v[j];
        v[j] = t;
        i += 1;
    }}
}}

// Silence the unused-import warning when Vec is only reached via vec!.
const _: fn() -> Vec<byte> = Vec::new;
'''

FIAT64_HDR = '''// go: file crypto/internal/fips140/nistec/fiat/{c}_fiat64.go decls: {decls}
//
// Code generated by Fiat Cryptography. DO NOT EDIT.
//
// Translated from Go by scripts/fiat64_to_rust.py, which parses the
// closed grammar these generated files use and raises on anything it does
// not recognise — it can fail to translate, but not silently
// mistranslate. Regenerate with `scripts/fiat_gen.py`; do not hand-edit.
//
// curve description: {c}   |   machine_wordsize = 64   |   limbs = {n}
//
// Two shape changes, both forced:
//
//   * Go's uint64 arithmetic wraps; Rust's panics in debug builds. Every
//     `+` is wrapping_add and every `*` is wrapping_mul.
//   * `{c}CmovznzU64` returns its result rather than writing through an
//     `out1 *uint64`. The out-parameter is a fiat-crypto calling
//     convention, not part of the algorithm.
//
// `{c}Uint1`/`{c}Int1` and the Montgomery/NonMontgomery element types are
// all defined in Go as `uint64`, `int64` and `[{n}]uint64` respectively,
// so every conversion between them is a value-level no-op and is elided.

#![allow(non_snake_case, non_camel_case_types)]
// The parenthesisation mirrors the Go source, which is itself machine
// output; stripping it would make the two harder to diff.
#![allow(unused_parens)]
//
// goishlint:ignore GOISH020 — `{c}CmovznzU64` returns its result where Go
// writes it through an `out1 *uint64` first parameter, so the arity is 3
// against Go's 4. The out-parameter is a fiat-crypto calling convention.

use crate::math::bits;
use crate::{{uint64, uint8}};

/// Go: `type {c}Uint1 uint64` — "We use uint64 instead of a more narrow
/// type for performance reasons."
pub(super) type {c}Uint1 = u64;

/// Go: `type {c}Int1 int64`. Declared by Fiat Cryptography but not used
/// by any function it generates, here or in Go.
#[allow(dead_code)]
pub(super) type {c}Int1 = i64;

/// Go: `type {c}MontgomeryDomainFieldElement [{n}]uint64` — a field
/// element in the Montgomery domain.
pub(super) type {c}MontgomeryDomainFieldElement = [u64; {n}];

/// Go: `type {c}NonMontgomeryDomainFieldElement [{n}]uint64` — a field
/// element NOT in the Montgomery domain.
pub(super) type {c}NonMontgomeryDomainFieldElement = [u64; {n}];

'''


def main():
    os.makedirs(OUT, exist_ok=True)
    mods = []
    for c, C, L, n, m in CURVES:
        with open(os.path.join(OUT, '%s.rs' % c), 'w') as f:
            f.write(WRAPPER.format(c=c, C=C, L=L, n=n, m=m))
        tmp = '/tmp/%s_fiat64.rs.gen' % c
        r = subprocess.run([sys.executable, 'scripts/fiat64_to_rust.py',
                            os.path.join(GOFIAT, '%s_fiat64.go' % c), tmp],
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stderr)
            raise SystemExit('fiat64 translation failed for %s' % c)
        decls = r.stdout.strip().replace(',', ', ')
        with open(os.path.join(OUT, '%s_fiat64.rs' % c), 'w') as f:
            f.write(FIAT64_HDR.format(c=c, n=n, decls=decls))
            f.write(open(tmp).read())
        mods += ['%s' % c, '%s_fiat64' % c]

    with open(os.path.join(OUT, 'mod.rs'), 'w') as f:
        f.write('// go: package crypto/internal/fips140/nistec/fiat\n\n')
        for mo in sorted(mods):
            f.write('mod %s;\n' % mo)
        f.write('\n')
        for c, C, L, n, m in CURVES:
            f.write('pub use %s::{%sElement, %sElementLen, %sUntypedFieldElement};\n'
                    % (c, C, c, c))
    print('wrote %d files' % (len(mods) + 1))


main()
