#!/usr/bin/env python3
"""p256_table_gen.py — translate nistec's p256_table.go byte array to Rust.

`var p256PrecomputedEmbed = [...]byte{…}` is 88064 bytes of precomputed
P-256 basepoint multiples on one 523 KB line. It is machine output on the
Go side too, so it is machine-translated here rather than transcribed:
the parser reads every `0x..` token, checks the count, and writes the same
bytes as a Rust array.

    scripts/p256_table_gen.py            # write src/.../nistec/p256_table.rs
    scripts/p256_table_gen.py --check    # exit 1 if it is stale
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "src/crypto/internal/fips140/nistec/p256_table.rs")

# 43 tables x 32 points x 2 coordinates x 4 limbs x 8 bytes.
EXPECTED = 43 * 32 * 2 * 4 * 8

HEADER = """// go: file crypto/internal/fips140/nistec/p256_table.go decls:
//
// p256PrecomputedEmbed is the precomputed table of P-256 basepoint
// multiples. See [p256GeneratorTables]. It's not embedded with go:embed
// because it's not supported within the FIPS module boundary.
//
// Code generated by scripts/p256_table_gen.py from Go's p256_table.go.
// DO NOT EDIT.
//
// p256_table.go declares no functions, so there is nothing for GOISH018
// to check here — only the one `var`, byte for byte.

#![allow(non_upper_case_globals)]

use crate::types::byte;

/// Go: `var p256PrecomputedEmbed = [...]byte{…}`
pub(super) static p256PrecomputedEmbed: [byte; %d] = [
"""


def goroot():
    if os.environ.get("GOROOT"):
        return os.environ["GOROOT"]
    return subprocess.check_output(["go", "env", "GOROOT"], text=True).strip()


def main():
    check = "--check" in sys.argv
    src = open(
        os.path.join(goroot(), "src/crypto/internal/fips140/nistec/p256_table.go")
    ).read()
    m = re.search(r"var p256PrecomputedEmbed = \[\.\.\.\]byte\{(.*)\}\s*$", src, re.S)
    if not m:
        sys.exit("p256_table_gen: no p256PrecomputedEmbed literal found")
    toks = [t.strip() for t in m.group(1).split(",") if t.strip()]
    if any(not re.fullmatch(r"0x[0-9a-fA-F]{1,2}", t) for t in toks):
        bad = next(t for t in toks if not re.fullmatch(r"0x[0-9a-fA-F]{1,2}", t))
        sys.exit("p256_table_gen: unexpected token %r" % bad)
    if len(toks) != EXPECTED:
        sys.exit(
            "p256_table_gen: got %d bytes, expected %d (43*32*2*4*8) — the table "
            "shape changed and p256.rs's reader would silently misread it"
            % (len(toks), EXPECTED)
        )

    body = []
    for i in range(0, len(toks), 16):
        body.append("    " + ", ".join(toks[i : i + 16]) + ",")
    out = HEADER % EXPECTED + "\n".join(body) + "\n];\n"

    old = open(OUT).read() if os.path.exists(OUT) else None
    if check:
        if old != out:
            sys.exit("p256_table_gen: p256_table.rs is stale — re-run scripts/p256_table_gen.py")
        print("p256_table_gen: p256_table.rs is up to date")
        return
    with open(OUT, "w") as f:
        f.write(out)
    print("wrote p256_table.rs (%d bytes, %d lines)" % (len(toks), out.count("\n")))


if __name__ == "__main__":
    main()
