#!/usr/bin/env python3
"""port_lint.py - run goishlint as a ratchet, not as a wall of text.

    scripts/port_lint.py                  # check the tree against the baseline
    scripts/port_lint.py --scope src/crypto
    scripts/port_lint.py --update         # re-record the baseline (review the diff!)
    scripts/port_lint.py --new            # only files absent from the baseline
    scripts/port_lint.py --rules GOISH018,GOISH021

Why this exists
---------------
`goishlint src` reports ~13.5k findings. A linter with a five-figure backlog
gates nothing: nobody reads it, so a *new* violation lands invisibly among the
old ones. That has already cost this repo real time - an anchor orphaned by a
blind insert was caught only because someone hand-diffed the finding count
against HEAD (56 -> 58) and noticed.

So the count itself becomes the gate. `scripts/lint_baseline.json` records the
finding count per (file, rule). `--check` (the default) fails when any pair
goes UP, and reports - without failing - when one goes down. The backlog is
allowed to exist; it is not allowed to grow.

Two properties fall out of keying on (file, rule) rather than on a global
total, and both are the point:

  * A file with no baseline entry must be clean. Newly ported files start at
    zero and stay there - the backlog is grandfathered, never extended.
  * Fixing file A cannot pay for a regression in file B, and moving code
    between files cannot launder a violation.

The fidelity tier
-----------------
GOISH017/018/019/020/021 - the rules that open the cited Go file and diff it
against the port - are opt-in in goishlint and were never part of the port
process. They are enabled here, because they check the one thing the whole
anchor system exists to check: that a function claimed as ported is actually
there, with the right arity, and that its types/consts/vars came along too.
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASELINE = os.path.join(ROOT, "scripts", "lint_baseline.json")

# The fidelity tier is opt-in in goishlint; the port process wants it on.
# --enable-goish018 switches on GOISH018/019/020/021 as a group.
FLAGS = ["--enable-goish017", "--enable-goish018"]

LINE = re.compile(r"^(?P<file>[^:]+):(?P<line>\d+):(?P<col>\d+): (?P<rule>GOISH\d{3}) (?P<msg>.*)$")


def binary():
    """Locate the goishlint binary: $GOISHLINT, else the sibling checkout."""
    env = os.environ.get("GOISHLINT")
    if env:
        return env
    # The sibling checkout, relative to the MAIN worktree — not to ROOT.
    # A linked worktree lives under `.claude/worktrees/agent-<id>/`, so
    # `ROOT/..` is `.claude/worktrees/` and the sibling lookup misses.
    # Every worktree-isolated agent then hit "goishlint not found" and
    # had to be told to export $GOISHLINT by hand.
    #
    # `git rev-parse --git-common-dir` resolves to the shared `.git` of
    # the main checkout from inside any worktree, so its parent is the
    # main tree regardless of where we are.
    roots = [ROOT]
    try:
        common = subprocess.check_output(
            ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
            cwd=ROOT, text=True, stderr=subprocess.DEVNULL).strip()
        if common:
            roots.append(os.path.dirname(common))
    except Exception:
        pass
    for r in roots:
        sib = os.path.join(r, "..", "goishlint", "target", "release", "goishlint")
        if os.path.exists(sib):
            return os.path.abspath(sib)
    sys.exit("port_lint: goishlint not found - set $GOISHLINT or build ../goishlint")


def run(scope):
    """Run goishlint over `scope`, returning [(file, rule, line, msg)]."""
    proc = subprocess.run([binary()] + FLAGS + [scope], cwd=ROOT,
                          capture_output=True, text=True)
    # goishlint exits 1 when it has findings and 2 on usage error.
    if proc.returncode not in (0, 1):
        sys.exit(f"port_lint: goishlint failed ({proc.returncode}):\n{proc.stderr}")
    out = []
    for ln in proc.stdout.splitlines():
        m = LINE.match(ln)
        if m:
            out.append((m["file"], m["rule"], int(m["line"]), m["msg"]))
    return out


def tally(findings, rules=None):
    """[(file, rule, ...)] -> {file: {rule: count}}, optionally rule-filtered."""
    counts = {}
    for f, rule, _, _ in findings:
        if rules and rule not in rules:
            continue
        counts.setdefault(f, {}).setdefault(rule, 0)
        counts[f][rule] += 1
    return counts


def load():
    if not os.path.exists(BASELINE):
        return {}
    with open(BASELINE) as fh:
        return json.load(fh).get("counts", {})


def save(counts, scope):
    """Write the baseline sorted, so a re-record produces a readable diff."""
    ordered = {f: dict(sorted(counts[f].items())) for f in sorted(counts)}
    payload = {
        "_comment": "Generated by scripts/port_lint.py --update. A count may "
                    "only go down; see the script docstring.",
        "scope": scope,
        "flags": FLAGS,
        "total": sum(sum(r.values()) for r in ordered.values()),
        "counts": ordered,
    }
    with open(BASELINE, "w") as fh:
        json.dump(payload, fh, indent=1, sort_keys=False)
        fh.write("\n")


def main():
    argv = sys.argv[1:]
    scope = "src"
    rules = None
    if "--scope" in argv:
        scope = argv[argv.index("--scope") + 1]
    if "--rules" in argv:
        rules = set(argv[argv.index("--rules") + 1].split(","))

    findings = run(scope)
    current = tally(findings, rules)
    # Compare like with like: a narrow --scope must not read the rest of the
    # tree as "fixed" simply because it was not linted this run.
    base = {f: r for f, r in load().items() if f.startswith(scope)}
    if rules:
        base = {f: {k: v for k, v in r.items() if k in rules} for f, r in base.items()}
        base = {f: r for f, r in base.items() if r}

    if "--new" in argv:
        fresh = sorted(f for f in current if f not in base)
        if not fresh:
            print("port_lint: no files outside the baseline.")
            return 0
        for f in fresh:
            for rule, n in sorted(current[f].items()):
                print(f"{f}: {rule} x{n}")
        print(f"\n{len(fresh)} file(s) carry findings but are not in the "
              f"baseline. A newly ported file is expected to be clean.")
        return 1

    if "--update" in argv:
        # Re-record only within the scope just linted, so a narrow --scope
        # cannot silently drop the rest of the tree from the baseline.
        merged = {f: r for f, r in base.items() if not f.startswith(scope)}
        merged.update(current)
        save(merged, scope)
        print(f"port_lint: baseline updated for {scope} - "
              f"{sum(sum(r.values()) for r in merged.values())} findings across "
              f"{len(merged)} files. Review the diff before committing.")
        return 0

    # --check (default): regressions fail, improvements are reported.
    worse, better, missing = [], [], []
    for f in sorted(set(current) | set(base)):
        cur, old = current.get(f, {}), base.get(f, {})
        for rule in sorted(set(cur) | set(old)):
            c, b = cur.get(rule, 0), old.get(rule, 0)
            if c > b:
                worse.append((f, rule, b, c))
            elif c < b:
                better.append((f, rule, b, c))
        if f in base and f not in current:
            missing.append(f)

    if better:
        fixed = sum(b - c for _, _, b, c in better)
        print(f"port_lint: {fixed} finding(s) fixed across {len(better)} "
              f"(file, rule) pair(s).")
    if missing:
        print(f"port_lint: {len(missing)} baselined file(s) are now clean or gone.")
    if better or missing:
        print("           Run `scripts/port_lint.py --update` to lock that in.\n")

    if not worse:
        total = sum(sum(r.values()) for r in current.values())
        print(f"port_lint: OK - {total} finding(s) under {scope}, none new.")
        return 0

    print("port_lint: NEW findings (the baseline is a ceiling, not a target):\n")
    by_file = {}
    for f, rule, b, c in worse:
        by_file.setdefault(f, []).append((rule, b, c))
    for f in sorted(by_file):
        for rule, b, c in by_file[f]:
            print(f"  {f}: {rule} {b} -> {c}")
            # Show the actual lines, so the fix does not need a second command.
            hits = [(l, m) for ff, rr, l, m in findings if ff == f and rr == rule]
            for l, m in sorted(hits)[:c - b if c - b < 5 else 5]:
                print(f"      {f}:{l}: {m[:120]}")
    print(f"\n{sum(c - b for _, _, b, c in worse)} new finding(s). Fix them, or "
          f"suppress with `// goishlint:ignore <RULE> - <reason>` if the "
          f"divergence is deliberate.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
