// go: file crypto/internal/fips140/nistec/p521.go decls: NewP521Point, P521Point.SetGenerator, P521Point.Set, P521Point.SetBytes, p521B, p521Polynomial, p521CheckOnCurve, P521Point.Bytes, P521Point.bytes, P521Point.BytesX, P521Point.bytesX, P521Point.BytesCompressed, P521Point.bytesCompressed, P521Point.Add, P521Point.Double, P521Point.Select, p521Table.Select, P521Point.ScalarMult, P521Point.generatorTable, P521Point.ScalarBaseMult, p521Sqrt, p521SqrtCandidate
//
// Code generated by generate.go (Go side) and scripts/nistec_gen.py
// (goish side) from p224.rs. DO NOT EDIT — edit p224.rs and re-run
//     scripts/nistec_gen.py
//
// Deviations from p521[go] @ Go 1.25.5:
//
//   * `fiat.P521Element` is a `[u64; N]` limb array and therefore `Copy`,
//     so the goish port takes field elements — and, for the same reason,
//     points — **by value** where Go takes `*fiat.P521Element` /
//     `*P521Point`. This is the deviation already recorded in
//     `fiat/p521.rs`, propagated one level up: it is what lets Go's
//     aliasing call sites (`q.Add(q, t)`,
//     `p521Sqrt(y, y)`) translate directly instead of becoming borrow
//     errors.
//   * Go's `func (p *P521Point) SetBytes(b []byte) (*P521Point, error)`
//     returns `nil` plus an error and leaves the receiver untouched. The
//     goish shape returns just `error` and mutates the receiver only on
//     success — the same shape `fiat.P521Element.SetBytes` already uses.
//     Same for ScalarMult and ScalarBaseMult.
//   * `var p521GeneratorTable *[p521ElementLength * 2]p521Table` guarded
//     by a `sync.Once` becomes a `goish::lazy::Lazy<Vec<p521Table>>`. Go's
//     is a pointer to a heap array; `Vec` is the goish equivalent that
//     keeps the table off any goroutine stack.
//
// goishlint:ignore GOISH021 — `_p521BOnce` and `p521GeneratorTableOnce` are
// the `sync.Once` guards for the two vars directly above them in p521.go.
// `goish::lazy::Lazy` carries its own one-shot latch, so there is nothing
// left for a separately-named Once to be.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types)]

extern crate alloc;
use alloc::vec::Vec;

use super::fiat::P521Element;
use crate::crypto::internal::fips140::subtle;
use crate::errors;
use crate::goslice::slice;
use crate::lazy::Lazy;
use crate::types::byte;
use crate::{error, int};

/// Go: `const p521ElementLength`
///
/// The length of an element of the base or scalar field, which have the
/// same bytes length for all NIST P curves.
pub const p521ElementLength: usize = 66;

// Go: p521.go:20-25
//   type P521Point struct { x, y, z *fiat.P521Element }
/// A P521 point. The zero value is NOT valid.
#[derive(Clone, Copy)]
pub struct P521Point {
    /// The point is represented in projective coordinates (X:Y:Z),
    /// where x = X/Z and y = Y/Z.
    x: P521Element,
    y: P521Element,
    z: P521Element,
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:27-34 NewP521Point
/// Return a new P521Point representing the point at infinity point.
pub fn NewP521Point() -> P521Point {
    // Go: return &P521Point{x: new(…), y: new(…).One(), z: new(…)}
    let mut p = P521Point {
        x: P521Element::New(),
        y: P521Element::New(),
        z: P521Element::New(),
    };
    p.y.One();
    return p;
}

impl P521Point {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:36-42 P521Point.SetGenerator
    /// Set p to the canonical generator and return p.
    pub fn SetGenerator(&mut self) -> &mut Self {
        let _ = self.x.SetBytes(slice::__from_vec(alloc::vec![
            0x0, 0xc6, 0x85, 0x8e, 0x6, 0xb7, 0x4, 0x4, 0xe9, 0xcd, 0x9e, 0x3e, 0xcb, 0x66, 0x23,
            0x95, 0xb4, 0x42, 0x9c, 0x64, 0x81, 0x39, 0x5, 0x3f, 0xb5, 0x21, 0xf8, 0x28, 0xaf,
            0x60, 0x6b, 0x4d, 0x3d, 0xba, 0xa1, 0x4b, 0x5e, 0x77, 0xef, 0xe7, 0x59, 0x28, 0xfe,
            0x1d, 0xc1, 0x27, 0xa2, 0xff, 0xa8, 0xde, 0x33, 0x48, 0xb3, 0xc1, 0x85, 0x6a, 0x42,
            0x9b, 0xf9, 0x7e, 0x7e, 0x31, 0xc2, 0xe5, 0xbd, 0x66
        ]));
        let _ = self.y.SetBytes(slice::__from_vec(alloc::vec![
            0x1, 0x18, 0x39, 0x29, 0x6a, 0x78, 0x9a, 0x3b, 0xc0, 0x4, 0x5c, 0x8a, 0x5f, 0xb4, 0x2c,
            0x7d, 0x1b, 0xd9, 0x98, 0xf5, 0x44, 0x49, 0x57, 0x9b, 0x44, 0x68, 0x17, 0xaf, 0xbd,
            0x17, 0x27, 0x3e, 0x66, 0x2c, 0x97, 0xee, 0x72, 0x99, 0x5e, 0xf4, 0x26, 0x40, 0xc5,
            0x50, 0xb9, 0x1, 0x3f, 0xad, 0x7, 0x61, 0x35, 0x3c, 0x70, 0x86, 0xa2, 0x72, 0xc2, 0x40,
            0x88, 0xbe, 0x94, 0x76, 0x9f, 0xd1, 0x66, 0x50
        ]));
        self.z.One();
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:44-50 P521Point.Set
    /// Set p = q and return p.
    pub fn Set(&mut self, q: P521Point) -> &mut Self {
        self.x.Set(q.x);
        self.y.Set(q.y);
        self.z.Set(q.z);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:52-108 P521Point.SetBytes
    /// Set p to the compressed, uncompressed, or infinity value encoded in
    /// b, as specified in SEC 1, Version 2.0, Section 2.3.4. If the point
    /// is not on the curve, it returns an error and the receiver is
    /// unchanged.
    pub fn SetBytes(&mut self, b: &slice<byte>) -> error {
        let raw: &[byte] = b;
        // Go: case len(b) == 1 && b[0] == 0: — point at infinity.
        if raw.len() == 1 && raw[0] == 0 {
            self.Set(NewP521Point());
            return crate::nil.into();
        }

        // Go: case len(b) == 1+2*p521ElementLength && b[0] == 4: — uncompressed form.
        if raw.len() == 1 + 2 * p521ElementLength && raw[0] == 4 {
            let mut x = P521Element::New();
            let err = x.SetBytes(slice::__from_vec(raw[1..1 + p521ElementLength].to_vec()));
            if err != crate::nil {
                return err;
            }
            let mut y = P521Element::New();
            let err = y.SetBytes(slice::__from_vec(raw[1 + p521ElementLength..].to_vec()));
            if err != crate::nil {
                return err;
            }
            let err = p521CheckOnCurve(x, y);
            if err != crate::nil {
                return err;
            }
            self.x.Set(x);
            self.y.Set(y);
            self.z.One();
            return crate::nil.into();
        }

        // Go: case len(b) == 1+p521ElementLength && (b[0] == 2 || b[0] == 3): — compressed form.
        if raw.len() == 1 + p521ElementLength && (raw[0] == 2 || raw[0] == 3) {
            let mut x = P521Element::New();
            let err = x.SetBytes(slice::__from_vec(raw[1..].to_vec()));
            if err != crate::nil {
                return err;
            }

            // y² = x³ - 3x + b
            let mut y = P521Element::New();
            p521Polynomial(&mut y, x);
            let y2 = y;
            if !p521Sqrt(&mut y, y2) {
                return errors::New("invalid P521 compressed point encoding");
            }

            // Select the positive or negative root, as indicated by the
            // least significant bit, based on the encoding type byte.
            let mut otherRoot = P521Element::New();
            otherRoot.Sub(otherRoot, y);
            let yb = y.Bytes();
            let ybr: &[byte] = &yb;
            let cond = ybr[p521ElementLength - 1] & 1 ^ raw[0] & 1;
            y.Select(otherRoot, y, int(cond));

            self.x.Set(x);
            self.y.Set(y);
            self.z.One();
            return crate::nil.into();
        }

        // Go: default:
        return errors::New("invalid P521 point encoding");
    }
}

// Go: p521.go:110-111 — `var _p521B *fiat.P521Element; var _p521BOnce sync.Once`
static _p521B: Lazy<P521Element> = Lazy::new(|| {
    let mut e = P521Element::New();
    let _ = e.SetBytes(slice::__from_vec(alloc::vec![
        0x0, 0x51, 0x95, 0x3e, 0xb9, 0x61, 0x8e, 0x1c, 0x9a, 0x1f, 0x92, 0x9a, 0x21, 0xa0, 0xb6,
        0x85, 0x40, 0xee, 0xa2, 0xda, 0x72, 0x5b, 0x99, 0xb3, 0x15, 0xf3, 0xb8, 0xb4, 0x89, 0x91,
        0x8e, 0xf1, 0x9, 0xe1, 0x56, 0x19, 0x39, 0x51, 0xec, 0x7e, 0x93, 0x7b, 0x16, 0x52, 0xc0,
        0xbd, 0x3b, 0xb1, 0xbf, 0x7, 0x35, 0x73, 0xdf, 0x88, 0x3d, 0x2c, 0x34, 0xf1, 0xef, 0x45,
        0x1f, 0xd4, 0x6b, 0x50, 0x3f, 0x0
    ]));
    return e;
});

// go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:113-118 p521B
fn p521B() -> P521Element {
    return *_p521B;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:120-130 p521Polynomial
/// Set y2 to x³ - 3x + b, and return y2.
fn p521Polynomial(y2: &mut P521Element, x: P521Element) -> P521Element {
    y2.Square(x);
    y2.Mul(*y2, x);

    let mut threeX = P521Element::New();
    threeX.Add(x, x);
    threeX.Add(threeX, x);
    y2.Sub(*y2, threeX);

    y2.Add(*y2, p521B());
    return *y2;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:132-140 p521CheckOnCurve
fn p521CheckOnCurve(x: P521Element, y: P521Element) -> error {
    // y² = x³ - 3x + b
    let mut rhs = P521Element::New();
    p521Polynomial(&mut rhs, x);
    let mut lhs = P521Element::New();
    lhs.Square(y);
    if rhs.Equal(lhs) != 1 {
        return errors::New("P521 point not on curve");
    }
    return crate::nil.into();
}

impl P521Point {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:142-150 P521Point.Bytes
    /// Return the uncompressed or infinity encoding of p, as specified in
    /// SEC 1, Version 2.0, Section 2.3.3. Note that the encoding of the
    /// point at infinity is shorter than all other encodings.
    pub fn Bytes(&self) -> slice<byte> {
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; 1 + 2 * p521ElementLength];
        return self.bytes(&mut out);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:152-165 P521Point.bytes
    fn bytes(&self, out: &mut [byte; 1 + 2 * p521ElementLength]) -> slice<byte> {
        if self.z.IsZero() == 1 {
            return slice::__from_vec(alloc::vec![0u8]);
        }

        let mut zinv = P521Element::New();
        zinv.Invert(&self.z);
        let mut x = P521Element::New();
        x.Mul(self.x, zinv);
        let mut y = P521Element::New();
        y.Mul(self.y, zinv);

        out[0] = 4;
        let xb = x.Bytes();
        let yb = y.Bytes();
        let xr: &[byte] = &xb;
        let yr: &[byte] = &yb;
        out[1..1 + p521ElementLength].copy_from_slice(xr);
        out[1 + p521ElementLength..].copy_from_slice(yr);
        return slice::__from_vec(out.to_vec());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:167-174 P521Point.BytesX
    /// Return the encoding of the x-coordinate of p, as specified in SEC 1,
    /// Version 2.0, Section 2.3.5, or an error if p is the point at
    /// infinity.
    pub fn BytesX(&self) -> (slice<byte>, error) {
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; p521ElementLength];
        return self.bytesX(&mut out);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:176-185 P521Point.bytesX
    fn bytesX(&self, out: &mut [byte; p521ElementLength]) -> (slice<byte>, error) {
        if self.z.IsZero() == 1 {
            return (
                slice::__from_vec(Vec::<byte>::new()),
                errors::New("P521 point is the point at infinity"),
            );
        }

        let mut zinv = P521Element::New();
        zinv.Invert(&self.z);
        let mut x = P521Element::New();
        x.Mul(self.x, zinv);

        let xb = x.Bytes();
        let xr: &[byte] = &xb;
        out.copy_from_slice(xr);
        return (slice::__from_vec(out.to_vec()), crate::nil.into());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:187-195 P521Point.BytesCompressed
    /// Return the compressed or infinity encoding of p, as specified in
    /// SEC 1, Version 2.0, Section 2.3.3. Note that the encoding of the
    /// point at infinity is shorter than all other encodings.
    pub fn BytesCompressed(&self) -> slice<byte> {
        // This function is outlined to make the allocations inline in the
        // caller rather than happen on the heap.
        let mut out = [0u8; 1 + p521ElementLength];
        return self.bytesCompressed(&mut out);
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:197-212 P521Point.bytesCompressed
    fn bytesCompressed(&self, out: &mut [byte; 1 + p521ElementLength]) -> slice<byte> {
        if self.z.IsZero() == 1 {
            return slice::__from_vec(alloc::vec![0u8]);
        }

        let mut zinv = P521Element::New();
        zinv.Invert(&self.z);
        let mut x = P521Element::New();
        x.Mul(self.x, zinv);
        let mut y = P521Element::New();
        y.Mul(self.y, zinv);

        // Encode the sign of the y coordinate (indicated by the least
        // significant bit) as the encoding type (2 or 3).
        let yb = y.Bytes();
        let ybr: &[byte] = &yb;
        out[0] = 2;
        out[0] |= ybr[p521ElementLength - 1] & 1;
        let xb = x.Bytes();
        let xr: &[byte] = &xb;
        out[1..].copy_from_slice(xr);
        return slice::__from_vec(out.to_vec());
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:214-267 P521Point.Add
    /// Set q = p1 + p2, and return q. The points may overlap.
    pub fn Add(&mut self, p1: P521Point, p2: P521Point) -> &mut Self {
        // Complete addition formula for a = -3 from "Complete addition
        // formulas for prime order elliptic curves"
        // (https://eprint.iacr.org/2015/1060), §A.2.

        let mut t0 = P521Element::New();
        t0.Mul(p1.x, p2.x); // t0 := X1 * X2
        let mut t1 = P521Element::New();
        t1.Mul(p1.y, p2.y); // t1 := Y1 * Y2
        let mut t2 = P521Element::New();
        t2.Mul(p1.z, p2.z); // t2 := Z1 * Z2
        let mut t3 = P521Element::New();
        t3.Add(p1.x, p1.y); // t3 := X1 + Y1
        let mut t4 = P521Element::New();
        t4.Add(p2.x, p2.y); // t4 := X2 + Y2
        t3.Mul(t3, t4); // t3 := t3 * t4
        t4.Add(t0, t1); // t4 := t0 + t1
        t3.Sub(t3, t4); // t3 := t3 - t4
        t4.Add(p1.y, p1.z); // t4 := Y1 + Z1
        let mut x3 = P521Element::New();
        x3.Add(p2.y, p2.z); // X3 := Y2 + Z2
        t4.Mul(t4, x3); // t4 := t4 * X3
        x3.Add(t1, t2); // X3 := t1 + t2
        t4.Sub(t4, x3); // t4 := t4 - X3
        x3.Add(p1.x, p1.z); // X3 := X1 + Z1
        let mut y3 = P521Element::New();
        y3.Add(p2.x, p2.z); // Y3 := X2 + Z2
        x3.Mul(x3, y3); // X3 := X3 * Y3
        y3.Add(t0, t2); // Y3 := t0 + t2
        y3.Sub(x3, y3); // Y3 := X3 - Y3
        let mut z3 = P521Element::New();
        z3.Mul(p521B(), t2); // Z3 := b * t2
        x3.Sub(y3, z3); // X3 := Y3 - Z3
        z3.Add(x3, x3); // Z3 := X3 + X3
        x3.Add(x3, z3); // X3 := X3 + Z3
        z3.Sub(t1, x3); // Z3 := t1 - X3
        x3.Add(t1, x3); // X3 := t1 + X3
        y3.Mul(p521B(), y3); // Y3 := b * Y3
        t1.Add(t2, t2); // t1 := t2 + t2
        t2.Add(t1, t2); // t2 := t1 + t2
        y3.Sub(y3, t2); // Y3 := Y3 - t2
        y3.Sub(y3, t0); // Y3 := Y3 - t0
        t1.Add(y3, y3); // t1 := Y3 + Y3
        y3.Add(t1, y3); // Y3 := t1 + Y3
        t1.Add(t0, t0); // t1 := t0 + t0
        t0.Add(t1, t0); // t0 := t1 + t0
        t0.Sub(t0, t2); // t0 := t0 - t2
        t1.Mul(t4, y3); // t1 := t4 * Y3
        t2.Mul(t0, y3); // t2 := t0 * Y3
        y3.Mul(x3, z3); // Y3 := X3 * Z3
        y3.Add(y3, t2); // Y3 := Y3 + t2
        x3.Mul(t3, x3); // X3 := t3 * X3
        x3.Sub(x3, t1); // X3 := X3 - t1
        z3.Mul(t4, z3); // Z3 := t4 * Z3
        t1.Mul(t3, t0); // t1 := t3 * t0
        z3.Add(z3, t1); // Z3 := Z3 + t1

        self.x.Set(x3);
        self.y.Set(y3);
        self.z.Set(z3);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:269-313 P521Point.Double
    /// Set q = p + p, and return q. The points may overlap.
    pub fn Double(&mut self, p: P521Point) -> &mut Self {
        // Complete addition formula for a = -3 from "Complete addition
        // formulas for prime order elliptic curves"
        // (https://eprint.iacr.org/2015/1060), §A.2.

        let mut t0 = P521Element::New();
        t0.Square(p.x); // t0 := X ^ 2
        let mut t1 = P521Element::New();
        t1.Square(p.y); // t1 := Y ^ 2
        let mut t2 = P521Element::New();
        t2.Square(p.z); // t2 := Z ^ 2
        let mut t3 = P521Element::New();
        t3.Mul(p.x, p.y); // t3 := X * Y
        t3.Add(t3, t3); // t3 := t3 + t3
        let mut z3 = P521Element::New();
        z3.Mul(p.x, p.z); // Z3 := X * Z
        z3.Add(z3, z3); // Z3 := Z3 + Z3
        let mut y3 = P521Element::New();
        y3.Mul(p521B(), t2); // Y3 := b * t2
        y3.Sub(y3, z3); // Y3 := Y3 - Z3
        let mut x3 = P521Element::New();
        x3.Add(y3, y3); // X3 := Y3 + Y3
        y3.Add(x3, y3); // Y3 := X3 + Y3
        x3.Sub(t1, y3); // X3 := t1 - Y3
        y3.Add(t1, y3); // Y3 := t1 + Y3
        y3.Mul(x3, y3); // Y3 := X3 * Y3
        x3.Mul(x3, t3); // X3 := X3 * t3
        t3.Add(t2, t2); // t3 := t2 + t2
        t2.Add(t2, t3); // t2 := t2 + t3
        z3.Mul(p521B(), z3); // Z3 := b * Z3
        z3.Sub(z3, t2); // Z3 := Z3 - t2
        z3.Sub(z3, t0); // Z3 := Z3 - t0
        t3.Add(z3, z3); // t3 := Z3 + Z3
        z3.Add(z3, t3); // Z3 := Z3 + t3
        t3.Add(t0, t0); // t3 := t0 + t0
        t0.Add(t3, t0); // t0 := t3 + t0
        t0.Sub(t0, t2); // t0 := t0 - t2
        t0.Mul(t0, z3); // t0 := t0 * Z3
        y3.Add(y3, t0); // Y3 := Y3 + t0
        t0.Mul(p.y, p.z); // t0 := Y * Z
        t0.Add(t0, t0); // t0 := t0 + t0
        z3.Mul(t0, z3); // Z3 := t0 * Z3
        x3.Sub(x3, z3); // X3 := X3 - Z3
        z3.Mul(t0, t1); // Z3 := t0 * t1
        z3.Add(z3, z3); // Z3 := Z3 + Z3
        z3.Add(z3, z3); // Z3 := Z3 + Z3

        self.x.Set(x3);
        self.y.Set(y3);
        self.z.Set(z3);
        return self;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:316-321 P521Point.Select
    /// Set q to p1 if cond == 1, and to p2 if cond == 0.
    pub fn Select(&mut self, p1: P521Point, p2: P521Point, cond: int) -> &mut Self {
        self.x.Select(p1.x, p2.x, cond);
        self.y.Select(p1.y, p2.y, cond);
        self.z.Select(p1.z, p2.z, cond);
        return self;
    }
}

// Go: p521.go:323-326
//   type p521Table [15]*P521Point
/// Holds the first 15 multiples of a point at offset -1, so [1]P is at
/// table[0], [15]P is at table[14], and [0]P is implicitly the identity
/// point.
#[derive(Clone, Copy)]
struct p521Table([P521Point; 15]);

impl p521Table {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:328-339 p521Table.Select
    /// Select the n-th multiple of the table base point into p. It works
    /// in constant time by iterating over every entry of the table. n must
    /// be in [0, 15].
    fn Select(&self, p: &mut P521Point, n: byte) {
        if n >= 16 {
            panic!("nistec: internal error: p521Table called with out-of-bounds value");
        }
        p.Set(NewP521Point());
        let mut i: byte = 1;
        while i < 16 {
            let cond = subtle::ConstantTimeByteEq(i, n);
            let e = self.0[(i - 1) as usize];
            p.Select(e, *p, cond);
            i += 1;
        }
    }
}

impl P521Point {
    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:341-384 P521Point.ScalarMult
    /// Set p = scalar * q, and return p.
    pub fn ScalarMult(&mut self, q: P521Point, scalar: &slice<byte>) -> error {
        // Compute a p521Table for the base point q.
        let mut table = p521Table([NewP521Point(); 15]);
        table.0[0].Set(q);
        let mut i: usize = 1;
        while i < 15 {
            let half = table.0[i / 2];
            table.0[i].Double(half);
            let prev = table.0[i];
            table.0[i + 1].Add(prev, q);
            i += 2;
        }

        // Instead of doing the classic double-and-add chain, we do it with
        // a four-bit window: we double four times, and then add [0-15]P.
        let mut t = NewP521Point();
        self.Set(NewP521Point());
        for (i, b) in crate::range!(scalar) {
            // No need to double on the first iteration, as p is the
            // identity at this point, and [N]∞ = ∞.
            if i != 0 {
                let s = *self;
                self.Double(s);
                let s = *self;
                self.Double(s);
                let s = *self;
                self.Double(s);
                let s = *self;
                self.Double(s);
            }

            let mut windowValue = *b >> 4;
            table.Select(&mut t, windowValue);
            let s = *self;
            self.Add(s, t);

            let s = *self;
            self.Double(s);
            let s = *self;
            self.Double(s);
            let s = *self;
            self.Double(s);
            let s = *self;
            self.Double(s);

            windowValue = *b & 0b1111;
            table.Select(&mut t, windowValue);
            let s = *self;
            self.Add(s, t);
        }

        return crate::nil.into();
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:389-408 P521Point.generatorTable
    /// Return a sequence of p521Tables. The first table contains multiples
    /// of G. Each successive table is the previous table doubled four
    /// times.
    fn generatorTable(&self) -> &'static Vec<p521Table> {
        return &p521GeneratorTable;
    }

    // go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:410-440 P521Point.ScalarBaseMult
    /// Set p = scalar * B, where B is the canonical generator, and return p.
    pub fn ScalarBaseMult(&mut self, scalar: &slice<byte>) -> error {
        if scalar.Len() != int(p521ElementLength) {
            return errors::New("invalid scalar length");
        }
        let tables = self.generatorTable();

        // This is also a scalar multiplication with a four-bit window like
        // in ScalarMult, but in this case the doublings are precomputed.
        // The value [windowValue]G added at iteration k would normally get
        // doubled (totIterations-k)×4 times, but with a larger
        // precomputation we can instead add
        // [2^((totIterations-k)×4)][windowValue]G and avoid the doublings
        // between iterations.
        let mut t = NewP521Point();
        self.Set(NewP521Point());
        let mut tableIndex = tables.len() - 1;
        for (_, b) in crate::range!(scalar) {
            let mut windowValue = *b >> 4;
            tables[tableIndex].Select(&mut t, windowValue);
            let s = *self;
            self.Add(s, t);
            tableIndex = tableIndex.wrapping_sub(1);

            windowValue = *b & 0b1111;
            tables[tableIndex].Select(&mut t, windowValue);
            let s = *self;
            self.Add(s, t);
            tableIndex = tableIndex.wrapping_sub(1);
        }

        return crate::nil.into();
    }
}

// Go: p521.go:386-387 — `var p521GeneratorTable *[…]p521Table; var …Once sync.Once`
static p521GeneratorTable: Lazy<Vec<p521Table>> = Lazy::new(|| {
    let mut tables: Vec<p521Table> = Vec::with_capacity(p521ElementLength * 2);
    let mut base = NewP521Point();
    base.SetGenerator();
    let mut i: usize = 0;
    while i < p521ElementLength * 2 {
        let mut tbl = p521Table([NewP521Point(); 15]);
        tbl.0[0].Set(base);
        let mut j: usize = 1;
        while j < 15 {
            let prev = tbl.0[j - 1];
            tbl.0[j].Add(prev, base);
            j += 1;
        }
        tables.push(tbl);
        let b = base;
        base.Double(b);
        let b = base;
        base.Double(b);
        let b = base;
        base.Double(b);
        let b = base;
        base.Double(b);
        i += 1;
    }
    return tables;
});

// go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:442-453 p521Sqrt
/// Set e to a square root of x. If x is not a square, p521Sqrt returns
/// false and e is unchanged. e and x can overlap.
fn p521Sqrt(e: &mut P521Element, x: P521Element) -> bool {
    let mut candidate = P521Element::New();
    p521SqrtCandidate(&mut candidate, x);
    let mut square = P521Element::New();
    square.Square(candidate);
    if square.Equal(x) != 1 {
        return false;
    }
    e.Set(candidate);
    return true;
}

// go: sdk 1.25.5 crypto/internal/fips140/nistec/p521.go:455-469 p521SqrtCandidate
/// Set z to a square root candidate for x.
fn p521SqrtCandidate(z: &mut P521Element, x: P521Element) {
    // Since p = 3 mod 4, exponentiation by (p + 1) / 4 yields a square root candidate.
    //
    // The sequence of 0 multiplications and 519 squarings is derived from the
    // following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
    //
    //	return  1 << 519
    //

    z.Square(x);
    let mut s: usize = 1;
    while s < 519 {
        z.Square(*z);
        s += 1;
    }
}
